// @vitest-environment jsdom
import {mount,flushPromises} from '@vue/test-utils';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import Orders from './OrdersView.vue';
import {api,brainRun} from '../api/client';
vi.mock('../stores/system',()=>({useSystemStore:()=>({snapshot:{tpOrders:[]},refresh:vi.fn()})}));
vi.mock('../api/client',()=>({api:{orders:vi.fn(),cancelEntry:vi.fn()},brainRun:vi.fn()}));
const row={id:'o',symbol:'UNIUSDT',side:'SHORT',quantity:135,price:7.442,filledQuantity:0,remainingQuantity:135,lifecycleStatus:'CANCELED',wasSubmitted:true,statusAuthority:'BINANCE_USER_DATA_WS',freshness:'TERMINAL',decisionRunId:'unique-primary',clientOrderId:'sensitive-client-1234',exchangeOrderId:'sensitive-exchange-5678',review:[{decision:'CANCEL',reason:'MODEL_REASON',at:1000}],orderAttempts:[{lifecycleStatus:'CANCELED',filledQuantity:0}],repriceHistory:[]};
let wrapper:any;
beforeEach(()=>{vi.clearAllMocks();vi.mocked(api.orders).mockResolvedValue({entry:[],entryReadback:{status:'READY',verifiedAt:1000},entryHistory:{items:[row],total:51,olderHiddenCount:4},historicalUnknown:[]} as any);vi.mocked(brainRun).mockResolvedValue({run:{id:'unique-primary'},timeline:[{type:'PENDING_ENTRY_REVIEW_ACTION_CONVERGED'}]} as any);});
afterEach(()=>{wrapper?.unmount();vi.useRealTimers();});
const open=async()=>{wrapper=mount(Orders,{global:{stubs:{Panel:{template:'<div><slot/></div>'},StatusBadge:{props:['value'],template:'<span>{{value}}</span>'}}}});await flushPromises();return wrapper;};
it('keeps current activity empty and exposes read-only canceled history with exact Run audit',async()=>{await open();expect(wrapper.text()).toContain('交易所当前没有活动建仓委托');await wrapper.findAll('button').find((b:any)=>b.text().includes('全部建仓历史')).trigger('click');expect(wrapper.text()).toContain('CANCELED');expect(wrapper.text()).toContain('MODEL_REASON');expect(wrapper.text()).toContain('曾成功提交');expect(wrapper.text()).not.toContain('sensitive-client-1234');expect(wrapper.findAll('button').some((b:any)=>b.text()==='取消')).toBe(false);await wrapper.findAll('button').find((b:any)=>b.text().includes('查看 AI Run')).trigger('click');await flushPromises();expect(brainRun).toHaveBeenCalledWith('unique-primary');expect(wrapper.text()).toContain('PENDING_ENTRY_REVIEW_ACTION_CONVERGED');expect(api.cancelEntry).not.toHaveBeenCalled();});
it('filters separate states, pages, refreshes and removes timers on unmount',async()=>{vi.useFakeTimers();await open();await wrapper.findAll('button').find((b:any)=>b.text().includes('全部建仓历史')).trigger('click');await wrapper.find('select').setValue('LOCAL_TTL_EXPIRED_REMOTE_UNKNOWN');await flushPromises();expect(api.orders).toHaveBeenLastCalledWith(expect.stringContaining('status=LOCAL_TTL_EXPIRED_REMOTE_UNKNOWN'));await wrapper.findAll('button').find((b:any)=>b.text()==='下一页').trigger('click');await flushPromises();expect(api.orders).toHaveBeenLastCalledWith(expect.stringContaining('offset=50'));await wrapper.findAll('button').find((b:any)=>b.text()==='刷新').trigger('click');await flushPromises();const count=vi.mocked(api.orders).mock.calls.length;window.dispatchEvent(new Event('focus'));await flushPromises();expect(api.orders).toHaveBeenCalledTimes(count+1);wrapper.unmount();wrapper=null;await vi.advanceTimersByTimeAsync(30000);expect(api.orders).toHaveBeenCalledTimes(count+1);});
it('failed refresh marks cached activity stale and disables cancel',async()=>{vi.mocked(api.orders).mockResolvedValueOnce({entry:[{...row,status:'WORKING'}],entryReadback:{status:'READY'}} as any);await open();vi.mocked(api.orders).mockRejectedValueOnce(new Error('OFFLINE'));await wrapper.findAll('button').find((b:any)=>b.text()==='刷新').trigger('click');await flushPromises();expect(wrapper.findAll('button').find((b:any)=>b.text()==='取消').attributes('disabled')).toBeDefined();expect(wrapper.text()).toContain('STALE');});
