<script setup lang="ts">
import { onMounted,onUnmounted,ref } from 'vue';
import { marketIntelligence } from '../api/client';
import Panel from '../components/Panel.vue';
import StatusBadge from '../components/StatusBadge.vue';
const intelligence=ref<any>(null),error=ref<string|null>(null);let timer:number|undefined;
const pct=(v:any)=>typeof v==='number'?`${(v*100).toFixed(1)}%`:'—';
const num=(v:any,digits=2)=>typeof v==='number'?v.toFixed(digits):'—';
const when=(v:any)=>typeof v==='number'?new Date(v).toLocaleString():'—';
async function load(){try{intelligence.value=await marketIntelligence();error.value=null;}catch(e){error.value=e instanceof Error?e.message:String(e);}}
onMounted(()=>{void load();timer=window.setInterval(load,15_000)});onUnmounted(()=>{if(timer)clearInterval(timer)});
</script>
<template><div class="page-stack"><div class="toolbar"><div><span class="eyebrow">READ_ONLY · SHADOW · OBSERVE_ONLY</span><h2 class="page-title">市场周期 / Market Intelligence</h2></div><StatusBadge :value="intelligence?.status??'STARTING'"/></div><div v-if="error" class="error-banner">{{error}}</div><div v-if="intelligence?.status==='OFFLINE_ONLY'" class="policy-card danger-lite"><strong>Temporal 当前没有在线研究快照</strong><span>{{intelligence.reason}}。这是隔离策略的预期结果，不会用空值冒充市场周期结论；需要单独的研究数据库副本并由人工启动研究 worker。</span></div>
<Panel title="当前市场结构" subtitle="现有 Hot 事实：15m方向 / 5m与1m时机；不冒充历史周期研究"><p v-if="!intelligence">正在读取市场事实…</p><p v-else-if="!intelligence.liveStructure?.length">暂无可展示的 Hot 行情；等待采集恢复。</p><table v-else class="data-table"><thead><tr><th>Symbol</th><th>15m结构</th><th>5m</th><th>1m</th><th>15m闭合时间</th><th>数据状态</th></tr></thead><tbody><tr v-for="row in intelligence.liveStructure" :key="row.symbol"><td>{{row.symbol}}</td><td>{{row.trend15m}}</td><td>{{row.trend5m}}</td><td>{{row.trend1m}}</td><td>{{when(row.asOf)}}</td><td>{{row.reasons?.length ? row.reasons.join(' · ') : 'READY'}}</td></tr></tbody></table></Panel><template v-if="intelligence && intelligence.status!=='OFFLINE_ONLY'"><Panel title="Global Regime" subtitle="状态、年龄、宽度与切换风险仅供研究，不进入交易决策"><div class="kpi-grid four"><div class="kpi"><span>Current Regime / Age</span><strong>{{intelligence?.currentRegime?.state??'INSUFFICIENT_DATA'}} / {{intelligence?.currentRegime?.ageMs?`${(intelligence.currentRegime.ageMs/3600000).toFixed(1)}h`:'—'}}</strong></div><div class="kpi"><span>Bullish / Bearish / Neutral</span><strong>{{pct(intelligence?.currentRegime?.bullishBreadth)}} / {{pct(intelligence?.currentRegime?.bearishBreadth)}} / {{pct(intelligence?.currentRegime?.neutralBreadth)}}</strong></div><div class="kpi"><span>Breadth Slope / Acceleration</span><strong>{{num(intelligence?.currentRegime?.breadthSlope,4)}} / {{num(intelligence?.currentRegime?.breadthAcceleration,4)}}</strong></div><div class="kpi"><span>Transition V1 / V2 / V3</span><strong>{{num(intelligence?.currentRegime?.candidates?.v1)}} / {{num(intelligence?.currentRegime?.candidates?.v2)}} / {{num(intelligence?.currentRegime?.candidates?.v3)}}</strong></div></div></Panel>
<div class="grid-2"><Panel title="Temporal Decision Memory" subtitle="AI Direction 不是标签；Outcome 来自后续真实 mark"><div class="facts"><div><dt>Complete / Partial</dt><dd>{{intelligence?.coverage?.complete??0}} / {{intelligence?.coverage?.partial??0}}</dd></div><div><dt>15m / 1h Coverage</dt><dd>{{pct(intelligence?.coverage?.outcomeCoverage15m)}} / {{pct(intelligence?.coverage?.outcomeCoverage1h)}}</dd></div><div><dt>4h / 24h Coverage</dt><dd>{{pct(intelligence?.coverage?.outcomeCoverage4h)}} / {{pct(intelligence?.coverage?.outcomeCoverage24h)}}</dd></div><div><dt>3d / 7d Coverage</dt><dd>{{pct(intelligence?.coverage?.outcomeCoverage3d)}} / {{pct(intelligence?.coverage?.outcomeCoverage7d)}}</dd></div></div></Panel><Panel title="Historical Analog" :subtitle="intelligence?.historicalAnalog?.status??'STARTING'"><div class="facts"><div><dt>Analog Count</dt><dd>{{intelligence?.historicalAnalog?.analogCount??0}}</dd></div><div><dt>Same / Underlying / Cross</dt><dd>{{intelligence?.historicalAnalog?.counts?.sameSymbol??0}} / {{intelligence?.historicalAnalog?.counts?.sameUnderlying??0}} / {{intelligence?.historicalAnalog?.counts?.crossSymbol??0}}</dd></div><div><dt>4h Outcome</dt><dd>{{pct(intelligence?.historicalAnalog?.outcomes?.return4h)}}</dd></div><div><dt>MFE / MAE</dt><dd>{{pct(intelligence?.historicalAnalog?.outcomes?.mfe)}} / {{pct(intelligence?.historicalAnalog?.outcomes?.mae)}}</dd></div></div></Panel></div>
<div class="grid-2"><Panel title="State Change Gate" subtitle="OBSERVE_ONLY · 不跳过 9B/27B"><div class="facts"><div><dt>Would Reuse / Recompute</dt><dd>{{intelligence?.stateChangeGate?.wouldReuseCount??0}} / {{intelligence?.stateChangeGate?.wouldRecomputeCount??0}}</dd></div><div><dt>9B / 27B Runs Saved</dt><dd>{{intelligence?.stateChangeGate?.estimated9BRunsSaved??0}} / {{intelligence?.stateChangeGate?.estimated27BRunsSaved??0}}</dd></div><div><dt>Token Saved</dt><dd>{{intelligence?.stateChangeGate?.estimated9BTokensSaved??0}} / {{intelligence?.stateChangeGate?.estimated27BTokensSaved??0}}</dd></div><div><dt>Missed Material Change</dt><dd>{{intelligence?.stateChangeGate?.missedMaterialStateChangeCount??0}}</dd></div></div></Panel><Panel title="Runtime Isolation" subtitle="Worker thread 与 HTTP 热路径隔离"><div class="facts"><div><dt>Worker / Active / Queue</dt><dd>{{intelligence?.runtime?.workerCount??0}} / {{intelligence?.runtime?.activeResearchJobs??0}} / {{intelligence?.runtime?.backgroundQueue??0}}</dd></div><div><dt>Event Loop p50 / p95 / max</dt><dd>{{num(intelligence?.runtime?.eventLoopLagMs?.p50)}} / {{num(intelligence?.runtime?.eventLoopLagMs?.p95)}} / {{num(intelligence?.runtime?.eventLoopLagMs?.max)}} ms</dd></div><div><dt>Last Build</dt><dd>{{when(intelligence?.generatedAt)}}</dd></div><div><dt>Research Brain</dt><dd>{{intelligence?.researchBrain?.mode??'IDLE_ONLY_LOW_PRIORITY'}} · NO ORDER PERMISSION</dd></div></div></Panel></div>
<Panel title="Regime Timeline" subtitle="最近 96 个 15m 时间桶"><table class="data-table"><thead><tr><th>时间</th><th>Regime</th><th>Bullish</th><th>Bearish</th><th>Transition</th></tr></thead><tbody><tr v-for="row in [...(intelligence?.timeline??[])].reverse()" :key="row.at"><td>{{when(row.at)}}</td><td><StatusBadge :value="row.state"/></td><td>{{pct(row.bullish)}}</td><td>{{pct(row.bearish)}}</td><td>{{num(row.transition)}}</td></tr></tbody></table></Panel>
<Panel title="Transition Walk-forward" subtitle="扩展窗口、时间切分、无随机打乱"><table class="data-table"><thead><tr><th>Candidate</th><th>Status</th><th>Features</th><th>Validation Folds</th></tr></thead><tbody><tr v-for="row in intelligence?.transitionResearch?.candidates??[]" :key="row.candidate_id"><td>{{row.version}}</td><td><StatusBadge :value="row.status"/></td><td>{{row.feature_set}}</td><td>{{row.metrics?.folds?.length??0}}</td></tr></tbody></table></Panel></template></div></template>
