<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue';
import { api } from '../api/client';
import Panel from '../components/Panel.vue';
import EmptyState from '../components/EmptyState.vue';
import StatusBadge from '../components/StatusBadge.vue';
import { money } from '../format';
import { financialClass } from '../positionModel';
import { tradeClosePresentation } from './tradeClosePresentation';

const categories=[['ALL','全部历史'],['COMPLETE','完整账本'],['PARTIAL','部分事实'],['IMPORTED','导入记录'],['EXTERNAL','外部记录'],['ISSUES','重复/冲突/无效']] as const;
const category=ref('ALL'),data=ref<any>({items:[],total:0,page:1,limit:20,autoSync:{status:'NOT_STARTED'},summary:{counts:{}}}),detail=ref<any>(null),page=ref(1),symbol=ref(''),direction=ref(''),outcome=ref(''),status=ref('');
const syncOpen=ref(false),syncRange=ref('5h'),maxFills=ref(500),includeExternal=ref(false),repairPartial=ref(true),fillFees=ref(true),recalcNet=ref(true),customStart=ref(''),customEnd=ref(''),preview=ref<any>(null),syncResult=ref<any>(null),syncBusy=ref(false),syncError=ref('');
const daily=ref<any>(null),dailyError=ref(''),dailyCheckedAt=ref<number|null>(null),dailyNow=ref(Date.now());
const amount=(value:unknown,asset:string)=>{
  if(typeof value!=='number'||!Number.isFinite(value))return '—';
  return new Intl.NumberFormat('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:4}).format(value)+' '+asset;
};
const dailyAssetRows=computed(()=>['USDT','USDC'].map(asset=>({asset,...daily.value?.byAsset?.[asset]})));
const dailyStale=computed(()=>!daily.value?.asOf||dailyNow.value-daily.value.asOf>60_000||Boolean(dailyError.value));
async function loadDaily(){dailyNow.value=Date.now();try{daily.value=await api.tradeRecords24h();dailyError.value='';dailyCheckedAt.value=Date.now();}catch(error){dailyError.value=error instanceof Error?error.message:String(error);}}
const count=(key:string)=>data.value.summary?.counts?.[key]??0;
const fee=(value:number|null|undefined)=>value==null?'—':money(value);
const closeKind=tradeClosePresentation;
const closeKindTally=computed(()=>{const tally:Record<string,number>={};for(const row of data.value.items??[]){const key=closeKind(row).label;tally[key]=(tally[key]??0)+1}return tally});
const totalPages=computed(()=>Math.max(1,Math.ceil((data.value.total??0)/(data.value.limit??20))));
async function load(){const q=new URLSearchParams({page:String(page.value),limit:'20',category:category.value});if(status.value)q.set('status',status.value);if(symbol.value)q.set('symbol',symbol.value);if(direction.value)q.set('direction',direction.value);if(outcome.value)q.set('outcome',outcome.value);data.value=await api.tradeRecords(q.toString());}
async function show(id:string){detail.value=await api.tradeRecord(id)}
function reset(){symbol.value='';direction.value='';outcome.value='';status.value='';page.value=1;void load()}
function openSync(){syncOpen.value=true;preview.value=null;syncResult.value=null;syncError.value=''}
function closeSync(){if(!syncBusy.value)syncOpen.value=false}
function syncBody(){const body:any={range:syncRange.value,maxFills:maxFills.value,includeExternal:includeExternal.value,repairPartial:repairPartial.value,fillFees:fillFees.value,recalcNet:recalcNet.value};if(syncRange.value==='custom'){body.startTime=new Date(customStart.value).getTime();body.endTime=new Date(customEnd.value).getTime()}return body}
async function runPreview(){syncBusy.value=true;syncError.value='';try{preview.value=await api.tradeRecordSyncPreview(syncBody());syncResult.value=null}catch(error){syncError.value=error instanceof Error?error.message:String(error)}finally{syncBusy.value=false}}
async function applySync(){if(!preview.value)return;syncBusy.value=true;syncError.value='';try{syncResult.value=await api.tradeRecordSyncApply({...syncBody(),syncId:preview.value.syncId,confirm:true});await load()}catch(error){syncError.value=error instanceof Error?error.message:String(error)}finally{syncBusy.value=false}}
const autoSyncLabel=computed(()=>({NOT_STARTED:'尚未启动',WAITING_FOR_PRIVATE_DATA:'等待 Testnet 私有数据就绪',RUNNING:'同步中',BACKFILLING:'正在逐日回填最近交易事实',ACTIVE:'最近一周滚动自动同步运行中',ERROR:'上次自动同步失败，正在等待重试'} as Record<string,string>)[data.value.autoSync?.status]??'自动同步状态未知');
const when=(value:number|null|undefined)=>value?new Date(value).toLocaleString():'—';
let refreshTimer:ReturnType<typeof setInterval>|null=null;
onMounted(()=>{void load();void loadDaily();refreshTimer=setInterval(()=>{void load();void loadDaily()},30_000)});
onUnmounted(()=>{if(refreshTimer)clearInterval(refreshTimer)});
</script>
<template>
  <div class="page-stack">
    <Panel title="最近24小时 · 真实已平仓盈亏" subtitle="按账本 closedAt 确认平仓时间，滚动24小时；按 USDT/USDC 原生币种分别结算，手续费已包含在不含资金费净收益中。">
      <p class="muted">窗口：{{daily?.window?when(daily.window.from)+' — '+when(daily.window.to):'UNKNOWN'}} · 最近采样 {{when(dailyCheckedAt)}} · 数据状态 {{daily?.status??'UNKNOWN'}} <strong v-if="dailyStale" class="error-text">（数据未确认/过期）</strong></p>
      <p v-if="dailyError" class="error-text">24小时只读汇总失败：{{dailyError}}；旧快照不能代表最新收益。</p>
      <div class="grid-2">
        <div v-for="asset in dailyAssetRows" :key="asset.asset" class="kpi">
          <strong>{{asset.asset}}</strong>
          <p class="muted">已证明完整平仓周期 {{asset.cycles??'—'}} · 盈利 {{asset.winningCycles??'—'}} · 亏损 {{asset.losingCycles??'—'}} · 持平 {{asset.flatCycles??'—'}}</p>
          <div class="facts wide">
            <div><dt>盈利合计（不含资金费净值）</dt><dd class="pos">{{amount(asset.grossProfit,asset.asset)}}</dd></div>
            <div><dt>亏损合计（负数）</dt><dd class="neg">{{amount(asset.grossLoss,asset.asset)}}</dd></div>
            <div><dt>24h 净收益（不含资金费）</dt><dd :class="financialClass(asset.netExFunding)">{{amount(asset.netExFunding,asset.asset)}}</dd></div>
            <div><dt>手续费（已计入净收益，不再扣一次）</dt><dd>{{amount(asset.totalFees,asset.asset)}}</dd></div>
          </div>
          <small class="muted">正式含 funding 已确认 {{asset.allInConfirmedCycles??'—'}} / {{asset.cycles??'—'}} 周期；确认全口径收益 {{amount(asset.allInConfirmedNet,asset.asset)}}；Funding UNKNOWN {{asset.fundingUnknownCycles??'—'}}。</small>
        </div>
      </div>
      <p class="muted">覆盖：窗口内已结算记录 {{daily?.coverage?.closedRows??'—'}}；符合双订单关联、唯一 cycle 和账本守恒的周期 {{daily?.coverage?.eligibleClosedCycles??'—'}}；未计入 {{daily?.coverage?.excludedClosedRows??'—'}}；观察到零仓但未结算 {{daily?.coverage?.closedObservedWithoutSettledAt??'—'}}；最近自动同步成功 {{when(daily?.coverage?.lastSyncSuccessAt)}}。</p>
      <p class="muted">统计仅覆盖 Engine 已保留且核实的本地周期，不代表交易所全部成交已完整对账。同步失败或未完成回填时可能缺少历史记录；USDT/USDC 不混合、不按 1:1 冒充 USD。亏损未被正利润抵消隐藏，正式全口径仍严格要求 funding 证据。</p>
    </Panel>
    <Panel title="V3.9.3 交易经济资格" subtitle="账本闭环、ex-funding 与正式含 funding 收益是独立资格；此区域只读，不触发回填或对账。">
      <div class="kpi-grid five">
        <div class="kpi"><span>CLOSED COMPLETE</span><strong>{{data.summary?.closedCompleteCount??'—'}}</strong><small>不要求 funding EXACT</small></div>
        <div class="kpi"><span>本地已实现净收益（不含资金费）</span><strong>{{data.summary?.localAccounting?.exFundingNet==null?'—':money(data.summary.localAccounting.exFundingNet)}}</strong><small>{{data.summary?.localAccounting?.completeCycles??'—'}} 个本地完整周期；资金费未知不影响此项</small></div>
        <div class="kpi"><span>正式净收益合格交易数</span><strong>{{data.summary?.canonicalPnlEligibleCount??'—'}}</strong><small>{{data.summary?.canonicalNetPnlStatus??'—'}}</small></div>
        <div class="kpi"><span>本地已确认全口径净收益</span><strong :class="financialClass(data.summary?.localAccounting?.confirmedAllInNet)">{{data.summary?.localAccounting?.confirmedAllInNet==null?'—':money(data.summary.localAccounting.confirmedAllInNet)}}</strong><small>仅覆盖 {{data.summary?.localAccounting?.confirmedAllInCycles??'—'}}/{{data.summary?.localAccounting?.completeCycles??'—'}} 个本地完整周期</small></div>
        <div class="kpi"><span>本地已确认资金费 / Funding UNKNOWN</span><strong>{{data.summary?.localAccounting?.confirmedFunding==null?'—':money(data.summary.localAccounting.confirmedFunding)}} / {{data.summary?.localAccounting?.fundingUnknownCycles??'—'}}</strong><small>全口径未确认 {{data.summary?.localAccounting?.allInUnconfirmedCycles??'—'}}，其中 Funding EXACT 但权威证据未闭合 {{data.summary?.localAccounting?.fundingExactEvidencePendingCycles??'—'}}；UNKNOWN 不等于 0，也不影响不含资金费收益</small></div>
      </div>
      <p class="muted">Prospective：{{data.summary?.prospective?.status??'—'}}；Entry {{data.summary?.prospective?.entryCycleCount??'—'}} / Closed {{data.summary?.prospective?.closedCycleCount??'—'}} / Canonical {{data.summary?.prospective?.canonicalPnlEligibleCount??'—'}}。缺 Manifest 时保持“—”，不会伪装成 0。</p>
    </Panel>

    <p role="status" :class="data.autoSync?.status==='ERROR'?'error-text':''">{{autoSyncLabel}}。滚动窗口：最近 {{data.autoSync?.rollingDays??7}} 天（{{when(data.autoSync?.windowStart)}} 至 {{when(data.autoSync?.windowEnd)}}）；最近成功：{{when(data.autoSync?.lastSuccessAt)}}。首次启动按天分批回填，追平后每 5 分钟增量同步；最近结果 {{data.autoSync?.lastResult?.created??0}} 新建 / {{data.autoSync?.lastResult?.repaired??0}} 修复 / 系统成交 {{data.autoSync?.lastResult?.systemFills??0}} / 外部成交 {{data.autoSync?.lastResult?.externalFills??0}}。另有 {{data.summary.awaitingReconciliation??0}} 笔已平仓待对账，未计入正式净收益。</p>
    <Panel title="TradeRecord 数据可信度控制台" subtitle="先预览事实窗口，再确认写入；未知手续费显示为 —，不会进入主收益和交易记忆。">
      <div class="toolbar"><div class="toolbar"><button v-for="item in categories" :key="item[0]" class="button" :class="category===item[0]?'primary':'secondary'" @click="category=item[0];page=1;load()">{{item[1]}} <span class="mono">{{item[0]==='ALL'?count('total'):item[0]==='ISSUES'?count('invalid')+count('duplicate')+count('conflict'):count(item[0].toLowerCase())}}</span></button></div><button class="button secondary" @click="openSync">高级手动同步</button></div>
      <div class="toolbar"><div class="toolbar"><select v-model="status" class="select"><option value="">全部账本状态</option><option value="OPEN">OPEN</option><option value="CLOSED">CLOSED</option><option value="INCOMPLETE">INCOMPLETE</option><option value="PARTIALLY_CLOSED">PARTIALLY_CLOSED</option></select><input v-model="symbol" class="input" placeholder="Symbol"/><select v-model="direction" class="select"><option value="">全部方向</option><option value="LONG">LONG</option><option value="SHORT">SHORT</option></select><select v-model="outcome" class="select"><option value="">全部净收益</option><option value="WIN">盈利</option><option value="LOSS">亏损</option></select><button class="button primary" @click="page=1;load()">查询</button><button class="button secondary" @click="reset">重置</button></div><span>{{data.total??0}} 条 · 本页平仓类型（独立于账本完整性）：来源冲突 {{(data.items??[]).filter((r:any)=>r.closeProvenance==='CONFLICT').length}} / 止盈 {{closeKindTally['止盈平仓']??0}} / 人工 {{closeKindTally['人工平仓']??0}} / 未知 {{closeKindTally['未知平仓']??0}}</span></div>
      <p class="muted">全部历史包含部分事实与导入记录。当前仓位、观察到零仓和已结算账本是不同状态；UNKNOWN 不等于零。生命周期最大浮盈/浮亏：UNKNOWN（缺完整同期库存与价格轨迹）。</p><table class="data-table"><thead><tr><th>平仓 / 建仓</th><th>Symbol / 方向</th><th>Entry → Exit</th><th>累计 Entry（原记录）</th><th>交易收益（不含资金费）</th><th>平仓类型</th><th>状态</th><th></th></tr></thead><tbody><tr v-for="row in data.items" :key="row.tradeId" class="clickable" @click="show(row.tradeId)"><td><strong>{{row.closedAt?new Date(row.closedAt).toLocaleString():row.lifecycleDiagnostics?.lifecycleStatus==='OBSERVED_FLAT_AWAITING_LEDGER'?'已观察零仓，账本待对账':'账本未闭合'}}</strong><small>建仓 {{row.openedAt?new Date(row.openedAt).toLocaleString():'首次同步'}}</small></td><td class="symbol">{{row.symbol}}<br/><small :class="row.direction==='SHORT'?'direction-short':'direction-long'">{{row.direction}}</small></td><td>{{row.entryAveragePrice??'—'}} → {{row.exitAveragePrice??'—'}}</td><td>{{row.entryQty??'—'}}<small v-if="row.lifecycleDiagnostics?.quantity?.entryLotMismatch">保留 lots {{row.lifecycleDiagnostics.quantity.retainedLotQuantity}} · 数量待对账</small></td><td :class="financialClass(row.tradingNetPnlExFunding)">{{row.tradingNetPnlExFunding==null?'—':money(row.tradingNetPnlExFunding)}}<small>{{row.moneyAsset??'UNKNOWN'}}</small></td><td><span class="status-badge" :class="closeKind(row).cls" :title="closeKind(row).hint">{{closeKind(row).label}}</span></td><td><StatusBadge :value="row.classification"/> <StatusBadge :value="row.status"/></td><td><button class="button tiny secondary" @click.stop="show(row.tradeId)">详情</button></td></tr></tbody></table><EmptyState v-if="!data.items?.length" title="当前分类暂无记录" detail="默认只显示完整交易；部分事实和问题记录保留在各自分类，不会混入正式收益。点击记录可查看手续费及关联成交事实。"/><div class="toolbar"><span>第 {{data.page??1}} 页 / 共 {{totalPages}} 页</span><span><button class="button secondary" :disabled="page<=1" @click="page--;load()">上一页</button> <button class="button secondary" :disabled="page>=totalPages" @click="page++;load()">下一页</button></span></div>
    </Panel>
    <Panel v-if="detail" :title="`交易详情 · ${detail.record.tradeId}`" subtitle="分类、完整性、手续费和关联成交事实"><div class="facts wide"><div><dt>Symbol / 方向</dt><dd>{{detail.record.symbol}} / {{detail.record.direction}}</dd></div><div><dt>状态 / 分类</dt><dd>{{detail.record.status}} · {{detail.record.classification}}</dd></div><div><dt>Canonical</dt><dd>{{detail.record.canonical?'是':'否'}} {{detail.record.duplicateOf??''}}</dd></div><div><dt>记录 / 手续费完整性</dt><dd>{{detail.record.recordCompleteness}} / {{detail.record.feeCompleteness}}</dd></div><div><dt>毛收益</dt><dd :class="financialClass(detail.record.grossRealizedPnl)">{{detail.record.grossRealizedPnl==null?'—':money(detail.record.grossRealizedPnl)}}</dd></div><div><dt>建仓 / 平仓手续费</dt><dd>{{fee(detail.record.entryFee)}} / {{fee(detail.record.exitFee)}}</dd></div><div><dt>总手续费</dt><dd>{{fee(detail.record.totalFee)}}</dd></div><div><dt>净收益 / ROI</dt><dd>{{detail.record.netPnl==null?'—':money(detail.record.netPnl)}} / {{detail.record.netRoiOnMargin==null?'—':`${detail.record.netRoiOnMargin.toFixed(2)}%`}}</dd></div><div><dt>缺失事实</dt><dd class="mono">{{(detail.record.missingFacts??[]).join(', ')||'无'}}</dd></div><div><dt>修复来源</dt><dd>{{detail.record.repairSource??'—'}}</dd></div></div><h3>生命周期与数量诊断</h3><p class="muted">记录建仓 {{when(detail.record.lifecycleDiagnostics?.recordedOpenedAt)}}；保留 lot 最早成交 {{when(detail.record.lifecycleDiagnostics?.firstRetainedLotFillAt)}}。观察零仓 {{when(detail.record.lifecycleDiagnostics?.observedClosedAt)}} 是本地观察时间，不能代替真实平仓成交时间。历史最大浮盈/浮亏 UNKNOWN，不代表从未出现。</p><pre class="mono json-view">{{JSON.stringify(detail.record.lifecycleDiagnostics,null,2)}}</pre><h3>退出来源身份证据（只读，不重写历史）</h3><p class="muted">冲突不是账本完整性分类；仅在同一成交的身份/角色相矛盾或数量越界时判定，不把 UNKNOWN 伪装为 TP。</p><pre class="mono json-view">{{JSON.stringify({closeProvenance:detail.record.closeProvenance,identityConflict:detail.record.identityConflict,quantityConflict:detail.record.quantityConflict,conflictReasons:detail.record.conflictReasons,proofCoverage:detail.record.proofCoverage,exitIdentityEvidence:detail.record.exitIdentityEvidence},null,2)}}</pre><h3>关联成交事实</h3><pre class="mono json-view">{{JSON.stringify(detail.linkedFills??[],null,2)}}</pre><h3>手续费明细 / 交易记忆</h3><pre class="mono json-view">{{JSON.stringify({feeBreakdown:detail.record.feeBreakdown,experience:detail.experience},null,2)}}</pre></Panel>
    <div v-if="syncOpen" class="modal-backdrop" @click.self="closeSync"><div class="modal"><div class="toolbar"><h2>TradeRecord 手动同步</h2><button class="button secondary" @click="closeSync">关闭</button></div><p class="muted">只读取 Binance 私有成交事实；默认仅纳入可识别的系统成交，外部成交不会自动写入。</p><div class="facts wide"><label>时间窗口<select v-model="syncRange" class="select"><option value="1h">近 1 小时</option><option value="5h">近 5 小时</option><option value="24h">近 24 小时</option><option value="custom">自定义</option></select></label><label>最多成交数<select v-model.number="maxFills" class="select"><option :value="100">100</option><option :value="300">300</option><option :value="500">500</option><option :value="1000">1000</option></select></label></div><div v-if="syncRange==='custom'" class="facts wide"><label>开始时间<input v-model="customStart" class="input" type="datetime-local"/></label><label>结束时间<input v-model="customEnd" class="input" type="datetime-local"/></label></div><div class="toolbar"><label><input v-model="includeExternal" type="checkbox"/> 纳入外部成交</label><label><input v-model="repairPartial" type="checkbox"/> 修复 PARTIAL</label><label><input v-model="fillFees" type="checkbox"/> 回填手续费</label><label><input v-model="recalcNet" type="checkbox"/> 重算净收益</label></div><div class="toolbar"><button class="button primary" :disabled="syncBusy" @click="runPreview">{{syncBusy?'读取中…':'生成 Preview'}}</button><button class="button secondary" :disabled="syncBusy||!preview" @click="applySync">确认并 Apply</button></div><p v-if="syncError" class="error-text">{{syncError}}</p><div v-if="preview" class="json-view"><h3>Preview · {{preview.syncId}}</h3><div class="facts wide"><div><dt>成交事实</dt><dd>{{preview.preview.fills}}（系统 {{preview.preview.systemFills}} / 外部 {{preview.preview.externalFills}}）</dd></div><div><dt>检测周期</dt><dd>{{preview.preview.cyclesDetected}}</dd></div><div><dt>新增 COMPLETE / PARTIAL</dt><dd>{{preview.preview.newComplete}} / {{preview.preview.newPartial}}</dd></div><div><dt>可修复 PARTIAL</dt><dd>{{preview.preview.repairablePartial}}</dd></div><div><dt>重复/冲突/无法闭环</dt><dd>{{preview.preview.duplicates}} / {{preview.preview.conflicts}} / {{preview.preview.unclosable}}</dd></div></div><pre class="mono">{{JSON.stringify(preview.preview.cyclePlans,null,2)}}</pre></div><div v-if="syncResult" class="json-view"><h3>Apply 结果</h3><pre class="mono">{{JSON.stringify({created:syncResult.created,repaired:syncResult.repaired,skipped:syncResult.skipped,newComplete:syncResult.newComplete,newPartial:syncResult.newPartial,experienceCreated:syncResult.experienceCreated,backupPath:syncResult.backupPath},null,2)}}</pre></div></div></div>
  </div>
</template>
