<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue';
import { api } from '../api/client';
import Panel from '../components/Panel.vue';
import EmptyState from '../components/EmptyState.vue';
import StatusBadge from '../components/StatusBadge.vue';
import { money } from '../format';
import { financialClass } from '../positionModel';
import { tradeClosePresentation } from './tradeClosePresentation';

const categories=[['COMPLETE','完整账本'],['PARTIAL','部分事实'],['IMPORTED','导入记录'],['EXTERNAL','外部记录'],['ISSUES','重复/冲突/无效']] as const;
const category=ref('COMPLETE'),data=ref<any>({items:[],total:0,page:1,limit:20,autoSync:{status:'NOT_STARTED'},summary:{counts:{}}}),detail=ref<any>(null),page=ref(1),symbol=ref(''),direction=ref(''),outcome=ref('');
const syncOpen=ref(false),syncRange=ref('5h'),maxFills=ref(500),includeExternal=ref(false),repairPartial=ref(true),fillFees=ref(true),recalcNet=ref(true),customStart=ref(''),customEnd=ref(''),preview=ref<any>(null),syncResult=ref<any>(null),syncBusy=ref(false),syncError=ref('');
const count=(key:string)=>data.value.summary?.counts?.[key]??0;
const fee=(value:number|null|undefined)=>value==null?'—':money(value);
const closeKind=tradeClosePresentation;
const closeKindTally=computed(()=>{const tally:Record<string,number>={};for(const row of data.value.items??[]){const key=closeKind(row).label;tally[key]=(tally[key]??0)+1}return tally});
const totalPages=computed(()=>Math.max(1,Math.ceil((data.value.total??0)/(data.value.limit??20))));
async function load(){const q=new URLSearchParams({page:String(page.value),limit:'20',category:category.value});if(symbol.value)q.set('symbol',symbol.value);if(direction.value)q.set('direction',direction.value);if(outcome.value)q.set('outcome',outcome.value);data.value=await api.tradeRecords(q.toString());}
async function show(id:string){detail.value=await api.tradeRecord(id)}
function reset(){symbol.value='';direction.value='';outcome.value='';page.value=1;void load()}
function openSync(){syncOpen.value=true;preview.value=null;syncResult.value=null;syncError.value=''}
function closeSync(){if(!syncBusy.value)syncOpen.value=false}
function syncBody(){const body:any={range:syncRange.value,maxFills:maxFills.value,includeExternal:includeExternal.value,repairPartial:repairPartial.value,fillFees:fillFees.value,recalcNet:recalcNet.value};if(syncRange.value==='custom'){body.startTime=new Date(customStart.value).getTime();body.endTime=new Date(customEnd.value).getTime()}return body}
async function runPreview(){syncBusy.value=true;syncError.value='';try{preview.value=await api.tradeRecordSyncPreview(syncBody());syncResult.value=null}catch(error){syncError.value=error instanceof Error?error.message:String(error)}finally{syncBusy.value=false}}
async function applySync(){if(!preview.value)return;syncBusy.value=true;syncError.value='';try{syncResult.value=await api.tradeRecordSyncApply({...syncBody(),syncId:preview.value.syncId,confirm:true});await load()}catch(error){syncError.value=error instanceof Error?error.message:String(error)}finally{syncBusy.value=false}}
const autoSyncLabel=computed(()=>({NOT_STARTED:'尚未启动',WAITING_FOR_PRIVATE_DATA:'等待 Testnet 私有数据就绪',RUNNING:'同步中',ACTIVE:'自动同步运行中',COMPLETE:'本次 24 小时同步窗口完成',ERROR:'上次自动同步失败，正在等待重试'} as Record<string,string>)[data.value.autoSync?.status]??'自动同步状态未知');
const when=(value:number|null|undefined)=>value?new Date(value).toLocaleString():'—';
let refreshTimer:ReturnType<typeof setInterval>|null=null;
onMounted(()=>{void load();refreshTimer=setInterval(()=>void load(),30_000)});
onUnmounted(()=>{if(refreshTimer)clearInterval(refreshTimer)});
</script>
<template>
  <div class="page-stack">
    <Panel title="V3.9.3 交易经济资格" subtitle="账本闭环、ex-funding 与正式含 funding 收益是独立资格；此区域只读，不触发回填或对账。">
      <div class="kpi-grid five">
        <div class="kpi"><span>CLOSED COMPLETE</span><strong>{{data.summary?.closedCompleteCount??'—'}}</strong><small>不要求 funding EXACT</small></div>
        <div class="kpi"><span>Trading net ex-funding</span><strong>{{data.summary?money(data.summary.tradingNetExFunding??0):'—'}}</strong><small>{{data.summary?.tradingNetExFundingEligibleCount??'—'}} 条合格账本</small></div>
        <div class="kpi"><span>正式净收益合格交易数</span><strong>{{data.summary?.canonicalPnlEligibleCount??'—'}}</strong><small>{{data.summary?.canonicalNetPnlStatus??'—'}}</small></div>
        <div class="kpi"><span>Canonical net PnL</span><strong :class="financialClass(data.summary?.canonicalNetPnl)">{{data.summary?.canonicalNetPnl==null?'—':money(data.summary.canonicalNetPnl)}}</strong><small>eligible=0 时不显示 0</small></div>
        <div class="kpi"><span>Funding UNKNOWN / Legacy</span><strong>{{data.summary?.fundingUnknownCount??'—'}} / {{data.summary?.legacyEconomicInconsistentCount??'—'}}</strong><small>不等于账本缺失</small></div>
      </div>
      <p class="muted">Prospective：{{data.summary?.prospective?.status??'—'}}；Entry {{data.summary?.prospective?.entryCycleCount??'—'}} / Closed {{data.summary?.prospective?.closedCycleCount??'—'}} / Canonical {{data.summary?.prospective?.canonicalPnlEligibleCount??'—'}}。缺 Manifest 时保持“—”，不会伪装成 0。</p>
    </Panel>

    <p role="status" :class="data.autoSync?.status==='ERROR'?'error-text':''">{{autoSyncLabel}}。自动窗口：{{when(data.autoSync?.windowStart)}} 至 {{when(data.autoSync?.windowEnd)}}；最近成功：{{when(data.autoSync?.lastSuccessAt)}}。启动前 24 小时（含昨日）至启动后 24 小时自动对账；最近结果 {{data.autoSync?.lastResult?.created??0}} 新建 / {{data.autoSync?.lastResult?.repaired??0}} 修复。另有 {{data.summary.awaitingReconciliation??0}} 笔已平仓待对账，未计入正式净收益。</p>
    <Panel title="TradeRecord 数据可信度控制台" subtitle="先预览事实窗口，再确认写入；未知手续费显示为 —，不会进入主收益和交易记忆。">
      <div class="toolbar"><div class="toolbar"><button v-for="item in categories" :key="item[0]" class="button" :class="category===item[0]?'primary':'secondary'" @click="category=item[0];page=1;load()">{{item[1]}} <span class="mono">{{item[0]==='ISSUES'?count('invalid')+count('duplicate')+count('conflict'):count(item[0].toLowerCase())}}</span></button></div><button class="button secondary" @click="openSync">高级手动同步</button></div>
      <div class="toolbar"><div class="toolbar"><input v-model="symbol" class="input" placeholder="Symbol"/><select v-model="direction" class="select"><option value="">全部方向</option><option value="LONG">LONG</option><option value="SHORT">SHORT</option></select><select v-model="outcome" class="select"><option value="">全部净收益</option><option value="WIN">盈利</option><option value="LOSS">亏损</option></select><button class="button primary" @click="page=1;load()">查询</button><button class="button secondary" @click="reset">重置</button></div><span>{{data.total??0}} 条 · 本页平仓类型：止盈 {{closeKindTally['止盈平仓']??0}} / 人工 {{closeKindTally['人工平仓']??0}} / 未知 {{closeKindTally['未知平仓']??0}}</span></div>
      <table class="data-table"><thead><tr><th>平仓 / 建仓</th><th>Symbol / 方向</th><th>Entry → Exit</th><th>数量</th><th>交易收益（不含资金费）</th><th>平仓类型</th><th>状态</th><th></th></tr></thead><tbody><tr v-for="row in data.items" :key="row.tradeId" class="clickable" @click="show(row.tradeId)"><td><strong>{{row.closedAt?new Date(row.closedAt).toLocaleString():'未平仓'}}</strong><small>建仓 {{row.openedAt?new Date(row.openedAt).toLocaleString():'首次同步'}}</small></td><td class="symbol">{{row.symbol}}<br/><small :class="row.direction==='SHORT'?'direction-short':'direction-long'">{{row.direction}}</small></td><td>{{row.entryAveragePrice??'—'}} → {{row.exitAveragePrice??'—'}}</td><td>{{row.entryQty??'—'}}</td><td :class="financialClass(row.tradingNetPnlExFunding)">{{row.tradingNetPnlExFunding==null?'—':money(row.tradingNetPnlExFunding)}}</td><td><span class="status-badge" :class="closeKind(row).cls" :title="closeKind(row).hint">{{closeKind(row).label}}</span></td><td><StatusBadge :value="row.classification"/> <StatusBadge :value="row.status"/></td><td><button class="button tiny secondary" @click.stop="show(row.tradeId)">详情</button></td></tr></tbody></table><EmptyState v-if="!data.items?.length" title="当前分类暂无记录" detail="默认只显示完整交易；部分事实和问题记录保留在各自分类，不会混入正式收益。点击记录可查看手续费及关联成交事实。"/><div class="toolbar"><span>第 {{data.page??1}} 页 / 共 {{totalPages}} 页</span><span><button class="button secondary" :disabled="page<=1" @click="page--;load()">上一页</button> <button class="button secondary" :disabled="page>=totalPages" @click="page++;load()">下一页</button></span></div>
    </Panel>
    <Panel v-if="detail" :title="`交易详情 · ${detail.record.tradeId}`" subtitle="分类、完整性、手续费和关联成交事实"><div class="facts wide"><div><dt>Symbol / 方向</dt><dd>{{detail.record.symbol}} / {{detail.record.direction}}</dd></div><div><dt>状态 / 分类</dt><dd>{{detail.record.status}} · {{detail.record.classification}}</dd></div><div><dt>Canonical</dt><dd>{{detail.record.canonical?'是':'否'}} {{detail.record.duplicateOf??''}}</dd></div><div><dt>记录 / 手续费完整性</dt><dd>{{detail.record.recordCompleteness}} / {{detail.record.feeCompleteness}}</dd></div><div><dt>毛收益</dt><dd :class="financialClass(detail.record.grossRealizedPnl)">{{detail.record.grossRealizedPnl==null?'—':money(detail.record.grossRealizedPnl)}}</dd></div><div><dt>建仓 / 平仓手续费</dt><dd>{{fee(detail.record.entryFee)}} / {{fee(detail.record.exitFee)}}</dd></div><div><dt>总手续费</dt><dd>{{fee(detail.record.totalFee)}}</dd></div><div><dt>净收益 / ROI</dt><dd>{{detail.record.netPnl==null?'—':money(detail.record.netPnl)}} / {{detail.record.netRoiOnMargin==null?'—':`${detail.record.netRoiOnMargin.toFixed(2)}%`}}</dd></div><div><dt>缺失事实</dt><dd class="mono">{{(detail.record.missingFacts??[]).join(', ')||'无'}}</dd></div><div><dt>平仓类型</dt><dd>{{closeKind(detail.record).label}}</dd></div><div><dt>修复来源</dt><dd>{{detail.record.repairSource??'—'}}</dd></div></div><h3>关联成交事实</h3><pre class="mono json-view">{{JSON.stringify(detail.linkedFills??[],null,2)}}</pre><h3>手续费明细 / 交易记忆</h3><pre class="mono json-view">{{JSON.stringify({feeBreakdown:detail.record.feeBreakdown,experience:detail.experience},null,2)}}</pre></Panel>
    <div v-if="syncOpen" class="modal-backdrop" @click.self="closeSync"><div class="modal"><div class="toolbar"><h2>TradeRecord 手动同步</h2><button class="button secondary" @click="closeSync">关闭</button></div><p class="muted">只读取 Binance 私有成交事实；默认仅纳入可识别的系统成交，外部成交不会自动写入。</p><div class="facts wide"><label>时间窗口<select v-model="syncRange" class="select"><option value="1h">近 1 小时</option><option value="5h">近 5 小时</option><option value="24h">近 24 小时</option><option value="custom">自定义</option></select></label><label>最多成交数<select v-model.number="maxFills" class="select"><option :value="100">100</option><option :value="300">300</option><option :value="500">500</option><option :value="1000">1000</option></select></label></div><div v-if="syncRange==='custom'" class="facts wide"><label>开始时间<input v-model="customStart" class="input" type="datetime-local"/></label><label>结束时间<input v-model="customEnd" class="input" type="datetime-local"/></label></div><div class="toolbar"><label><input v-model="includeExternal" type="checkbox"/> 纳入外部成交</label><label><input v-model="repairPartial" type="checkbox"/> 修复 PARTIAL</label><label><input v-model="fillFees" type="checkbox"/> 回填手续费</label><label><input v-model="recalcNet" type="checkbox"/> 重算净收益</label></div><div class="toolbar"><button class="button primary" :disabled="syncBusy" @click="runPreview">{{syncBusy?'读取中…':'生成 Preview'}}</button><button class="button secondary" :disabled="syncBusy||!preview" @click="applySync">确认并 Apply</button></div><p v-if="syncError" class="error-text">{{syncError}}</p><div v-if="preview" class="json-view"><h3>Preview · {{preview.syncId}}</h3><div class="facts wide"><div><dt>成交事实</dt><dd>{{preview.preview.fills}}（系统 {{preview.preview.systemFills}} / 外部 {{preview.preview.externalFills}}）</dd></div><div><dt>检测周期</dt><dd>{{preview.preview.cyclesDetected}}</dd></div><div><dt>新增 COMPLETE / PARTIAL</dt><dd>{{preview.preview.newComplete}} / {{preview.preview.newPartial}}</dd></div><div><dt>可修复 PARTIAL</dt><dd>{{preview.preview.repairablePartial}}</dd></div><div><dt>重复/冲突/无法闭环</dt><dd>{{preview.preview.duplicates}} / {{preview.preview.conflicts}} / {{preview.preview.unclosable}}</dd></div></div><pre class="mono">{{JSON.stringify(preview.preview.cyclePlans,null,2)}}</pre></div><div v-if="syncResult" class="json-view"><h3>Apply 结果</h3><pre class="mono">{{JSON.stringify({created:syncResult.created,repaired:syncResult.repaired,skipped:syncResult.skipped,newComplete:syncResult.newComplete,newPartial:syncResult.newPartial,experienceCreated:syncResult.experienceCreated,backupPath:syncResult.backupPath},null,2)}}</pre></div></div></div>
  </div>
</template>
