import { defineStore } from 'pinia';import { computed,ref } from 'vue';import type { DashboardSnapshot, EntryIntelligencePacket, SystemSettings, UniverseCandidate } from '@zdj/contracts';import { api,residentPosition } from '../api/client';import { connectRealtime } from '../api/realtime';
type RefreshDomain='SNAPSHOT'|'UNIVERSE'|'BRAIN'|'OPERATIONS';
export const useSystemStore=defineStore('system',()=>{
const snapshot=ref<DashboardSnapshot|null>(null),universe=ref<UniverseCandidate[]>([]),selectedEip=ref<EntryIntelligencePacket|null>(null),eipState=ref<any>(null),loading=ref(false),error=ref<string|null>(null),connected=ref(false),equityHistory=ref<{ts:number;value:number}[]>([]);
let stopWs:(()=>void)|null=null,inFlight:Promise<void>|null=null,lastUniverseAt=0,universeGeneration=-1;const pending=new Set<RefreshDomain>();
const chronological=(a:any,b:any,key:string)=>{const av=Number.isFinite(a?.[key])?Number(a[key]):-Infinity,bv=Number.isFinite(b?.[key])?Number(b[key]):-Infinity;return bv-av||String(a?.id??a?.tradeId??'').localeCompare(String(b?.id??b?.tradeId??''));};
const pool=computed(()=>snapshot.value?.pool??[]),positions=computed(()=>[...(snapshot.value?.positions??[])].sort((a,b)=>chronological(a,b,'openedAt'))),entryOrders=computed(()=>snapshot.value?.entryOrders??[]),settings=computed(()=>snapshot.value?.settings??null),attention=computed(()=>{const out:{level:'warn'|'danger';text:string}[]=[];for(const p of positions.value)if(p.tpStatus==='POSITION_FACT_UNRESOLVED')out.push({level:'warn',text:`${p.symbol} TP 未决：交易所仓位事实未裁定，不提交 reduce-only`});else if(p.tpStatus!=='PROTECTED')out.push({level:'danger',text:`${p.symbol} TP ${p.tpStatus}`});for(const h of snapshot.value?.health??[])if(h.status!=='HEALTHY')out.push({level:'warn',text:`${h.label}: ${h.detail}`});return out;});
const applySnapshot=(s:DashboardSnapshot)=>{if(((s as any).snapshotVersion??0)<((snapshot.value as any)?.snapshotVersion??0))return;snapshot.value=s;if(s.account.equityUsd!=null){equityHistory.value.push({ts:s.ts,value:s.account.equityUsd});if(equityHistory.value.length>120)equityHistory.value.splice(0,equityHistory.value.length-120);}};
async function drain(){loading.value=true;error.value=null;try{while(pending.size){const domains=new Set(pending);pending.clear();const s=await api.snapshot();applySnapshot(s);const universeDue=domains.has('UNIVERSE')&&document.visibilityState!=='hidden'&&(universe.value.length===0||Date.now()-lastUniverseAt>=30000||(s.universe as any).generation!==universeGeneration);if(universeDue){const u=await api.universe();universe.value=u.candidates;universeGeneration=u.generation;lastUniverseAt=Date.now();}}}catch(e){error.value=e instanceof Error?e.message:String(e);}finally{loading.value=false;inFlight=null;if(pending.size)void refresh([]);}}
function refresh(domains:RefreshDomain[]=['SNAPSHOT','UNIVERSE']){for(const domain of domains)pending.add(domain);if(!pending.size)pending.add('SNAPSHOT');if(!inFlight)inFlight=drain();return inFlight;}
	async function loadEip(symbol:string){try{const result=await api.eip(symbol) as any;eipState.value=result;selectedEip.value=result.packet??null;}catch(e){const position=positions.value.find(row=>row.symbol===symbol);if(position){try{const detail=await residentPosition(position.id),candidate=universe.value.find(row=>row.symbol===symbol);eipState.value={status:'RESIDENT_INSPECTION',reason:'该标的已有持仓；当前展示只读市场证据，禁止用于新建仓授权'};selectedEip.value={symbol,packetId:`resident_inspection_${symbol}`,selection:candidate??{symbol,rank:0,score:0},market:detail.market,globalRegime:null,microstructure:{},portfolio:{},experience:{sampleSize:0},evidenceCompleteness:candidate?.dataCompleteness??null,contradictions:['ACTIVE_POSITION：只读检查，不允许新建仓']} as any;return;}catch{}}eipState.value={status:'UNAVAILABLE',reason:e instanceof Error?e.message:String(e)};selectedEip.value=null;}}
async function saveSettings(value:SystemSettings){await api.saveSettings(value);await refresh();}
async function blacklistCandidate(value:{symbol?:string;underlying:string;scope:'SYMBOL'|'UNDERLYING';reason:'USER_BLACKLIST'}){await api.blacklistCandidate(value);await refresh();}
async function refreshPool(){await api.refreshPool();await refresh();}async function cancelEntry(id:string){await api.cancelEntry(id);await refresh(['SNAPSHOT']);}async function repairTp(id:string){await api.repairTp(id);await refresh(['SNAPSHOT']);}
function onVisibility(){if(document.visibilityState==='visible')void refresh(['SNAPSHOT','UNIVERSE']);}
function startRealtime(){if(stopWs)return;document.addEventListener('visibilitychange',onVisibility);stopWs=connectRealtime(event=>{const domains=Array.isArray(event?.domains)?event.domains:['SNAPSHOT'];void refresh(domains);},v=>connected.value=v);}
function stopRealtime(){stopWs?.();stopWs=null;document.removeEventListener('visibilitychange',onVisibility);}
return{snapshot,universe,selectedEip,eipState,loading,error,connected,equityHistory,pool,positions,entryOrders,settings,attention,refresh,loadEip,saveSettings,blacklistCandidate,refreshPool,cancelEntry,repairTp,startRealtime,stopRealtime};});
