# Windows 11 x64 C: fixed 48GiB + retain D: system-managed pagefile.
# MODE PLAN=readonly, APPLY=explicit OS setting change (admin), VERIFY=readonly after manual reboot.
# NEVER reboots, stops/starts processes, changes any other driver/Windows security setting.
# This is a capacity mitigation, not a Windows File/FilterManager pool-leak fix.
[CmdletBinding()]
param(
    [ValidateSet('SelfTest','Plan','Apply','Verify')][string]$Mode='Plan',
    [switch]$ConfirmApply
)
$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
$CPageMB=49152
$KeepCFreeGiB=16
$KeepDFreeGiB=16
$regPath='HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management'
function Get-Snapshot {
    $cs=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop
    $settings=@(Get-CimInstance Win32_PageFileSetting -ErrorAction Stop)
    $usage=@(Get-CimInstance Win32_PageFileUsage -ErrorAction Stop)
    $mem=Get-CimInstance Win32_PerfFormattedData_PerfOS_Memory -ErrorAction Stop
    $c=Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='C:'" -ErrorAction Stop
    $d=Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='D:'" -ErrorAction Stop
    $reg=(Get-ItemProperty -LiteralPath $regPath -Name PagingFiles -ErrorAction Stop).PagingFiles
    $crash=Get-ItemProperty -LiteralPath 'HKLM:\SYSTEM\CurrentControlSet\Control\CrashControl' -ErrorAction Stop
    [pscustomobject]@{
        utc=[DateTimeOffset]::UtcNow.ToString('o')
        automaticManaged=[bool]$cs.AutomaticManagedPagefile
        pagefileSettings=@($settings | Select-Object Name,InitialSize,MaximumSize)
        actualPagefiles=@($usage | Select-Object Name,AllocatedBaseSize,CurrentUsage,PeakUsage)
        registryPagingFiles=@($reg)
        dumpType=$crash.CrashDumpEnabled
        dedicatedDumpFile=$(if($crash.PSObject.Properties['DedicatedDumpFile']){[string]$crash.DedicatedDumpFile}else{$null})
        cFreeGiB=[Math]::Round([double]$c.FreeSpace/1GB,3)
        dFreeGiB=[Math]::Round([double]$d.FreeSpace/1GB,3)
        commitUsedGiB=[Math]::Round([double]$mem.CommittedBytes/1GB,3)
        commitLimitGiB=[Math]::Round([double]$mem.CommitLimit/1GB,3)
        commitFreeGiB=[Math]::Round(([double]$mem.CommitLimit-[double]$mem.CommittedBytes)/1GB,3)
        pagedPoolGiB=[Math]::Round([double]$mem.PoolPagedBytes/1GB,3)
        nonpagedPoolGiB=[Math]::Round([double]$mem.PoolNonpagedBytes/1GB,3)
    }
}
function Get-OnlyPagefileDrives {
    param($Snapshot)
    $names=@($Snapshot.actualPagefiles | ForEach-Object {[string]$_.Name})+
        @($Snapshot.pagefileSettings | ForEach-Object {[string]$_.Name})
    foreach($name in $names){
        if($name -notmatch '^[CD]:\\pagefile\.sys$'){
            throw "UNEXPECTED_PAGEFILE_TOPOLOGY: $name ; no changes performed"
        }
    }
}
function Write-LocalReceipt {
    param([string]$Name,$Payload)
    $dir=Join-Path $env:LOCALAPPDATA 'ZDJMITS\diagnostics'
    [IO.Directory]::CreateDirectory($dir)|Out-Null
    $out=Join-Path $dir ($Name+'-'+(Get-Date -Format 'yyyyMMdd-HHmmss')+'.json')
    [IO.File]::WriteAllText($out,($Payload|ConvertTo-Json -Depth 9),[Text.UTF8Encoding]::new($false))
    Write-Host "LOCAL_ONLY_RECEIPT: $out"
}
function Assert-PostSwitchPagefileEntries {
    param([object[]]$Entries)
    foreach($entry in @($Entries)){
        if([string]$entry.Name -notin @('C:\pagefile.sys','D:\pagefile.sys')){
            throw "UNEXPECTED_PAGEFILE_ENTRY_AFTER_SWITCH: $($entry.Name)"
        }
        if([int]$entry.InitialSize -ne 0 -or [int]$entry.MaximumSize -ne 0){
            throw "UNEXPECTED_AUTOGENERATED_PAGEFILE_SIZE: $($entry.Name) min=$($entry.InitialSize) max=$($entry.MaximumSize)"
        }
    }
    $cs=@($Entries | Where-Object {[string]$_.Name -ieq 'C:\pagefile.sys'})
    $ds=@($Entries | Where-Object {[string]$_.Name -ieq 'D:\pagefile.sys'})
    if($cs.Count -gt 1 -or $ds.Count -gt 1){throw 'DUPLICATE_PAGEFILE_SETTING_AFTER_SWITCH'}
    [pscustomobject]@{generatedC=($cs.Count -eq 1); existingD=($ds.Count -eq 1)}
}
if($Mode -eq 'SelfTest'){
    $autoC=[pscustomobject]@{Name='C:\pagefile.sys';InitialSize=0;MaximumSize=0}
    $autoD=[pscustomobject]@{Name='D:\pagefile.sys';InitialSize=0;MaximumSize=0}
    $good=Assert-PostSwitchPagefileEntries -Entries @($autoC,$autoD)
    if(-not $good.generatedC -or -not $good.existingD){throw 'SELFTEST_AUTOGENERATED_C_FAILED'}
    $onlyD=Assert-PostSwitchPagefileEntries -Entries @($autoD)
    if($onlyD.generatedC -or -not $onlyD.existingD){throw 'SELFTEST_D_ONLY_FAILED'}
    $negativeCases=@(
        [pscustomobject]@{label='unknown drive';entries=@([pscustomobject]@{Name='E:\pagefile.sys';InitialSize=0;MaximumSize=0})}
        [pscustomobject]@{label='unexpected size';entries=@([pscustomobject]@{Name='C:\pagefile.sys';InitialSize=123;MaximumSize=500})}
        [pscustomobject]@{label='duplicate C';entries=@($autoC,$autoC)}
    )
    foreach($case in $negativeCases){
        $failed=$false
        try{[void](Assert-PostSwitchPagefileEntries -Entries $case.entries)}catch{$failed=$true}
        if(-not $failed){throw "SELFTEST_UNSAFE_ENTRY_WAS_ACCEPTED case=$($case.label)"}
    }
    Write-Host 'PAGEFILE_WMI_TRANSITION_SELFTEST_PASS: C auto-generated 0/0 supported; unknown/nonzero/duplicate rejected. NO_OS_QUERY_OR_WRITE'
    return
}
$before=Get-Snapshot
Write-Host ("CURRENT: autoManaged={0}; C free={1:N2}GiB D free={2:N2}GiB; COMMIT={3:N2}/{4:N2}GiB free={5:N2}GiB" -f $before.automaticManaged,$before.cFreeGiB,$before.dFreeGiB,$before.commitUsedGiB,$before.commitLimitGiB,$before.commitFreeGiB)
Write-Host 'CURRENT PAGEFILE USAGE:'
$before.actualPagefiles | Format-Table -AutoSize | Out-Host
Write-Host 'CURRENT PAGEFILE SETTINGS:'
$before.pagefileSettings | Format-Table -AutoSize | Out-Host
if($Mode -eq 'Verify'){
    $c=@($before.actualPagefiles | Where-Object {[string]$_.Name -ieq 'C:\pagefile.sys'})
    $d=@($before.actualPagefiles | Where-Object {[string]$_.Name -ieq 'D:\pagefile.sys'})
    $cSetting=@($before.pagefileSettings|Where-Object {[string]$_.Name -ieq 'C:\pagefile.sys'})
    $dSetting=@($before.pagefileSettings|Where-Object {[string]$_.Name -ieq 'D:\pagefile.sys'})
    if($before.automaticManaged -or $c.Count -ne 1 -or $d.Count -ne 1 -or
       $c[0].AllocatedBaseSize -lt 48000 -or
       $cSetting.Count -ne 1 -or $dSetting.Count -ne 1 -or
       [int]$cSetting[0].InitialSize -ne $CPageMB -or [int]$cSetting[0].MaximumSize -ne $CPageMB -or
       [int]$dSetting[0].InitialSize -ne 0 -or [int]$dSetting[0].MaximumSize -ne 0 -or
       $before.commitFreeGiB -lt 70){
       Write-Warning 'PAGEFILE_VERIFY_BLOCKED: no model start permitted. Check after Windows reboot; inspect settings and current commit.'
       Write-LocalReceipt -Name 'pagefile-verify-failed' -Payload $before
       throw 'PAGEFILE_VERIFY_BLOCKED: STOP; do not start any model'
    }
    Write-Host 'PAGEFILE_VERIFY_PASS: C fixed48GiB + D system-managed; host free-commit>=70GiB'
    Write-LocalReceipt -Name 'pagefile-verify-pass' -Payload $before
    return
}
Get-OnlyPagefileDrives -Snapshot $before
$cs=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop
$settings=@(Get-CimInstance Win32_PageFileSetting -ErrorAction Stop)
$cSettings=@($settings|Where-Object {[string]$_.Name -ieq 'C:\pagefile.sys'})
$dSettings=@($settings|Where-Object {[string]$_.Name -ieq 'D:\pagefile.sys'})
$livePagefiles=@($before.actualPagefiles)
$cLive=@($livePagefiles|Where-Object {[string]$_.Name -ieq 'C:\pagefile.sys'})
$dLive=@($livePagefiles|Where-Object {[string]$_.Name -ieq 'D:\pagefile.sys'})
if($cLive.Count -ne 0 -or $cSettings.Count -ne 0){
    throw 'C_PAGEFILE_ALREADY_CONFIGURED: do not overwrite unknown configuration'
}
if($dLive.Count -ne 1 -or $dSettings.Count -gt 0){
    throw 'D_PAGEFILE_BASELINE_NOT_AUTOMATIC: no changes performed'
}
# Previous failed Apply must have restored the exact original auto-managed baseline.
if(@($before.pagefileSettings).Count -ne 0 -or
   @($before.registryPagingFiles).Count -ne 1 -or
   [string]$before.registryPagingFiles[0] -ine '?:\pagefile.sys'){
    throw 'PREVIOUS_PAGEFILE_ROLLBACK_UNVERIFIED: require auto wildcard and zero explicit settings; no change performed'
}
if(-not $before.automaticManaged) {
    throw 'CUSTOM_PAGEFILE_LAYOUT_ALREADY_ACTIVE: inspect actual config before editing'
}
if($before.cFreeGiB -lt 48+$KeepCFreeGiB -or $before.dFreeGiB -lt $KeepDFreeGiB){
    throw ("DISK_SPACE_GUARD: require C free>=64GiB and D free>=16GiB; currently C={0:N2} D={1:N2}" -f $before.cFreeGiB,$before.dFreeGiB)
}
Write-Host 'PAGEFILE_AUTO_BASELINE_VERIFIED: wildcard registry config, zero explicit entries, runtime D pagefile present.'
Write-Host 'PLAN: disable global auto flag; keep D: as 0/0; convert WMI-generated C: from 0/0 to fixed 49152/49152 MiB.'
Write-Host 'PLAN: existing runtime pagefiles remain until user performs an OS restart; preserve crash dump configuration (do not edit CrashControl).'
Write-Host ("ESTIMATED HOST FREE COMMIT AFTER REBOOT IF USAGE IS UNCHANGED: ~{0:N2}GiB; ACTUAL VALUE MUST BE MEASURED" -f ($before.commitFreeGiB+48))
Write-LocalReceipt -Name 'pagefile-before' -Payload $before
if($Mode -eq 'Plan'){Write-Host 'PLAN_ONLY_NO_CHANGES';return}
if(-not $ConfirmApply.IsPresent){throw 'EXPLICIT_CONFIRMATION_REQUIRED: -Mode Apply -ConfirmApply'}
$identity=[Security.Principal.WindowsIdentity]::GetCurrent()
$principal=[Security.Principal.WindowsPrincipal]::new($identity)
if(-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)){
    throw 'ADMINISTRATOR_REQUIRED: open elevated Windows PowerShell; no changes performed'
}
# Verify exact readback just before first write, avoiding silent extra pagefiles.
$beforeWrite=Get-Snapshot
if(-not $beforeWrite.automaticManaged -or
   $beforeWrite.cFreeGiB -lt 48+$KeepCFreeGiB -or
   @($beforeWrite.actualPagefiles).Count -ne 1 -or
   [string]$beforeWrite.actualPagefiles[0].Name -ine 'D:\pagefile.sys' -or
   @($beforeWrite.pagefileSettings).Count -ne 0 -or
   @($beforeWrite.registryPagingFiles).Count -ne 1 -or
   [string]$beforeWrite.registryPagingFiles[0] -ine '?:\pagefile.sys'){
    throw 'CONFIG_CHANGED_SINCE_PLAN: automatic pagefile baseline not intact; no change performed'
}
$changedAuto=$false
$addedD=$false
$addedC=$false
$convertedC=$false
try{
    $cs | Set-CimInstance -Property @{AutomaticManagedPagefile=$false} -ErrorAction Stop
    $changedAuto=$true
    # Automatic mode often has no explicit Win32_PageFileSetting object.
    $afterSwitch=@(Get-CimInstance Win32_PageFileSetting -ErrorAction Stop)
    $classed=Assert-PostSwitchPagefileEntries -Entries $afterSwitch
    # WMI may generate C:\pagefile.sys 0/0 while flipping AutomaticManagedPagefile.
    # Accept ONLY this known-safe placeholder shape. Never overwrite custom data.
    $cGenerated=@($afterSwitch|Where-Object {[string]$_.Name -ieq 'C:\pagefile.sys'})
    $dExisting=@($afterSwitch|Where-Object {[string]$_.Name -ieq 'D:\pagefile.sys'})
    if($dExisting.Count -eq 1){
        # Already system-managed, do not write an unchanged D setting.
        Write-Host 'D_SYSTEM_MANAGED_ENTRY_ALREADY_PRESENT: preserving 0/0.'
    }else{
        [void](New-CimInstance -ClassName Win32_PageFileSetting -Property @{
            Name='D:\pagefile.sys';InitialSize=[uint32]0;MaximumSize=[uint32]0
        } -ErrorAction Stop)
        $addedD=$true
    }
    # Refresh immediately before the C write. If it appeared after the global switch
    # and is still 0/0, convert it IN PLACE instead of incorrectly treating it as
    # a third-party creation. Never overwrite a nonzero/unexpected setting.
    $cExisting=@(Get-CimInstance Win32_PageFileSetting -ErrorAction Stop |
        Where-Object {[string]$_.Name -ieq 'C:\pagefile.sys'})
    if($cExisting.Count -gt 1){throw 'DUPLICATE_C_SETTING_BEFORE_WRITE'}
    if($cExisting.Count -eq 1){
        if([int]$cExisting[0].InitialSize -ne 0 -or
           [int]$cExisting[0].MaximumSize -ne 0){
            throw 'C_PAGEFILE_CONFIG_CHANGED_DURING_APPLY: no overwrite'
        }
        $cExisting[0] | Set-CimInstance -Property @{
            InitialSize=[uint32]$CPageMB;MaximumSize=[uint32]$CPageMB
        } -ErrorAction Stop
        $convertedC=$true
        Write-Host 'WMI_AUTOGENERATED_C_ENTRY_CONVERTED_IN_PLACE: from 0/0 to fixed 49152/49152.'
    }else{
        [void](New-CimInstance -ClassName Win32_PageFileSetting -Property @{
            Name='C:\pagefile.sys';InitialSize=[uint32]$CPageMB;MaximumSize=[uint32]$CPageMB
        } -ErrorAction Stop)
        $addedC=$true
        Write-Host 'C_PAGEFILE_ENTRY_CREATED: fixed 49152/49152.'
    }
    $pending=Get-Snapshot
    $cc=@($pending.pagefileSettings|Where-Object {$_.Name -ieq 'C:\pagefile.sys'})
    $dd=@($pending.pagefileSettings|Where-Object {$_.Name -ieq 'D:\pagefile.sys'})
    if($pending.automaticManaged -or $cc.Count -ne 1 -or $dd.Count -ne 1 -or
       [int]$cc[0].InitialSize -ne $CPageMB -or [int]$cc[0].MaximumSize -ne $CPageMB -or
       [int]$dd[0].InitialSize -ne 0 -or [int]$dd[0].MaximumSize -ne 0){
        throw 'PAGEFILE_PENDING_READBACK_MISMATCH'
    }
    Write-LocalReceipt -Name 'pagefile-pending-reboot' -Payload ([ordered]@{
        before=$before;pending=$pending;requiresManualReboot=$true
    })
    Write-Host 'PAGEFILE_CONFIG_APPLIED_PENDING_REBOOT: C fixed48GiB; D remains system-managed. DO NOT START models yet.'
    Write-Host 'NEXT: operator chooses Windows Restart (this stops the currently running 9B), then run -Mode Verify.'
}catch{
    $failure=$_.Exception.Message
    Write-Warning "PAGEFILE_CONFIG_FAILED: $failure"
    # Best-effort rollback of ONLY the entries created by this invocation.
    # If rollback fails, preserve the existing state and demand manual inspection.
    $rollback=@()
    if($addedC){
        try{
            $cc=@(Get-CimInstance Win32_PageFileSetting -ErrorAction Stop|
                 Where-Object {$_.Name -ieq 'C:\pagefile.sys'})
            foreach($e in $cc){$e|Remove-CimInstance -ErrorAction Stop}
            $rollback+='C_PAGEFILE_ENTRY_DELETED'
        }catch{$rollback+=("C_ROLLBACK_FAILED:"+$_.Exception.Message)}
    }
    if($convertedC){
        try{
            $cc=@(Get-CimInstance Win32_PageFileSetting -ErrorAction Stop|
                 Where-Object {$_.Name -ieq 'C:\pagefile.sys'})
            if($cc.Count -eq 1 -and [int]$cc[0].InitialSize -eq $CPageMB -and
               [int]$cc[0].MaximumSize -eq $CPageMB){
                $cc[0]|Set-CimInstance -Property @{InitialSize=[uint32]0;MaximumSize=[uint32]0} -ErrorAction Stop
                $rollback+='C_AUTOGENERATED_ENTRY_RESTORED_TO_0_0'
            }else{$rollback+='C_AUTO_ENTRY_CHANGED_EXTERNALLY_NO_TOUCH'}
        }catch{$rollback+=("C_AUTOGENERATED_ROLLBACK_FAILED:"+$_.Exception.Message)}
    }
    if($addedD){
        try{
            $dd=@(Get-CimInstance Win32_PageFileSetting -ErrorAction Stop|
                Where-Object {$_.Name -ieq 'D:\pagefile.sys'})
            foreach($e in $dd){$e|Remove-CimInstance -ErrorAction Stop}
            $rollback+='CREATED_D_ENTRY_REMOVED'
        }catch{$rollback+=("D_ROLLBACK_FAILED:"+$_.Exception.Message)}
    }
    if($changedAuto){
        try{
            (Get-CimInstance Win32_ComputerSystem -ErrorAction Stop)|
                Set-CimInstance -Property @{AutomaticManagedPagefile=$true} -ErrorAction Stop
            $rollback+='RESTORED_AUTOMATIC_MANAGEMENT_FLAG'
        }catch{$rollback+=("AUTO_FLAG_ROLLBACK_FAILED:"+$_.Exception.Message)}
    }
    $afterRollback=Get-Snapshot
    if($afterRollback.automaticManaged -and
       ($afterRollback.registryPagingFiles -join '|') -ceq ($before.registryPagingFiles -join '|') -and
       @($afterRollback.pagefileSettings).Count -eq @($before.pagefileSettings).Count){
        $rollback+='ROLLBACK_BASELINE_MATCHED'
    }else{
        $rollback+='ROLLBACK_BASELINE_MISMATCH_INSPECT_BEFORE_REBOOT'
    }
    Write-LocalReceipt -Name 'pagefile-apply-error' -Payload ([ordered]@{
        error=$failure;rollback=$rollback;before=$before;after=$afterRollback
    })
    throw 'PAGEFILE_APPLY_FAILED_INSPECT_LOCAL_RECEIPT; DO_NOT_REBOOT_UNTIL_PENDING_SETTINGS_REVIEWED'
}
