import json,pathlib,gzip,statistics,collections,csv,math,datetime
P=pathlib.Path(__file__).resolve().parent
load=lambda n:json.loads((P/n).read_text(encoding='utf-8-sig'))
s=load('live-snapshot.json')['data'];E=load('analysis-entities-slim.json');T=load('offline-projected-records.json');R=load('linked-primary-runs.json');Q=load('linked-tq-episodes.json');D=load('position-details.json');now=s['ts'];since=now-7*86400000
num=lambda x:isinstance(x,(int,float)) and math.isfinite(x)
def stats(v):
 v=sorted(x for x in v if num(x));return {'n':len(v),'min':v[0] if v else None,'max':v[-1] if v else None,'median':statistics.median(v) if v else None,'mean':statistics.mean(v) if v else None,'p95':v[math.ceil(.95*len(v))-1] if v else None}
def save(n,v):(P/n).write_text(json.dumps(v,ensure_ascii=False,indent=2),encoding='utf-8')
paths={f.stem.split('.')[0]:sorted(json.loads(gzip.decompress(f.read_bytes()))) for f in (P/'mark-paths').glob('*.gz')}
plans={x['planId']:x for x in E['tradePlans']};intents={x['id']:x for x in E['entryIntents']};orders={x['intentId']:x for x in E['entryOrders']};fills={x['fillId']:x for x in E['executionFills']};owners=load('owner-authority.json')
def parse(v):
 if isinstance(v,str):
  try:return json.loads(v)
  except:return {}
 return v if isinstance(v,dict) else {}
def decision(r):return parse(r.get('normalizedPreview')) if r else {}
def excursion(symbol,side,entry,start,end):
 rows=[x for x in paths.get(symbol,[]) if start<=x[0]<=end and x[4]-x[0]<=5000 and x[4]>=x[0]]
 if not rows:return {'status':'UNKNOWN_NO_FRESH_PATH','sampleCount':0}
 sign=1 if side=='LONG' else -1;v=[(sign*(x[1]-entry)/entry*100,x) for x in rows];hi=max(v,key=lambda x:x[0]);lo=min(v,key=lambda x:x[0]);gaps=[rows[0][0]-start]+[b[0]-a[0] for a,b in zip(rows,rows[1:])]+[end-rows[-1][0]];covered=sum(b[0]-a[0] for a,b in zip(rows,rows[1:]) if b[0]-a[0]<=5000)
 above=sum(b[0]-a[0] for a,b in zip(rows,rows[1:]) if b[0]-a[0]<=5000 and sign*(a[1]-entry)>0);below=sum(b[0]-a[0] for a,b in zip(rows,rows[1:]) if b[0]-a[0]<=5000 and sign*(a[1]-entry)<0)
 return {'status':'COMPLETE_SAMPLED' if max(gaps)<=5000 else 'SPARSE_LOWER_BOUNDS_ONLY','sampleCount':len(rows),'sampledMfePct':max(0,hi[0]),'sampledMaePct':max(0,-lo[0]),'sampledLastSignedPct':v[-1][0],'timeToSampledMfeMinutes':(hi[1][0]-start)/60000,'first':rows[0][0],'last':rows[-1][0],'maxGapMs':max(gaps),'coveredAdjacentMinutes':covered/60000,'observedAboveEntryMinutes':above/60000,'observedBelowEntryMinutes':below/60000,'unobservedMinutes':max(0,(end-start-covered)/60000),'basis':'MARK samples, fixed entry anchor; not guaranteed executable fill or full extrema'}
def candle_vol(detail,tf,at):
 ms={'1m':60000,'5m':300000,'15m':900000}[tf];raw=detail.get('market',{}).get('candles',{}).get(tf,[]);bars=sorted([x for x in raw if x.get('isClosed') is True and x.get('closeTime',at+1)<at],key=lambda x:x['closeTime']);last=bars[-21:];expected=(at//ms)*ms-1;continuous=len(last)>=21 and all(b['openTime']-a['openTime']==ms for a,b in zip(last,last[1:]));fresh=bool(last and last[-1]['closeTime']==expected)
 if not continuous or not fresh:return {'status':'UNKNOWN_MISSING_OR_STALE_CLOSED_BARS','bars':len(last),'actualClose':last[-1]['closeTime'] if last else None,'expectedClose':expected}
 tr=[max(b['high']-b['low'],abs(b['high']-a['close']),abs(b['low']-a['close'])) for a,b in zip(last,last[1:])];return {'status':'FRESH_CLOSED_CONTIGUOUS','method':'SMA20_TRUE_RANGE','atr':statistics.mean(tr),'atrPct':statistics.mean(tr)/last[-1]['close']*100,'lastClose':last[-1]['closeTime'],'bars':20}
posrows=[]
for pos in s['positions']:
 detail=D.get(pos['id'],{});at=detail.get('capturedAtMs',now);v=detail.get('data',{});q=v.get('market',{}).get('quote') or {};age=at-q.get('ts',0);fresh=bool(q and 0<=age<=5000);tp=v.get('tp') or next((t for t in E['tpOrders'] if t['id']==pos.get('tpOrderId')),{});entry=pos['entryPrice'];sign=1 if pos['side']=='LONG' else -1;target=tp.get('price');qty=pos['quantity'];planned=pos.get('profitTakePlan') or {};h=planned.get('targetHorizonMinutes');held=(now-pos['openedAt'])/3600000;vol={tf:candle_vol(v,tf,at) for tf in ('1m','5m','15m')};tpdist=sign*(target-entry)/entry*100 if num(target) else None;gross=sign*(target-entry)*qty if num(target) else None;active=[t for t in E['tpOrders'] if t.get('symbol')==pos['symbol'] and t.get('positionId')==pos['id'] and t.get('status') in ('WORKING','PARTIALLY_FILLED','UNKNOWN','SUBMITTING')]
 related=[t for t in T if t.get('cycleId')==pos.get('cycleId')];fees=sum(t.get('entryFee') or 0 for t in related) if related and all(num(t.get('entryFee')) for t in related) else None;expected=qty*target*.0004 if num(target) else None;owner=next((o for o in owners if o['cycleId']==pos.get('cycleId')),None);mark=q.get('mark') if fresh else None;executable=q.get('bid' if sign==1 else 'ask') if fresh else None;spread=(q['ask']-q['bid'])/((q['ask']+q['bid'])/2)*10000 if fresh and q.get('bid') and q.get('ask') else None;atr=vol['15m'].get('atr');x=excursion(pos['symbol'],pos['side'],entry,pos['openedAt'],now)
 posrows.append({'id':pos['id'],'symbol':pos['symbol'],'side':pos['side'],'quoteAsset':pos.get('marginAsset'),'captureAt':now,'detailCaptureAt':at,'openedAt':pos['openedAt'],'heldHours':held,'entry':entry,'qty':qty,'leverage':pos['leverage'],'entryNotionalQuote':qty*entry,'entryNotionalOverCurrentLeverageDiagnostic':qty*entry/pos['leverage'],'marginStatus':'EXACT_ALLOCATED_MARGIN_UNKNOWN_CROSS_POSITION','privateSnapshotUnrealizedPnl':pos['unrealizedPnl'],'privateSnapshotRoiDisplayed':pos.get('unrealizedPnlPercent'),'mark':mark,'executableExitPrice':executable,'quoteAgeMs':age if q else None,'marketFreshness':'FRESH_MIN_FIELD_TIMESTAMP_LE_5000MS' if fresh else 'UNKNOWN_STALE_OR_MISSING','detailError':detail.get('error'),'snapshotQtyEqualsDetail':v.get('position',{}).get('quantity')==qty if v else None,'tpId':tp.get('id'),'tpClientId':tp.get('clientOrderId'),'tpExchangeId':tp.get('exchangeOrderId'),'tpPrice':target,'tpQty':tp.get('quantity'),'tpStatus':tp.get('status'),'tpPositionStatus':pos.get('tpStatus'),'tpLastVerifiedAt':pos.get('tpLastVerifiedAt'),'tpCoverageSource':pos.get('tpCoverageSource'),'tpSource':pos.get('profitTakePlanSource'),'tpDistanceEntryPct':tpdist,'tpDistanceEntryAbsolute':sign*(target-entry) if num(target) else None,'remainingTpDistancePct':sign*(target-executable)/executable*100 if fresh and num(target) else None,'tpGrossQuote':gross,'knownEntryFeeQuote':fees,'expectedExitFeeQuote':expected,'expectedExitFeeBasis':'Settings TAKER0.0004 assumption, not realized fee','knownCostsTpPayoffExFundingQuote':gross-fees-expected if fees is not None and gross is not None else None,'funding':'UNKNOWN','allInNetTpPayoff':'UNKNOWN','spreadBps':spread,'targetHorizonMinutes':h,'targetHorizonExceeded':held*60>h if h else None,'horizonRatio':held*60/h if h else None,'entryTtlNotHoldingHorizon':True,'managementStatus':pos.get('managementStatus'),'ownerAuthority':owner,'addCount':pos.get('addCount',0),'firstAnchorVsCurrentVwap':'CHANGED_COST_BASIS' if pos.get('addCount',0) else 'NO_RECORDED_ADDS','path':x,'volatility':vol,'tpDistanceAtr15m':abs(target-entry)/atr if num(target) and num(atr) and atr>0 else None,'remainingTpDistanceAtr15m':abs(target-executable)/atr if fresh and num(target) and num(atr) and atr>0 else None,'TPWithinHorizonProbability':'UNKNOWN_NO_CALIBRATED_EXECUTABLE_PATH','labels':['HOLD_TOO_LONG_OBSERVED_HORIZON_OVERRUN'] if h and held*60>h else []})
save('position-quality-metrics.json',posrows)
recent=[r for r in T if (r.get('closedAt') or 0)>=since];traderows=[]
for t in recent:
 intent=intents.get(t.get('entryIntentId'),{});run=R.get(t.get('entryRunId'));dec=decision(run);plan=plans.get(intent.get('planId'),{});target=plan.get('targetPrice') or (dec.get('profitTakePlan') or {}).get('targetPrice');h=plan.get('targetHorizonMinutes') or (dec.get('profitTakePlan') or {}).get('targetHorizonMinutes');ep=Q.get(t.get('entryIntentId'));ep=ep.get('data',{}) if ep else {};anchor=ep.get('fillVwap') or t.get('entryAveragePrice');start=ep.get('completeFillAt') or t['openedAt'];end=t['closedAt'];path=excursion(t['symbol'],t['direction'],anchor,start,end);costpct=(t.get('totalFee') or 0)/max(t.get('entryGrossNotional') or 1,1)*100;labels=[]
 if h and t['durationMs']/60000>h:labels.append('HOLD_TOO_LONG_OBSERVED_HORIZON_OVERRUN')
 if t['closeProvenance']=='SYSTEM_MANUAL':labels.append('MANUAL_RESCUE_ACTION_PROVEN_BENEFIT_UNKNOWN')
 if t['closeProvenance']=='CONFLICT':labels.append('PROVENANCE_UNCERTAINTY_OR_MIXED_PATH')
 if path.get('sampledMfePct',0)>costpct and (t.get('tradingNetPnlExFunding') or 0)<0:labels.append('PROFIT_GIVEBACK_SAMPLED_EX_FUNDING_NOT_CAUSAL')
 exact=(t['economicEligibility']['ledgerClosedComplete'] and t['closeProvenance']!='CONFLICT');inp=parse(run.get('inputPreview')) if run else {};packet=inp.get('packet') or {};quoteAt=packet.get('market',{}).get('quote',{}).get('ts');early={str(hor):next((x for x in ep.get('firstFillPath',[]) if x['horizonMs']==hor),{'coverage':'MISSING'}) for hor in (300000,900000,3600000)}
 traderows.append({'tradeId':t['tradeId'],'symbol':t['symbol'],'quoteAsset':'USDC' if t['symbol'].endswith('USDC') else 'USDT','side':t['direction'],'openedAt':t['openedAt'],'closedAt':t['closedAt'],'heldHours':t['durationMs']/3600000,'closeProvenance':t['closeProvenance'],'classification':t['classification'],'ledgerClosedComplete':t['economicEligibility']['ledgerClosedComplete'],'formalCanonicalNetEligible':t['economicEligibility']['canonicalPnlEligible'],'exFundingDiagnosticEligibleNoProvenanceConflict':exact,'gross':t.get('grossRealizedPnl'),'fees':t.get('totalFee'),'funding':t.get('funding'),'exFundingNet':t.get('tradingNetPnlExFunding'),'formalNet':t.get('formalNetPnl'),'target':target,'targetHorizonMinutes':h,'entryTtlMinutes':plan.get('entryTtlMinutes'),'invalidationPredicate':plan.get('invalidationPredicate'),'entryLots':len(t.get('entryLots',[])),'entryRunId':t.get('entryRunId'),'runPresent':bool(run),'model':run.get('model') if run else None,'modelLatencyMs':run.get('latencyMs') if run else None,'quoteAgeAtRunCompleteMs':run['completedAt']-quoteAt if run and num(run.get('completedAt')) and num(quoteAt) else None,'firstFillFromDecisionMs':t['openedAt']-run['completedAt'] if run and num(run.get('completedAt')) else None,'fillSlippageBps':ep.get('fillToIdealBps'),'repriceCount':ep.get('repriceCount'),'confidence':dec.get('confidence'),'setup':dec.get('opportunityType'),'regime':t.get('regime'),'modelRegime':dec.get('marketRegime'),'targetDistanceOriginPct':abs(target-anchor)/anchor*100 if num(target) else None,'earlyPath':early,'path':path,'labels':labels,'netFeeCoverageSampled':path.get('sampledMfePct',0)>costpct if path.get('sampleCount') else None,'feeCoverageBasis':'Known actual full-cycle commissions divided by entry notional; funding/slippage unknown; adds mismatch prevents causal good-entry label','BAD_ENTRY':'UNKNOWN_INCOMPLETE_EARLY_PATH','GOOD_ENTRY_BAD_EXIT':'UNKNOWN_WITHOUT_COMPLETE_EXECUTABLE_COST_PATH'})
save('recent-cycle-quality-metrics.json',traderows)
def cohort(rows):
 vals=[r['exFundingNet'] for r in rows if num(r['exFundingNet'])];return {'n':len(rows),'wins':sum(x>0 for x in vals),'losses':sum(x<0 for x in vals),'winRate':sum(x>0 for x in vals)/len(vals) if vals else None,'netExFundingQuoteSum':sum(vals) if vals else None,'holdingHours':stats([r['heldHours'] for r in rows]),'winningHoldingHours':stats([r['heldHours'] for r in rows if num(r['exFundingNet']) and r['exFundingNet']>0]),'losingHoldingHours':stats([r['heldHours'] for r in rows if num(r['exFundingNet']) and r['exFundingNet']<0]),'tpCycleCount':sum(r['closeProvenance']=='TP' for r in rows),'manualCycleCount':sum(r['closeProvenance']=='SYSTEM_MANUAL' for r in rows),'manualExFundingQuoteSum':sum(r['exFundingNet'] for r in rows if r['closeProvenance']=='SYSTEM_MANUAL' and num(r['exFundingNet'])),'horizonKnown':sum(bool(r['targetHorizonMinutes']) for r in rows),'horizonExceeded':sum(bool(r['targetHorizonMinutes']) and r['heldHours']*60>r['targetHorizonMinutes'] for r in rows),'sampledPathFeeCoverObserved':sum(r['netFeeCoverageSampled'] is True for r in rows),'completeEarly5m':sum(r['earlyPath']['300000'].get('coverage')=='COMPLETE' for r in rows),'completeEarly15m':sum(r['earlyPath']['900000'].get('coverage')=='COMPLETE' for r in rows)}
clean=[r for r in traderows if r['exFundingDiagnosticEligibleNoProvenanceConflict']];summary={'window':{'since':since,'until':now,'weeks':1,'recordsCaptured':len(T),'closedInWeek':len(traderows)},'formalCanonicalEligible':sum(r['formalCanonicalNetEligible'] for r in traderows),'classification':dict(collections.Counter(r['classification'] for r in traderows)),'provenance':dict(collections.Counter(r['closeProvenance'] for r in traderows)),'exFundingDiagnostic':cohort(clean),'ledgerIncludingMixed':cohort([r for r in traderows if r['ledgerClosedComplete']]),'uncertaintyBucket':cohort([r for r in traderows if not r['exFundingDiagnosticEligibleNoProvenanceConflict']]),'quoteBreakdown':{q:cohort([r for r in clean if r['quoteAsset']==q]) for q in ('USDT','USDC')},'symbolBreakdown':{sym:cohort([r for r in clean if r['symbol']==sym]) for sym in sorted(set(r['symbol'] for r in clean))},'regimeBreakdown':{str(reg):cohort([r for r in clean if r['regime']==reg]) for reg in set(r['regime'] for r in clean)},'modelLatencyMs':stats([r['modelLatencyMs'] for r in traderows]),'quoteAgeAtDecisionMs':stats([r['quoteAgeAtRunCompleteMs'] for r in traderows]),'firstFillDelayMs':stats([r['firstFillFromDecisionMs'] for r in traderows]),'fillToIdealBps':stats([r['fillSlippageBps'] for r in traderows]),'predicateDistribution':dict(collections.Counter(r['invalidationPredicate'] for r in traderows)),'open':{'count':len(posrows),'humanManaged':sum(x['managementStatus']=='HUMAN_MANAGED' for x in posrows),'horizonExceeded':sum(x['targetHorizonExceeded'] is True for x in posrows),'marketFresh':sum(x['mark'] is not None for x in posrows),'unknownStaleMarket':sum(x['mark'] is None for x in posrows),'tpEntryPct':stats([x['tpDistanceEntryPct'] for x in posrows]),'remainingTpPctFreshOnly':stats([x['remainingTpDistancePct'] for x in posrows]),'tpSources':dict(collections.Counter(x['tpSource'] for x in posrows)),'holdingHours':stats([x['heldHours'] for x in posrows]),'snapshotUnrealizedQuoteByAsset':{q:sum(x['privateSnapshotUnrealizedPnl'] for x in posrows if x['quoteAsset']==q) for q in ('USDT','USDC')},'detailMissingCount':sum(x['detailError'] is not None for x in posrows)},'metricsPolicy':'No canonical net inference from UNKNOWN funding. Path gaps retained, no interpolation. Numeric sampled excursions are lower bounds; multi-lot fixed anchor not position-level true path. Closed cohort is censored by retained open losers.'}
save('quality-summary.json',summary)
for name,rows in [('position-quality-metrics.csv',posrows),('recent-cycle-quality-metrics.csv',traderows)]:
 with (P/name).open('w',encoding='utf-8-sig',newline='') as f:
  keys=[k for k,v in rows[0].items() if not isinstance(v,(dict,list))];w=csv.DictWriter(f,fieldnames=keys,extrasaction='ignore');w.writeheader();w.writerows(rows)
print(json.dumps(summary,ensure_ascii=True,indent=2))
