import json,pathlib
p=pathlib.Path('docs/reports/v397-trade-entry-exit-quality-review-20261008'); e=json.loads((p/'durable-entities.json').read_text(encoding='utf-8'));t=json.loads((p/'trade-records-bounded.json').read_text(encoding='utf-8'));pr=[r['payload'] for r in json.loads((p/'provenance-cases.json').read_text())]
for sym in ('AAVEUSDT','ETHFIUSDC'):
 r=next(x for x in t if x['symbol']==sym and x.get('direction')=='LONG' and 1791450300000<(x.get('closedAt') or 0)<1791450600000);ids=set(map(str,r['exitOrderIds']));fills=[f for f in e['executionFills'] if f['symbol']==sym and (str(f.get('orderId','')) in ids or str(f.get('clientOrderId','')) in ids)];alllinked=[f for f in e['executionFills'] if f.get('id',f.get('fillId')) in set(r['linkedFillIds'])];out={'record':r,'linkedFills':alllinked,'exitFills':fills,'identityEvidence':[]}
 print(sym,{k:r.get(k) for k in ('tradeId','openedAt','closedAt','entryRunId','entryQty','entryAveragePrice','exitAveragePrice','totalFee','tradingNetPnlExFunding','fundingAttributionStatus','cycleId')});print('fills retained',len(alllinked),'wanted',len(r['linkedFillIds']))
 for f in fills:
  match=lambda o:o.get('symbol')==sym and any(o.get(a) and str(o[a])==str(f.get(b,'')) for a,b in [('exchangeOrderId','orderId'),('clientOrderId','clientOrderId'),('id','orderId'),('id','clientOrderId')])
  regs=[v for v in pr if v['symbol']==sym and ((f.get('clientOrderId') and v.get('clientOrderId')==f['clientOrderId']) or(f.get('orderId') and str(v.get('exchangeOrderId'))==str(f['orderId'])))];manual=[o for o in e['manualOrders'] if o.get('reduceOnly')!=False and match(o)];tp=[o for o in e['tpOrders'] if match(o)];roles=set(v['role'] for v in regs);resolved=[] if len(roles)>1 else regs;finalroles=set(v['role'] for v in resolved)|({'MANUAL'} if manual else set())|({'TP'} if tp else set());x={'fill':f,'registryMatches':regs,'resolveStatus':'UNRESOLVED' if len(roles)>1 or not regs else 'SYSTEM_PROVEN','resolvedRoles':[v['role'] for v in resolved],'manualMatches':manual,'tpMatches':tp,'rolesForProjection':sorted(finalroles)};out['identityEvidence'].append(x);print(json.dumps(x,ensure_ascii=True)[:4500])
 out['relatedTpOrders']=[o for o in e['tpOrders'] if o.get('symbol')==sym and o.get('cycleId')==r['cycleId']];out['linkedIntent']=next((o for o in e['entryIntents'] if o['id']==r['entryIntentId']),None);out['linkedOrder']=next((o for o in e['entryOrders'] if o.get('intentId')==r['entryIntentId']),None);(p/('case-'+sym+'.json')).write_text(json.dumps(out,indent=2),encoding='utf-8')
