from pathlib import Path
import json,datetime,urllib.request,subprocess
out=Path(__file__).resolve().parent
read=lambda n:json.loads((out/n).read_text(encoding='utf-8-sig'))
r=read('runtime-final.json');before=read('runtime-before.json');i=read('source-build-runtime-identity.json');a=read('persistence-safety-before.json');b=read('persistence-safety-after.json');sc=r['scopedUnknown'];book=r['capacityVisibility']['admission']
health=json.load(urllib.request.urlopen('http://127.0.0.1:8080/health',timeout=10))
checks={'ready':health['ready'],'identityClosed':i['verdict']=='IDENTITY_CLOSED','settingsUnchanged':a['settingsVersion']==b['settingsVersion']==r['settingsVersion']==219 and a['settingsPayloadSha256']==b['settingsPayloadSha256'],'testnetLocked':r['productionWriteBoundary']['lockedToTestnet'] and r['environment']=='TESTNET','zeroProductionWrites':r['productionWriteBoundary']['productionWrites']==0,'allPositionsProtected':r['positionCount']==r['takeProfit']['protected'] and r['takeProfit']['missing']==r['takeProfit']['qtyMismatch']==r['takeProfit']['wrongSide']==0,'unknownPartition':sc['entryUnknownHistorical']==sc['entryUnknownProofValid']+sc['entryUnknownOccupyingRisk'],'manualSeparate':sc['manualUnknown']==1 and sc['tpUnknown']==0,'bookScope':book['scope']=='BOOK','firstBlockerSamePass':book['code']==book['firstBinding']['code']==r['authoritativeBlocker']['code'],'unavailableIsFailClosed':book['status']=='UNAVAILABLE' and book['ceilingUsdBySide']=={'LONG':0,'SHORT':0},'onlyCanonicalWorktree':subprocess.check_output(['git','worktree','list','--porcelain'],encoding='utf-8').count('worktree ')==1,'onlyDMitsRoot':[p.name for p in Path('D:/').iterdir() if p.is_dir() and p.name.upper().startswith('MITS')]==['MITS']}
result={'status':'V396_LOCAL_MAIN_SYNC_CLEANUP_RESTART_COMPLETE' if all(checks.values()) else 'V396_LOCAL_MAIN_SYNC_CLEANUP_RESTART_BLOCKED','capturedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'checks':checks,'canonical':'D:/MITS','branch':'main','deployedCommit':read('lifecycle-receipt.json')['gitSha'],'identity':{k:i[k] for k in ['buildId']},'runtime':r['runtime'],'scopedUnknown':sc,'authoritativeBook':book,'healthSummary':{'ready':health['ready'],'status':health['status']},'lifecycleCounts':{'stop':1,'manualStart':1},'writes':r['productionWriteBoundary'],'r3':read('r3-runtime-observation.json')['verdict'],'initialPostStartupCashFlowUnprovided':'Resolved through natural private-data hydration; no setting override. Final BOOK evidence blocker is recorded verbatim.','prestopCheckerAfterRuntime':'persistence-safety-final.json is a conservative pre-stop checklist re-used observationally: noPendingEntry=false due naturally expired UNKNOWN proof; no new lifecycle was attempted. Post-start acceptance permits fail-closed unresolved risk.','limitations':['Snapshots have explicit observation timestamps; runtime is not frozen.','Production/Testnet counters cover instrumented write paths; no external account-wide attestation.','Natural proof expiry/renewal changes scope counts; history was not deleted or force-reconciled.']}
(out/'acceptance-summary.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
(out/'admission-readback.json').write_text(json.dumps(book,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
(out/'unknown-scoped-readback.json').write_text(json.dumps(sc,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
l=read('lifecycle-receipt.json');l['status']='READY_IDENTITY_CLOSED_READ_ONLY_ACCEPTANCE_PASS';l['newInstance']=r['runtime']['instanceId'];l['events'].append({'action':'READ_ONLY_ACCEPTANCE_PASS','at':result['capturedAt']});(out/'lifecycle-receipt.json').write_text(json.dumps(l,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'status':result['status'],'checks':checks},indent=2));assert all(checks.values())
