import type { ModelRunResult } from '../../types.js';
import { createHash } from 'node:crypto';

export class AiRequestError extends Error {constructor(message:string,readonly stage:'REQUEST'|'PARSE',readonly rawOutput:string|null=null,readonly httpStatus:number|null=null,readonly usage:{inputTokens:number|null;outputTokens:number|null}|null=null){super(message);this.name='AiRequestError';}}
export function parseSingleJsonDecision(text:string):Record<string,unknown>{let trimmed=text.trim();if(!trimmed)throw new AiRequestError('AI_OUTPUT_INVALID: exactly one JSON object is required','PARSE',text);const fenced=trimmed.match(/^```(?:json)?\s*([\s\S]*?)\s*```$/i);if(fenced)trimmed=fenced[1]!.trim();if(!trimmed||trimmed.includes('```'))throw new AiRequestError('AI_OUTPUT_INVALID: exactly one JSON object is required','PARSE',text);let value:unknown;try{value=JSON.parse(trimmed);}catch{throw new AiRequestError('AI_OUTPUT_INVALID: exactly one JSON object is required','PARSE',text);}if(!value||typeof value!=='object'||Array.isArray(value))throw new AiRequestError('AI_OUTPUT_INVALID: decision must be one JSON object','PARSE',text);return value as Record<string,unknown>;}
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));

export class OpenAiCompatibleClient {
  private identities=new Map<string,Promise<Record<string,unknown>|null>>();
  constructor(private apiKey='local'){}
  private identity(baseUrl:string,requestedModel:string){const root=baseUrl.replace(/\/$/,'').replace(/\/v1$/,'');if(!this.identities.has(root))this.identities.set(root,(async()=>{try{const response=await fetch(`${root}/props`,{signal:AbortSignal.timeout(2_000)});if(!response.ok)return null;const p:any=await response.json(),template=typeof p.chat_template==='string'?p.chat_template:'';return{requestedModel,modelAlias:p.model_alias??null,modelPath:p.model_path??null,quantization:p.model_ftype??null,contextTokens:p.default_generation_settings?.n_ctx??null,reasoningFormat:p.default_generation_settings?.params?.reasoning_format??null,templateSha256:template?createHash('sha256').update(template).digest('hex'):null,serverBuild:p.build_info??null,observedAt:Date.now()};}catch{return null;}})());return this.identities.get(root)!;}
  /** Read-only, bounded circuit probe. It never submits a completion or alters a service. */
  async probe(baseUrl:string,timeoutMs=2_000):Promise<{ok:boolean;identity:Record<string,unknown>|null;reason:string|null}>{const root=baseUrl.replace(/\/$/,'').replace(/\/v1$/,''),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(`${root}/health`,{signal:controller.signal});if(!response.ok)return{ok:false,identity:null,reason:`AI health HTTP ${response.status}`};await response.text();return{ok:true,identity:await this.identity(baseUrl,''),reason:null};}catch(error){return{ok:false,identity:null,reason:error instanceof Error?error.message:String(error)};}finally{clearTimeout(timer);}}
  async runJson<T>(args:{baseUrl:string;model:string;prompt:string;schemaName:string;timeoutMs:number;jsonSchema?:Record<string,unknown>;maxOutputTokens?:number;parse:(value:unknown)=>T}):Promise<ModelRunResult<T>>{
    const identity=this.identity(args.baseUrl,args.model),deadline=Date.now()+args.timeoutMs,requestStarted=Date.now();let response:Response|undefined,retryMs=0,last:unknown,activeTimer:NodeJS.Timeout|undefined;
    try{for(let attempt=0;attempt<2;attempt++){const remaining=deadline-Date.now();if(remaining<=0)break;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),remaining);try{const candidate=await fetch(`${args.baseUrl.replace(/\/$/,'')}/chat/completions`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${this.apiKey}`},body:JSON.stringify({model:args.model,messages:[{role:'user',content:args.prompt}],temperature:.1,stream:false,max_tokens:args.maxOutputTokens??900,response_format:args.jsonSchema?{type:'json_schema',json_schema:{name:args.schemaName,strict:true,schema:args.jsonSchema}}:{type:'json_object'}}),signal:controller.signal});if(candidate.ok||!(candidate.status>=500||candidate.status===429)){response=candidate;activeTimer=timer;break;}last=new AiRequestError(`AI HTTP ${candidate.status}`,'REQUEST',null,candidate.status);clearTimeout(timer);const retryAfter=Number(candidate.headers.get('retry-after')),delay=Number.isFinite(retryAfter)&&retryAfter>=0?retryAfter*1_000:250;if(attempt===0){const started=Date.now();await sleep(Math.min(delay,Math.max(0,deadline-Date.now())));retryMs+=Date.now()-started;}}catch(error){clearTimeout(timer);last=error;if(attempt===0){const started=Date.now();await sleep(Math.min(250,Math.max(0,deadline-Date.now())));retryMs+=Date.now()-started;}}}
      if(!response)throw new AiRequestError(last instanceof Error?last.message:String(last??'AI endpoint unavailable'),'REQUEST');const requestMs=Date.now()-requestStarted-retryMs;if(!response.ok){const body=await response.text();throw new AiRequestError(`AI HTTP ${response.status}: ${body}`,'REQUEST',body,response.status);}let raw:any;try{raw=await response.json();}catch(error){throw new AiRequestError(`AI response JSON parse failed: ${error instanceof Error?error.message:String(error)}`,'PARSE',null);}const finishReason=typeof raw?.choices?.[0]?.finish_reason==='string'?raw.choices[0].finish_reason:null,content=raw?.choices?.[0]?.message?.content;if(finishReason==='length')throw new AiRequestError('AI_OUTPUT_INVALID: output token limit reached','PARSE',typeof content==='string'?content:JSON.stringify(raw),null,{inputTokens:raw?.usage?.prompt_tokens??null,outputTokens:raw?.usage?.completion_tokens??null});if(typeof content!=='string')throw new AiRequestError('AI response content missing','PARSE',JSON.stringify(raw));const parseStarted=Date.now();let value:T,parsed:Record<string,unknown>;try{parsed=parseSingleJsonDecision(content);value=args.parse(parsed);}catch(error){throw new AiRequestError(error instanceof AiRequestError?error.message:(error instanceof Error?error.message:String(error)),'PARSE',content,null,{inputTokens:raw?.usage?.prompt_tokens??null,outputTokens:raw?.usage?.completion_tokens??null});}return{value,inputTokens:raw?.usage?.prompt_tokens??null,outputTokens:raw?.usage?.completion_tokens??null,finishReason,modelIdentity:await identity,raw:{...raw,__zdjParsedDecision:parsed},timing:{requestMs,parseMs:Date.now()-parseStarted,retryMs}};
    }finally{if(activeTimer)clearTimeout(activeTimer);}
  }
}
