import { terminalDecision, observedOutcome } from '../services/decisionEpisodeFacts.js';
import { parentPort, workerData } from 'node:worker_threads';
import { DatabaseSync } from 'node:sqlite';
import { createHash } from 'node:crypto';
import { analogDistance, breadth, classifyRegime, compactFeature, extractEvidence, liquidityClass, quoteOf, similarityDistribution, stateFingerprint, transitionCandidates, underlyingOf, validateCutoff, type CompactFeature, type RegimeState } from '../services/temporalAlgorithms.js';

type JobMessage={type:'run';reason?:string}|{type:'stop'};
const dbPath=String(workerData?.dbPath??'');
let stopped=false,running=false;
const send=(value:unknown)=>parentPort?.postMessage(value);
const parse=(text:unknown)=>{try{return JSON.parse(String(text??'{}'));}catch{return{};}};
const finite=(value:unknown):number|null=>typeof value==='number'&&Number.isFinite(value)?value:null;
const avg=(values:Array<number|null|undefined>)=>{const rows=values.filter((v):v is number=>typeof v==='number'&&Number.isFinite(v));return rows.length?rows.reduce((a,b)=>a+b,0)/rows.length:null;};
const median=(values:number[])=>{if(!values.length)return 0;const x=[...values].sort((a,b)=>a-b),m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2;};

const outcome=observedOutcome;

function backfill(db:DatabaseSync){
  const rows=db.prepare("SELECT a.run_id,a.payload,e.decision_json previous_decision FROM ai_runs_archive a LEFT JOIN decision_episodes e ON e.run_id=a.run_id WHERE json_extract(a.payload,'$.role')='PRIMARY_BRAIN' AND a.status IN ('COMPLETED','FAILED') AND (e.run_id IS NULL OR json_extract(e.decision_json,'$.factVersion') IS NOT 'V3.8.0' OR json_extract(e.decision_json,'$.status') IS NOT a.status) ORDER BY a.started_at ASC LIMIT 20000").all() as Array<{run_id:string;payload:string;previous_decision?:string}>;
  const nearest=db.prepare('SELECT snapshot_id,payload FROM decision_snapshots WHERE symbol=? AND created_at<=? ORDER BY created_at DESC LIMIT 1');
  const insert=db.prepare(`INSERT OR REPLACE INTO decision_episodes(episode_id,run_id,packet_id,scout_run_id,symbol,underlying,quote_asset,decided_at,direction,decision,completeness,outcome_status,snapshot_id,risk_tier,liquidity_class,regime_state,regime_age_ms,transition_score,fingerprint,would_reuse,return_15m,return_1h,return_4h,return_24h,return_3d,return_7d,mfe,mae,feature_json,decision_json,outcome_json,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`);
  let complete=0,partial=0;db.exec('BEGIN IMMEDIATE');try{for(const row of rows){const run=parse(row.payload),decision=terminalDecision(run,row.previous_decision?parse(row.previous_decision):null),hasAnchor=decision.labelStatus==='VALID',at=Number(decision.anchorPriceAt??decision.decisionAt??0),symbol=String(run.symbol??'').toUpperCase();if(!symbol||!at)continue;let evidence=extractEvidence(run.inputPreview),snapshot:any=null;if(!evidence){const n=nearest.get(symbol,at) as any;if(n&&at-Number(parse(n.payload)?.createdAt??0)<=10*60_000)snapshot={id:n.snapshot_id,...parse(n.payload)};}
      const feature=evidence?compactFeature(evidence):({trend15m:null,trend4h:null,trend1d:null,emaDistanceAtr:null,atrPercent:null,bbPercentile:null,macdAcceleration:null,locationScore:null,spreadBps:null,volume24h:null,riskTier:'UNKNOWN',liquidityClass:'UNKNOWN',btcEthAlignment:'UNKNOWN',multiTfConflict:null,mark:finite(snapshot?.reference?.mark),bar15m:Math.floor(at/900_000),evidenceCompleteness:finite(snapshot?.observationValidity?.weightedCompleteness)} satisfies CompactFeature);
      feature.bar15m=Math.floor(at/900_000);if(feature.liquidityClass==='UNKNOWN')feature.liquidityClass=liquidityClass(feature.volume24h);
      const out:any=hasAnchor?outcome(db,symbol,at,decision.anchorPrice,String(run.direction??''),Date.now(),decision.targetPrice):{factVersion:'V3.8.0',status:'UNKNOWN',labelStatus:'INVALID_LABEL',supersedes:'V3.7.0_MIXED_COMPLETED_AT_AND_EIP_PRICE',horizons:{},mfe:null,mae:null},completeness=evidence&&hasAnchor&&out.horizons.m15?'COMPLETE':'PARTIAL';if(completeness==='COMPLETE')complete++;else partial++;insert.run(`episode_${row.run_id}`,row.run_id,run.packetId??null,null,symbol,underlyingOf(symbol),quoteOf(symbol),Number(decision.decisionAt??at),run.direction??null,run.decision??null,completeness,out.status,snapshot?.id??null,feature.riskTier,feature.liquidityClass,null,null,null,null,0,out.horizons.m15?.value??null,out.horizons.h1?.value??null,out.horizons.h4?.value??null,out.horizons.h24?.value??null,out.horizons.d3?.value??null,out.horizons.d7?.value??null,out.mfe,out.mae,JSON.stringify(feature),JSON.stringify(decision),JSON.stringify(out),Date.now());
    }db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');throw error;}return{inserted:rows.length,complete,partial};
}

function refreshOutcomes(db:DatabaseSync){const rows=db.prepare("SELECT episode_id,symbol,direction,feature_json,decision_json,outcome_json,completeness FROM decision_episodes WHERE json_extract(outcome_json,'$.factVersion') IS NOT 'V3.8.0' OR outcome_status!='OBSERVED' OR return_7d IS NULL ORDER BY decided_at ASC LIMIT 20000").all() as any[],update=db.prepare('UPDATE decision_episodes SET outcome_status=?,return_15m=?,return_1h=?,return_4h=?,return_24h=?,return_3d=?,return_7d=?,mfe=?,mae=?,outcome_json=?,completeness=?,updated_at=? WHERE episode_id=?');let changed=0;db.exec('BEGIN IMMEDIATE');try{for(const row of rows){const f=parse(row.feature_json) as CompactFeature,d=parse(row.decision_json),at=Number(d.anchorPriceAt??0),price=finite(d.anchorPrice);const out:any=at&&price!=null?outcome(db,row.symbol,at,price,row.direction,Date.now(),finite(d.targetPrice)):{factVersion:'V3.8.0',status:'UNKNOWN',labelStatus:'INVALID_LABEL',supersedes:'V3.7.0_MIXED_COMPLETED_AT_AND_EIP_PRICE',horizons:{},mfe:null,mae:null},complete=f.trend15m&&out.horizons?.m15?'COMPLETE':'PARTIAL',outcomeJson=JSON.stringify(out);if(row.outcome_json===outcomeJson&&row.completeness===complete)continue;update.run(out.status,out.horizons?.m15?.value??null,out.horizons?.h1?.value??null,out.horizons?.h4?.value??null,out.horizons?.h24?.value??null,out.horizons?.d3?.value??null,out.horizons?.d7?.value??null,out.mfe,out.mae,outcomeJson,complete,Date.now(),row.episode_id);changed++;}db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');throw error;}return changed;}

function rebuildRegimes(db:DatabaseSync){
  const rows=db.prepare('SELECT symbol,decided_at,feature_json,return_4h,mfe,mae FROM decision_episodes ORDER BY decided_at ASC').all() as any[],buckets=new Map<number,any[]>();for(const row of rows){const at=(Math.floor(Number(row.decided_at)/900_000)+1)*900_000,items=buckets.get(at)??[];items.push(row);buckets.set(at,items);}
  const samples:any[]=[];let previousBreadth=.5,previousSlope=0,age=0,lastBase='';for(const[at,items]of buckets){const unique=new Map<string,any>();for(const x of items)unique.set(String(x.symbol),x);const crossSection=[...unique.values()],features=crossSection.map(x=>parse(x.feature_json) as CompactFeature),b=breadth(features),dominant=Math.max(b.bullish??0,b.bearish??0),slope=dominant-previousBreadth,acceleration=slope-previousSlope,base=(b.bullish??0)>=(b.bearish??0)?'UP':'DOWN';age=base===lastBase?age+1:1;lastBase=base;const extension=median(features.map(x=>Math.abs(x.emaDistanceAtr??0))),conflict=avg(features.map(x=>x.multiTfConflict))??0,outcomeDecay=0,alignmentConflict=0,c=transitionCandidates({dominant,slope,acceleration,ageBars:age,alignmentConflict,extension,outcomeDecay,multiTfConflict:conflict}),state=classifyRegime({bullish:b.bullish,bearish:b.bearish,slope,ageBars:age,transition:c.v3}),confidence=Math.min(1,Math.abs((b.bullish??.5)-(b.bearish??.5))+.35);
    samples.push({at,state,confidence,b,slope,acceleration,age,alignment:alignmentConflict>.5?'CONFLICT':'ALIGNED',volatility:avg(features.map(x=>x.atrPercent)),extension,conflict,c});previousBreadth=dominant;previousSlope=slope;}
  db.exec('BEGIN IMMEDIATE');try{db.exec('DELETE FROM regime_samples; DELETE FROM regime_episodes;');const ins=db.prepare('INSERT INTO regime_samples(sample_at,state,confidence,bullish_breadth,bearish_breadth,neutral_breadth,breadth_slope,breadth_acceleration,breadth_persistence,eligible_count,btc_eth_alignment,volatility,extension,multi_tf_conflict,transition_v1,transition_v2,transition_v3,feature_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');for(const s of samples)ins.run(s.at,s.state,s.confidence,s.b.bullish,s.b.bearish,s.b.neutral,s.slope,s.acceleration,s.age,s.b.eligibleCount,s.alignment,s.volatility,s.extension,s.conflict,s.c.v1,s.c.v2,s.c.v3,JSON.stringify(s));
    const ep=db.prepare('INSERT INTO regime_episodes(regime_id,state,started_at,ended_at,confidence,breadth_start,breadth_peak,breadth_current,transition_score,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)');let start=0,current:any=null;for(let i=0;i<samples.length;i++){const s=samples[i];if(!current||current.state!==s.state){if(current)ep.run(`regime_${current.at}`,current.state,current.at,s.at,avg(samples.slice(start,i).map(x=>x.confidence))??0,current.b.bullish,Math.max(...samples.slice(start,i).map(x=>Math.max(x.b.bullish??0,x.b.bearish??0))),Math.max(samples[i-1].b.bullish??0,samples[i-1].b.bearish??0),samples[i-1].c.v3,Date.now());current=s;start=i;}}if(current){const slice=samples.slice(start),last=slice.at(-1);ep.run(`regime_${current.at}`,current.state,current.at,null,avg(slice.map(x=>x.confidence))??0,current.b.bullish,Math.max(...slice.map(x=>Math.max(x.b.bullish??0,x.b.bearish??0))),Math.max(last.b.bullish??0,last.b.bearish??0),last.c.v3,Date.now());}
    db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');throw error;}return samples;
}
const clamp01=(n:number)=>Math.max(0,Math.min(1,n));
function validateCandidates(db:DatabaseSync,samples:any[]){
  const names=['v1','v2','v3'] as const,results:any={method:'EXPANDING_WINDOW_WALK_FORWARD',lookAheadBars:4,folds:[]};const n=samples.length,bounds=[.55,.7,.85,1].map(x=>Math.floor(n*x));let start=Math.floor(n*.4);
  for(const end of bounds){if(end<=start)continue;const fold:any={train:{from:samples[0]?.at??null,to:samples[start-1]?.at??null,count:start},validation:{from:samples[start]?.at??null,to:samples[end-1]?.at??null,count:end-start},candidates:{}};for(const name of names){let tp=0,fp=0,fn=0,continuation=0,lead:number[]=[];for(let i=start;i<end;i++){const score=samples[i]?.c?.[name]??0,nowDirection=(samples[i].b.bullish??0)>=(samples[i].b.bearish??0)?1:-1;const future=samples.slice(i+1,Math.min(end,i+5)),reversal=future.some(x=>(((x.b.bullish??0)>=(x.b.bearish??0)?1:-1)!==nowDirection));if(score>=65&&reversal){tp++;const j=future.findIndex(x=>(((x.b.bullish??0)>=(x.b.bearish??0)?1:-1)!==nowDirection));if(j>=0)lead.push(j+1);}else if(score>=65){fp++;continuation++;}else if(reversal)fn++;}fold.candidates[name]={trueTransitions:tp,falseTransitions:fp,missedReversals:fn,falseTransitionRate:tp+fp?fp/(tp+fp):null,missedReversalRate:tp+fn?fn/(tp+fn):null,meanLeadBars:avg(lead),continuationAfterHighScore:tp+fp?continuation/(tp+fp):null};}results.folds.push(fold);start=end;}
  db.exec("DELETE FROM research_candidates WHERE kind='TRANSITION'");const ins=db.prepare('INSERT INTO research_candidates(candidate_id,kind,version,source,status,proposed_at,feature_set,formula,code_hash,training_window,validation_windows,metrics_json,hypothesis) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)');for(const name of names){const formulas={v1:'breadth decay + acceleration + BTC/ETH alignment conflict',v2:'V1 + regime age + ATR-normalized extension',v3:'V2 + multi-timeframe conflict; future outcome excluded'},formula=formulas[name],metrics={folds:results.folds.map((f:any)=>({validation:f.validation,...f.candidates[name]}))};ins.run(`transition_${name}`,'TRANSITION',name.toUpperCase(),'CODEX_DETERMINISTIC_RESEARCH','TESTING',Date.now(),formula,formula,createHash('sha256').update(formula).digest('hex'),JSON.stringify(results.folds.map((f:any)=>f.train)),JSON.stringify(results.folds.map((f:any)=>f.validation)),JSON.stringify(metrics),`High ${name.toUpperCase()} score should precede a directional breadth reversal without excessive false transitions.`);}
  return results;
}

function stateGate(db:DatabaseSync,samples:any[]){
  const regimes=new Map(samples.map(x=>[x.at,x])),rows=db.prepare('SELECT run_id,symbol,decided_at,feature_json,decision_json,regime_state,regime_age_ms,transition_score,fingerprint,would_reuse FROM decision_episodes ORDER BY decided_at ASC').all() as any[],last=new Map<string,{fingerprint:string;at:number;feature:CompactFeature}>(),ins=db.prepare(`INSERT INTO state_change_observations(run_id,symbol,observed_at,fingerprint,would_reuse,material_change,reason,scout_tokens,primary_tokens) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(run_id) DO UPDATE SET fingerprint=excluded.fingerprint,would_reuse=excluded.would_reuse,material_change=excluded.material_change,reason=excluded.reason,primary_tokens=excluded.primary_tokens WHERE fingerprint IS NOT excluded.fingerprint OR would_reuse IS NOT excluded.would_reuse OR material_change IS NOT excluded.material_change OR reason IS NOT excluded.reason OR primary_tokens IS NOT excluded.primary_tokens`),updateEpisode=db.prepare('UPDATE decision_episodes SET regime_state=?,regime_age_ms=?,transition_score=?,fingerprint=?,would_reuse=? WHERE run_id=?');let reuse=0,recompute=0,missed=0,primaryTokens=0;db.exec('BEGIN IMMEDIATE');try{for(const row of rows){const f=parse(row.feature_json) as CompactFeature,d=parse(row.decision_json),r=regimes.get(Math.floor(row.decided_at/900_000)*900_000),state=(r?.state??'INSUFFICIENT_DATA') as RegimeState,score=Number(r?.c?.v3??0),ageMs=Number(r?.age??0)*900_000,fp=stateFingerprint(row.symbol,f,state,score),prev=last.get(row.symbol),same=Boolean(prev&&prev.fingerprint===fp&&row.decided_at-prev.at<=15*60_000),material=Boolean(prev&&(Math.abs((f.emaDistanceAtr??0)-(prev.feature.emaDistanceAtr??0))>=.5||f.trend15m!==prev.feature.trend15m)),wouldReuse=same&&!material;if(wouldReuse)reuse++;else recompute++;if(same&&material)missed++;const p=Number(d.inputTokens??0);primaryTokens+=p;ins.run(row.run_id,row.symbol,row.decided_at,fp,wouldReuse?1:0,material?1:0,wouldReuse?'UNCHANGED_FINGERPRINT':material?'MATERIAL_CHANGE':'TTL_OR_BUCKET_CHANGE',0,p);if(row.regime_state!==state||Number(row.regime_age_ms??-1)!==ageMs||Number(row.transition_score??-1)!==score||row.fingerprint!==fp||Number(row.would_reuse)!==(wouldReuse?1:0))updateEpisode.run(state,ageMs,score,fp,wouldReuse?1:0,row.run_id);last.set(row.symbol,{fingerprint:fp,at:row.decided_at,feature:f});}db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');throw error;}
  const roleStats=db.prepare("SELECT json_extract(payload,'$.role') role,COUNT(*) runs,SUM(COALESCE(json_extract(payload,'$.inputTokens'),0)) tokens,SUM(COALESCE(json_extract(payload,'$.latencyMs'),0)) latency FROM ai_runs_archive GROUP BY role").all() as any[],scout=roleStats.find(x=>x.role==='SCOUT'),primary=roleStats.find(x=>x.role==='PRIMARY_BRAIN'),rate=rows.length?reuse/rows.length:0;
  return{mode:'OBSERVE_ONLY',actualAiRuns:{scout:Number(scout?.runs??0),primary:Number(primary?.runs??rows.length)},wouldReuseCount:reuse,wouldRecomputeCount:recompute,estimated9BRunsSaved:Math.round(Number(scout?.runs??0)*rate),estimated27BRunsSaved:reuse,estimated9BTokensSaved:Math.round(Number(scout?.tokens??0)*rate),estimated27BTokensSaved:Math.round(primaryTokens*rate),estimatedGpuSecondsSaved:Math.round((Number(scout?.latency??0)+Number(primary?.latency??0))*rate/1000),missedMaterialStateChangeCount:missed,reuseAccuracyProxy:null,validationStatus:'INCONCLUSIVE_NO_INDEPENDENT_LABEL',aiCadenceChanged:false};
}

function analogSummary(db:DatabaseSync){const current=db.prepare('SELECT * FROM decision_episodes ORDER BY decided_at DESC LIMIT 1').get() as any;if(!current)return{status:'INSUFFICIENT_ANALOGS',analogCount:0};const target=parse(current.feature_json) as CompactFeature,rows=db.prepare('SELECT episode_id,run_id,symbol,underlying,decided_at,risk_tier,liquidity_class,feature_json,return_15m,return_1h,return_4h,return_24h,mfe,mae,outcome_json FROM decision_episodes WHERE decided_at<? AND risk_tier=? AND liquidity_class=? ORDER BY decided_at DESC LIMIT 5000').all(current.decided_at,current.risk_tier,current.liquidity_class) as any[],ranked=rows.map(x=>({...x,distance:analogDistance(target,parse(x.feature_json))})).filter(x=>Number.isFinite(x.distance)&&parse(x.outcome_json)?.factVersion==='V3.8.0'&&Number.isFinite(parse(x.outcome_json)?.horizons?.h24?.maturedAt)&&validateCutoff(current.decided_at,x.decided_at,parse(x.outcome_json).horizons.h24.maturedAt)).sort((a,b)=>a.distance-b.distance).slice(0,50);const counts={sameSymbol:ranked.filter(x=>x.symbol===current.symbol).length,sameUnderlying:ranked.filter(x=>x.underlying===current.underlying&&x.symbol!==current.symbol).length,crossSymbol:ranked.filter(x=>x.underlying!==current.underlying).length};return{status:ranked.length>=10?'SUFFICIENT':'INSUFFICIENT_ANALOGS',queryEpisodeId:current.episode_id,querySymbol:current.symbol,analogCount:ranked.length,counts,similarity:similarityDistribution(ranked.map(x=>x.distance)),outcomes:{return15m:avg(ranked.map(x=>finite(x.return_15m))),return1h:avg(ranked.map(x=>finite(x.return_1h))),return4h:avg(ranked.map(x=>finite(x.return_4h))),return24h:avg(ranked.map(x=>finite(x.return_24h))),mfe:avg(ranked.map(x=>finite(x.mfe))),mae:avg(ranked.map(x=>finite(x.mae)))},top:ranked.slice(0,10).map(x=>({episodeId:x.episode_id,symbol:x.symbol,at:x.decided_at,similarity:1/(1+x.distance),return4h:x.return_4h,mfe:x.mfe,mae:x.mae}))};}

function summary(db:DatabaseSync,samples:any[],walkForward:any,gate:any,analog:any,startedAt:number){const coverage=db.prepare(`SELECT COUNT(*) total,SUM(completeness='COMPLETE') complete,SUM(completeness='PARTIAL') partial,SUM(return_15m IS NOT NULL)c15,SUM(return_1h IS NOT NULL)c1,SUM(return_4h IS NOT NULL)c4,SUM(return_24h IS NOT NULL)c24,SUM(return_3d IS NOT NULL)c3d,SUM(return_7d IS NOT NULL)c7d,MIN(decided_at) first_at,MAX(decided_at) last_at FROM decision_episodes`).get() as any,current=samples.at(-1)??null,episode=db.prepare('SELECT * FROM regime_episodes ORDER BY started_at DESC LIMIT 1').get() as any,candidates=db.prepare("SELECT candidate_id,version,status,feature_set,training_window,validation_windows,metrics_json,hypothesis FROM research_candidates WHERE kind='TRANSITION' ORDER BY version").all().map((x:any)=>({...x,metrics:parse(x.metrics_json)}));return{generatedAt:Date.now(),workerDurationMs:Date.now()-startedAt,mode:'READ_ONLY_SHADOW_RESEARCH',coverage:{total:Number(coverage.total??0),complete:Number(coverage.complete??0),partial:Number(coverage.partial??0),outcomeCoverage15m:coverage.total?Number(coverage.c15)/Number(coverage.total):0,outcomeCoverage1h:coverage.total?Number(coverage.c1)/Number(coverage.total):0,outcomeCoverage4h:coverage.total?Number(coverage.c4)/Number(coverage.total):0,outcomeCoverage24h:coverage.total?Number(coverage.c24)/Number(coverage.total):0,outcomeCoverage3d:coverage.total?Number(coverage.c3d)/Number(coverage.total):0,outcomeCoverage7d:coverage.total?Number(coverage.c7d)/Number(coverage.total):0,firstAt:coverage.first_at??null,lastAt:coverage.last_at??null},currentRegime:current?{state:current.state,ageMs:Number(current.age)*900_000,confidence:current.confidence,bullishBreadth:current.b.bullish,bearishBreadth:current.b.bearish,neutralBreadth:current.b.neutral,breadthSlope:current.slope,breadthAcceleration:current.acceleration,breadthPersistence:current.age,eligibleCount:current.b.eligibleCount,btcEthAlignment:current.alignment,transitionScore:current.c.v3,candidates:current.c,startedAt:episode?.started_at??current.at}:null,timeline:samples.slice(-96).map(x=>({at:x.at,state:x.state,bullish:x.b.bullish,bearish:x.b.bearish,transition:x.c.v3})),transitionResearch:{...walkForward,candidates},historicalAnalog:analog,stateChangeGate:gate,researchBrain:{mode:'IDLE_ONLY_LOW_PRIORITY',allowedOutputs:['HYPOTHESIS','FEATURE_IDEA','ALGORITHM_PROPOSAL','CONTRADICTION','DATA_QUALITY_QUESTION'],entryIntentPermission:false,orderPermission:false,queueLimit:1,maxRunsPerHour:1,hypotheses:candidates.map((x:any)=>({type:'HYPOTHESIS',text:x.hypothesis,status:'TESTING',candidateId:x.candidate_id}))},runtime:{activeResearchJobs:0,backgroundQueue:0,workerCount:1,workerKind:'worker_threads',httpHotPath:false}};}

async function run(){if(running||stopped)return;running=true;const startedAt=Date.now(),db=new DatabaseSync(dbPath);try{db.exec('PRAGMA busy_timeout=5000; PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL; PRAGMA journal_size_limit=67108864;');db.prepare("INSERT OR REPLACE INTO temporal_jobs(job_id,kind,status,started_at,completed_at,cursor,error,metrics_json) VALUES('temporal_rebuild','TEMPORAL_REBUILD','RUNNING',?,NULL,NULL,NULL,'{}')").run(startedAt);const backfillResult=backfill(db),outcomes=refreshOutcomes(db),samples=rebuildRegimes(db),walkForward=validateCandidates(db,samples),gate=stateGate(db,samples),analog=analogSummary(db),value={...summary(db,samples,walkForward,gate,analog,startedAt),backfill:backfillResult,outcomesRefreshed:outcomes};db.prepare("UPDATE temporal_jobs SET status='COMPLETED',completed_at=?,metrics_json=? WHERE job_id='temporal_rebuild'").run(Date.now(),JSON.stringify({durationMs:Date.now()-startedAt,backfillResult,outcomes}));db.prepare('PRAGMA wal_checkpoint(PASSIVE)').get();send({type:'summary',value});}catch(error){try{db.prepare("INSERT OR REPLACE INTO temporal_jobs(job_id,kind,status,started_at,completed_at,cursor,error,metrics_json) VALUES('temporal_rebuild','TEMPORAL_REBUILD','FAILED',?,?,NULL,?,'{}')").run(startedAt,Date.now(),error instanceof Error?error.message:String(error));}catch{}send({type:'error',message:error instanceof Error?error.stack??error.message:String(error)});}finally{db.close();running=false;}}
parentPort?.on('message',(message:JobMessage)=>{if(message.type==='stop'){stopped=true;send({type:'stopped'});return;}if(message.type==='run')void run();});
send({type:'ready'});
