import type {EntryIntelligencePacket,ScoutAnnotation} from '@zdj/contracts';

const decisionFrames=['1m','5m','15m','1h','4h','1d','1w'] as const;
const referenceFrames=['15m','1h','4h','1d','1w'] as const;

/** Lossless wire representation: no candidate, value, proof or authorization is removed. */
export function encodeCandidateMenu(candidates:Record<string,unknown>[]) {
  if (!candidates.length) return { encoding:'COMMON_COLUMNS_V1', common:{}, columns:[], rows:[] };
  const keys=[...new Set(candidates.flatMap(candidate=>Object.keys(candidate)))];
  const common=Object.fromEntries(keys.filter(key=>candidates.every(candidate=>Object.hasOwn(candidate,key)&&JSON.stringify(candidate[key])===JSON.stringify(candidates[0]![key]))).map(key=>[key,candidates[0]![key]]));
  const columns=keys.filter(key=>!Object.hasOwn(common,key));
  // Presence is explicit, so absent fields cannot turn into null or UNKNOWN into zero.
  return {encoding:'COMMON_COLUMNS_V1',common,columns,rows:candidates.map(candidate=>columns.map(key=>Object.hasOwn(candidate,key)?{v:candidate[key]}:{absent:true}))};
}

export function decodeCandidateMenu(menu:ReturnType<typeof encodeCandidateMenu>):Record<string,unknown>[] {
  return menu.rows.map(row=>Object.assign({},menu.common,Object.fromEntries(menu.columns.flatMap((key,i)=>'v' in row[i]! ? [[key,(row[i] as {v:unknown}).v]] : []))));
}

export function compactFactIds(p:EntryIntelligencePacket):string[]{
  const ids=['quote.top','microstructure.book5','execution.envelope','execution.recentTrades','positions.current','economics.entry','portfolio.context','experience.context'];
  for(const tf of decisionFrames)if(p.market.technical[tf])ids.push(`technical.${tf}.confirmed`);
  for(const name of ['btc','eth'] as const)for(const tf of referenceFrames)if((p as any).referenceMarkets?.[name]?.technical?.[tf])ids.push(`${name}.${tf}.confirmed`);
  return ids;
}

const technicalFacts=(technical:any,frames:readonly string[],createdAt:number,prefix='technical')=>Object.fromEntries(frames.flatMap(tf=>{
  const t=technical?.[tf];if(!t)return [];
  return [[tf,{factId:`${prefix}.${tf}.confirmed`,role:tf==='1m'||tf==='5m'?'TIMING':'MARKET_STRUCTURE',observedAt:createdAt,asOf:t.asOf,...(t.barOpenTime!==undefined?{barOpenTime:t.barOpenTime}:{}),barCloseTime:t.barCloseTime??t.asOf,receivedAt:t.receivedAt??createdAt,isClosed:t.isClosed!==false&&t.asOf<=createdAt,source:t.source??'UNKNOWN',trend:t.trend,trendStrength:t.trendStrength,ema8:t.ema8,ema21:t.ema21,ema55:t.ema55,emaSlope21:t.emaSlope21,macdLine:t.macdLine,macdSignal:t.macdSignal,macdHistogram:t.macdHistogram,macdHistogramSlope:t.macdHistogramSlope,macdCrossDirection:t.macdCrossDirection,macdCrossAgeBars:t.macdCrossAgeBars,bbPosition:t.bbPosition,bbBandwidth:t.bbBandwidth,bbUpper:t.bbUpper,bbMiddle:t.bbMiddle,bbLower:t.bbLower,atr14:t.atr14,atrPercent:t.atrPercent,volumeZScore:t.volumeZScore,swingLow:t.recentSwingLow,swingHigh:t.recentSwingHigh,higherHighs:t.higherHighs,higherLows:t.higherLows,lowerHighs:t.lowerHighs,lowerLows:t.lowerLows,...(t.lastClosedBar?{lastClosedBar:t.lastClosedBar}:{missingClosedBarAnchor:true}),...(t.inProgressBar?{inProgressBar:t.inProgressBar}:{})}]];
}));

export function compactEntryFacts(p:EntryIntelligencePacket) {
  const q=p.market.quote,[bandA,bandB]=p.microstructure.reachableBand1m as [number,number],refs=(p as any).referenceMarkets??{};
  const envelope=(p as any).executionEnvelope;if(!envelope)throw new Error('PRE_AI_EXECUTION_ENVELOPE_MISSING');
  const symbolFacts={identity:{symbol:p.symbol,underlying:p.symbol.replace(/(USDT|USDC|BUSD)$/,''),venue:'BINANCE_USDM',packetId:p.packetId,observedAt:p.createdAt,expiresAt:p.expiresAt},quote:{factId:'quote.top',unit:'QUOTE_ASSET_PER_BASE',source:'BINANCE_EXECUTION_MARKET',receivedAt:q.ts,bid:q.bid,ask:q.ask,last:q.last,mark:q.mark},technical:technicalFacts(p.market.technical,decisionFrames,p.createdAt),derivatives:p.market.derivatives,orderBook:{factId:'microstructure.book5',source:'BINANCE_EXECUTION_ORDERBOOK',receivedAt:p.market.orderBook.ts,bids:p.market.orderBook.bids.slice(0,5),asks:p.market.orderBook.asks.slice(0,5),spreadBps:p.microstructure.spreadBps,bidDepthUsd5:p.microstructure.bidDepthUsd5,askDepthUsd5:p.microstructure.askDepthUsd5,imbalance:p.microstructure.imbalance,imbalanceFormula:'(bidDepthUsd5-askDepthUsd5)/(bidDepthUsd5+askDepthUsd5)',imbalanceMeaning:'positive=greater resting bid depth; negative=greater resting ask depth; not trade flow'},recentTrades:{factId:'execution.recentTrades',recentTradedPrices:p.market.recentTradedPrices??[],windowSeconds:300,missingRecentTradeEvidence:!p.market.recentTradedPrices?.length},makerReachableBand1m:{min:Math.min(bandA,bandB),max:Math.max(bandA,bandB)}};
  const reference=(name:'btc'|'eth')=>{const m=refs[name];return m?{symbol:m.symbol,quote:{last:m.quote?.last,mark:m.quote?.mark,change24hPercent:m.quote?.priceChangePercent24h,ts:m.quote?.ts},technical:technicalFacts(m.technical,referenceFrames,p.createdAt,name)}:{missing:true};};
  const fundsOnly=envelope.resourcePolicy==='TESTNET_FUNDS_ONLY';
  const sideFacts=(side:any)=>fundsOnly?{executable:side.executable,maxMarginUsd:side.maxMarginUsd,maxNotionalUsd:side.maxNotionalUsd,maxQuantityUnits:side.maxQuantityUnits,minQuantityUnits:side.minQuantityUnits,legalQuantityRangeUnits:side.legalQuantityRangeUnits,minimumLegalNotionalUsd:side.minimumLegalNotionalUsd,minimumInitialMarginQuote:side.minimumInitialMarginQuote,minimumOrderNotionalQuote:side.minimumOrderNotionalQuote,businessMinimumConfigured:side.businessMinimumConfigured,legalNotionalRangeUsd:side.legalNotionalRangeUsd,authorization:side.authorization,candidateSetHash:side.candidateSetHash,candidateSetFactVersion:side.candidateSetFactVersion,planCandidates:side.planCandidates}:{...side};
  const economics=envelope.economics?{...envelope.economics,...(fundsOnly?{humanManagedExposure:undefined}:{})}:undefined;
  const presentedEnvelope=fundsOnly?{version:envelope.version,entryAuthorizationPolicy:envelope.entryAuthorizationPolicy,resourcePolicy:envelope.resourcePolicy,symbol:envelope.symbol,quoteAsset:envelope.quoteAsset,createdAt:envelope.createdAt,expiresAt:envelope.expiresAt,notice:envelope.notice,account:envelope.account,entryCapitalBudget:envelope.entryCapitalBudget,leverage:envelope.leverage,exchange:envelope.exchange,makerReachableBand:envelope.makerReachableBand,fees:envelope.fees,economics,LONG:sideFacts(envelope.LONG),SHORT:sideFacts(envelope.SHORT),executableSides:envelope.executableSides,noExecutableSide:envelope.noExecutableSide,sideAuthorization:envelope.sideAuthorization,leaseRequiredMarginUsd:envelope.leaseRequiredMarginUsd}:envelope;
  return {contract:'V3.9.7-AUTONOMOUS-DIRECTION-ECONOMIC-MANDATE',CURRENT_POSITION_CONTEXT:p.existingPositionContext??{coverage:'UNKNOWN_CONTEXT_NOT_SUPPLIED',positions:[],notice:'Missing position context does not mean no position.'},MARKET_FACTS:{symbol:symbolFacts,BTC:reference('btc'),ETH:reference('eth'),economics:{factId:'economics.entry',unit:'BPS',...p.economic},...(fundsOnly?{}:{portfolio:{factId:'portfolio.context',...p.portfolio},experience:{factId:'experience.context',...p.experience}}),externalContext:(p as any).externalContext??[]},EXECUTION_ENVELOPE:{...presentedEnvelope,notice:'EXECUTION FACTS ARE NOT MARKET SIGNALS.'},validFactIds:fundsOnly?compactFactIds(p).filter(id=>id!=='portfolio.context'&&id!=='experience.context'):compactFactIds(p)};
}

export function buildCompactBrainPrompt(packet:EntryIntelligencePacket,confirmation?:unknown,_externalContext?:unknown,scout?:ScoutAnnotation|null,candidateChoice=false):string {
  const facts=compactEntryFacts(packet);
  // Change only the presentation copy; the frozen packet and candidate hashes remain original.
  const wireFacts=JSON.parse(JSON.stringify(facts));
  let encodedMenus=false;
  for(const side of ['LONG','SHORT']) {
    const candidates=wireFacts.EXECUTION_ENVELOPE[side]?.planCandidates;
    if(Array.isArray(candidates)&&candidates.length){wireFacts.EXECUTION_ENVELOPE[side].planCandidates=encodeCandidateMenu(candidates);encodedMenus=true;}
  }
  return `You are the single autonomous Entry Primary under protocol V3.9.7. Use only the supplied MARKET_FACTS and EXECUTION_ENVELOPE. You have no tools and no order-write permission.
When EXECUTION_ENVELOPE.resourcePolicy is TESTNET_FUNDS_ONLY, portfolio/history/UNKNOWN/pending risk, gross/direction/cluster exposure, human-managed capacity, position count, stress and risk proofs are audit context only: they MUST NOT cause WAIT, REJECT, smaller sizing or a different direction. Only the published funded legal quantity/price bounds constrain resources. Continue to judge the market opportunity independently; do not manufacture a PLACE.
CURRENT_POSITION_CONTEXT is as-of execution evidence. PARTIAL does not verify complete history; UNKNOWN age is not zero. No independent same-side adds. Opposite inventory alone neither selects nor vetoes a direction. Primary alone chooses a legal frozen candidate.
EXECUTION FACTS ARE NOT MARKET SIGNALS. Capacity asymmetry, leverage, margin, maxNotional, maxQuantityUnits, position slots, permissions and risk headroom may constrain execution but MUST NOT select LONG or SHORT.
Independently test BOTH LONG and SHORT hypotheses from MARKET_FACTS. 15m is the tactical focus, not a direction command. 1m/5m are timing evidence. 1h/4h/1d/1w are context. BTC and ETH reference markets are evidence only. Evaluate EMA, MACD, Bollinger, ATR, volume, swing/HH/HL/LH/LL, order book, recent trades and derivatives without treating any derived trend label as an answer key.
  ${candidateChoice?'Use confirmed bars only; explain conflicting timeframes. Invalidation must oppose the thesis: falling alone does not invalidate SHORT, rising alone does not invalidate LONG. Do not invent an anchor.':''}
Return exactly one unfenced JSON object matching the provided schema. For PLACE_LONG or PLACE_SHORT, first choose the side from market evidence, then choose exactly one selectedCandidateId from that side's EXECUTION_ENVELOPE planCandidates. ${candidateChoice?'Do not output quantityUnits.':'Set quantityUnits to null.'} The candidate menu was generated deterministically from the current Settings, available capital, leverage, exchange filters, costs and target evidence. minimumInitialMarginQuote is a quote-denominated initial-margin floor; minimumOrderNotionalQuote is a distinct Qty×Price floor. Do not reinterpret either value, assume a fixed 100/200 rule, invent a raw quantity, or select a candidate from the opposite side because it has more capacity.
${candidateChoice?`Output executionSelection="FROZEN_CANDIDATE_ID_V1". For PLACE, echo the selected side's candidateSetHash and selectedCandidateId exactly. Omit quantityUnits, idealPrice, acceptablePriceRange, horizonMinutes and profitTakePlan entirely. You select the complete frozen candidate, including its entry price, sizing proof, quantity, leverage, target, target range and horizon; the system materializes those exact facts. Never author, repair or override execution numbers. For non-PLACE, candidateSetHash and selectedCandidateId are null. If no offered candidate fits the independently chosen opportunity, return a non-PLACE decision. A missing, wrong-side, expired or conflicting identity fails closed. No guessing or fallback candidate is permitted.`:`For PLACE, copy the chosen candidate's targetPrice, acceptableTargetRange and targetHorizonMinutes exactly into profitTakePlan. profitTakePlan.targetHorizonMinutes must therefore be one of EXECUTION_ENVELOPE.economics.targetHorizonMinutes and must equal the chosen candidate; this list does not imply a preferred horizon. Any mismatch, unknown id, stale candidateSetHash or later legality failure is rejected and never rounded, clamped, resized or switched to another candidate. idealPrice must be inside acceptablePriceRange and the range must remain compatible with objective maker reachability. If no offered candidate fits the independently chosen opportunity, return a non-PLACE decision. If your chosen side has zero executable candidates, do not flip merely because the other side is executable; return a non-PLACE decision and state the execution conflict.`}
Deterministic opportunity evidence is NON_AUTHORITATIVE about direction and cannot veto or flip your side. It may support timing/location only when it matches your independently chosen side. Scout content is also non-authoritative.
Cite supplied fact IDs in supportingEvidenceRefs. State at least one material counterpoint. Never expose hidden reasoning; provide concise conclusions and evidence references only. Never invent evidence, prices, permissions, fills or probabilities. entryInvalidation is ENTRY_ONLY and never authorizes a close, reversal, market order or risk expansion.
${encodedMenus?`COMMON_COLUMNS_V1 menus are lossless: each row is one candidate, common supplies shared fields; columns[i] names rows[n][i].v; absent:true omits the key. Reconstruct each exact candidate, select its candidateId${candidateChoice?'': ' and copy its TP fields'}. All LONG/SHORT candidates and proofs are present.\n`:''}
${scout?`SCOUT_FACTS_NON_AUTHORITATIVE:${JSON.stringify(scout)}\n`:''}INPUT:${JSON.stringify(wireFacts)}${confirmation?`\nPREVIOUS_WAIT_RECONFIRMATION:${JSON.stringify(confirmation)}\nReassess from fresh facts; the previous decision is context, not authorization or direction.`:''}`;
}
