import type {EntryIntelligencePacket,ScoutAnnotation} from '@zdj/contracts';

const decisionFrames=['1m','5m','15m','1h','4h','1d','1w'] as const;

export function compactFactIds(p:EntryIntelligencePacket):string[]{
  const ids=['quote.top','microstructure.book5','permissions.direction','context.market','execution.recentTrades','economics.entry'];
  for(const tf of decisionFrames)if(p.market.technical[tf])ids.push(`technical.${tf}.confirmed`);
  return ids;
}

export function compactEntryFacts(p:EntryIntelligencePacket) {
  const q=p.market.quote,pi=p.portfolioIntelligence,capital=(p as any).capitalEnvelope,[bandA,bandB]=p.microstructure.reachableBand1m as [number,number];
  const technical=Object.fromEntries(decisionFrames.flatMap(tf=>{
    const t=p.market.technical[tf];if(!t)return [];
    return [[tf,{factId:`technical.${tf}.confirmed`,role:tf==='1m'||tf==='5m'?'TIMING':'MARKET_STRUCTURE',observedAt:p.createdAt,asOf:t.asOf,
      ...(t.barOpenTime!==undefined?{barOpenTime:t.barOpenTime}:{}),barCloseTime:t.barCloseTime??t.asOf,receivedAt:t.receivedAt??p.createdAt,isClosed:t.isClosed!==false&&t.asOf<=p.createdAt,source:t.source??'UNKNOWN',
      trend:t.trend,trendStrength:t.trendStrength,ema8:t.ema8,ema21:t.ema21,ema55:t.ema55,emaSlope21:t.emaSlope21,
      macdLine:t.macdLine,macdSignal:t.macdSignal,macdHistogram:t.macdHistogram,macdHistogramSlope:t.macdHistogramSlope,macdCrossDirection:t.macdCrossDirection,macdCrossAgeBars:t.macdCrossAgeBars,
      bbPosition:t.bbPosition,bbBandwidth:t.bbBandwidth,bbUpper:t.bbUpper,bbMiddle:t.bbMiddle,bbLower:t.bbLower,
      atr14:t.atr14,atrPercent:t.atrPercent,volumeZScore:t.volumeZScore,swingLow:t.recentSwingLow,swingHigh:t.recentSwingHigh,higherHighs:t.higherHighs,higherLows:t.higherLows,lowerHighs:t.lowerHighs,lowerLows:t.lowerLows,
      ...(t.lastClosedBar?{lastClosedBar:t.lastClosedBar}:{missingClosedBarAnchor:true}),
      ...(t.inProgressBar?{inProgressBar:t.inProgressBar}:{})}]];
  }));
  return {contract:'V3.9.3-AUTONOMOUS-DIRECTION',identity:{symbol:p.symbol,underlying:pi?.underlying??p.symbol.replace(/(USDT|USDC|BUSD)$/,''),venue:'BINANCE_USDM',purpose:'TESTNET_EXECUTION',packetId:p.packetId,observedAt:p.createdAt,expiresAt:p.expiresAt},
    quote:{factId:'quote.top',unit:'QUOTE_ASSET_PER_BASE',source:'BINANCE_EXECUTION_MARKET',receivedAt:q.ts,bid:q.bid,ask:q.ask,last:q.last,mark:q.mark},technical,
    execution:{factId:'execution.recentTrades',recentTradedPrices:p.market.recentTradedPrices??[],windowSeconds:300,missingRecentTradeEvidence:!p.market.recentTradedPrices?.length,pricing:'Best quote within authorized band; exact recent traded price required; never invent a distant limit'},
    context:{factId:'context.market',role:'MARKET_CONTEXT_NOT_DIRECTION',change24hPercent:q.priceChangePercent24h,btc15m:p.globalRegime.btc.trend15m,eth15m:p.globalRegime.eth.trend15m,regime:p.globalRegime.regime},
    microstructure:{factId:'microstructure.book5',source:'BINANCE_EXECUTION_ORDERBOOK',receivedAt:p.market.orderBook.ts,unit:'USD_WITHIN_5_LEVELS',spreadBps:p.microstructure.spreadBps,bidDepthUsd5:p.microstructure.bidDepthUsd5,askDepthUsd5:p.microstructure.askDepthUsd5,imbalance:p.microstructure.imbalance,imbalanceFormula:'(bidDepthUsd5-askDepthUsd5)/(bidDepthUsd5+askDepthUsd5)',imbalanceMeaning:'positive=greater resting bid depth; negative=greater resting ask depth; not trade flow',makerReachableBand1m:{min:Math.min(bandA,bandB),max:Math.max(bandA,bandB)}},
    economics:{factId:'economics.entry',unit:'BPS',makerFeeBps:p.economic.makerFeeBps,takerFeeBps:p.economic.takerFeeBps,roundTripCostBps:p.economic.roundTripCostBps,safetyMarginBps:p.economic.safetyMarginBps,configuredTargetMoveBps:p.economic.configuredTargetMoveBps,minimumEconomicEdgeBps:p.economic.minimumEconomicEdgeBps,longSpaceToResistanceBps:p.economic.longSpaceToResistanceBps,shortSpaceToSupportBps:p.economic.shortSpaceToSupportBps,provenance:p.economic.provenance},
    permissions:{factId:'permissions.direction',allowedDirections:pi?.allowedDirections??[],longExceptionRequired:pi?.longExceptionRequired??false,longExecutable:capital?.longExecutable??false,shortExecutable:capital?.shortExecutable??false,longAvailableNotionalUsd:capital?.longAvailableNotionalUsd??0,shortAvailableNotionalUsd:capital?.shortAvailableNotionalUsd??0,minExecutableMarginUsd:capital?.minExecutableMargin??0,capitalGeneration:capital?.capitalGeneration??0,reasonCodes:capital?.reasonCodes??[]},
    validFactIds:compactFactIds(p)};
}

export function buildCompactBrainPrompt(packet:EntryIntelligencePacket,confirmation?:unknown,externalContext?:unknown,scout?:ScoutAnnotation|null):string {
  return `You are the single autonomous Entry Primary under protocol V3.9.3. Use only supplied FACTS. You have no tools and no order-write permission.
Your first responsibility is independent market reasoning. No supplied trend label, timeframe, indicator, deterministic helper, permission field, capacity field, candidate rank, or prior decision is an answer key for LONG or SHORT. Treat every indicator as evidence, not instruction. Explicitly test BOTH LONG and SHORT hypotheses before choosing PLACE_LONG, PLACE_SHORT, WAIT_FOR_PRICE, NO_DIRECTION_EDGE, RESELECT_SYMBOL, or REJECT_CANDIDATE.
1 Direction/structure: infer tradeSide yourself from the complete supplied multi-timeframe evidence. 15m is the primary tactical horizon, but its trend field is only one derived feature and MUST NOT mechanically choose the side. Evaluate raw EMA order/slope, MACD line/signal/histogram/cross/slope, Bollinger position/bandwidth, confirmed swings, ATR/volume and the 1h/4h/1d/1w context when present. Higher timeframes provide regime/risk context and may materially reduce confidence or justify rejecting a tactical counter-trend entry. You may disagree with any single derived trend label. Never infer direction from allowedDirections, executable capital, long/short available notional, payoff-space fields, or which opportunity happens to be present.
2 Timing/location: 1m/5m are timing evidence, not an answer key. PLACE requires a concrete completed/confirmed entry event, an anchor and sufficient remaining support/resistance space. lastClosedBar is the current-bar anchor. Recent trades and maker reachability prove execution legality only, never directional advantage. If your preferred side lacks a completed timing event, use WAIT_FOR_PRICE or RESELECT_SYMBOL rather than flipping side to satisfy an available event.
3 Execution: allowedDirections and capital fields are hard execution permissions only. They can make your chosen side unexecutable, but they never choose the market direction. If the independently preferred side is not executable, reject/wait; never reverse merely to consume capacity.
4 Deterministic opportunity evidence, when supplied, is NON_AUTHORITATIVE about direction. It may prove freshness, a completed timing event, price band, target and economics for the same side only. If it conflicts with your independent directional conclusion, do not PLACE the opposite side just to match it; WAIT/RESELECT/REJECT and state the conflict.
NO_DIRECTION_EDGE is valid whenever evidence is mixed. RANGE_BOUNDARY_REVERSAL remains OFFLINE_ONLY. For microstructure, imbalance=(bidDepth-askDepth)/(bidDepth+askDepth): positive means more resting bid depth and negative more resting ask depth; it is not aggressive trade flow.
Return exactly one unfenced V3.9.3-compatible JSON object matching the provided schema. Each short reason must cite supplied fact IDs. State at least one material counterpoint. Never expose hidden reasoning; provide concise conclusions and evidence references only. entryInvalidation is ENTRY_ONLY and never authorizes a close, reversal, market order or risk expansion.
For PLACE, idealPrice must be inside your acceptable range and justified by supplied price/structure facts. Explain why remaining space exceeds economics.minimumEconomicEdgeBps after costs. An actual recent traded price is still required for execution. Never invent evidence, prices, permissions, fills or probabilities.
${packet.opportunityEvidence?`DETERMINISTIC_OPPORTUNITY_NON_AUTHORITATIVE:${JSON.stringify(packet.opportunityEvidence)}\nUse this only as execution/timing evidence. Its direction is NOT a command and must not override your independent side. If you choose PLACE on the same side, use only a genuinely completed supplied event and constrain price to a demonstrably executable band. If your chosen side differs, do not fabricate an opposite event: WAIT/RESELECT/REJECT.\n`:''}${scout?`SCOUT_FACTS_NON_AUTHORITATIVE:${JSON.stringify(scout)}\nScout cannot establish direction, permissions, timing, or authorization.\n`:''}FACTS:${JSON.stringify(compactEntryFacts(packet))}${externalContext?`\nEXTERNAL_CONTEXT:${JSON.stringify(externalContext)}\nExternal context is auxiliary evidence only; verify freshness and never treat it as an answer key.`:''}${confirmation?`\nPREVIOUS_WAIT_RECONFIRMATION:${JSON.stringify(confirmation)}\nReassess from fresh facts; the previous decision is context, not authorization or direction.`:''}`;
}
