import { describe,it,expect } from 'vitest';
import { chooseMakerPrice,sizeEntryQuantity } from './makerPricing.js';
import type { EntryIntent, MarketSymbolSnapshot } from '@zdj/contracts';

const market={quote:{symbol:'AAAUSDT',last:100,mark:100,bid:99.9,ask:100.1,tickSize:.1,stepSize:.01,minQty:.01,minNotional:5,quoteVolumeUsd24h:1e9,priceChangePercent24h:0,tradeCount24h:1e6,ts:Date.now()},technical:{'1m':{atr14:.5},'5m':{atr14:1}}} as unknown as MarketSymbolSnapshot;
const base={id:'i',symbol:'AAAUSDT',confidence:.8,idealPrice:100,acceptablePriceRange:{min:99,max:101},horizonMinutes:5,leverage:20,createdAt:Date.now(),absoluteExpiresAt:Date.now()+3600000,packetId:'p',brainRunId:'r'} as EntryIntent;
describe('maker boundary',()=>{
  it('long never crosses ask and stays in AI band',()=>{const q=chooseMakerPrice({...base,side:'LONG'},market);expect(q.price).toBeLessThanOrEqual(market.quote.bid);expect(q.price).toBeGreaterThanOrEqual(99);});
  it('short never crosses bid and stays in AI band',()=>{const q=chooseMakerPrice({...base,side:'SHORT'},market);expect(q.price).toBeGreaterThanOrEqual(market.quote.ask);expect(q.price).toBeLessThanOrEqual(101);});
  it('accepts a tick-rounded maker price at a decimal range boundary without widening a tick',()=>{const boundaryMarket={...market,quote:{...market.quote,last:.02669,mark:.02669,bid:.02669,ask:.0267,tickSize:.00001},technical:{...market.technical,'1m':{atr14:.0001},'5m':{atr14:.0002}}} as MarketSymbolSnapshot,minimum=.026690000000000002;const q=chooseMakerPrice({...base,symbol:'4USDT',side:'LONG',idealPrice:minimum,acceptablePriceRange:{min:minimum,max:.02673}},boundaryMarket);expect(q.reachable).toBe(true);expect(q.price).toBe(.02669);expect(q.price).toBeLessThan(minimum);expect(minimum-q.price).toBeLessThan(boundaryMarket.quote.tickSize*1e-9);});
  it('preserves maker and AI-band invariants across randomized inputs',()=>{for(let i=0;i<500;i++){const last=1+Math.random()*50_000,tick=last>=1000?.1:last>=10?.01:.001,spread=tick*(1+Math.floor(Math.random()*5));const m={...market,quote:{...market.quote,last,bid:last-spread,ask:last+spread,tickSize:tick},technical:{...market.technical,'1m':{atr14:last*.002},'5m':{atr14:last*.004}}} as MarketSymbolSnapshot;for(const side of ['LONG','SHORT'] as const){const band={min:last*.98,max:last*1.02};const q=chooseMakerPrice({...base,side,idealPrice:last,acceptablePriceRange:band},m,Math.floor(Math.random()*3));expect(q.reachable).toBe(true);expect(q.price).toBeGreaterThanOrEqual(band.min);expect(q.price).toBeLessThanOrEqual(band.max);expect(side==='LONG'?q.price<=m.quote.bid:q.price>=m.quote.ask).toBe(true);expect(Math.abs(q.price/tick-Math.round(q.price/tick))).toBeLessThan(1e-6);}}});
  it('sizes to step, minQty and minNotional without undersizing',()=>{for(const [notional,price,step,minQty,minNotional] of [[4000,100.12,.001,.001,5],[2,100,.01,.01,5],[10,.1234,1,1,5]] as const){const q=sizeEntryQuantity(notional,price,step,minQty,minNotional);expect(q).toBeGreaterThanOrEqual(minQty);expect(q*price).toBeGreaterThanOrEqual(minNotional-1e-9);expect(Math.abs(q/step-Math.round(q/step))).toBeLessThan(1e-8);}});
});
