import { describe,it,expect } from 'vitest';
import { DynamicPool } from './pool.js';
import type { SystemSettings, UniverseCandidate } from '@zdj/contracts';
const settings={selection:{poolTarget:2,poolMax:3,replacementDelta:4},entryProfile:'CUSTOM'} as unknown as SystemSettings;
const c=(symbol:string,score:number,rank:number)=>({symbol,score,rank,eligible:true,components:{liquidity:score,tradingActivity:score,capitalActivity:score,technicalOpportunity:score,executionReachability:score,dataQuality:score},selectionGeneration:1} as UniverseCandidate);
describe('dynamic pool',()=>{
  it('keeps residents after expiry and does not count two quotes for one underlying',()=>{const p=new DynamicPool(settings),rows=[c('BTCUSDT',90,1),c('BTCUSDC',85,2),c('ETHUSDT',80,3)];p.replenish(rows,1);expect(p.list()).toHaveLength(2);expect(p.list().filter(x=>x.symbol.startsWith('BTC'))).toHaveLength(1);p.replenish(rows,600001);expect(p.list()).toHaveLength(2);});
  it('fills target and replaces weak READY item with materially better candidate',()=>{const p=new DynamicPool(settings);p.replenish([c('A',60,1),c('B',55,2)]);expect(p.list()).toHaveLength(2);p.replenish([c('A',60,2),c('B',55,3),c('C',80,1)]);expect(p.list().map(x=>x.symbol)).toContain('C');});
  it('immediately evicts a position or active-entry symbol and refills',()=>{const p=new DynamicPool(settings);p.replenish([c('A',60,1),c('B',55,2)]);p.markAnalyzing('A');const blocked={...c('A',60,0),eligible:false};p.replenish([blocked,c('B',55,2),c('C',50,3)]);expect(p.list().map(x=>x.symbol)).toEqual(['B','C']);});
  it('updates ranking and generation while holding the configured resident target',()=>{const p=new DynamicPool(settings);p.replenish([c('A',60,1),c('B',55,2)]);const next={...c('A',70,2),selectionGeneration:2};p.replenish([next,{...c('B',80,1),selectionGeneration:2},{...c('C',40,3),selectionGeneration:2},{...c('D',30,4),selectionGeneration:2}]);expect(p.list()).toHaveLength(2);expect(p.list().every(x=>x.selectionGeneration===2)).toBe(true);});
  it('retains an occupied qualified resident as WAITING without making it runnable',()=>{const p=new DynamicPool(settings);p.replenish([c('A',60,1),c('B',55,2)]);p.replenish([{...c('A',60,1),eligible:false,residentEligible:true,pipelineEligible:false},c('B',55,2)]);expect(p.list().map(x=>x.symbol)).toContain('A');expect(p.list().find(x=>x.symbol==='A')?.state).toBe('WAITING');});
  it('keeps non-runnable admitted candidates visible but separate from READY',()=>{const p=new DynamicPool(settings),waiting={...c('WAITUSDT',70,1),pipelineEligible:false};p.replenish([waiting,c('READYUSDT',60,2)]);expect(p.list().find(x=>x.symbol==='WAITUSDT')?.state).toBe('WAITING');expect(p.list().find(x=>x.symbol==='READYUSDT')?.state).toBe('READY');});
  it('does not let WAITING residents consume the execution-ready target',()=>{const cfg={...(settings as any),selection:{...settings.selection,poolTarget:20,poolMax:24}} as any,p=new DynamicPool(cfg),waiting=Array.from({length:20},(_,i)=>({...c(`W${i}USDT`,100-i,i+1),pipelineEligible:false,residentEligible:true})),ready=Array.from({length:10},(_,i)=>({...c(`R${i}USDT`,50-i,21+i),residentEligible:true}));p.replenish(waiting);expect(p.list().filter(x=>x.state==='READY')).toHaveLength(0);p.replenish([...waiting,...ready]);expect(p.list().filter(x=>x.state==='READY')).toHaveLength(10);expect(p.list().length).toBeLessThanOrEqual(24);});
  it('uses the configured 10/12 target without BALANCED profile override',()=>{const p=new DynamicPool({...(settings as any),entryProfile:'BALANCED',selection:{...settings.selection,poolTarget:10,poolMax:12}} as any),rows=Array.from({length:12},(_,i)=>c(`S${i}USDT`,90-i,i+1));expect(p.replenish(rows)).toHaveLength(10);});
  it('uses scheduler fairness without lowering admission quality',()=>{const p=new DynamicPool(settings),core={...c('BTCUSDT',40,3),schedulerPriority:1_000_100},high=c('SOLUSDT',90,1),blocked={...c('BADUSDT',99,2),eligible:false,schedulerPriority:2_000_000};p.replenish([high,blocked,core]);expect(p.list().map(x=>x.symbol)).toEqual(['SOLUSDT','BTCUSDT']);expect(p.list().map(x=>x.symbol)).not.toContain('BADUSDT');});
});
