import { describe,it,expect } from 'vitest';
import { DynamicPool } from './pool.js';
import type { SystemSettings, UniverseCandidate } from '@zdj/contracts';
const settings={selection:{poolTarget:2,poolMax:3,replacementDelta:4},entryProfile:'CUSTOM'} as unknown as SystemSettings;
const c=(symbol:string,score:number,rank:number)=>({symbol,score,rank,eligible:true,components:{liquidity:score,tradingActivity:score,capitalActivity:score,technicalOpportunity:score,executionReachability:score,dataQuality:score},selectionGeneration:1} as UniverseCandidate);
describe('dynamic pool',()=>{
  it('replaces a high-score preflight-blocked resident with a lower-score legal dispatch candidate',()=>{const p=new DynamicPool({...settings,selection:{...settings.selection,poolMax:2,poolTarget:1}} as any),rows=[c('AUSDT',99,1),c('BUSDT',98,2),c('CUSDT',10,3)];p.replenish(rows);p.replenish(rows,Date.now(),new Set(['CUSDT']));expect(p.readyList().map(x=>x.symbol)).toEqual(['CUSDT']);expect(p.list()).toHaveLength(2);expect(rows[0]!.eligible).toBe(true);});
  it('keeps residents after expiry and does not count two quotes for one underlying',()=>{const p=new DynamicPool(settings),rows=[c('BTCUSDT',90,1),c('BTCUSDC',85,2),c('ETHUSDT',80,3)];p.replenish(rows,1);expect(p.list()).toHaveLength(2);expect(p.list().filter(x=>x.symbol.startsWith('BTC'))).toHaveLength(1);p.replenish(rows,600001);expect(p.list()).toHaveLength(2);});
  it('fills target and replaces weak READY item with materially better candidate',()=>{const p=new DynamicPool(settings);p.replenish([c('A',60,1),c('B',55,2)]);expect(p.list()).toHaveLength(2);p.replenish([c('A',60,2),c('B',55,3),c('C',80,1)]);expect(p.list().map(x=>x.symbol)).toContain('C');});
  it('immediately evicts a position or active-entry symbol and refills',()=>{const p=new DynamicPool(settings);p.replenish([c('A',60,1),c('B',55,2)]);p.markAnalyzing('A');const blocked={...c('A',60,0),eligible:false};p.replenish([blocked,c('B',55,2),c('C',50,3)]);expect(p.list().map(x=>x.symbol)).toEqual(['B','C']);});
  it('updates ranking and generation while holding the configured resident limit',()=>{const p=new DynamicPool(settings);p.replenish([c('A',60,1),c('B',55,2)]);const next={...c('A',70,2),selectionGeneration:2};p.replenish([next,{...c('B',80,1),selectionGeneration:2},{...c('C',40,3),selectionGeneration:2},{...c('D',30,4),selectionGeneration:2}]);expect(p.list()).toHaveLength(3);expect(p.list().every(x=>x.selectionGeneration===2)).toBe(true);});
  it('retains an occupied qualified resident as WAITING without making it runnable',()=>{const p=new DynamicPool(settings);p.replenish([c('A',60,1),c('B',55,2)]);p.replenish([{...c('A',60,1),eligible:false,residentEligible:true,pipelineEligible:false},c('B',55,2)]);expect(p.list().map(x=>x.symbol)).toContain('A');expect(p.list().find(x=>x.symbol==='A')?.state).toBe('WAITING');});
  it('keeps non-runnable admitted candidates visible but separate from READY',()=>{const p=new DynamicPool(settings),waiting={...c('WAITUSDT',70,1),pipelineEligible:false};p.replenish([waiting,c('READYUSDT',60,2)]);expect(p.list().find(x=>x.symbol==='WAITUSDT')?.state).toBe('WAITING');expect(p.list().find(x=>x.symbol==='READYUSDT')?.state).toBe('READY');});
  it('uses the configured 10/12 ready/resident limits without BALANCED profile override',()=>{const p=new DynamicPool({...(settings as any),entryProfile:'BALANCED',selection:{...settings.selection,poolTarget:10,poolMax:12}} as any),rows=Array.from({length:12},(_,i)=>c(`S${i}USDT`,90-i,i+1));expect(p.replenish(rows)).toHaveLength(12);expect(p.readyList()).toHaveLength(10);});
  it('uses scheduler fairness without lowering admission quality',()=>{const p=new DynamicPool(settings),core={...c('BTCUSDT',40,3),schedulerPriority:1_000_100},high=c('SOLUSDT',90,1),blocked={...c('BADUSDT',99,2),eligible:false,schedulerPriority:2_000_000};p.replenish([high,blocked,core]);expect(p.list().map(x=>x.symbol)).toEqual(['SOLUSDT','BTCUSDT']);expect(p.list().map(x=>x.symbol)).not.toContain('BADUSDT');});
  it('does not let waiting residents consume execution-ready capacity',()=>{const p=new DynamicPool({...(settings as any),selection:{poolTarget:10,poolMax:30,replacementDelta:4}} as any),waiting=Array.from({length:20},(_,i)=>({...c(`WAIT${i}USDT`,100-i,i+1),pipelineEligible:false,residentEligible:true})),ready=Array.from({length:10},(_,i)=>c(`READY${i}USDT`,10-i,i+21));p.replenish([...waiting,...ready]);expect(p.list()).toHaveLength(30);expect(p.readyList()).toHaveLength(10);expect(p.readyList().every(item=>item.symbol.startsWith('READY'))).toBe(true);});
  it('does not reoccupy a ready slot when a cooled candidate is removed and replenished',()=>{const p=new DynamicPool({...(settings as any),selection:{poolTarget:1,poolMax:3,replacementDelta:4}} as any),cooled={...c('COOLEDUSDT',99,1),pipelineEligible:false,residentEligible:true},ready=c('READYUSDT',10,2);p.replenish([cooled,ready]);expect(p.readyList().map(item=>item.symbol)).toEqual(['READYUSDT']);p.remove('COOLEDUSDT');p.replenish([cooled,ready]);expect(p.readyList().map(item=>item.symbol)).toEqual(['READYUSDT']);});
  it('updates the ready view from a current route without rebuilding residents',()=>{const p=new DynamicPool({...(settings as any),selection:{poolTarget:1,poolMax:2,replacementDelta:4}} as any);p.replenish([c('HIGHUSDT',90,1),c('LOWUSDT',80,2)]);p.refreshReadyView(new Set(['LOWUSDT']));expect(p.list()).toHaveLength(2);expect(p.readyList().map(item=>item.symbol)).toEqual(['LOWUSDT']);});
});
