import { describe, expect, it } from 'vitest';
import { PortfolioIntelligenceSettingsSchema } from '@zdj/contracts';
import { buildAllocationPlan, decorateUniverse, directionPolicy, locationScore, resolveUnderlying, routeContract, riskTier } from './portfolio.js';

const p=PortfolioIntelligenceSettingsSchema.parse({});
const card=(last:number,overrides:any={})=>({timeframe:'15m',asOf:Date.now(),sampleSize:80,lastPrice:last,trend:'RANGE',trendStrength:.6,ema8:last,ema21:last,ema55:last,emaSlope21:0,macdLine:0,macdSignal:0,macdHistogram:0,macdHistogramSlope:0,macdCrossDirection:'NONE',macdCrossAgeBars:0,bbUpper:last*1.02,bbMiddle:last,bbLower:last*.98,bbPosition:.5,bbBandwidth:.04,atr14:last*.005,atrPercent:.5,volumeZScore:0,recentSwingHigh:last*1.01,recentSwingLow:last*.99,higherHighs:2,higherLows:2,lowerHighs:1,lowerLows:1,freshnessMs:0,...overrides});
const snap=(symbol:string,overrides:any={})=>{const last=100;return{symbol,quote:{symbol,last,mark:last,bid:last-.01,ask:last+.01,tickSize:.01,stepSize:.01,minQty:.01,minNotional:5,quoteVolumeUsd24h:100_000_000,priceChangePercent24h:0,tradeCount24h:10000,ts:Date.now()},orderBook:{symbol,bids:[[99.99,100000]],asks:[[100.01,100000]],ts:Date.now()},derivatives:{symbol,openInterest:1_000_000,openInterestChange5m:0,openInterestChange15m:0,fundingRate:0,takerBuySellRatio5m:1,globalLongShortRatio:1,topTraderPositionRatio:1,ts:Date.now()},technical:{'1m':card(last),'5m':card(last),'15m':card(last),'4h':card(last),'1d':card(last),'1w':card(last)},dataCompleteness:1,...overrides} as any;};
const settings={portfolio:{entryMarginUsd:200},portfolioIntelligence:p} as any;

describe('Portfolio Intelligence',()=>{
  it('resolves underlyings and routes USDT=0 to a healthy USDC contract',()=>{expect(resolveUnderlying('ETHUSDT')).toBe('ETH');expect(resolveUnderlying('ETHUSDC')).toBe('ETH');const usdc=snap('ETHUSDC'),usdt=snap('ETHUSDT');const selected=routeContract('ETH',[usdt,usdc],{...p,quoteAssetPolicy:'AUTO'},[{asset:'USDT',availableBalance:0,usdValue:0},{asset:'USDC',availableBalance:500,usdValue:500}] as any);expect(selected?.symbol).toBe('ETHUSDC');});
  it('qualifies each contract before routing so a rejected USDC market cannot eliminate healthy USDT',()=>{const base={rank:1,score:80,lifecycle:'SHORTLIST',components:{liquidity:80,tradingActivity:80,capitalActivity:80,technicalOpportunity:80,executionReachability:80,dataQuality:100},quoteVolumeUsd24h:1e8,spreadBps:1,lastPrice:100,change24hPercent:0,dataCompleteness:1,selectionGeneration:1,updatedAt:Date.now()},usdt:any={...base,symbol:'ETHUSDT',eligible:true,exclusionReasons:[]},usdc:any={...base,symbol:'ETHUSDC',eligible:false,exclusionReasons:['MARKET_QUALITY_D']};const rows=decorateUniverse([usdt,usdc],[snap('ETHUSDT'),snap('ETHUSDC')],settings,[{asset:'USDT',availableBalance:500,usdValue:500},{asset:'USDC',availableBalance:1000,usdValue:1000}] as any,[]);expect(rows.find(row=>row.selectedContract==='ETHUSDT'&&row.symbol==='ETHUSDT')).toBeTruthy();expect(rows.find(row=>row.symbol==='ETHUSDC')?.eligible).toBe(false);});
  it('assigns objective risk tiers and direction policy overrides',()=>{expect(riskTier(snap('BTCUSDT',{quote:{...snap('BTCUSDT').quote,quoteVolumeUsd24h:2_000_000_000}}),p)).toBe('CORE');expect(directionPolicy('DOGEUSDT','SPECULATIVE',{...p,symbolDirectionPolicies:{DOGEUSDT:'SHORT_ONLY'}})).toBe('SHORT_ONLY');});
  it('records overextended location in shadow without duplicating Primary timing as a veto',()=>{const s=snap('ALTUSDT',{technical:{...snap('ALTUSDT').technical,'15m':card(100,{ema21:90,bbPosition:.97,atr14:1,atrPercent:1,trend:'UP'})}});expect(locationScore(s,'LONG')).toBeLessThan(45);const plan=buildAllocationPlan({candidate:{symbol:'ALTUSDT',rank:1,score:80,lifecycle:'SHORTLIST',eligible:true,exclusionReasons:[],components:{liquidity:80,tradingActivity:70,capitalActivity:60,technicalOpportunity:70,executionReachability:80,dataQuality:100},quoteVolumeUsd24h:100_000_000,spreadBps:2,lastPrice:100,change24hPercent:0,dataCompleteness:1,selectionGeneration:1,updatedAt:Date.now(),underlyingAsset:'ALT',quoteAsset:'USDT',riskTier:'LIQUID_ALT',directionPolicy:'BOTH',locationScore:20} as any,snapshot:s,direction:'LONG',confidence:.8,settings,positions:[],assets:[{asset:'USDT',availableBalance:1000,usdValue:1000}] as any});expect(plan.admission).toBe('ALLOW');expect(plan.locationWouldBlock).toBe(true);expect(plan.marginUsd).not.toBe(200);});
  it('fails closed when exposure room is below the executable minimum instead of forcing min margin',()=>{const s=snap('BTCUSDT');const current=[{symbol:'ETHUSDT',side:'LONG' as const,quantity:50,markPrice:100,leverage:10}];const plan=buildAllocationPlan({candidate:{symbol:'BTCUSDT',rank:1,score:80,lifecycle:'SHORTLIST',eligible:true,exclusionReasons:[],components:{liquidity:80,tradingActivity:70,capitalActivity:60,technicalOpportunity:70,executionReachability:80,dataQuality:100},quoteVolumeUsd24h:100_000_000,spreadBps:2,lastPrice:100,change24hPercent:0,dataCompleteness:1,selectionGeneration:1,updatedAt:Date.now(),underlyingAsset:'BTC',quoteAsset:'USDT',riskTier:'LIQUID_ALT',directionPolicy:'BOTH'} as any,snapshot:s,direction:'LONG',confidence:.8,settings:{...settings,portfolioIntelligence:{...p,maxLongExposurePct:.5}} as any,positions:current,assets:[{asset:'USDT',availableBalance:1000,usdValue:1000}] as any});expect(plan.admission).toBe('REJECT_EXPOSURE_LIMIT');expect(plan.reasons).toContain('REJECT_EXPOSURE_LIMIT');});
  it('hard blocks max positions including working and reserved capacity',()=>{const s=snap('BTCUSDT');const plan=buildAllocationPlan({candidate:{symbol:'BTCUSDT',rank:1,score:80,lifecycle:'SHORTLIST',eligible:true,exclusionReasons:[],components:{liquidity:80,tradingActivity:70,capitalActivity:60,technicalOpportunity:70,executionReachability:80,dataQuality:100},quoteVolumeUsd24h:100_000_000,spreadBps:2,lastPrice:100,change24hPercent:0,dataCompleteness:1,selectionGeneration:1,updatedAt:Date.now(),underlyingAsset:'BTC',quoteAsset:'USDT',riskTier:'LIQUID_ALT',directionPolicy:'BOTH'} as any,snapshot:s,direction:'LONG',confidence:.8,settings:{...settings,portfolio:{entryMarginUsd:200,maxPositions:1,maxPendingEntries:2}} as any,positions:[],admissionContext:{reservedIntents:1,workingEntryOrders:0},assets:[{asset:'USDT',availableBalance:1000,usdValue:1000}] as any});expect(plan.admission).toBe('REJECT_MAX_POSITIONS');});
});
