import { describe,it,expect } from 'vitest';
import { selectionWeights, directionWeights } from './profiles.js';
import { selectUniverse } from './selection.js';
import { buildTechnicalCard } from './indicators.js';
import type { MarketSymbolSnapshot,SystemSettings,SelectionMode } from '@zdj/contracts';
const technical=(activity:number,technicalStrength:number)=>({'1m':{atrPercent:activity,lastPrice:100},'5m':{atrPercent:activity,lastPrice:100},'15m':{volumeZScore:activity,atrPercent:activity,trendStrength:technicalStrength,macdHistogramSlope:technicalStrength,bbPosition:.5+technicalStrength/10,higherHighs:1,higherLows:1,lowerHighs:0,lowerLows:0,lastPrice:100}} as any);
const snap=(symbol:string,volume:number,trades:number,capital:number,activity:number,tech:number):MarketSymbolSnapshot=>({symbol,quote:{symbol,last:100,mark:100,bid:99.99,ask:100.01,tickSize:.01,stepSize:.01,minQty:.001,minNotional:5,quoteVolumeUsd24h:volume,priceChangePercent24h:0,tradeCount24h:trades,ts:1},orderBook:{symbol,bids:[[99.99,1]],asks:[[100.01,1]],ts:1},derivatives:{symbol,openInterest:1,openInterestChange5m:0,openInterestChange15m:capital,fundingRate:0,takerBuySellRatio5m:1,globalLongShortRatio:1,topTraderPositionRatio:1,ts:1},technical:technical(activity,tech),dataCompleteness:1} as MarketSymbolSnapshot);
const baseSettings={selection:{mode:'COMPREHENSIVE_MAINSTREAM',universeTopN:2,poolTarget:2,poolMax:3,replacementDelta:4,customSymbols:['TECHUSDT'],excludeSymbols:[],minQuoteVolumeUsd24h:1,maxSpreadBps:10,minDataCompleteness:.9,marketQuality:{enabled:false,minQuoteVolumeUsd24h:0,minTradeCount24h:0,maxSpreadBps:0,minDepthUsd:0,minOpenInterestUsd:0,minListingAgeDays:0,allowedGrades:['A','B'],allowSpeculative:true,allowNewListings:false,liquidityTopN:0,symbolBlacklist:[],underlyingBlacklist:[]}}} as unknown as SystemSettings;
describe('V3 defaults',()=>{
  it('mainstream comprehensive selection is liquidity biased',()=>{ expect(selectionWeights('COMPREHENSIVE_MAINSTREAM').liquidity).toBe(0.35); });
  it('higher timeframes remain weights, not hard vetoes',()=>{ const w=directionWeights('TREND_4H'); expect(w['15m']).toBeGreaterThan(w['4h']!); expect(w['4h']).toBeGreaterThan(0.35); });
  it('all five selection modes produce bounded explainable Top N rankings',()=>{const snapshots=[snap('LIQUSDT',1e12,100,0,0,0),snap('ACTUSDT',1e8,9_000_000,0,5,0),snap('CAPUSDT',5e11,100,.8,.2,.3),snap('TECHUSDT',1e8,100,0,0,1)];for(const mode of ['COMPREHENSIVE_MAINSTREAM','EXCHANGE_RANK','TRADING_ACTIVITY','CAPITAL_ACTIVITY','CUSTOM_SYMBOLS'] as SelectionMode[]){const settings={...baseSettings,selection:{...baseSettings.selection,mode}};const rows=selectUniverse({snapshots,positions:new Set(),pendingEntries:new Set(),settings,generation:7,now:1});expect(rows.filter(x=>x.rank>0)).toHaveLength(mode==='CUSTOM_SYMBOLS'?1:2);expect(rows.every(x=>x.score>=0&&x.score<=100&&x.selectionGeneration===7)).toBe(true);if(mode==='EXCHANGE_RANK')expect(rows[0]?.symbol).toBe('LIQUSDT');if(mode==='TRADING_ACTIVITY'){const x=rows.find(x=>x.symbol==='ACTUSDT')!;expect(x.components.tradingActivity).toBeGreaterThanOrEqual(85);expect(x.rank).toBeGreaterThan(0);}if(mode==='CAPITAL_ACTIVITY'){const x=rows.find(x=>x.symbol==='CAPUSDT')!;expect(x.components.capitalActivity).toBeGreaterThanOrEqual(85);expect(x.rank).toBeGreaterThan(0);}if(mode==='CUSTOM_SYMBOLS')expect(rows[0]?.symbol).toBe('TECHUSDT');}});
  it('does not rank stale derivatives as current capital activity',()=>{const high=snap('HIGHUSDT',1e9,100,.9,0,0),low=snap('LOWUSDT',1e9,100,0,0,0),fresh=selectUniverse({snapshots:[high,low],positions:new Set(),pendingEntries:new Set(),settings:baseSettings,generation:1,now:1}),stale=selectUniverse({snapshots:[high,low],positions:new Set(),pendingEntries:new Set(),settings:baseSettings,generation:2,now:400_001});expect(fresh.find(x=>x.symbol==='HIGHUSDT')!.components.capitalActivity).toBeGreaterThan(fresh.find(x=>x.symbol==='LOWUSDT')!.components.capitalActivity);expect(stale.find(x=>x.symbol==='HIGHUSDT')!.components.capitalActivity).toBe(stale.find(x=>x.symbol==='LOWUSDT')!.components.capitalActivity);});
  it('hard-excludes held and pending symbols',()=>{const snapshots=[snap('AUSDT',1e9,100,0,0,0),snap('BUSDT',1e8,100,0,0,0)];const rows=selectUniverse({snapshots,positions:new Set(['AUSDT']),pendingEntries:new Set(['BUSDT']),settings:baseSettings,generation:1});expect(rows.every(x=>!x.eligible&&x.rank===0)).toBe(true);expect(rows.flatMap(x=>x.exclusionReasons)).toEqual(expect.arrayContaining(['ACTIVE_POSITION','ACTIVE_ENTRY_ORDER']));});
  it('admits only configured A/B market quality before a symbol can be ranked',()=>{const settings={...baseSettings,selection:{...baseSettings.selection,marketQuality:{...baseSettings.selection.marketQuality,enabled:true,minQuoteVolumeUsd24h:100_000_000,minTradeCount24h:100_000,maxSpreadBps:10,minDepthUsd:10_000,minOpenInterestUsd:1_000_000,minListingAgeDays:30,allowedGrades:['A','B']}}} as SystemSettings;const good={...snap('GOODUSDT',1_000_000_000,1_000_000,0,1,1),listingAgeDays:365,orderBook:{symbol:'GOODUSDT',bids:[[99.99,1000]],asks:[[100.01,1000]],ts:1},derivatives:{...snap('GOODUSDT',1,1,0,1,1).derivatives,openInterest:1_000_000}} as MarketSymbolSnapshot;const bad={...snap('BADUSDT',1_000_000,10,0,4,1),listingAgeDays:2,quote:{...snap('BADUSDT',1,1,0,1,1).quote,bid:99,ask:101},orderBook:{symbol:'BADUSDT',bids:[[99,.01]],asks:[[101,.01]],ts:1},derivatives:{...snap('BADUSDT',1,1,0,1,1).derivatives,openInterest:1}} as MarketSymbolSnapshot;const rows=selectUniverse({snapshots:[good,bad],positions:new Set(),pendingEntries:new Set(),settings,generation:1,now:1});expect(rows.find(x=>x.symbol==='GOODUSDT')?.eligible).toBe(true);const rejected=rows.find(x=>x.symbol==='BADUSDT')!;expect(rejected.eligible).toBe(false);expect(rejected.marketQuality?.grade).toBe('D');expect(rejected.exclusionReasons).toContain('MARKET_QUALITY_D');});
  it('reconciles flat EMA/MACD/BB/ATR as neutral rather than bearish',()=>{const candles=Array.from({length:80},(_,i)=>({openTime:i*60_000,closeTime:(i+1)*60_000,open:100,high:101,low:99,close:100,volume:10,quoteVolume:1000,trades:5}));const card=buildTechnicalCard('1m',candles,80*60_000);expect(card.lastClosedBar).toMatchObject({openTime:79*60_000,closeTime:80*60_000,close:100});expect(card.ema8).toBeCloseTo(100,10);expect(card.ema21).toBeCloseTo(100,10);expect(card.ema55).toBeCloseTo(100,10);expect(card.macdLine).toBeCloseTo(0,10);expect(card.macdSignal).toBeCloseTo(0,10);expect(card.bbMiddle).toBeCloseTo(100,10);expect(card.bbUpper).toBeCloseTo(100,10);expect(card.bbLower).toBeCloseTo(100,10);expect(card.atr14).toBeCloseTo(2,10);expect(card.volumeZScore).toBe(0);expect(card.freshnessMs).toBe(0);expect(card.trend).toBe('RANGE');expect(card.trendStrength).toBe(0);});
  it('is directionally symmetric for mirrored rising and falling series',()=>{const make=(sign:1|-1)=>Array.from({length:80},(_,i)=>{const close=100+sign*i*.2;return{openTime:i*900_000,closeTime:(i+1)*900_000-1,open:close-sign*.1,high:close+.5,low:close-.5,close,volume:10,quoteVolume:1000,trades:5,isClosed:true};});const up=buildTechnicalCard('15m',make(1),80*900_000),down=buildTechnicalCard('15m',make(-1),80*900_000);expect(up.trend).toBe('UP');expect(down.trend).toBe('DOWN');expect(up.trendStrength).toBeCloseTo(down.trendStrength,5);expect(Math.sign(up.emaSlope21)).toBe(1);expect(Math.sign(down.emaSlope21)).toBe(-1);});
  it('computes confirmed trend only from closed bars and exposes the active bar separately',()=>{const now=80*60_000,closed=Array.from({length:80},(_,i)=>({openTime:i*60_000,closeTime:(i+1)*60_000,receivedAt:now,isClosed:true as const,source:'BINANCE_REST' as const,open:100,high:101,low:99,close:100,volume:10,quoteVolume:1000,trades:5})),active={...closed.at(-1)!,openTime:now,closeTime:now+60_000,receivedAt:now+1,isClosed:false as const,source:'BINANCE_WS' as const,open:100,high:130,low:99,close:130};const card=buildTechnicalCard('1m',[...closed,active],now+1);expect(card.trend).toBe('RANGE');expect(card.asOf).toBe(now);expect(card.isClosed).toBe(true);expect(card.inProgressBar).toMatchObject({openTime:now,closeTime:now+60_000,lastPrice:130,source:'BINANCE_WS'});});
});