import {binanceRequestBudget,getBinanceRequestBudget} from './requestBudget.js';
import { describe, expect, it, vi } from 'vitest';
import {mkdtempSync,rmSync,truncateSync,writeFileSync} from 'node:fs';import os from 'node:os';import path from 'node:path';
import {resetStorageCapacityGuardForTest} from '../../services/storageCapacityGuard.js';
import { BinanceTransport,binanceRequestWeight,extractObservedIp } from './BinanceTransport.js';
const settings=(enabled=true)=>({executionMode:'TESTNET_ENABLED',exchange:{environment:'TESTNET',testnetBaseUrl:'https://demo-fapi.binance.com',testnetRestBaseUrl:'https://demo-fapi.binance.com',testnetWsBaseUrl:'wss://stream.binancefuture.com/ws',productionBaseUrl:'https://fapi.binance.com',productionRestBaseUrl:'https://fapi.binance.com',productionWsBaseUrl:'wss://fstream.binance.com/ws'},proxy:{enabled,url:'socks5h://127.0.0.1:20081',forceBinanceRest:true,forceBinanceWs:true,proxyDns:true,failClosed:true,binanceRestRoute:'CONFIGURED'}});
describe('BinanceTransport proxy-only boundary',()=>{
 it('routes REST and WebSocket through the configured proxy',()=>{const transport=new BinanceTransport(settings() as never);expect(transport.restRoute()).toMatchObject({mode:'CONFIGURED',throughProxy:true,proxyUrl:'socks5h://127.0.0.1:20081',failClosed:true});expect((transport as any).restAgent()).toBeDefined();expect(transport.websocketRoute()).toMatchObject({throughProxy:true,proxyUrl:'socks5h://127.0.0.1:20081',tlsServername:'stream.binancefuture.com',failClosed:true});expect(transport.websocketOptions().agent).toBeDefined();});
 it('ignores a legacy DIRECT flag and still uses the configured proxy',()=>{const cfg={...settings(),proxy:{...settings().proxy,binanceRestRoute:'DIRECT',forceBinanceRest:false,forceBinanceWs:false}};const transport=new BinanceTransport(cfg as never);expect(transport.restRoute()).toMatchObject({mode:'CONFIGURED',throughProxy:true});expect((transport as any).restAgent()).toBeDefined();expect(transport.websocketRoute().throughProxy).toBe(true);});
 it('fails closed when proxy is disabled instead of silently using DIRECT',async()=>{const transport=new BinanceTransport(settings(false) as never);expect(transport.restRoute()).toMatchObject({mode:'CONFIGURED',throughProxy:false,failClosed:true});expect(()=>transport.websocketOptions()).toThrow('PROXY_REQUIRED');await expect(transport.json('/fapi/v1/time')).rejects.toThrow('PROXY_REQUIRED');});
});
it('reserves the private-truth lane for listen-key maintenance without relying on signature heuristics',async()=>{const transport=new BinanceTransport(settings() as never),run=vi.spyOn((transport as any).budget,'run').mockResolvedValue({} as never);try{await transport.json('/fapi/v1/listenKey',{method:'PUT',headers:{'X-MBX-APIKEY':'isolated-test'}});expect(run.mock.calls[0]![0]).toBe(1);expect(run.mock.calls[0]![1]).toBe(1);expect(run.mock.calls[0]![3]).toMatchObject({source:'USER_DATA_STREAM',endpoint:'/fapi/v1/listenKey'});}finally{run.mockRestore();}});
it('accounts for heavy USD-M endpoints instead of counting every HTTP call as one',()=>{expect(binanceRequestWeight(new URL('https://fapi.binance.com/fapi/v1/openOrders?timestamp=1&signature=x'))).toBe(40);expect(binanceRequestWeight(new URL('https://fapi.binance.com/fapi/v1/openOrders?symbol=BTCUSDT&timestamp=1&signature=x'))).toBe(1);expect(binanceRequestWeight(new URL('https://fapi.binance.com/fapi/v1/income?limit=1000&timestamp=1&signature=x'))).toBe(30);expect(binanceRequestWeight(new URL('https://fapi.binance.com/fapi/v1/depth?symbol=BTCUSDT&limit=500'))).toBe(10);expect(binanceRequestWeight(new URL('https://fapi.binance.com/fapi/v1/klines?symbol=BTCUSDT&interval=15m&limit=240'))).toBe(2);});
it('isolates production, testnet and different proxy route identities',()=>{expect(getBinanceRequestBudget('TESTNET')).not.toBe(getBinanceRequestBudget('PRODUCTION'));expect(getBinanceRequestBudget('TESTNET')).toBe(binanceRequestBudget);expect(getBinanceRequestBudget('TESTNET','proxy-a')).not.toBe(getBinanceRequestBudget('TESTNET','proxy-b'));});
it('never reports AVAILABLE after observed weight has crossed the hard ceiling',()=>{const t=new BinanceTransport(settings() as never),budget=(t as any).budget;budget.observe(200,'2301',undefined,{source:'RECONCILIATION',endpoint:'/fapi/v1/openOrders'});expect(t.requestBudgetHealth().status).toBe('SATURATED');});
it('admits market hydration below the public ceiling even when observed weight differs from local estimates',async()=>{const cfg={...settings(),proxy:{...settings().proxy,url:'socks5h://127.0.0.1:20082'}},t=new BinanceTransport(cfg as never),budget=(t as any).budget,run=vi.spyOn(budget,'run').mockResolvedValue({} as never);try{budget.observe(200,'400',undefined,{source:'PRIVATE_STATE',endpoint:'/fapi/v2/account'});await t.json('/fapi/v1/ticker/bookTicker?symbol=BTCUSDT');expect(run).toHaveBeenCalledWith(3,2,expect.any(Function),expect.objectContaining({source:'MARKET_DATA'}));}finally{run.mockRestore();}});
it('blocks a cross-environment absolute URL before dispatch',async()=>{const transport=new BinanceTransport(settings() as never);await expect(transport.json('https://fapi.binance.com/fapi/v1/time')).rejects.toThrow('ENVIRONMENT_ORIGIN_MISMATCH');});
it('uses different budgets when the configured proxy changes',()=>{const first=settings(),second={...first,proxy:{...first.proxy,url:'socks5h://127.0.0.1:29999'}};expect((new BinanceTransport(first as never) as any).budget).not.toBe((new BinanceTransport(second as never) as any).budget);});
it('checks Entry pressure after budget admission and before opening a socket',async()=>{const transport=new BinanceTransport(settings() as never),budget=(transport as any).budget;const run=vi.spyOn(budget,'run').mockImplementation(async(...args:any[])=>{budget.observe(200,'2300',undefined);return args[2]();});try{await expect(transport.json('/fapi/v1/order',{method:'POST',purpose:'NEW_ENTRY'})).rejects.toThrow('ENTRY_BUDGET_BLOCKED');}finally{run.mockRestore();}});
it('checks SQLite capacity after budget admission and blocks only NEW_ENTRY before a socket opens',async()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'zdj-transport-storage-')),prior=process.env.ZDJ_DATA_DIR,file=path.join(dir,'zdj-settings.sqlite');process.env.ZDJ_DATA_DIR=dir;writeFileSync(file,'');truncateSync(file,1300*1024*1024);resetStorageCapacityGuardForTest();const transport=new BinanceTransport(settings() as never),budget=(transport as any).budget,run=vi.spyOn(budget,'run').mockImplementation(async(...args:any[])=>args[2]());try{await expect(transport.json('/fapi/v1/order',{method:'POST',purpose:'NEW_ENTRY'})).rejects.toThrow('STORAGE_ENTRY_BLOCKED:SQLITE_CAPACITY_ENTRY_BLOCKED');}finally{run.mockRestore();if(prior===undefined)delete process.env.ZDJ_DATA_DIR;else process.env.ZDJ_DATA_DIR=prior;resetStorageCapacityGuardForTest();rmSync(dir,{recursive:true,force:true});}});
it('extracts only valid observed IP addresses instead of the letters in IP banned',()=>{expect(extractObservedIp('IP banned until 1900000000000')).toBeNull();expect(extractObservedIp('IP(15.158.242.74) banned until 1900000000000')).toBe('15.158.242.74');expect(extractObservedIp('IP: 2001:db8::1')).toBe('2001:db8::1');});

it('allows Demo REST writes but rejects the deprecated Testnet REST hostname',()=>{
 const demo=new BinanceTransport(settings() as never);expect(()=>demo.assertTestnetExchangeWrite()).not.toThrow();
 const legacy={...settings(),exchange:{...settings().exchange,testnetBaseUrl:'https://testnet.binancefuture.com',testnetRestBaseUrl:'https://testnet.binancefuture.com'}};
 expect(()=>new BinanceTransport(legacy as never).assertTestnetExchangeWrite()).toThrow('TESTNET_ONLY_WRITE_LOCK');
});
it('fails closed for an unregistered Binance endpoint weight',()=>{
 expect(()=>binanceRequestWeight(new URL('https://demo-fapi.binance.com/fapi/v1/unknown?signature=x'),'GET')).toThrow('BINANCE_ENDPOINT_WEIGHT_UNREGISTERED');
});

it('tracks configured static egress expectation separately from Binance rate-limit truth',()=>{
 const cfg={...settings(),proxy:{...settings().proxy,expectedStaticEgressIp:'203.0.113.10'}},transport=new BinanceTransport(cfg as never);
 expect(transport.restRoute()).toMatchObject({expectedStaticEgressIp:'203.0.113.10'});
 expect(transport.egressStatus()).toMatchObject({expectedEgressIp:'203.0.113.10',lastVerifiedEgressIp:null,status:'UNVERIFIED'});
});
