import WebSocket from 'ws';import { BinanceTransport } from './BinanceTransport.js';
export class BinanceUserDataStream{
  private socket:WebSocket|null=null;private stopped=true;private retry:NodeJS.Timeout|null=null;private heartbeat:NodeJS.Timeout|null=null;private keepalive:NodeJS.Timeout|null=null;private attempt=0;private lastMessageAt=0;private stats={state:'STOPPED',reconnects:0,lastMessageAt:null as number|null,lastError:null as string|null};
  constructor(private transport:BinanceTransport,private apiKey:string,private onUserEvent:(event:any)=>void){}
  start(){if(!this.stopped)return;this.stopped=false;void this.connect();}
  stop(){this.stopped=true;for(const t of [this.retry,this.heartbeat,this.keepalive])if(t)clearInterval(t);this.retry=this.heartbeat=this.keepalive=null;this.socket?.close();this.socket=null;this.stats.state='STOPPED';}
  metrics(){return{...this.stats};}
  private async listenKey(method:'POST'|'PUT',key?:string){return this.transport.json<{listenKey:string}>(`/fapi/v1/listenKey${key?`?listenKey=${encodeURIComponent(key)}`:''}`,{method,headers:{'X-MBX-APIKEY':this.apiKey}});}
  private async connect(){if(this.stopped)return;this.stats.state='CONNECTING';try{const {listenKey}=await this.listenKey('POST');if(this.stopped)return;const socket=new WebSocket(`${this.transport.effectiveWsUrl()}/${listenKey}`,this.transport.websocketOptions());this.socket=socket;socket.on('open',()=>{this.attempt=0;this.stats.state='LIVE';this.stats.lastError=null;this.lastMessageAt=Date.now();this.heartbeat=setInterval(()=>{if(Date.now()-this.lastMessageAt>45_000)socket.terminate();else socket.ping();},15_000);this.keepalive=setInterval(()=>void this.listenKey('PUT',listenKey).catch(e=>{this.stats.lastError=e instanceof Error?e.message:String(e);socket.terminate();}),50*60_000);});socket.on('pong',()=>{if(this.socket===socket)this.lastMessageAt=Date.now();});socket.on('message',raw=>{if(this.socket===socket)this.onMessage(String(raw));});socket.on('error',e=>this.stats.lastError=e.message);socket.on('close',()=>{for(const t of [this.heartbeat,this.keepalive])if(t)clearInterval(t);this.heartbeat=this.keepalive=null;if(this.socket===socket)this.socket=null;this.schedule();});}catch(e){this.stats.lastError=e instanceof Error?e.message:String(e);this.schedule();}}
  private schedule(){if(this.stopped)return;this.stats.state='BACKOFF';this.stats.reconnects++;const ms=Math.min(30_000,500*2**Math.min(this.attempt++,6));this.retry=setTimeout(()=>void this.connect(),ms);}
  private onMessage(raw:string){this.lastMessageAt=Date.now();this.stats.lastMessageAt=this.lastMessageAt;let event:any;try{event=JSON.parse(raw);}catch{return;}if(event.e==='listenKeyExpired'){this.socket?.terminate();return;}if(event.e==='ORDER_TRADE_UPDATE'||event.e==='ACCOUNT_UPDATE'||event.e==='MARGIN_CALL')this.onUserEvent(event);}
}
