import {mkdirSync,readFileSync,writeFileSync,renameSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

type Priority=0|1|2|3|4;
export type RateLimitType='REQUEST_WEIGHT'|'ORDERS';
export type RateLimitInterval='SECOND'|'MINUTE'|'HOUR'|'DAY';
export type BinanceRateLimitDefinition={rateLimitType:RateLimitType;interval:RateLimitInterval;intervalNum:number;limit:number};
export type RequestBudgetMeta={requestId?:string;source?:string;purpose?:string;endpoint?:string;method?:string;routeIdentity?:string;orderCount?:number};
type DispatchDecision='QUEUED'|'ADMITTED'|'BLOCKED'|'TIMEOUT';
export type DispatchLedgerRow={requestId:string;source:string;purpose:string;endpoint:string;method:string;routeIdentity:string;estimatedWeight:number;queuedAt:number|null;admittedAt:number|null;queueAgeMs:number|null;completedAt:number|null;status:number|null;usedWeight1m:number|null;retryAfter:string|null;blockedUntil:number;observedBanIp:string|null;decision:DispatchDecision};
type ObservationTrust='PENDING'|'TRUSTED'|'INCONSISTENT'|'RATE_LIMITED';
type WeightObservation={at:number;source:string;endpoint:string;status:number;usedWeight1m:number;previousUsedWeight1m:number|null;estimatedWeight1m:number;counterDiscontinuity:boolean;windowId?:number;windowReset?:boolean};
type RateLimitCounter={rateLimitType:RateLimitType;interval:RateLimitInterval;intervalNum:number;intervalMs:number;windowId:number;observedCount:number;observedAt:number;limit:number|null;localFixedEstimate:number;headroom:number|null;usageRatio:number|null;counterDiscontinuity:boolean;windowReset:boolean};
type QueueItem={priority:Priority;weight:number;run:()=>void;reject:(error:Error)=>void;expiresAt:number;meta:RequestBudgetMeta;queuedAt:number;ledger:DispatchLedgerRow};
type Attribution={source:string;endpoint:string;requests:number;estimatedWeight:number;admitted:number;queued:number;blocked:number;lastStatus:number|null;lastObservedWeight:number|null;lastAt:number;lastAttemptAt:number};
type BudgetOptions={scope?:string;persistKey?:string;softPublicWeight?:number;softBackgroundWeight?:number;hardWeight?:number;privateTruthWeight?:number};

const EXECUTION_SOURCES=new Set(['EXECUTION_CRITICAL']);
const CONTROL_SOURCES=new Set(['CLOCK','HEALTH_PROBE','RATE_LIMIT_CONTROL']);
const PRIVATE_TRUTH_SOURCES=new Set(['ORDER_VERIFICATION','PRIVATE_STATE','USER_DATA_STREAM','RECONCILIATION']);
const BACKGROUND_SOURCES=new Set(['BACKGROUND_AUDIT','RESEARCH_AUDIT','HISTORICAL_REPAIR']);
export function binanceBudgetLane(source:unknown){const value=String(source??'UNKNOWN');return EXECUTION_SOURCES.has(value)?'EXECUTION':PRIVATE_TRUTH_SOURCES.has(value)?'PRIVATE_TRUTH':CONTROL_SOURCES.has(value)?'CONTROL':BACKGROUND_SOURCES.has(value)?'BACKGROUND':'MARKET_PUBLIC';}
function intervalMs(interval:RateLimitInterval,intervalNum:number){const unit=interval==='SECOND'?1000:interval==='MINUTE'?60_000:interval==='HOUR'?3_600_000:86_400_000;return unit*Math.max(1,intervalNum);}
function intervalFromToken(token:string):{interval:RateLimitInterval;intervalNum:number}|null{const m=String(token).toUpperCase().match(/^(\d+)([SMHD])$/);if(!m)return null;return{interval:m[2]==='S'?'SECOND':m[2]==='M'?'MINUTE':m[2]==='H'?'HOUR':'DAY',intervalNum:Number(m[1])};}
function counterKey(type:RateLimitType,interval:RateLimitInterval,intervalNum:number){return `${type}:${intervalNum}:${interval}`;}
export function parseBinanceRateLimitHeaders(headers:Record<string,string|string[]|undefined>){const out:Array<{rateLimitType:RateLimitType;interval:RateLimitInterval;intervalNum:number;count:number}>=[];for(const [rawName,rawValue] of Object.entries(headers)){const name=rawName.toLowerCase(),m=name.match(/^x-mbx-(used-weight|order-count)-(\d+[smhd])$/i);if(!m)continue;const parsed=intervalFromToken(m[2]!);const count=Number(Array.isArray(rawValue)?rawValue[0]:rawValue);if(!parsed||!Number.isFinite(count))continue;out.push({rateLimitType:m[1]!.toLowerCase()==='used-weight'?'REQUEST_WEIGHT':'ORDERS',...parsed,count});}return out;}
export function binanceHealthBlocksEntry(status:unknown){return['PRIVATE_ONLY','SATURATED','RATE_LIMITED','RECOVERING','PERSISTENCE_FAILED'].includes(String(status));}

/** Process-local REQUEST_WEIGHT governor. All Binance HTTP dispatches must pass here. */
export class RequestBudget {
  private activeWeight=0;private persistenceError:string|null=null;private anomalyUntil=0;private active=0;private publicActive=0;private starts:Array<{at:number;weight:number}>=[];private fixedStarts:Array<{at:number;weight:number;orderCount:number}>=[];private blockedUntil=0;
  private queue:QueueItem[]=[];private timer:ReturnType<typeof setTimeout>|null=null;
  private weightObservedAt=0;private usedWeight:number|null=null;
  private weightObservations:WeightObservation[]=[];
  private observationTrust:ObservationTrust='PENDING';private rateLimitDefinitions=new Map<string,BinanceRateLimitDefinition>();private observedCounters=new Map<string,RateLimitCounter>();
  private http418=0;private http429=0;private lastLimitedAt:number|null=null;private lastObservedBanIp:string|null=null;
  private recovering=false;private recoverySuccesses=0;private nextRecoveryProbeAt=0;private nextSaturationProbeAt=0;
  private attribution=new Map<string,Attribution>();private decisions={admitted:0,queued:0,blocked:0,queueTimeout:0};private ledger:DispatchLedgerRow[]=[];
  private readonly scope:string;private readonly persistFile:string|null;private readonly dataDir:string;
  private softPublicWeight:number;private softBackgroundWeight:number;private hardWeight:number;private privateTruthWeight:number;private requestWeightLimit1m:number|null=null;private limitSource:'CONSERVATIVE_DEFAULT'|'BINANCE_EXCHANGE_INFO'='CONSERVATIVE_DEFAULT';
  constructor(private readonly total=6,private readonly publicLimit=4,private readonly startsPerSecond=8,options:BudgetOptions={}){
    this.scope=options.scope??'TEST';this.softPublicWeight=options.softPublicWeight??1000;this.softBackgroundWeight=options.softBackgroundWeight??1800;this.hardWeight=options.hardWeight??2200;this.privateTruthWeight=options.privateTruthWeight??Math.max(this.hardWeight,2300);
    this.dataDir=process.env.ZDJ_DATA_DIR??path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../../../../data');
    this.persistFile=options.persistKey?path.join(this.dataDir,'rate-limit',`${options.persistKey.replace(/[^a-z0-9_.-]/gi,'_')}.json`):null;this.restore();
  }
  private applyRequestWeightLimit(limit:number){const normalized=Math.floor(Number(limit));if(!Number.isFinite(normalized)||normalized<100)return false;this.requestWeightLimit1m=normalized;this.limitSource='BINANCE_EXCHANGE_INFO';this.softPublicWeight=Math.max(100,Math.floor(normalized*.50));this.softBackgroundWeight=Math.max(this.softPublicWeight+50,Math.floor(normalized*.72));this.hardWeight=Math.max(this.softBackgroundWeight+50,Math.floor(normalized*.85));this.privateTruthWeight=Math.max(this.hardWeight+25,Math.floor(normalized*.95));return true;}
  configureRequestWeightLimit(limit:number){if(!this.applyRequestWeightLimit(limit))return;this.persist();this.pump();}
  configureRateLimits(definitions:unknown){if(!Array.isArray(definitions))return;for(const raw of definitions){const type=String((raw as any)?.rateLimitType) as RateLimitType,interval=String((raw as any)?.interval) as RateLimitInterval,intervalNum=Math.max(1,Math.floor(Number((raw as any)?.intervalNum??1))),limit=Math.floor(Number((raw as any)?.limit));if(!['REQUEST_WEIGHT','ORDERS'].includes(type)||!['SECOND','MINUTE','HOUR','DAY'].includes(interval)||!Number.isFinite(limit)||limit<=0)continue;const row={rateLimitType:type,interval,intervalNum,limit};this.rateLimitDefinitions.set(counterKey(type,interval,intervalNum),row);if(type==='REQUEST_WEIGHT'&&interval==='MINUTE'&&intervalNum===1)this.applyRequestWeightLimit(limit);}this.persist();this.pump();}
  async run<T>(priority:Priority,weightOrFn:number|(()=>Promise<T>),maybeFn?:()=>Promise<T>,meta:RequestBudgetMeta={}):Promise<T>{
    const weight=typeof weightOrFn==='number'?Math.max(0,Math.ceil(weightOrFn)):1,fn=(typeof weightOrFn==='function'?weightOrFn:maybeFn)!;
    if(!fn)throw new Error('BINANCE_REQUEST_FUNCTION_REQUIRED');
    const now=Date.now(),normalized=this.normalizeMeta(meta),row=this.attr(normalized),ledger=this.newLedger(normalized,weight,now),lane=binanceBudgetLane(normalized.source);
    row.requests++;row.estimatedWeight+=weight;row.lastAttemptAt=now;
    if(now<this.blockedUntil){this.decisions.blocked++;row.blocked++;ledger.decision='BLOCKED';ledger.completedAt=now;ledger.blockedUntil=this.blockedUntil;throw new Error(`BINANCE_RATE_LIMIT_UNTIL:${this.blockedUntil}`);}
    if(this.queue.length>=512){this.decisions.blocked++;row.blocked++;ledger.decision='BLOCKED';ledger.completedAt=now;throw new Error('BINANCE_REQUEST_QUEUE_FULL');}
    this.decisions.queued++;row.queued++;ledger.queuedAt=now;const ttl=lane==='EXECUTION'?15_000:lane==='PRIVATE_TRUTH'?10_000:lane==='CONTROL'?8_000:5_000;
    await new Promise<void>((resolve,reject)=>{this.queue.push({priority,weight,run:resolve,reject,expiresAt:Date.now()+ttl,meta:normalized,queuedAt:now,ledger});this.queue.sort((a,b)=>a.priority-b.priority||a.weight-b.weight);this.pump();});
    try{return await fn();}finally{ledger.completedAt??=Date.now();this.activeWeight=Math.max(0,this.activeWeight-weight);this.active=Math.max(0,this.active-1);if(priority===2)this.publicActive=Math.max(0,this.publicActive-1);this.pump();}
  }
  observe(status:number,weight:string|undefined,retryAfter:string|undefined,meta:RequestBudgetMeta={},observedIp:string|null=null,bodyBlockedUntil=0){
    const headers:Record<string,string|undefined>={};if(weight!==undefined)headers['x-mbx-used-weight-1m']=weight;
    this.observeResponse(status,headers,retryAfter,meta,observedIp,bodyBlockedUntil);
  }
  observeResponse(status:number,headers:Record<string,string|string[]|undefined>,retryAfter:string|undefined,meta:RequestBudgetMeta={},observedIp:string|null=null,bodyBlockedUntil=0){
    const now=Date.now(),normalized=this.normalizeMeta(meta),row=this.attr(normalized);row.lastStatus=status;row.lastAt=now;
    let usedWeight1m:number|null=null,anomalyChanged=false,trustChanged=false;
    for(const parsed of parseBinanceRateLimitHeaders(headers)){
      const ms=intervalMs(parsed.interval,parsed.intervalNum),windowId=Math.floor(now/ms),key=counterKey(parsed.rateLimitType,parsed.interval,parsed.intervalNum),previous=this.observedCounters.get(key),sameWindow=previous?.windowId===windowId,windowReset=Boolean(previous&&!sameWindow),discontinuity=Boolean(previous&&sameWindow&&parsed.count<previous.observedCount),localFixedEstimate=this.localFixedEstimate(parsed.rateLimitType,ms,windowId),definition=this.rateLimitDefinitions.get(key),limit=definition?.limit??null;
      if(discontinuity&&this.observationTrust!=='INCONSISTENT'){this.observationTrust='INCONSISTENT';trustChanged=true;}else if(!discontinuity&&(this.observationTrust==='PENDING'||windowReset)){this.observationTrust='TRUSTED';trustChanged=true;}
      const counter:RateLimitCounter={...parsed,intervalMs:ms,windowId,observedCount:parsed.count,observedAt:now,limit,localFixedEstimate,headroom:limit===null?null:Math.max(0,limit-parsed.count),usageRatio:limit===null?null:parsed.count/limit,counterDiscontinuity:discontinuity,windowReset};this.observedCounters.set(key,counter);
      if(parsed.rateLimitType==='REQUEST_WEIGHT'&&parsed.interval==='MINUTE'&&parsed.intervalNum===1){const previousWeight=this.usedWeight,estimated=this.estimatedWeight(now),unexplained=parsed.count>localFixedEstimate+Math.max(20,localFixedEstimate*.25);if(unexplained){const until=now+60_000;anomalyChanged=until>this.anomalyUntil||parsed.count>(this.usedWeight??0);this.anomalyUntil=Math.max(this.anomalyUntil,until);}this.usedWeight=parsed.count;this.weightObservedAt=now;usedWeight1m=parsed.count;this.weightObservations.push({at:now,source:String(normalized.source),endpoint:String(normalized.endpoint),status,usedWeight1m:parsed.count,previousUsedWeight1m:previousWeight,estimatedWeight1m:estimated,counterDiscontinuity:discontinuity,windowId,windowReset});if(this.weightObservations.length>128)this.weightObservations.splice(0,this.weightObservations.length-128);row.lastObservedWeight=parsed.count;}
    }
    if(anomalyChanged||trustChanged)this.persist();
    if(observedIp)this.lastObservedBanIp=observedIp;
    if(status===418||status===429){this.observationTrust='RATE_LIMITED';this.lastLimitedAt=now;if(status===418)this.http418++;else this.http429++;const raw=Number(retryAfter),date=Date.parse(retryAfter??''),delay=retryAfter!=null&&Number.isFinite(raw)?Math.max(1000,raw*1000):Number.isFinite(date)?Math.max(1000,date-now):bodyBlockedUntil>now?bodyBlockedUntil-now:status===418?24*60*60_000:60_000,safety=status===418?5_000:1_000;this.blockedUntil=Math.max(this.blockedUntil,Math.max(now+delay,bodyBlockedUntil)+safety);this.recovering=true;this.recoverySuccesses=0;this.nextRecoveryProbeAt=this.blockedUntil;this.updateLedger(normalized,{completedAt:now,status,usedWeight1m,retryAfter:retryAfter??null,blockedUntil:this.blockedUntil,observedBanIp:observedIp});this.persist();this.persistRateLimitEvidence(status,now);this.pump();return;}
    this.updateLedger(normalized,{completedAt:now,status,usedWeight1m,retryAfter:retryAfter??null,blockedUntil:this.blockedUntil,observedBanIp:observedIp});
    if(this.recovering&&status>=200&&status<400&&binanceBudgetLane(normalized.source)==='CONTROL'){this.recoverySuccesses++;if(this.recoverySuccesses>=2){this.recovering=false;this.nextRecoveryProbeAt=0;this.blockedUntil=0;this.observationTrust=this.observedCounters.size?'TRUSTED':'PENDING';this.persist();}else this.nextRecoveryProbeAt=now+1500;this.pump();}
  }
  health(){const now=Date.now(),estimated=this.estimatedWeight(now),observedFresh=this.usedWeight!==null&&now-this.weightObservedAt<60_000,admissionObservedWeight=observedFresh?this.usedWeight:null,pressure=Math.max(estimated,admissionObservedWeight??0),lastActivityAt=Math.max(this.weightObservedAt,this.lastLimitedAt??0,...[...this.attribution.values()].map(row=>Math.max(row.lastAttemptAt,row.lastAt)));return{scope:this.scope,active:this.active,publicActive:this.publicActive,queued:this.queue.length,queuedWeight:this.queue.reduce((sum,row)=>sum+row.weight,0),activeWeight:this.activeWeight,observedWeightAnomaly:now<this.anomalyUntil,observationTrust:now<this.blockedUntil?'RATE_LIMITED':this.observationTrust,rateLimits:[...this.observedCounters.values()].sort((a,b)=>a.rateLimitType.localeCompare(b.rateLimitType)||a.intervalMs-b.intervalMs).map(row=>({...row,localFixedEstimate:this.localFixedEstimate(row.rateLimitType,row.intervalMs,row.windowId)})),admissionObservedWeight1m:admissionObservedWeight,persistenceError:this.persistenceError,usedWeight1m:this.usedWeight,estimatedWeight1m:estimated,requestWeightLimit1m:this.requestWeightLimit1m,limitSource:this.limitSource,softPublicWeight:this.softPublicWeight,softBackgroundWeight:this.softBackgroundWeight,hardWeight:this.hardWeight,privateTruthWeight:this.privateTruthWeight,blockedUntil:this.blockedUntil,status:this.persistenceError?'PERSISTENCE_FAILED':now<this.blockedUntil?'RATE_LIMITED':this.recovering?'RECOVERING':pressure>=this.privateTruthWeight?'SATURATED':pressure>=this.hardWeight?'PRIVATE_ONLY':pressure>=this.softBackgroundWeight?'PRESSURED':'AVAILABLE',lastActivityAt,recoverySuccesses:this.recoverySuccesses,retryInMs:Math.max(0,(now<this.blockedUntil?this.blockedUntil:this.nextRecoveryProbeAt)-now),http418:this.http418,http429:this.http429,lastLimitedAt:this.lastLimitedAt,lastObservedBanIp:this.lastObservedBanIp,decisions:{...this.decisions},attribution:[...this.attribution.values()].sort((a,b)=>b.estimatedWeight-a.estimatedWeight).slice(0,40),weightObservations:this.weightObservations.slice(-128).map(row=>({...row})),recentDispatches:this.ledger.slice(-64).map(row=>({...row}))};}
  dispatchLedger(){return this.ledger.map(row=>({...row}));}
  private normalizeMeta(meta:RequestBudgetMeta):RequestBudgetMeta{return{requestId:meta.requestId??null as any,source:String(meta.source??'UNKNOWN'),purpose:String(meta.purpose??'UNSPECIFIED'),endpoint:String(meta.endpoint??'UNKNOWN'),method:String(meta.method??'GET').toUpperCase(),routeIdentity:String(meta.routeIdentity??this.scope),orderCount:Math.max(0,Math.floor(Number(meta.orderCount??0)))};}
  private attr(meta:RequestBudgetMeta){const source=String(meta.source??'UNKNOWN'),endpoint=String(meta.endpoint??'UNKNOWN'),key=`${source}|${endpoint}`;let row=this.attribution.get(key);if(!row){row={source,endpoint,requests:0,estimatedWeight:0,admitted:0,queued:0,blocked:0,lastStatus:null,lastObservedWeight:null,lastAt:0,lastAttemptAt:0};this.attribution.set(key,row);}return row;}
  private newLedger(meta:RequestBudgetMeta,estimatedWeight:number,now:number){const row:DispatchLedgerRow={requestId:String(meta.requestId??`anonymous-${now}`),source:String(meta.source??'UNKNOWN'),purpose:String(meta.purpose??'UNSPECIFIED'),endpoint:String(meta.endpoint??'UNKNOWN'),method:String(meta.method??'GET'),routeIdentity:String(meta.routeIdentity??this.scope),estimatedWeight,queuedAt:null,admittedAt:null,queueAgeMs:null,completedAt:null,status:null,usedWeight1m:null,retryAfter:null,blockedUntil:this.blockedUntil,observedBanIp:null,decision:'QUEUED'};this.ledger.push(row);if(this.ledger.length>512)this.ledger.splice(0,this.ledger.length-512);return row;}
  private updateLedger(meta:RequestBudgetMeta,patch:Partial<DispatchLedgerRow>){const requestId=String(meta.requestId??'');if(!requestId)return;for(let i=this.ledger.length-1;i>=0;i--){if(this.ledger[i]!.requestId===requestId){Object.assign(this.ledger[i]!,patch);return;}}}
  private persistRateLimitEvidence(status:number,at:number){if(process.env.VITEST)return;try{const dir=path.join(this.dataDir,'runtime-logs');mkdirSync(dir,{recursive:true});const stamp=new Date(at).toISOString().replace(/[:.]/g,'-'),file=path.join(dir,`p0-binance-${status}-dispatch-ledger-${stamp}.json`);writeFileSync(file,JSON.stringify({status,scope:this.scope,capturedAt:at,blockedUntil:this.blockedUntil,lastObservedBanIp:this.lastObservedBanIp,usedWeight1m:this.usedWeight,estimatedWeight1m:this.estimatedWeight(at),requestWeightLimit1m:this.requestWeightLimit1m,dispatches:this.ledger},null,2),{flag:'wx',flush:true});}catch{/* Evidence persistence must never create a retry loop or mask the exchange response. */}}
  private estimatedWeight(now=Date.now()){this.starts=this.starts.filter(row=>now-row.at<60_000);return this.starts.reduce((sum,row)=>sum+row.weight,0);}
  private localFixedEstimate(type:RateLimitType,ms:number,windowId:number){const now=Date.now();this.fixedStarts=this.fixedStarts.filter(row=>now-row.at<86_400_000);return this.fixedStarts.filter(row=>Math.floor(row.at/ms)===windowId).reduce((sum,row)=>sum+(type==='REQUEST_WEIGHT'?row.weight:row.orderCount),0);}
  private orderBudgetAllows(q:QueueItem,now:number){const cost=Math.max(0,Number(q.meta.orderCount??0));if(!cost)return true;for(const counter of this.observedCounters.values()){if(counter.rateLimitType!=='ORDERS'||now-counter.observedAt>counter.intervalMs)continue;const definition=this.rateLimitDefinitions.get(counterKey('ORDERS',counter.interval,counter.intervalNum)),limit=definition?.limit??counter.limit;if(!limit)continue;const currentWindow=Math.floor(now/counter.intervalMs);const observed=currentWindow===counter.windowId?counter.observedCount:0,local=this.localFixedEstimate('ORDERS',counter.intervalMs,currentWindow);if(Math.max(observed,local)+cost>Math.floor(limit*.95))return false;}return true;}
  private allowed(q:QueueItem,now:number){const lane=binanceBudgetLane(q.meta.source);if(!this.orderBudgetAllows(q,now))return false;if(this.persistenceError&&lane!=='EXECUTION'&&lane!=='CONTROL'&&lane!=='PRIVATE_TRUTH')return false;if(this.recovering){if(lane!=='EXECUTION'&&lane!=='CONTROL')return false;if(lane==='CONTROL'&&(this.active>0||now<this.nextRecoveryProbeAt))return false;}if(q.priority===2&&this.publicActive>=this.publicLimit)return false;const observedFresh=this.usedWeight!==null&&now-this.weightObservedAt<60_000,observed=observedFresh?this.usedWeight!:0,estimated=this.estimatedWeight(now),pressure=Math.max(observed+this.activeWeight,estimated),projected=pressure+q.weight;if(lane==='EXECUTION'&&q.weight===0)return true;if(lane==='CONTROL'&&projected>this.privateTruthWeight){if(this.active>0||now<this.nextSaturationProbeAt)return false;return true;}if(lane==='PRIVATE_TRUTH')return projected<=this.privateTruthWeight;if(lane==='BACKGROUND')return projected<=Math.min(this.softPublicWeight,this.softBackgroundWeight);if(lane==='MARKET_PUBLIC')return projected<=this.softBackgroundWeight;return projected<=this.hardWeight;}
  private pump(){const now=Date.now();this.starts=this.starts.filter(row=>now-row.at<60_000);this.queue=this.queue.filter(q=>{if(now<this.blockedUntil||now>=q.expiresAt){const row=this.attr(q.meta);row.blocked++;this.decisions.blocked++;q.ledger.decision=now<this.blockedUntil?'BLOCKED':'TIMEOUT';q.ledger.completedAt=now;q.ledger.blockedUntil=this.blockedUntil;if(now>=q.expiresAt)this.decisions.queueTimeout++;q.reject(new Error(now<this.blockedUntil?`BINANCE_RATE_LIMIT_UNTIL:${this.blockedUntil}`:'BINANCE_REQUEST_QUEUE_TIMEOUT'));return false;}return true;});const starts1s=this.starts.filter(row=>now-row.at<1000).length;let started=starts1s;while(this.active<this.total&&started<this.startsPerSecond&&now>=this.blockedUntil){const index=this.queue.findIndex(q=>this.allowed(q,now));if(index<0)break;const[q]=this.queue.splice(index,1),lane=binanceBudgetLane(q!.meta.source);this.active++;this.activeWeight+=q!.weight;if(q!.priority===2)this.publicActive++;this.starts.push({at:now,weight:q!.weight});this.fixedStarts.push({at:now,weight:q!.weight,orderCount:Math.max(0,Number(q!.meta.orderCount??0))});started++;this.decisions.admitted++;this.attr(q!.meta).admitted++;q!.ledger.decision='ADMITTED';q!.ledger.admittedAt=now;q!.ledger.queueAgeMs=Math.max(0,now-q!.queuedAt);if(lane==='CONTROL'&&Math.max(this.usedWeight??0,this.estimatedWeight(now))>=this.privateTruthWeight)this.nextSaturationProbeAt=now+5_000;if(this.recovering)this.nextRecoveryProbeAt=now+3000;q!.run();if(this.recovering)break;}if(this.queue.length&&!this.timer){const target=now<this.blockedUntil?this.blockedUntil:this.recovering?Math.max(now+20,this.nextRecoveryProbeAt):now+100;this.timer=setTimeout(()=>{this.timer=null;this.pump();},Math.max(20,Math.min(1000,target-now)));}}
  private restore(){if(!this.persistFile)return;try{const value=JSON.parse(readFileSync(this.persistFile,'utf8'));this.lastLimitedAt=Number(value.lastLimitedAt)||null;this.http418=Number(value.http418)||0;this.http429=Number(value.http429)||0;this.lastObservedBanIp=typeof value.lastObservedBanIp==='string'?value.lastObservedBanIp:null;const persistedLimit=Number(value.requestWeightLimit1m);if(Number.isFinite(persistedLimit)&&persistedLimit>=100)this.applyRequestWeightLimit(persistedLimit);if(Array.isArray(value.rateLimitDefinitions))this.configureRateLimits(value.rateLimitDefinitions);const restoredTrust=value.observationTrust==='PENDING'?'PENDING':value.observationTrust==='INCONSISTENT'?'INCONSISTENT':null,restoredAnomalyUntil=Number(value.anomalyUntil)||0,restoredObservedAt=Number(value.weightObservedAt)||0,restoredUsedWeight=Number(value.usedWeight);if(restoredTrust==='PENDING'&&restoredAnomalyUntil>Date.now()&&Math.floor(restoredObservedAt/60000)===Math.floor(Date.now()/60000)&&Number.isFinite(restoredUsedWeight)){this.observationTrust=restoredTrust;this.anomalyUntil=restoredAnomalyUntil;this.weightObservedAt=restoredObservedAt;this.usedWeight=restoredUsedWeight;}if(Number(value.blockedUntil)>Date.now()){this.blockedUntil=Number(value.blockedUntil);this.recovering=true;this.nextRecoveryProbeAt=this.blockedUntil;}}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')this.persistenceError=String(error);}}
  private persist(){if(!this.persistFile)return;try{mkdirSync(path.dirname(this.persistFile),{recursive:true});writeFileSync(this.persistFile+'.tmp',JSON.stringify({scope:this.scope,blockedUntil:this.blockedUntil,lastLimitedAt:this.lastLimitedAt,http418:this.http418,http429:this.http429,lastObservedBanIp:this.lastObservedBanIp,anomalyUntil:this.anomalyUntil,usedWeight:this.usedWeight,weightObservedAt:this.weightObservedAt,observationTrust:this.observationTrust,requestWeightLimit1m:this.requestWeightLimit1m,rateLimitDefinitions:[...this.rateLimitDefinitions.values()],updatedAt:Date.now()}),{flush:true});renameSync(this.persistFile+'.tmp',this.persistFile);this.persistenceError=null;}catch(error){this.persistenceError=String(error);}}
}

const budgets=new Map<string,RequestBudget>();
export function getBinanceRequestBudget(environment:string,routeIdentity='default'){const env=environment.toUpperCase()==='PRODUCTION'?'PRODUCTION':'TESTNET',scope=`${env}:${routeIdentity}`;let budget=budgets.get(scope);if(!budget){budget=new RequestBudget(6,4,8,{scope,persistKey:process.env.VITEST?undefined:`binance-${scope.toLowerCase()}`});budgets.set(scope,budget);}return budget;}
export function binanceRequestBudgetsHealth(){return Object.fromEntries([...budgets.entries()].map(([scope,budget])=>[scope,budget.health()]));}
export const binanceRequestBudget=getBinanceRequestBudget('TESTNET');
export function binanceEntryBlockReason(environment:string,routeIdentity?:string){const env=String(environment??'TESTNET').toUpperCase(),exact=routeIdentity?budgets.get(`${env}:${routeIdentity}`):null;if(exact){const health=exact.health();return binanceHealthBlocksEntry(health.status)?`BINANCE_BUDGET_${health.status}`:null;}const candidates=[...budgets.entries()].filter(([scope])=>scope.startsWith(env+':')&&!scope.endsWith(':default')).map(([,budget])=>budget.health()).sort((a,b)=>b.lastActivityAt-a.lastActivityAt),current=candidates[0];return current&&binanceHealthBlocksEntry(current.status)?`BINANCE_BUDGET_${current.status}`:null;}
