import {afterEach,expect,it,vi} from 'vitest';import {mkdtemp,rm} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
import {SettingsStore} from './settingsStore.js';import {NO_RISK_ABSENCE_SOURCES,entryIdentityTombstone} from '../services/entryRiskOccupancy.js';
const dirs:string[]=[];afterEach(async()=>{vi.useRealTimers();vi.restoreAllMocks();for(const p of dirs.splice(0))await rm(p,{recursive:true,force:true});});
async function fixture(){const dir=await mkdtemp(path.join(os.tmpdir(),'zdj-claim-index-'));dirs.push(dir);const store=new SettingsStore(path.resolve('../../config'),dir);await store.load();vi.spyOn(Date,'now').mockReturnValue(Date.now());return{store,dir,db:(store as any).db};}
function record(id:string,status='UNKNOWN'){return{intent:{id},order:{id,intentId:id,symbol:'BTCUSDT',side:'LONG',clientOrderId:'c'+id,status,filledQuantity:0,quantity:1}} as any;}
function insert(db:any,value:any,active=1,mode='SUBMISSION_ONLY'){db.prepare('INSERT INTO entry_execution_tasks(intent_id,scope,active,payload,updated_at,submission_key,isolation_key,isolation_mode) VALUES(?,?,?,?,1,?,?,?)').run(value.intent.id,value.intent.id,active,JSON.stringify(value),value.intent.id,value.intent.id,mode);}
it('incremental stats equal full durable truth after direct SQL updates, malformed rows and deletion',async()=>{const{store,db}=await fixture();try{insert(db,record('a'));insert(db,record('b','CANCELED'),0,'UNDERLYING_LEGACY');expect(store.entryExecutionClaimStats()).toEqual((store as any).scanEntryExecutionClaimStats());db.exec("UPDATE entry_execution_tasks SET payload='not-json',active=0 WHERE intent_id='b'");expect(store.entryExecutionClaimStats()).toEqual((store as any).scanEntryExecutionClaimStats());db.exec("DELETE FROM entry_execution_tasks WHERE intent_id='a'");expect(store.entryExecutionClaimStats()).toEqual((store as any).scanEntryExecutionClaimStats());}finally{if(db.isOpen)store.close();}});
it('unchanged snapshots do not SELECT or JSON.parse full durable history; changed IDs only',async()=>{const{store,db}=await fixture();try{db.exec('BEGIN');for(let i=0;i<1000;i++)insert(db,record('i'+i,'CANCELED'),0);db.exec('COMMIT');store.entryExecutionClaimStats();const prepare=vi.spyOn(db,'prepare');expect(store.entryExecutionClaimStats().durableTasks).toBe(1000);expect(prepare.mock.calls.some(([sql])=>String(sql).includes('FROM entry_execution_tasks'))).toBe(false);insert(db,record('new'));expect(store.entryExecutionClaimStats().activeClaims).toBe(1);expect(db.prepare('SELECT COUNT(*) n FROM entry_claim_stat_changes').get().n).toBe(0);}finally{if(db.isOpen)store.close();}});
it('expiry and clock rollback revalidate strict proof exactly without a durable rewrite',async()=>{const{store,db}=await fixture();try{vi.restoreAllMocks();vi.useFakeTimers();const now=Date.now(),v=record('proof');v.order.activeRiskExposure=false;v.order.activeRiskEvidence={status:'VERIFIED_NO_ACTIVE_RISK',sources:[...NO_RISK_ABSENCE_SOURCES,'BINANCE_LONG_SHORT_POSITION_ZERO'],checkedAt:now,validUntil:now+1000,identityTombstone:entryIdentityTombstone(v.order)};insert(db,v,0);expect(store.entryExecutionClaimStats().activeClaims).toBe(0);vi.setSystemTime(now+1000);expect(store.entryExecutionClaimStats()).toEqual((store as any).scanEntryExecutionClaimStats());expect(store.entryExecutionClaimStats().activeUnknownClaims).toBe(1);vi.setSystemTime(now+500);expect(store.entryExecutionClaimStats().activeClaims).toBe(0);vi.setSystemTime(now-1);expect(store.entryExecutionClaimStats().activeClaims).toBe(1);vi.setSystemTime(now);expect(store.entryExecutionClaimStats().activeClaims).toBe(0);}finally{if(db.isOpen)store.close();}});
it('transaction rollback and restart do not leave optimistic cached telemetry',async()=>{const{store,db,dir}=await fixture();try{insert(db,record('a'));store.entryExecutionClaimStats();await expect(store.transaction(()=>{db.exec("UPDATE entry_execution_tasks SET active=0,payload='{}'");expect(store.entryExecutionClaimStats().activeClaims).toBe(1);throw Error('rollback');})).rejects.toThrow('rollback');expect(store.entryExecutionClaimStats()).toEqual((store as any).scanEntryExecutionClaimStats());store.close();const next=new SettingsStore(path.resolve('../../config'),dir);await next.load();try{expect(next.entryExecutionClaimStats().activeClaims).toBe(1);}finally{next.close();}}finally{if(db.isOpen)store.close();}});
