import { afterEach, describe, expect, it, vi } from 'vitest';
import { mkdtemp, rm, stat } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
vi.mock('@zdj/contracts', async () => import(new URL('../../../../packages/contracts/src/index.js', import.meta.url).href));
import { SettingsStore } from './settingsStore.js';
vi.mock('@zdj/core', async () => import(new URL('../../../../packages/core/src/index.js', import.meta.url).href));
import { classifyAsset } from '@zdj/core';

const paths: string[] = [];
afterEach(async () => { await Promise.all(paths.splice(0).map(value => rm(value, { recursive: true, force: true }))); });

describe('SettingsStore', () => {
  it('persists versioned settings in SQLite and creates an integrity-checked backup', async () => {
    const dataDir = await mkdtemp(path.join(os.tmpdir(), 'zdj-settings-')); paths.push(dataDir);
    const configDir = path.resolve(process.cwd(), '../../config'); const store = new SettingsStore(configDir, dataDir);
    const initial = await store.load(); const saved = await store.save({ ...initial, entry: { ...initial.entry, maxReprices: initial.entry.maxReprices + 1 } });
    expect(saved.settingsVersion).toBeGreaterThan(initial.settingsVersion); expect(store.integrityCheck()).toBe(true);
    const backup = path.join(dataDir, 'backup.sqlite'); await store.backup(backup); expect((await stat(backup)).size).toBeGreaterThan(0);
    const restored = new SettingsStore(configDir, dataDir); const recovered = await restored.load(); expect(recovered.entry.maxReprices).toBe(saved.entry.maxReprices); restored.close(); store.close();
  });
  it('rejects a stale compare-and-swap settings publish without changing current settings',async()=>{const dataDir=await mkdtemp(path.join(os.tmpdir(),'zdj-settings-cas-'));paths.push(dataDir);const store=new SettingsStore(path.resolve(process.cwd(),'../../config'),dataDir),initial=await store.load();await store.save({...initial,entry:{...initial.entry,maxReprices:initial.entry.maxReprices+1}});await expect(store.saveIfVersion({...initial,entry:{...initial.entry,maxReprices:99}},initial.settingsVersion)).rejects.toThrow('SETTINGS_VERSION_CONFLICT');expect((await store.load()).entry.maxReprices).toBe(initial.entry.maxReprices+1);store.close();});
  it('accepts exactly one concurrent same-version CAS publish',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'zdj-settings-cas-race-'));paths.push(dir);const store=new SettingsStore(path.resolve(process.cwd(),'../../config'),dir),initial=await store.load(),a={...initial,entry:{...initial.entry,maxReprices:31}},b={...initial,entry:{...initial.entry,maxReprices:32}},results=await Promise.allSettled([store.saveIfVersion(a,initial.settingsVersion),store.saveIfVersion(b,initial.settingsVersion)]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect((await store.load()).settingsVersion).toBe(initial.settingsVersion+1);store.close();});
  it('round-trips per-asset admission evidence through schema and SQLite',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'zdj-settings-admission-'));paths.push(dir);const store=new SettingsStore(path.resolve(process.cwd(),'../../config'),dir),initial=await store.load(),now=1_000_000,approval={symbol:'SOLUSDT',reason:'TEST',reviewedAt:now,validUntil:now+10,graceUntil:now+20,lkgSourceFailed:false,quoteVolumeUsd24h:30_000_000,medianDailyQuoteVolumeUsd30d:30_000_000,tradeCount24h:30_000,openInterestUsd:6_000_000,listingAgeDays:200,liquidityComposite:.5};await store.save({...initial,selection:{...initial.selection,assetDirectory:{...initial.selection.assetDirectory,version:'V3.9.1-test',methodVersion:'V3.9.1-LIQUIDITY-30D-V4',reviewedAt:now,nextReviewAt:now+10,evidenceHash:'evidence',approvedLiquid:['SOL'],excluded:[],approvals:{SOL:approval},lkgAssets:[]}}});const reopened=new SettingsStore(path.resolve(process.cwd(),'../../config'),dir);try{const reloaded=await reopened.load(),fresh=classifyAsset('SOLUSDT',reloaded,now+1);expect(fresh.reason).toBe('TRACEABLE_V4_DIRECTORY_APPROVAL');expect(fresh.classification).toBe('APPROVED_LIQUID');const grace=structuredClone(reloaded);(grace.selection.assetDirectory.approvals.SOL as any).lkgSourceFailed=true;expect(classifyAsset('SOLUSDT',grace,now+15).classification).toBe('APPROVED_LIQUID');expect(classifyAsset('SOLUSDT',grace,now+21).reason).toBe('ASSET_APPROVAL_EXPIRED');grace.selection.assetDirectory.excluded=['SOL'];expect(classifyAsset('SOLUSDT',grace,now+1).classification).toBe('EXCLUDED');}finally{reopened.close();store.close();}});
  it('persists runtime facts and redacted bounded audit metrics',async()=>{const dataDir=await mkdtemp(path.join(os.tmpdir(),'zdj-runtime-'));paths.push(dataDir);const store=new SettingsStore(path.resolve(process.cwd(),'../../config'),dataDir);await store.load();store.persistRuntime({positions:[['p',{symbol:'BTCUSDT'}]]});store.recordRuntimeEvent({id:'e1',type:'TEST',ts:1,payload:{apiSecret:'must-not-leak'}});expect(store.loadRuntime<any>().positions[0][0]).toBe('p');expect(store.operationalMetrics()).toMatchObject({integrity:true,auditEvents:1});store.close();});
  it('keeps complete AI artifacts in the run archive and a lossless JSON reference in its decision chain',async()=>{const dataDir=await mkdtemp(path.join(os.tmpdir(),'zdj-run-artifact-'));paths.push(dataDir);const store=new SettingsStore(path.resolve(process.cwd(),'../../config'),dataDir);await store.load();const run={id:'run1',symbol:'BTCUSDT',startedAt:1,status:'COMPLETED',inputPreview:'x'.repeat(20_000),outputPreview:'y'.repeat(20_000),normalizedPreview:'{}'};store.recordRuntimeEvent({id:'e1',type:'AI_RUN_COMPLETED',ts:2,symbol:'BTCUSDT',payload:run});expect(store.getAiRun('run1').inputPreview).toHaveLength(20_000);expect(store.getDecisionChain('run1').events[0].payload).toMatchObject({artifactRef:{table:'ai_runs_archive',runId:'run1'}});expect(store.getDecisionChain('run1').events[0].payload.inputPreview).toBeUndefined();store.close();});
  it('paginates compact AI summaries in SQL with a stable tie-break and keeps full detail by id',async()=>{const dataDir=await mkdtemp(path.join(os.tmpdir(),'zdj-run-page-'));paths.push(dataDir);const store=new SettingsStore(path.resolve(process.cwd(),'../../config'),dataDir);await store.load();for(let i=0;i<105;i++)store.upsertAiRun({id:`run_${String(i).padStart(3,'0')}`,symbol:i%2?'ETHUSDT':'BTCUSDT',role:'PRIMARY_BRAIN',model:'qwen3.5:27b',status:'COMPLETED',decision:i%3?'NO_DIRECTION_EDGE':'WAIT_FOR_PRICE',direction:i%2?'LONG':'SHORT',startedAt:1000,completedAt:1100,latencyMs:100,inputTokens:10,outputTokens:5,inputPreview:'x'.repeat(10000)});const page=store.listAiRunSummaries({from:0,page:2,limit:20,role:'PRIMARY_BRAIN'});expect(page).toMatchObject({page:2,limit:20,total:105});expect(page.items).toHaveLength(20);expect(page.items[0].id).toBe('run_084');expect(JSON.stringify(page).length).toBeLessThan(50_000);expect(store.getAiRun('run_084').inputPreview).toHaveLength(10_000);store.close();});
  it('deduplicates and recovers external research tasks across store instances',async()=>{const dataDir=await mkdtemp(path.join(os.tmpdir(),'zdj-research-'));paths.push(dataDir);const configDir=path.resolve(process.cwd(),'../../config');const snapshot={contentHash:'hash1',sourceId:'source1',availableAt:1};const first=new SettingsStore(configDir,dataDir);await first.load();expect(first.enqueueExternalResearch(snapshot)).toBe(true);expect(first.enqueueExternalResearch(snapshot)).toBe(false);expect(first.nextExternalResearch(2)?.contentHash).toBe('hash1');first.close();const second=new SettingsStore(configDir,dataDir);await second.load();(second as any).db.prepare("UPDATE external_research_tasks SET updated_at=0 WHERE content_hash='hash1'").run();expect(second.nextExternalResearch(200000)?.attempts).toBe(2);second.completeExternalResearch('hash1',{facts:[]});expect(second.externalResearchMetrics()).toMatchObject({queued:0,running:0,completed:1});second.close();});
  it('recovers deduplicated persisted exchange fill facts for restart-safe sync',async()=>{const dataDir=await mkdtemp(path.join(os.tmpdir(),'zdj-fill-facts-'));paths.push(dataDir);const store=new SettingsStore(path.resolve(process.cwd(),'../../config'),dataDir);await store.load();const fill={symbol:'币安人生USDT',tradeId:'f1',executionTime:100,source:'USER_DATA_WS'};store.recordRuntimeEvent({id:'fill-ws',type:'EXCHANGE_FILL_ATTRIBUTED',ts:110,symbol:'币安人生USDT',payload:{fill}});store.recordRuntimeEvent({id:'fill-audit',type:'EXCHANGE_FILL_ATTRIBUTED',ts:120,symbol:'币安人生USDT',payload:{fill:{...fill,source:'EXCHANGE_AUDIT'}}});expect(store.listPersistedExchangeFillFacts('币安人生USDT',0,200)).toEqual([{...fill,source:'EXCHANGE_AUDIT'}]);store.close();});
  it('creates versioned product tables and supports resource CRUD',async()=>{const dataDir=await mkdtemp(path.join(os.tmpdir(),'zdj-resources-'));paths.push(dataDir);const store=new SettingsStore(path.resolve(process.cwd(),'../../config'),dataDir);await store.load();store.upsertTradeRecord({tradeId:'t1',status:'OPEN',symbol:'BTCUSDT'});store.upsertExperienceSample({sampleId:'s1',tradeId:'t1',createdAt:1});store.resourceSave('proxy',{id:'p1',enabled:true});expect(store.listTradeRecords()).toHaveLength(1);expect(store.listExperienceSamples()).toHaveLength(1);expect(store.resourceList('proxy').some(row=>row.id==='p1')).toBe(true);store.resourceDelete('proxy','p1');expect(store.resourceList('proxy').some(row=>row.id==='p1')).toBe(false);store.close();});
  it('repairs missing external intelligence tables even when migration 7 is marked',async()=>{const dataDir=await mkdtemp(path.join(os.tmpdir(),'zdj-external-migration-'));paths.push(dataDir);const configDir=path.resolve(process.cwd(),'../../config');const first=new SettingsStore(configDir,dataDir);await first.load();(first as any).db.exec('DROP TABLE external_provider_state; INSERT OR IGNORE INTO schema_migrations(version,applied_at) VALUES(7,1)');first.close();const repaired=new SettingsStore(configDir,dataDir);await repaired.load();repaired.setExternalProviderState('FEDERAL_RESERVE',{provider:'FEDERAL_RESERVE',status:'DISABLED'});expect(repaired.listExternalProviderStates()).toEqual([{provider:'FEDERAL_RESERVE',status:'DISABLED'}]);repaired.close();});
  it('rolls back a bounded transaction and rejects async transaction callbacks',async()=>{const dataDir=await mkdtemp(path.join(os.tmpdir(),'zdj-transaction-'));paths.push(dataDir);const store=new SettingsStore(path.resolve(process.cwd(),'../../config'),dataDir);await store.load();try{await expect(store.transaction(()=>{store.resourceSave('proxy',{id:'rolled-back'});throw new Error('FORCE_ROLLBACK');},{timeoutMs:50,label:'TEST'})).rejects.toThrow('FORCE_ROLLBACK');expect(store.resourceList('proxy').some(row=>row.id==='rolled-back')).toBe(false);await expect(store.transaction((async()=>1) as any,{timeoutMs:50,label:'ASYNC'})).rejects.toThrow('SQLITE_TRANSACTION_ASYNC_CALLBACK_FORBIDDEN');}finally{store.close();}});
  it('rolls back when the transaction deadline is exceeded',async()=>{const dataDir=await mkdtemp(path.join(os.tmpdir(),'zdj-transaction-timeout-'));paths.push(dataDir);const store=new SettingsStore(path.resolve(process.cwd(),'../../config'),dataDir);await store.load();try{await expect(store.transaction(()=>{store.resourceSave('proxy',{id:'too-slow'});const until=Date.now()+8;while(Date.now()<until){}return 1;},{timeoutMs:1,label:'TIMEOUT'})).rejects.toThrow('SQLITE_TRANSACTION_TIMEOUT:TIMEOUT');expect(store.resourceList('proxy').some(row=>row.id==='too-slow')).toBe(false);}finally{store.close();}});
});

it('migrates full recovery facts into atomic incremental entities and survives a database reopen',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'zdj-entities-'));paths.push(dir);const config=path.resolve('../../config');let store=new SettingsStore(config,dir);await store.load();const value={positions:[['p',{quantity:2}]],aiRuns:[{id:'run',inputPreview:'x'.repeat(100000)}],executionFills:[{fillId:'fill',qty:2}],manualExitGoals:[['p',{attempt:1}]]};store.persistRuntime(value);expect(store.checkpointMetrics().entityWrites).toBe(3);store.persistRuntime({...value,positions:[['p',{quantity:1}]]});expect(store.checkpointMetrics().entityWrites).toBe(1);expect(store.checkpointMetrics().checkpointBytes).toBeLessThan(1000);store.close();store=new SettingsStore(config,dir);await store.load();expect(store.loadRuntime()).toEqual({...value,positions:[['p',{quantity:1}]]});store.close();});
it('rolls back entity changes if checkpoint commit fails',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'zdj-entities-rollback-'));paths.push(dir);const store=new SettingsStore(path.resolve('../../config'),dir);await store.load();store.persistRuntime({positions:[['p',{quantity:1}]]});(store as any).db.exec("CREATE TRIGGER fail_checkpoint BEFORE UPDATE ON runtime_state BEGIN SELECT RAISE(ABORT,'TEST_CHECKPOINT_FAILURE'); END;");expect(()=>store.persistRuntime({positions:[['p',{quantity:2}]]})).toThrow('TEST_CHECKPOINT_FAILURE');expect(store.loadRuntime()).toEqual({positions:[['p',{quantity:1}]]});store.close();});
it('records capacity before/after and preserves memory when settings persistence fails',async()=>{
 const dataDir=await mkdtemp(path.join(os.tmpdir(),'zdj-capacity-audit-'));paths.push(dataDir);const store=new SettingsStore(path.resolve(process.cwd(),'../../config'),dataDir);const initial=await store.load();
 try{await store.save({...initial,portfolio:{...initial.portfolio,maxPositions:15}});const row=(store as any).db.prepare('SELECT summary FROM settings_audit ORDER BY id DESC LIMIT 1').get();expect(JSON.parse(row.summary).maxPositions).toEqual({before:initial.portfolio.maxPositions,after:15});
 (store as any).db.exec("CREATE TRIGGER reject_settings BEFORE UPDATE ON settings BEGIN SELECT RAISE(FAIL,'TEST_REJECT'); END");await expect(store.save({...initial,portfolio:{...initial.portfolio,maxPositions:20}})).rejects.toThrow('TEST_REJECT');expect((store as any).current.portfolio.maxPositions).toBe(15);
 }finally{store.close();}
});

it('archives AI telemetry without journaling it and retains changed position transitions',async()=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'zdj-telemetry-'));paths.push(dir);const store=new SettingsStore(path.resolve('../../config'),dir);await store.load();
 try{store.recordRuntimeEvent({id:'run-event',type:'AI_RUN_COMPLETED',ts:Date.now(),payload:{id:'run',status:'COMPLETED',symbol:'BTCUSDT',startedAt:Date.now(),decision:'WAIT_FOR_PRICE'}});
 expect(store.getAiRun('run').decision).toBe('WAIT_FOR_PRICE');expect(store.runtimeEvents(0,['AI_RUN_COMPLETED'])).toHaveLength(0);
 for(const transition of ['UNCHANGED','OPEN','REDUCE','CLOSE'])store.recordRuntimeEvent({id:transition,type:'POSITION_LIFECYCLE_TRANSITION',ts:Date.now(),payload:{transition}});
 expect(store.runtimeEvents(0,['POSITION_LIFECYCLE_TRANSITION'])).toHaveLength(3);
 }finally{store.close();}
});
it('runs bounded retention, keeps raw running AI and all critical events, and evicts only orphan AI entities',async()=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'zdj-retention-'));paths.push(dir);const store=new SettingsStore(path.resolve('../../config'),dir);await store.load();const db=(store as any).db,now=Date.now(),old=now-120*86400000;
 try{for(let i=0;i<150;i++)db.prepare('INSERT INTO decision_snapshots VALUES(?,?,?,?,?)').run('s'+i,null,'BTCUSDT',old,'{}');
 for(const status of ['RUNNING','COMPLETED'])store.upsertAiRun({id:status,startedAt:old,status,inputPreview:'raw'});
 store.recordRuntimeEvent({id:'critical',type:'TP_REPAIR_FAILED',ts:old,payload:{order:'working'}});
 store.persistRuntime({aiRuns:[{id:'old-ai'}],positions:[['p',{quantity:1}]]});store.persistRuntime({aiRuns:[],positions:[]});
 expect(db.prepare("SELECT count(*) n FROM runtime_entities WHERE kind='aiRuns'").get().n).toBe(0);expect(db.prepare("SELECT count(*) n FROM runtime_entities WHERE kind='positions'").get().n).toBe(1);
 store.maintainRetention(now);expect(db.prepare('SELECT count(*) n FROM decision_snapshots').get().n).toBe(50);
 for(let i=0;i<22;i++)store.maintainRetention(now);
 expect(store.getAiRun('RUNNING').inputPreview).toBe('raw');expect(store.getAiRun('COMPLETED')).toBeNull();expect(store.runtimeEvents(0,['TP_REPAIR_FAILED'])).toHaveLength(1);
 }finally{store.close();}
});
it('reuses a single trade sync baseline across concurrent sync requests',async()=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'zdj-baseline-'));paths.push(dir);const store=new SettingsStore(path.resolve('../../config'),dir);await store.load();
 try{const results=await Promise.all([store.tradeSyncBaseline(dir),store.tradeSyncBaseline(dir)]);expect(results[0]).toBe(results[1]);const first=await stat(results[0]!);store.persistRuntime({newFact:true});expect(await store.tradeSyncBaseline(dir)).toBe(results[0]);expect((await stat(results[0]!)).mtimeMs).toBe(first.mtimeMs);}finally{store.close();}
});
