import type { DashboardSnapshot, EntryIntelligencePacket, SystemSettings, UniverseCandidate } from '@zdj/contracts';
const json=async<T>(url:string,init?:RequestInit):Promise<T>=>{const r=await fetch(url,{...init,headers:{'content-type':'application/json',...(init?.headers??{})}});if(!r.ok){const body=await r.text();try{const parsed=JSON.parse(body);throw new Error(String(parsed?.error?.message??parsed?.message??parsed?.error??`${r.status}`));}catch(error){if(error instanceof Error&&error.message!==body)throw error;throw new Error(body||`${r.status}`);}}if(r.status===204)return undefined as T;return await r.json() as T;};
export const api={
 operationalIncidents:()=>json<{active:any[];history:any[]}>('/api/v3/operational-incidents'),
 snapshot:(signal?:AbortSignal)=>json<DashboardSnapshot>('/api/v3/snapshot',{signal}),binanceGovernance:()=>json<any>('/api/v3/diagnostics/binance-governance'),pipeline:()=>json<any>('/api/v3/pipeline'),runtimeControl:()=>json<any>('/api/v3/runtime/trading-control'),runtimeStatus:()=>json<any>('/api/v3/ops/runtime'),lanStatus:()=>json<any>('/api/v3/ops/lan'),shadowReadiness:()=>json<any>('/api/v3/shadow/readiness'),shadowMetrics:()=>json<any>('/api/v3/shadow/metrics'),cleanupPreview:()=>json<any>('/api/v3/testnet/cleanup/preview'),cleanupRun:(waitMs=60000)=>json<any>('/api/v3/testnet/cleanup/run',{method:'POST',body:JSON.stringify({confirm:true,waitMs})}),
 pauseTrading:(reason?:string)=>json<any>('/api/v3/runtime/trading-control/pause',{method:'POST',body:JSON.stringify({reason})}),resumeTrading:()=>json<any>('/api/v3/runtime/trading-control/resume',{method:'POST'}),riskPausePreview:()=>json<any>('/api/v3/runtime/risk-pause/preview'),overrideRiskPause:(reason:string)=>json<any>('/api/v3/runtime/risk-pause/override',{method:'POST',body:JSON.stringify({confirm:true,reason})}),
 accountAssets:()=>json<any>('/api/v3/account/assets'),orders:(query='')=>json<any>(`/api/v3/orders${query?'?'+query:''}`),entryAudit:(since=Date.now()-3*60*60_000)=>json<any>(`/api/v3/audit/entry-chain?since=${since}`),
 universe:(signal?:AbortSignal)=>json<{generation:number;candidates:UniverseCandidate[]}>('/api/v3/universe',{signal}),eip:(symbol:string)=>json<{packet:EntryIntelligencePacket}>(`/api/v3/eip/${encodeURIComponent(symbol)}`),settings:()=>json<SystemSettings>('/api/v3/settings'),readiness:()=>json<any>('/api/v3/settings/readiness'),
 blacklistCandidate:(value:{symbol?:string;underlying:string;scope:'SYMBOL'|'UNDERLYING';reason:'USER_BLACKLIST'})=>json<any>('/api/v3/universe/blacklist',{method:'POST',body:JSON.stringify(value)}),
 saveSettings:(s:SystemSettings)=>json<SystemSettings>('/api/v3/settings',{method:'PUT',body:JSON.stringify(s)}),connections:()=>json<any>('/api/v3/settings/connections'),
 governanceSettings:()=>json<any>('/api/v3/settings/governance'),
 saveGovernanceFields:(fields:Record<string,unknown>,expectedSettingsVersion:number,acks:string[]=[])=>json<any>('/api/v3/settings/governance',{method:'PATCH',body:JSON.stringify({expectedSettingsVersion,fields,acks})}),
 testResource:(kind:string,id:string)=>json<any>(`/api/v3/settings/resources/${kind}/${encodeURIComponent(id)}/test`,{method:'POST'}),aiDutyRoutes:()=>json<any>('/api/v3/settings/ai-duty-routes'),saveAiDutyRoutes:(routes:any[],expectedSettingsVersion:number)=>json<any>('/api/v3/settings/ai-duty-routes',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({routes,expectedSettingsVersion})}),refreshPool:()=>json('/api/v3/pool/refresh',{method:'POST'}),cancelEntry:(id:string)=>json(`/api/v3/entry/${id}/cancel`,{method:'POST'}),repairTp:(id:string)=>json(`/api/v3/tp/${id}/repair`,{method:'POST'}),
 humanManaged:()=>json<any>('/api/v3/human-managed'),acknowledgeHumanManaged:(id:string,note='')=>json<any>(`/api/v3/positions/${encodeURIComponent(id)}/human-managed/acknowledge`,{method:'POST',body:JSON.stringify({note})}),
 position:(id:string)=>json<any>(`/api/v3/positions/${encodeURIComponent(id)}`),manualPreview:(id:string)=>json<any>(`/api/v3/positions/${encodeURIComponent(id)}/manual-preview`),manualPosition:(id:string,value:any)=>json<any>(`/api/v3/positions/${encodeURIComponent(id)}/manual`,{method:'POST',body:JSON.stringify(value)}),
 cancelLimits:(id:string)=>json<any>(`/api/v3/positions/${encodeURIComponent(id)}/cancel-limits`,{method:'POST',body:JSON.stringify({confirm:true})}),cancelConditionals:(id:string)=>json<any>(`/api/v3/positions/${encodeURIComponent(id)}/cancel-conditionals`,{method:'POST',body:JSON.stringify({confirm:true})}),
 experience:()=>json<any>('/api/v3/experience'),tradeRecords:(query='')=>json<any>(`/api/v3/trade-records${query?`?${query}`:''}`),tradeRecord:(id:string)=>json<any>(`/api/v3/trade-records/${encodeURIComponent(id)}`),tradeRecordSyncPreview:(body:any)=>json<any>('/api/v3/trade-records/sync/preview',{method:'POST',body:JSON.stringify(body)}),tradeRecordSyncApply:(body:any)=>json<any>('/api/v3/trade-records/sync/apply',{method:'POST',body:JSON.stringify(body)}),tradeRecordSyncHistory:(limit=50)=>json<any>(`/api/v3/trade-records/sync/history?limit=${limit}`),resources:(kind:string)=>json<any>(`/api/v3/settings/resources/${kind}`),saveResource:(kind:string,value:any,expectedSettingsVersion:number)=>json<any>(`/api/v3/settings/resources/${kind}/${encodeURIComponent(value.id)}`,{method:'PUT',body:JSON.stringify({...value,expectedSettingsVersion})}),activateResource:(kind:string,id:string,expectedSettingsVersion:number)=>json<any>(`/api/v3/settings/resources/${kind}/${encodeURIComponent(id)}/activate`,{method:'POST',body:JSON.stringify({expectedSettingsVersion})}),deleteResource:(kind:string,id:string,expectedSettingsVersion:number)=>json<void>(`/api/v3/settings/resources/${kind}/${encodeURIComponent(id)}`,{method:'DELETE',headers:{'if-match':String(expectedSettingsVersion)}})
};
export const residentPosition=(id:string)=>json<any>(`/api/v3/positions/${encodeURIComponent(id)}`);
export const brainRuns=(query='',signal?:AbortSignal)=>json<any>(`/api/v3/brain/runs${query?`?${query}`:''}`,{signal});
export const brainRun=(id:string,signal?:AbortSignal)=>json<any>(`/api/v3/brain/runs/${encodeURIComponent(id)}`,{signal});
export const marketIntelligence=()=>json<any>('/api/v3/market-intelligence');
export const entryObservation=()=>json<any>('/api/v3/observability/entry');
export const testPrivateCredentials=(apiKey:string,apiSecret:string)=>json<any>('/api/v3/settings/exchange/private/test',{method:'POST',body:JSON.stringify({apiKey,apiSecret})});
export const saveExchangeCredentials=(apiKey:string,apiSecret:string)=>json<any>('/api/v3/settings/exchange/credentials',{method:'PUT',body:JSON.stringify({apiKey,apiSecret})});
