"""Derived evidence only; never mutates live records. Fixed cohort and denominators."""
import json,gzip,pathlib,collections,datetime,hashlib,csv
root=pathlib.Path(__file__).resolve().parents[1];b=root/'docs/reports/v398-trade-record-integrity-20261009/evidence'
def read(n):
 p=b/n;return json.loads(gzip.decompress(p.read_bytes()) if n.endswith('.gz') else p.read_text(encoding='utf-8'))
def save(n,obj):(b/n).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
records=read('trade-records.json.gz');entities=read('entities.json.gz');exchange=read('exchange-current-history.json');runtime=read('runtime-phase-a.json');native=[]
for window in exchange['windows']:
 if isinstance(window.get('fills'),list):native+=window['fills']
native=list({(f['symbol'],str(f['id'])):f for f in native}.values());native.sort(key=lambda f:f['time'])
lots=[]
for (symbol,side,order),fills in __import__('itertools').groupby(sorted(native,key=lambda f:(f['symbol'],f['positionSide'],str(f['orderId']),f['time'])),key=lambda f:(f['symbol'],f['positionSide'],str(f['orderId']))):
 fills=list(fills);qty=sum(float(f['qty']) for f in fills);cost=sum(float(f['quoteQty']) for f in fills);entry=fills[0]['side']==('BUY' if side=='LONG' else 'SELL');local=next((o for o in entities['entryOrders' if entry else 'tpOrders'] if o['symbol']==symbol and str(o.get('exchangeOrderId'))==order),None)
 lots.append({'symbol':symbol,'positionSide':side,'role':'ENTRY' if entry else 'EXIT','exchangeOrderId':order,'fillIds':[str(f['id']) for f in fills],'fillCount':len(fills),'firstFillAt':min(f['time'] for f in fills),'lastFillAt':max(f['time'] for f in fills),'quantity':qty,'vwap':cost/qty,'realizedPnl':sum(float(f['realizedPnl']) for f in fills),'commissionByAsset':dict((asset,sum(float(f['commission']) for f in fills if f['commissionAsset']==asset)) for asset in {f['commissionAsset'] for f in fills}),'localOrderId':local.get('id') if local else None,'intentId':local.get('intentId') if local else None})
lots.sort(key=lambda f:f['firstFillAt']);save('native-orders-derived.json',lots)
anomalies=[]
for r in records:
 lotQty=sum(float(l['quantity']) for l in r.get('entryLots',[]));entry=r.get('entryQty',0);exit=r.get('exitQty',0);remaining=r.get('remainingQty',0);reasons=[]
 if entry is not None and abs(lotQty-entry)>1e-8:reasons.append('ENTRY_LOT_SUM_NE_ENTRY_QTY')
 if None not in [entry,exit,remaining] and abs(entry-exit-remaining)>1e-8:reasons.append('ENTRY_EXIT_REMAINING_ARITHMETIC')
 if remaining is not None and remaining<0:reasons.append('NEGATIVE_REMAINING_QTY')
 if r.get('closedAt') and r['closedAt']<r['openedAt']:reasons.append('CLOSE_BEFORE_OPEN')
 if reasons:anomalies.append({'tradeId':r['tradeId'],'symbol':r['symbol'],'side':r['direction'],'classification':r['classification'],'status':r['status'],'entryQty':entry,'lotQty':lotQty,'exitQty':exit,'remainingQty':remaining,'reasons':reasons})
save('all-record-anomalies.json',{'denominator':len(records),'definitions':'raw arithmetic diagnostics, not new canonical eligibility or permission to rewrite history','anomalousRecords':len(anomalies),'byReason':dict(collections.Counter(reason for r in anomalies for reason in r['reasons'])),'rows':anomalies})
avaxRecords=[r for r in records if r['symbol']=='AVAXUSDT'];short=[r for r in avaxRecords if r['direction']=='SHORT'];shortLots=[r for r in lots if r['symbol']=='AVAXUSDT' and r['positionSide']=='SHORT'];shortEntry=[r for r in shortLots if r['role']=='ENTRY'];shortExit=[r for r in shortLots if r['role']=='EXIT']
cutoffs=[('2026-10-05T00:00:00+08:00',datetime.datetime.fromisoformat('2026-10-05T00:00:00+08:00').timestamp()*1000),('2026-10-06T00:00:00+08:00',datetime.datetime.fromisoformat('2026-10-06T00:00:00+08:00').timestamp()*1000)]
summary={'observedAt':exchange['observedAt'],'environment':'TESTNET','positionMode':exchange['positionMode'],'physicalCurrent': [p for p in exchange.get('positions',[]) if p['symbol']=='AVAXUSDT'],'openOrders':[p for p in exchange.get('openOrders',[]) if p['symbol']=='AVAXUSDT'],'nativeShortEntryOrders':len(shortEntry),'nativeShortSeparateAdds':max(0,len(shortEntry)-1),'nativeShortEntryQty':sum(r['quantity'] for r in shortEntry),'nativeShortExitOrders':len(shortExit),'nativeShortExitQty':sum(r['quantity'] for r in shortExit),'firstNativeShortFillAt':min([r['firstFillAt'] for r in shortEntry],default=None),'lastNativeShortExitAt':max([r['lastFillAt'] for r in shortExit],default=None),'atOct5':[{ 'cutoff':label,'independentEntryOrders':sum(r['firstFillAt']<at for r in shortEntry),'separateAdds':max(0,sum(r['firstFillAt']<at for r in shortEntry)-1),'fillStages':sum(f['symbol']=='AVAXUSDT' and f['positionSide']=='SHORT' and f['side']=='SELL' and f['time']<at for f in native)} for label,at in cutoffs],'localShortRecords':[{k:r.get(k) for k in ['tradeId','cycleId','openedAt','closedAt','status','classification','entryQty','exitQty','remainingQty','closeReason','fundingAttributionStatus']}|{'lotQuantity':sum(l['quantity'] for l in r.get('entryLots',[]))} for r in short],'localPositions':[p for p in entities['positions'] if p['symbol']=='AVAXUSDT'],'apiCategories':[{'endpoint':r['endpoint'],'http':r.get('httpStatus'),'total':r.get('data',{}).get('total'),'ids':[z['tradeId'] for z in r.get('data',{}).get('items',[])]} for r in runtime['results'] if 'trade-records?' in r['endpoint']],'coverage':'6-day signed GET windows, each <1000 non-saturated; retention remains a separate question','user1000Plus':'UNKNOWN_USER_OBSERVATION_NOT_EXACT_REPLAY','historical13Adds':'UNKNOWN_EXACT_OBSERVATION_TIME_AND_DEFINITION_NOT_RETAINED'}
save('avax-layer-reconciliation.json',summary)
save('ai-context-audit-summary.json',{'archiveProofRows':len(read('ai-input-fact-presence.json')),'explicitExistingPositionContextPresent':sum(p.get('positionContext') is not None for p in read('ai-input-fact-presence.json')),'physicalUNIUSDC':[p for p in exchange.get('positions',[]) if p['symbol']=='UNIUSDC'],'hedgeMode':exchange['positionMode'],'reverseRuntimeAcceptance':'UNKNOWN_NO_FORCED_ORDERS'})
print(json.dumps({'records':len(records),'classifications':dict(collections.Counter(r['classification'] for r in records)),'rawAnomalies':len(anomalies),'avaxNativeEntries':len(shortEntry),'avaxEntryQty':summary['nativeShortEntryQty'],'avaxExits':len(shortExit),'avaxExitQty':summary['nativeShortExitQty'],'avaxLocalShortRecords':summary['localShortRecords'],'avaxAPI':summary['apiCategories'],'oct5':summary['atOct5']},ensure_ascii=True))
