import {describe,expect,it} from 'vitest';
import {archivedPacket,projectBrainRun} from './brainRunArchive.js';
describe('brain run archived facts',()=>{
  it('uses only the run archive packet and reports absence instead of current facts',()=>{const packet={packetId:'historical',market:{quote:{last:1}}};expect(archivedPacket(JSON.stringify({packet}))).toEqual(packet);expect(archivedPacket('{}')).toBeNull();expect(archivedPacket('{bad')).toBeNull();});
});
describe('brain run execution attribution',()=>{
  const run={id:'airun_old',symbol:'BTCUSDT',direction:'SHORT',decision:'PLACE_SHORT',status:'COMPLETED',terminalStage:'SCHEMA_VALID'};
  it('uses the verified working order instead of a later stale PRIMARY_START reason',()=>{const chain={status:'PRIMARY_RUNNING',events:[{type:'ENTRY_INTENT_CREATED',ts:10,payload:{intentId:'intent_old'}},{type:'ENTRY_ORDER_CREATED',ts:20,payload:{intentId:'intent_old',order:{id:'entry_old',clientOrderId:'ml_btc',exchangeOrderId:'28574055715',status:'WORKING'}}},{type:'CANDIDATE_LIFECYCLE_CHANGED',ts:30,payload:{runId:'airun_old',reason:'PRIMARY_START'}}]},order={id:'entry_old',intentId:'intent_old',decisionChainId:'airun_old',clientOrderId:'ml_btc',exchangeOrderId:'28574055715',symbol:'BTCUSDT',side:'SHORT',quantity:.0159,filledQuantity:0,price:79700,status:'WORKING',createdAt:1,updatedAt:20,verifiedAt:25,timeInForce:'GTX',maker:true,factSource:'BINANCE_EXACT_ORDER'};const projected=projectBrainRun(run,chain,[order],[],100);expect(projected.summary).toMatchObject({finalStage:'ORDER_WORKING',reason:null,submitted:true});expect(projected.orderFact).toMatchObject({clientOrderId:'ml_btc',exchangeOrderId:'28574055715',remainingQuantity:.0159,timeInForce:'GTX',maker:true,factSource:'BINANCE_EXACT_ORDER'});});
  it('reports partial terminal truth and does not relabel PRIMARY_START as an execution reason',()=>{const projected=projectBrainRun(run,{events:[{type:'CANDIDATE_LIFECYCLE_CHANGED',ts:20,payload:{reason:'PRIMARY_START'}}]},[{id:'o',intentId:'i',decisionChainId:'airun_old',symbol:'BTCUSDT',side:'SHORT',quantity:10,filledQuantity:4,price:1,status:'CANCELED',createdAt:1,updatedAt:30}],[]);expect(projected.summary.finalStage).toBe('ORDER_CANCELED_PARTIAL');expect(projected.summary.reason).toBeNull();});
  it('uses UNKNOWN when an unsubmitted queue has no factual reason',()=>{const projected=projectBrainRun({...run,id:'new'}, {status:'PRIMARY_QUEUED',events:[{type:'CANDIDATE_LIFECYCLE_CHANGED',ts:1,payload:{reason:'WAITING_PRIMARY_SLOT'}}]},[],[]);expect(projected.summary).toMatchObject({reason:'UNKNOWN',submitted:false});});
});
