import {describe,expect,it} from 'vitest';
import {reconcileCandidateLifecycles} from './candidateLifecycleDeriver.js';

function state(){const s:any={positions:new Map(),entryOrders:new Map(),entryReservations:new Map(),entryIntents:new Map(),candidateLifecycle:new Map(),rejectionCooldown:new Map(),aiRuns:[],universe:[],cleanupReservations(){},positionSymbols(){return new Set([...this.positions.values()].map((x:any)=>x.symbol));}};return s;}

describe('fact-derived candidate lifecycle',()=>{
  it('releases stale ENTRY_WORKING after terminal facts',()=>{const s=state();s.candidateLifecycle.set('BTCUSDT',{status:'ENTRY_WORKING'});const out=reconcileCandidateLifecycles(s);expect(out.migrated).toBe(1);expect(s.candidateLifecycle.get('BTCUSDT').status).toBe('READY');});
  it.each(['CANCELED','EXPIRED','REJECTED','FILLED'])('releases ENTRY_WORKING after %s order terminal',status=>{const s=state();s.entryOrders.set('o',{symbol:'BTCUSDT',status});s.candidateLifecycle.set('BTCUSDT',{status:'ENTRY_WORKING'});reconcileCandidateLifecycles(s);expect(s.candidateLifecycle.get('BTCUSDT').status).toBe('READY');});
  it('holds active order and position facts',()=>{const s=state();s.entryOrders.set('o',{symbol:'BTCUSDT',status:'WORKING'});s.positions.set('p',{symbol:'ETHUSDT'});s.candidateLifecycle.set('BTCUSDT',{status:'READY'});s.candidateLifecycle.set('ETHUSDT',{status:'READY'});reconcileCandidateLifecycles(s);expect(s.candidateLifecycle.get('BTCUSDT').status).toBe('ENTRY_WORKING');expect(s.candidateLifecycle.get('ETHUSDT').status).toBe('POSITION_HELD');});
  it('derives same-underlying exclusion and later releases it',()=>{const s=state();s.entryOrders.set('o',{symbol:'BTCUSDT',status:'WORKING'});s.candidateLifecycle.set('BTCUSDC',{status:'READY'});reconcileCandidateLifecycles(s);expect(s.candidateLifecycle.get('BTCUSDC').status).toBe('EXCLUDED_UNDERLYING');s.entryOrders.get('o').status='FILLED';reconcileCandidateLifecycles(s);expect(s.candidateLifecycle.get('BTCUSDC').status).toBe('READY');});
  it('keeps a live cooldown during restart recovery',()=>{const s=state(),now=Date.now();s.candidateLifecycle.set('BTCUSDT',{status:'ENTRY_WORKING'});s.rejectionCooldown.set('BTCUSDT',{until:now+10_000,reason:'AI_FAILED'});reconcileCandidateLifecycles(s,undefined,'RESTART',now);expect(s.candidateLifecycle.get('BTCUSDT').status).toBe('COOLDOWN');});
  it('releases interrupted Primary after restart but preserves a truly running run',()=>{const s=state();s.aiRuns=[];s.candidateLifecycle.set('BTCUSDT',{status:'PRIMARY_RUNNING'});reconcileCandidateLifecycles(s);expect(s.candidateLifecycle.get('BTCUSDT').status).toBe('READY');s.aiRuns=[{symbol:'ETHUSDT',status:'RUNNING'}];s.candidateLifecycle.set('ETHUSDT',{status:'PRIMARY_RUNNING'});reconcileCandidateLifecycles(s);expect(s.candidateLifecycle.get('ETHUSDT').status).toBe('PRIMARY_RUNNING');});
  it('preserves an authorized execution wait instead of relaunching Primary',()=>{const s=state(),now=Date.now();s.entryIntents.set('i',{id:'i',symbol:'BTCUSDT'});s.entryReservations.set('r',{id:'r',intentId:'i',underlying:'BTC',status:'RESERVED',expiresAt:now+60_000});s.candidateLifecycle.set('BTCUSDT',{status:'WAIT_EXECUTION_RANGE',executionWait:{intentId:'i',reservationId:'r'}});reconcileCandidateLifecycles(s,undefined,'TICK',now);expect(s.candidateLifecycle.get('BTCUSDT').status).toBe('WAIT_EXECUTION_RANGE');});
});
