import {EconomicEvidenceSchema,type TradePlanEconomics} from '@zdj/contracts';
/** Historical candle touches and an assumed miss payoff never produce calibrated EV. */
export function economicEvidence(input:{conditionalNet:number;requiredProfit:number;probability:number|null;samples:number;source:string|null}) {
 const known=input.probability!==null && Number.isFinite(input.probability) && input.probability>=0 && input.probability<=1;
 const miss=-Math.max(0,input.requiredProfit);
 return EconomicEvidenceSchema.parse({costBoundProof:{status:'CONDITIONAL_BOUND',targetConditionalExFunding:input.conditionalNet,assumptions:['CONFIGURED_FEES_SLIPPAGE_AND_BUFFER','TARGET_FILL_CONDITIONAL','FUNDING_AND_FX_NOT_VERIFIED']},historicalTouchEstimate:{status:known?'ESTIMATE':'UNKNOWN',probability:known?input.probability:null,sampleCount:input.samples,source:input.source,overlappingWindows:true,executableFillProbability:false},scenarioExpectedPayoff:{status:known?'SCENARIO':'UNKNOWN',value:known?input.probability!*input.conditionalNet+(1-input.probability!)*miss:null,nonTouchPayoff:miss,nonTouchPolicy:'ASSUMED_NEGATIVE_PROFIT_FLOOR'},calibratedExpectedNetPnl:{status:'UNKNOWN',value:null,proof:null}});
}
/** Historical stored VERIFIED proxies are relabelled on read, never rewritten in durable plans. */
export function projectEconomicEvidence(raw:TradePlanEconomics) {
 return {...raw,reachProbabilityStatus:raw.reachProbabilityStatus==='VERIFIED'?'ESTIMATE' as const:raw.reachProbabilityStatus,expectedNetPnlAtHorizonStatus:raw.expectedNetPnlAtHorizonStatus==='VERIFIED'?'SCENARIO' as const:raw.expectedNetPnlAtHorizonStatus,targetConditionalNetProfitStatus:raw.targetConditionalNetProfitStatus==='VERIFIED'?'ESTIMATE' as const:raw.targetConditionalNetProfitStatus,evidence:raw.evidence??{costBoundProof:{status:raw.targetConditionalNetProfitUsd==null?'UNKNOWN' as const:'CONDITIONAL_BOUND' as const,targetConditionalExFunding:raw.targetConditionalNetProfitUsd,assumptions:['LEGACY_CONFIGURED_COST_BOUND','TARGET_FILL_CONDITIONAL','FUNDING_AND_FX_NOT_VERIFIED']},historicalTouchEstimate:{status:raw.reachProbability==null?'UNKNOWN' as const:'ESTIMATE' as const,probability:raw.reachProbability,sampleCount:raw.reachSampleCount,source:raw.statisticalSource,overlappingWindows:true as const,executableFillProbability:false as const},scenarioExpectedPayoff:{status:raw.expectedNetPnlAtHorizonUsd==null?'UNKNOWN' as const:'SCENARIO' as const,value:raw.expectedNetPnlAtHorizonUsd,nonTouchPayoff:null,nonTouchPolicy:'ASSUMED_NEGATIVE_PROFIT_FLOOR' as const},calibratedExpectedNetPnl:{status:'UNKNOWN' as const,value:null,proof:null}}};
}
