import { describe,expect,it,vi } from 'vitest';
import { RuntimeState } from '../state/runtimeState.js';import { EventBus } from '../events/eventBus.js';import { EntryCoordinator } from './entryCoordinator.js';import { PositionService } from './positionService.js';import type { EntryIntent,EntryOrder,SystemSettings } from '@zdj/contracts';
const settings={entry:{reviewIntervalSeconds:5,maxReprices:12,minReachability:.1,makerOffsetTicks:0},portfolio:{maxPendingEntries:6,maxPositions:12}} as unknown as SystemSettings;
const intent={id:'i',symbol:'BTCUSDT',side:'LONG',confidence:.8,idealPrice:100,acceptablePriceRange:{min:99,max:101},horizonMinutes:5,leverage:20,createdAt:1,absoluteExpiresAt:2,packetId:'p',brainRunId:'r'} as EntryIntent;
const order={id:'o',exchangeOrderId:'x',symbol:'BTCUSDT',side:'LONG',quantity:2,price:100,filledQuantity:.4,leverage:20,status:'PARTIALLY_FILLED',createdAt:1,updatedAt:1,absoluteExpiresAt:2,repriceCount:0,intentId:'i',reachability:.8} as EntryOrder;
describe('Entry Manager chain',()=>{
  it('cancels remaining quantity at the absolute TTL',async()=>{const state=new RuntimeState(settings);state.entryIntents.set(intent.id,intent);state.entryOrders.set(order.id,order);const cancelEntry=vi.fn(async(o:EntryOrder)=>({...o,status:'CANCELED' as const}));const entry=new EntryCoordinator(state,{} as never,{} as never,{cancelEntry} as never,new EventBus());await entry.reviewPending();expect(cancelEntry).toHaveBeenCalledOnce();expect(state.entryOrders.get('o')?.status).toBe('CANCELED');});
  it('opens only the actually filled partial quantity',()=>{const state=new RuntimeState(settings);const position=new PositionService(state,new EventBus()).onEntryFilled(order);expect(position.quantity).toBe(.4);expect(state.account.availableUsd).toBe(0);});
  it('keeps the single-flight compatibility hook open while cooldown remains per candidate',()=>{const state=new RuntimeState(settings);const entry=new EntryCoordinator(state,{} as never,{} as never,{} as never,new EventBus());expect((entry as any).cadenceReady(Date.now())).toBe(true);});
  it('isolates a failed symbol lifecycle without blocking another ready symbol',()=>{const state=new RuntimeState(settings);const entry=new EntryCoordinator(state,{} as never,{} as never,{} as never,new EventBus());(entry as any).transition('USELESSUSDT','AI_FAILURE_COOLDOWN','AI_SCHEMA_INVALID',{nextEligibleAt:Date.now()+1000});expect((entry as any).lifecycleRunnable('USELESSUSDT')).toBe(false);expect((entry as any).lifecycleRunnable('BULLAUSDT')).toBe(true);});
  it('recovers an accepted-but-disconnected submit by stable client id without a second order',async()=>{const state=new RuntimeState(settings),remote=new Map<string,EntryOrder>(),placeEntry=vi.fn(async(o:EntryOrder)=>{remote.set(o.clientOrderId!,{...o,status:'WORKING',exchangeOrderId:'exchange-1'});throw new Error('socket disconnected');}),findEntryByClientOrderId=vi.fn(async(o:EntryOrder)=>remote.get(o.clientOrderId!)??null),entry=new EntryCoordinator(state,{} as never,{} as never,{placeEntry,findEntryByClientOrderId} as never,new EventBus());(entry as any).executionHardBlock=()=>null;const liveIntent={...intent,id:'stable-intent',absoluteExpiresAt:Date.now()+60_000,aiAuthorizationExpiresAt:Date.now()+60_000,reservationId:'r'} as EntryIntent,prepared=(entry as any).preparedOrder(liveIntent,1,100,.8);const placed=await (entry as any).submitExactlyOnce(liveIntent,prepared);expect(placed.exchangeOrderId).toBe('exchange-1');expect(placeEntry).toHaveBeenCalledOnce();expect(prepared.clientOrderId).toBe((entry as any).preparedOrder(liveIntent,1,100,.8).clientOrderId);});
  it('keeps the same order identity across restart recovery from UNKNOWN',async()=>{const state=new RuntimeState(settings),ids:string[]=[],remote=new Map<string,EntryOrder>(),adapter={placeEntry:vi.fn(async(o:EntryOrder)=>{ids.push(o.clientOrderId!);throw new Error('timeout');}),findEntryByClientOrderId:vi.fn(async(o:EntryOrder)=>remote.get(o.clientOrderId!)??null)},first=new EntryCoordinator(state,{} as never,{} as never,adapter as never,new EventBus());(first as any).executionHardBlock=()=>null;const liveIntent={...intent,id:'restart-intent',absoluteExpiresAt:Date.now()+60_000,aiAuthorizationExpiresAt:Date.now()+60_000,reservationId:'r'} as EntryIntent,prepared=(first as any).preparedOrder(liveIntent,1,100,.8);await expect((first as any).submitExactlyOnce(liveIntent,prepared)).rejects.toThrow('ENTRY_SUBMISSION_UNKNOWN');const persisted=JSON.parse(JSON.stringify(state.entryOrders.get(prepared.id))) as EntryOrder;remote.set(persisted.clientOrderId!,{...persisted,status:'WORKING',exchangeOrderId:'exchange-after-restart'});const restarted=new EntryCoordinator(state,{} as never,{} as never,adapter as never,new EventBus());(restarted as any).executionHardBlock=()=>null;const recovered=await (restarted as any).submitExactlyOnce(liveIntent,persisted);expect(recovered.exchangeOrderId).toBe('exchange-after-restart');expect(ids).toEqual([persisted.clientOrderId]);});
  it.each(['NEW','SUBMITTING','UNKNOWN','WORKING','PARTIALLY_FILLED'])('blocks a new Primary for the occupied underlying while remote status is %s',status=>{const state=new RuntimeState(settings),entry=new EntryCoordinator(state,{} as never,{} as never,{} as never,new EventBus());state.entryOrders.set('remote',{...order,status,symbol:'BTCUSDT'} as EntryOrder);expect((entry as any).primaryOccupancyBlock('BTCUSDC')).toBe('UNDERLYING_ENTRY_EXISTS');expect((entry as any).stopPrimaryForOccupancy('BTCUSDC','AFTER_PRIMARY_SLOT')).toBe(true);expect(state.candidateLifecycle.get('BTCUSDC')).toMatchObject({status:'ENTRY_WORKING',reason:'UNDERLYING_ENTRY_EXISTS'});});
  it('clears a previous run attribution when a new Primary lease starts',()=>{const state=new RuntimeState(settings),entry=new EntryCoordinator(state,{} as never,{} as never,{} as never,new EventBus());state.candidateLifecycle.set('BTCUSDT',{symbol:'BTCUSDT',status:'READY',runId:'airun_old'} as any);(entry as any).transition('BTCUSDT','PRIMARY_QUEUED','WAITING_PRIMARY_SLOT');expect(state.candidateLifecycle.get('BTCUSDT')).toMatchObject({runId:null,previousRunId:'airun_old'});});
});

it('terminates an unsent prepared order when capacity changes before the wire call',async()=>{const state=new RuntimeState(settings),placeEntry=vi.fn(),entry=new EntryCoordinator(state,{} as never,{} as never,{placeEntry} as never,new EventBus());(entry as any).executionHardBlock=()=> 'RISK_MAX_POSITIONS';const prepared=(entry as any).preparedOrder(intent,1,100,1);await expect((entry as any).submitExactlyOnce(intent,prepared)).rejects.toThrow('RISK_MAX_POSITIONS');expect(state.entryOrders.get(prepared.id)).toMatchObject({status:'REJECTED',factSource:'LOCAL_NOT_SUBMITTED'});expect(placeEntry).not.toHaveBeenCalled();});
