import {describe,it,expect} from 'vitest';
import {SystemSettingsSchema} from '@zdj/contracts';
import defaults from '../../../../config/settings.default.json' with {type:'json'};
import {clusterFor,riskClusterKey,computeExecutableRiskHeadroom} from './executableRiskHeadroom.js';
import {buildRiskEnvelope} from './riskReadiness.js';
const settings=()=>SystemSettingsSchema.parse({...defaults,appearance:{...defaults.appearance,theme:'BINANCE_NOIR'}});
const pos=(symbol:string,side:'LONG'|'SHORT',notional:number)=>({symbol,side,quantity:1,markPrice:notional});
function input(){return{settings:settings(),equity:10000,positions:[] as ReturnType<typeof pos>[],symbol:'ADAUSDT',side:'LONG' as const,plannedNotional:300,expectedAdverseMovePct:.005,dailyDrawdownPct:0,minimumNotional:5};}
describe('shared executable risk headroom',()=>{
 it('does not equate unknown assets, but aggregates one underlying across quotes',()=>{const x=input();x.positions=[pos('SOLUSDT','LONG',3500)];expect(computeExecutableRiskHeadroom(x).finalNotional).toBe(300);x.symbol='SOLUSDC';expect(computeExecutableRiskHeadroom(x).reason).toBe('REJECT_CORRELATED_CLUSTER');expect(riskClusterKey('SOLUSDT')).toBe(riskClusterKey('SOLUSDC'));});
 it('uses exact known membership including multiplier contracts, not substrings',()=>{expect(clusterFor('1000PEPEUSDT')).toBe('MEME');expect(clusterFor('RAILUSDT')).toBe('OTHER');expect(clusterFor('ETHFIUSDT')).toBe('OTHER');expect(clusterFor('RENDERUSDT')).toBe('AI');});
 it('sizes into actual cluster remainder instead of rejecting an oversized recommendation',()=>{const x=input();x.symbol='DOGEUSDT';x.positions=[pos('PEPEUSDT','LONG',3450)];const h=computeExecutableRiskHeadroom(x);expect(h.finalNotional).toBe(50);expect(h.executable).toBe(true);expect(buildRiskEnvelope({...x,positions:x.positions as any,reservedIntents:0,workingOrders:0,quoteMarginUsage:0}).status).toBe('REJECT_CORRELATED_CLUSTER');expect(buildRiskEnvelope({...x,plannedNotional:h.finalNotional,positions:x.positions as any,reservedIntents:0,workingOrders:0,quoteMarginUsage:0}).status).toBe('PASS');});
 it('enforces cluster direction separately in route sizing and final validation',()=>{const x=input();x.settings.riskGovernance.maxClusterDirectionExposurePct=.1;x.symbol='DOGEUSDT';x.positions=[pos('PEPEUSDT','LONG',999)];expect(computeExecutableRiskHeadroom(x).reason).toBe('REJECT_CLUSTER_DIRECTION_EXPOSURE');expect(buildRiskEnvelope({...x,positions:x.positions as any,reservedIntents:0,workingOrders:0,quoteMarginUsage:0}).status).toBe('REJECT_CLUSTER_DIRECTION_EXPOSURE');});
 it('keeps gross, direction, quote and risk sizing limits with specific blockers',()=>{const x=input();x.positions=[pos('BTCUSDT','SHORT',9999)];expect(computeExecutableRiskHeadroom(x).blockers).toContain('REJECT_GROSS_EXPOSURE');x.positions=[pos('BTCUSDT','LONG',4999)];expect(computeExecutableRiskHeadroom(x).reason).toBe('REJECT_DIRECTION_EXPOSURE');x.positions=[];expect(computeExecutableRiskHeadroom({...x,quoteNotionalCapacity:4}).reason).toBe('INSUFFICIENT_AVAILABLE_MARGIN');x.expectedAdverseMovePct=25;expect(computeExecutableRiskHeadroom(x).reason).toBe('REJECT_RISK_PER_TRADE');x.expectedAdverseMovePct=.5;expect(computeExecutableRiskHeadroom(x).finalNotional).toBe(200);});
 it('fails closed for invalid equity, ATR and positions and daily drawdown',()=>{const x=input();expect(computeExecutableRiskHeadroom({...x,equity:NaN}).reason).toBe('RISK_FACTS_INVALID');expect(computeExecutableRiskHeadroom({...x,expectedAdverseMovePct:NaN}).reason).toBe('RISK_FACTS_INVALID');expect(computeExecutableRiskHeadroom({...x,positions:[pos('BTCUSDT','LONG',NaN)]}).executable).toBe(false);expect(computeExecutableRiskHeadroom({...x,dailyDrawdownPct:.06}).reason).toBe('REJECT_DAILY_DRAWDOWN');});
});
