import {describe,it,expect,vi} from 'vitest';
import {ExternalIntelligenceService} from './externalIntelligenceService.js';

const settings=(overrides:any={})=>({externalIntelligence:{enabled:true,feedToPrimary:false,refreshSeconds:900,timeoutMs:10000,maxContextItems:3,maxContextTokens:300,alpaca:{enabled:false,credentialRef:'alpaca-market-data',feed:'us',ttlSeconds:1800},federalReserve:{enabled:false,rssUrl:'https://www.federalreserve.gov/feeds/press_monetary.xml',ttlSeconds:86400},...overrides}});
function harness(config:any,fetcher:any,creds:{key?:string;secret?:string}={}){const snapshots:any[]=[],states:any[]=[],store={getSecret:vi.fn(async(ref:string)=>ref.endsWith(':apiKey')?creds.key??null:creds.secret??null),upsertExternalIntelligenceSnapshot:vi.fn((x:any)=>snapshots.push(x)),listExternalIntelligenceSnapshots:vi.fn(()=>snapshots),setExternalProviderState:vi.fn((_p:string,x:any)=>states.push(x)),listExternalProviderStates:vi.fn(()=>states)} as any,state={settings:config,externalIntelligence:new Map(),externalProviderStatus:new Map()} as any,events={publish:vi.fn()} as any,service=new ExternalIntelligenceService(state,store,events,fetcher);return{service,store,state,snapshots,states,events};}

describe('external intelligence read-only shared collector',()=>{
  it('does not issue requests while disabled',async()=>{const fetcher=vi.fn(),h=harness(settings({enabled:false}),fetcher);await h.service.tick(true);expect(fetcher).not.toHaveBeenCalled();expect(h.states.map(x=>x.status)).toEqual(['DISABLED','DISABLED']);});
  it('stores traceable Federal Reserve facts with availability and revision times',async()=>{const rss=`<rss><channel><item><title>Federal Reserve issues FOMC statement</title><link>https://www.federalreserve.gov/newsevents/pressreleases/monetary20260901a.htm</link><description><![CDATA[Policy statement.]]></description><pubDate>Tue, 01 Sep 2026 18:00:00 GMT</pubDate></item></channel></rss>`,fetcher=vi.fn(async()=>new Response(rss,{status:200})),h=harness(settings({federalReserve:{enabled:true,rssUrl:'https://www.federalreserve.gov/feeds/press_monetary.xml',ttlSeconds:86400}}),fetcher);await h.service.tick(true);expect(h.snapshots).toHaveLength(1);expect(h.snapshots[0]).toMatchObject({provider:'FEDERAL_RESERVE',quality:'OFFICIAL',closedBar:null,sourceId:'fed:https://www.federalreserve.gov/newsevents/pressreleases/monetary20260901a.htm'});expect(h.snapshots[0].availableAt).toBe(h.snapshots[0].receivedAt);expect(h.snapshots[0].contentHash).toHaveLength(64);expect(h.events.publish).toHaveBeenCalledWith('EXTERNAL_INTELLIGENCE_REFRESHED',expect.objectContaining({readOnly:true,entryPermission:false}));});
  it('reports Alpaca unconfigured without a network call or mock success',async()=>{const fetcher=vi.fn(),h=harness(settings({alpaca:{enabled:true,credentialRef:'alpaca-market-data',feed:'us',ttlSeconds:1800}}),fetcher);await h.service.tick(true);expect(fetcher).not.toHaveBeenCalled();expect(h.states.at(-1)).toMatchObject({provider:'ALPACA',status:'UNCONFIGURED',lastError:'READ_ONLY_CREDENTIALS_MISSING'});});
  it('accepts only completed Alpaca bars and keeps Primary input unchanged until feedToPrimary is enabled',async()=>{const now=Date.now(),body={bars:{'BTC/USD':[{t:new Date(now-31*60_000).toISOString(),o:100,h:102,l:99,c:101,v:1},{t:new Date(now-16*60_000).toISOString(),o:101,h:103,l:100,c:102,v:2},{t:new Date(now-5*60_000).toISOString(),o:102,h:104,l:101,c:103,v:3}],'ETH/USD':[]}},fetcher=vi.fn(async()=>new Response(JSON.stringify(body),{status:200,headers:{'content-type':'application/json'}})),h=harness(settings({alpaca:{enabled:true,credentialRef:'alpaca-market-data',feed:'us',ttlSeconds:1800}}),fetcher,{key:'k',secret:'s'});await h.service.tick(true);expect(h.snapshots).toHaveLength(1);expect(h.snapshots[0]).toMatchObject({provider:'ALPACA',instrument:'BTC/USD',closedBar:true,quality:'AUTHENTICATED_MARKET_DATA'});expect(h.service.context('ARBUSDC',now)).toEqual([]);h.state.settings.externalIntelligence.feedToPrimary=true;expect(h.service.context('ARBUSDC',Date.now())).toHaveLength(1);});
  it('backs off on provider 429 without throwing into Binance or Entry loops',async()=>{const fetcher=vi.fn(async()=>new Response('limited',{status:429})),h=harness(settings({federalReserve:{enabled:true,rssUrl:'https://www.federalreserve.gov/feeds/press_monetary.xml',ttlSeconds:86400}}),fetcher);await expect(h.service.tick(true)).resolves.toBeUndefined();expect(h.states.at(-1)).toMatchObject({provider:'FEDERAL_RESERVE',status:'BACKOFF',lastError:'FED_RSS_HTTP_429'});});
});
