import {describe,it,expect} from 'vitest';
import {SystemSettingsSchema} from '@zdj/contracts';
import defaults from '../../../../config/settings.default.json' with {type:'json'};
import {RuntimeState} from '../state/runtimeState.js';
import {collectPendingEntryRiskExposures,entryOrderOccupiesRisk} from './entryRiskOccupancy.js';
import {computeExecutableRiskHeadroom} from './executableRiskHeadroom.js';

const settings=()=>SystemSettingsSchema.parse({...defaults,appearance:{...defaults.appearance,theme:'BINANCE_NOIR'}});
const reservation=(id:string,underlying:string,notionalUsd:number,createdAt:number)=>({id,underlying,quoteAsset:'USDT',marginUsd:notionalUsd/10,notionalUsd,planId:`plan_${id}`,intentId:`intent_${id}`,createdAt,expiresAt:createdAt+60_000,status:'WORKING'} as any);
const order=(id:string,reservationId:string,symbol:string,side:'LONG'|'SHORT',quantity:number,price:number,filledQuantity=0)=>({id,clientOrderId:`ml_${id}`,exchangeOrderId:'1',symbol,side,quantity,price,filledQuantity,leverage:10,status:'WORKING',createdAt:1,updatedAt:1,absoluteExpiresAt:9999999999999,repriceCount:0,intentId:`intent_${id}`,reservationId,reachability:1} as any);

describe('final order risk convergence',()=>{
  it('deduplicates reservation plus working order and counts only remaining partial quantity',()=>{const state=new RuntimeState(settings()),now=10_000;state.entryReservations.set('r',reservation('r','DOGE',1000,1));state.entryOrders.set('o',order('o','r','DOGEUSDT','LONG',10,100,4));const rows=collectPendingEntryRiskExposures(state,{now});expect(rows).toHaveLength(1);expect(rows[0]).toMatchObject({source:'ORDER',notionalUsd:600,reservationId:'r'});});
  it('serializes competing reservations by creation order so concurrent candidates cannot share headroom',()=>{const state=new RuntimeState(settings()),now=10_000;state.entryReservations.set('early',reservation('early','DOGE',900,1));state.entryReservations.set('late',reservation('late','PEPE',900,2));expect(collectPendingEntryRiskExposures(state,{now,excludeReservationId:'early',priorityReservationId:'early'})).toHaveLength(0);expect(collectPendingEntryRiskExposures(state,{now,excludeReservationId:'late',priorityReservationId:'late'})).toMatchObject([{id:'reservation:early',notionalUsd:900}]);});
  it('makes pending notional consume gross, direction, cluster and cluster-direction headroom',()=>{const s=settings();s.riskGovernance.maxGrossExposurePct=.2;s.riskGovernance.maxDirectionExposurePct=.2;s.riskGovernance.maxClusterExposurePct=.2;s.riskGovernance.maxClusterDirectionExposurePct=.2;const pending=[{id:'order:a',symbol:'PEPEUSDT',side:'LONG' as const,notionalUsd:1900,reservationId:'r',orderId:'o',source:'ORDER' as const}],risk=computeExecutableRiskHeadroom({settings:s,equity:10000,positions:[],pendingRiskExposures:pending,symbol:'DOGEUSDT',side:'LONG',plannedNotional:200,expectedAdverseMovePct:.005,dailyDrawdownPct:0,minimumNotional:5});expect(risk.finalNotional).toBe(100);expect(risk.remaining).toMatchObject({gross:100,direction:100,cluster:100,clusterDirection:100});expect(risk.factVersion).toContain('order:a');});
  it('reoccupies risk automatically when verified UNKNOWN evidence expires',()=>{const now=10_000,row:any={...order('o','r','FETUSDT','LONG',1,100),status:'UNKNOWN',activeRiskExposure:false,activeRiskEvidence:{status:'VERIFIED_NO_ACTIVE_RISK',sources:['x'],checkedAt:now,validUntil:now+1000,identityTombstone:'ENTRY:FETUSDT:ml_o'}};expect(entryOrderOccupiesRisk(row,now)).toBe(false);expect(entryOrderOccupiesRisk(row,now+1001)).toBe(true);});
});
