import {expect,it,vi} from 'vitest';
import {MarketCohort} from './marketCohort.js';

function fixture(){let now=0;const snapshots=new Map<string,any>(),state:any={settings:{settingsVersion:1,selection:{cohort:{size:3,hydrateBatchSize:2,readyLowWatermark:1,refillBackoffSeconds:30,discoveryRefreshSeconds:30,staleMemberRotationMinutes:120,protectedRatio:.75},assetDirectory:{version:'a',approvedLiquid:[]}}},generation:1,runtimeControl:{mode:'RUNNING',reasonCode:'NONE',capital:{executableCandidateCount:1}},executionGovernance:{mode:'AUTO_RUNNING'},pool:{readyList:()=>[]},positionSymbols:()=>new Set(['HELDUSDT']),activeEntrySymbols:()=>new Set(['UNKNOWNUSDT']),candidateLifecycle:new Map([['WAITUSDT',{status:'WAIT_FOR_PRICE'}]])};const market:any={retained:new Set<string>(),setRetentionSymbols(symbols:Iterable<string>){this.retained=new Set(symbols);},retentionSymbols(){return new Set(this.retained);},discover:vi.fn(async()=>['AAAUSDT','BBBUSDT','CCCUSDT']),hydrateSymbols:vi.fn(async(symbols:string[])=>{for(const symbol of symbols)snapshots.set(symbol,{symbol});return symbols.length;}),snapshot:(s:string)=>snapshots.get(s)};return{state,market,snapshots,events:{publish:vi.fn()},clock:(v:number)=>now=v,now:()=>now};}

it('hydrates only a bounded delta and retains positions, unknown orders and waiting analysis owners',async()=>{const h=fixture(),cohort=new MarketCohort(h.state,h.market,h.events as any,h.now);expect(await cohort.tick()).toBe(2);expect(h.market.hydrateSymbols).toHaveBeenCalledWith(['AAAUSDT','BBBUSDT']);for(const symbol of ['AAAUSDT','BBBUSDT','HELDUSDT','UNKNOWNUSDT','WAITUSDT','BTCUSDT','ETHUSDT'])expect(h.market.retained.has(symbol)).toBe(true);expect(await cohort.tick()).toBe(1);expect(h.market.hydrateSymbols).toHaveBeenCalledTimes(2);});
it('caps a high configured hydrate batch before it can exhaust the shared REST budget',async()=>{const h=fixture();h.state.settings.selection.cohort={...h.state.settings.selection.cohort,size:20,hydrateBatchSize:20};h.market.discover=vi.fn(async()=>['AAAUSDT','BBBUSDT','CCCUSDT','DDDUSDT']);const cohort=new MarketCohort(h.state,h.market,h.events as any,h.now);expect(await cohort.tick()).toBe(2);expect(h.market.hydrateSymbols).toHaveBeenCalledWith(['AAAUSDT','BBBUSDT']);});
it('suppresses refill only for a real global capital block and never starts overlapping discovery',async()=>{const h=fixture();let release!:()=>void;h.market.discover=vi.fn(()=>new Promise<string[]>(resolve=>release=()=>resolve(['AAAUSDT'])));const cohort=new MarketCohort(h.state,h.market,h.events as any,h.now);const first=cohort.tick(),second=cohort.tick();expect(h.market.discover).toHaveBeenCalledTimes(1);release();await Promise.all([first,second]);h.state.runtimeControl.mode='PAUSED_NO_CAPITAL';h.state.runtimeControl.reasonCode='NO_CAPITAL';expect(await cohort.tick()).toBe(0);expect(h.market.discover).toHaveBeenCalledTimes(1);});
it('does not bootstrap or rotate inventory while a global capital blocker is active',async()=>{const h=fixture();h.state.runtimeControl.mode='PAUSED_NO_CAPITAL';h.state.runtimeControl.reasonCode='NO_CAPITAL';const empty=new MarketCohort(h.state,h.market,h.events as any,h.now);expect(await empty.tick()).toBe(0);expect(h.market.discover).not.toHaveBeenCalled();h.state.runtimeControl.mode='RUNNING';h.state.runtimeControl.reasonCode='NONE';expect(await empty.tick()).toBe(2);h.clock(121*60_000);h.state.runtimeControl.mode='PAUSED_NO_CAPITAL';h.state.runtimeControl.reasonCode='NO_CAPITAL';const before=empty.symbols();expect(await empty.tick()).toBe(0);expect(empty.symbols()).toEqual(before);});
it('uses actual position capacity as a global blocker even when runtime reason is only supply-related',async()=>{const h=fixture();h.state.entryCapacity=()=>({used:3,max:3,positions:3,pendingEntries:0,reservations:0});h.state.runtimeControl.mode='PAUSED_NO_EXECUTABLE_CONTRACT';h.state.runtimeControl.reasonCode='MIN_EXECUTABLE_CANDIDATES_NOT_MET';const cohort=new MarketCohort(h.state,h.market,h.events as any,h.now);expect(await cohort.tick()).toBe(0);expect(h.market.discover).not.toHaveBeenCalled();expect(h.events.publish).toHaveBeenCalledWith('MARKET_COHORT_DEFERRED',expect.objectContaining({blocker:'POSITION_CAPACITY_FULL'}));});
it('bootstraps an empty cohort despite zero executable candidates and backs off an empty discovery result',async()=>{const h=fixture();h.state.runtimeControl.capital.executableCandidateCount=0;h.market.discover=vi.fn(async()=>[]);const cohort=new MarketCohort(h.state,h.market,h.events as any,h.now);expect(await cohort.tick()).toBe(0);expect(h.market.discover).toHaveBeenCalledOnce();expect(await cohort.tick()).toBe(0);expect(h.market.discover).toHaveBeenCalledOnce();h.clock(30_000);expect(await cohort.tick()).toBe(0);expect(h.market.discover).toHaveBeenCalledTimes(2);});
it('invalidates a no-result backoff when governance/settings version changes',async()=>{const h=fixture();h.market.discover=vi.fn(async()=>[]);const cohort=new MarketCohort(h.state,h.market,h.events as any,h.now);expect(await cohort.tick()).toBe(0);expect(h.market.discover).toHaveBeenCalledOnce();h.state.settings.settingsVersion=2;h.state.settings.selection.assetDirectory.version='b';expect(await cohort.tick('GOVERNANCE_CHANGE')).toBe(0);expect(h.market.discover).toHaveBeenCalledTimes(2);expect(h.events.publish).toHaveBeenCalledWith('MARKET_COHORT_BACKOFF_INVALIDATED',expect.objectContaining({key:'b:2'}));});
it('backs off a partial hydrate instead of rediscovering every scheduler tick',async()=>{const h=fixture();h.market.discover=vi.fn(async()=>['AAAUSDT','BBBUSDT']);h.market.hydrateSymbols=vi.fn(async()=>{h.snapshots.set('AAAUSDT',{symbol:'AAAUSDT'});return 1;});const cohort=new MarketCohort(h.state,h.market,h.events as any,h.now);expect(await cohort.tick()).toBe(1);expect(h.market.discover).toHaveBeenCalledOnce();expect(await cohort.tick()).toBe(0);expect(h.market.discover).toHaveBeenCalledOnce();h.clock(30_000);await cohort.tick();expect(h.market.discover).toHaveBeenCalledTimes(2);});
it('keeps an active hydrate owner through a 15-second retention sync, then releases it on failure',async()=>{const h=fixture();let release!:(value:number)=>void;h.market.hydrateSymbols=vi.fn(()=>new Promise<number>(resolve=>release=resolve));const cohort=new MarketCohort(h.state,h.market,h.events as any,h.now);const hydrate=cohort.tick('REFILL');await Promise.resolve();expect(h.market.retained.has('AAAUSDT')).toBe(true);h.clock(15_000);cohort.remove('NOT_A_MEMBER');expect(h.market.retained.has('AAAUSDT')).toBe(true);const sync=cohort.tick('SYNC_15S');expect(h.market.retained.has('AAAUSDT')).toBe(true);release(0);await Promise.all([hydrate,sync]);expect(h.market.retained.has('AAAUSDT')).toBe(false);expect(await cohort.tick()).toBe(0);expect(h.market.discover).toHaveBeenCalledOnce();});
it('adopts already hydrated bootstrap snapshots instead of deleting and rehydrating them',async()=>{const h=fixture();for(const symbol of ['AAAUSDT','BBBUSDT']){h.snapshots.set(symbol,{symbol});h.market.retained.add(symbol);}h.market.retained.add('HELDUSDT');const cohort=new MarketCohort(h.state,h.market,h.events as any,h.now);expect(await cohort.tick('BOOTSTRAP')).toBe(1);expect(cohort.symbols()).toEqual(new Set(['AAAUSDT','BBBUSDT','CCCUSDT']));expect(h.market.hydrateSymbols).toHaveBeenCalledOnce();expect(h.market.hydrateSymbols).toHaveBeenCalledWith(['CCCUSDT']);expect(h.events.publish).toHaveBeenCalledWith('MARKET_COHORT_BOOTSTRAP_ADOPTED',expect.objectContaining({adopted:2,members:2}));});
