import {readFileSync,readdirSync} from 'node:fs';
import {join} from 'node:path';
import {describe,expect,it} from 'vitest';

/**
 * S02 asked whether the ownership ledger could escape the backup routine; S08 answered it in code, so
 * this guard now has the opposite job: prove the coverage claim is still true today.
 *
 * The report under docs/evidence is generated by scripts/v396-storage-coverage.mjs from the repository,
 * and the same derivation is repeated here. If somebody edits the report without editing the tooling,
 * or removes the ledger from the backup inventory, the two disagree and this fails.
 */
const root=join(process.cwd(),'..','..');
const sources=['services/ownershipJournal.ts','services/ownershipService.ts','services/ownershipMigration.ts','services/ownershipRuntime.ts','runtime/appRuntime.ts'];
const read=(relative:string)=>readFileSync(join(root,'apps','engine','src',relative),'utf8');
const s02=JSON.parse(readFileSync(join(root,'docs/evidence/v396/S02/20260921T190000Z/storage-coverage.json'),'utf8'));
const coveragePath='docs/evidence/v396/final-convergence-20260922/J5/storage-coverage.json';
const coverage=JSON.parse(readFileSync(join(root,coveragePath),'utf8'));
const inventory=()=>readFileSync(join(root,'scripts','durable-storage-inventory.mjs'),'utf8')
  .match(/DURABLE_SQLITE\s*=\s*\[([^\]]*)\]/)![1].split(',').map(entry=>entry.trim().replace(/['"]/g,'')).filter(Boolean);
const walk=(dir:string):string[]=>readdirSync(dir,{withFileTypes:true}).flatMap(entry=>{
  const full=join(dir,entry.name);
  return entry.isDirectory()?walk(full):entry.name.endsWith('.ts')&&!entry.name.endsWith('.test.ts')?[full]:[];
});

describe('ownership storage boundaries',()=>{
  it('never opens or mutates the live settings database',()=>{
    for(const file of sources){
      const text=read(file);
      expect(text,file).not.toMatch(/new DatabaseSync\([^)]*zdj-settings\.sqlite/);
      expect(text,file).not.toMatch(/settingsStore[^;]{0,40}\.db\b/);
    }
    expect(coverage.durableSqliteInventory).toContain('v396-ownership.sqlite');
  });

  it('keeps the ledger in the pre-deploy backup inventory',()=>{
    expect(inventory()).toEqual(coverage.durableSqliteInventory);
    expect(inventory()).toContain('v396-ownership.sqlite');
    const preflight=readFileSync(join(root,'scripts','v394-stage6-preflight.mjs'),'utf8');
    expect(preflight).toMatch(/for\s*\(\s*const\s+name\s+of\s+DURABLE_SQLITE\s*\)/);
    expect(preflight).toContain('BACKUP_FINGERPRINT_MISMATCH');
    expect(preflight).toContain('sqliteBackup(handle,target)');
  });

  it('derives the same coverage the committed report claims',()=>{
    const derived=coverage.durableSqliteInventory.map(name=>{
      const consumers=walk(join(root,'apps','engine','src')).filter(file=>readFileSync(file,'utf8').includes(name)).length;
      return{name,consumers,backedUp:inventory().includes(name)};
    });
    for(const row of derived){
      const claim=coverage.files.find((entry:{$comment?:string;name:string})=>entry.name===row.name);
      expect(claim,row.name).toBeTruthy();
      expect(claim.backedUpByExistingTooling,row.name).toBe(row.backedUp);
      expect(claim.readByAnyRuntimeConsumer,row.name).toBe(row.consumers>0);
      expect(claim.releaseBlocking,row.name).toBe(!(row.backedUp&&row.consumers>0));
    }
  });

  it('reports S08 coverage as closed, with no file left blocking a deploy',()=>{
    expect(coverage.gate).toBe('S08_STORAGE_COVERAGE_PASS');
    expect(coverage.blockingFiles).toEqual([]);
    expect(coverage.files.every((file:{releaseBlocking:boolean})=>!file.releaseBlocking)).toBe(true);
    // The S02 record stays as the history of the gap rather than being rewritten to look resolved.
    expect(s02.gate).toBe('S02_MIGRATION_AND_BACKUP_COVERAGE_OPEN');
    expect(s02.files[0].releaseBlocking).toBe(true);
  });

  it('refuses a newer or half-present ledger schema instead of half-upgrading it',()=>{
    const journal=read('services/ownershipJournal.ts');
    expect(journal).toMatch(/OWNERSHIP_SCHEMA_NEWER_THAN_RUNTIME/);
    expect(journal).toMatch(/OWNERSHIP_SCHEMA_TABLES_MISSING/);
    // The stamp is read before any DDL runs, which is the whole point of the guard.
    const stamp=journal.indexOf('PRAGMA user_version'),ddl=journal.indexOf('CREATE TABLE IF NOT EXISTS v396_owners');
    expect(stamp).toBeGreaterThan(-1);
    expect(ddl).toBeGreaterThan(stamp);
    expect(journal).toMatch(/if\(!stamped\)this\.db\.exec\(`PRAGMA user_version=\$\{OWNERSHIP_SCHEMA_VERSION\}`\)/);
  });

  it('does not let the ledger silently widen AI authority',()=>{
    const service=read('services/ownershipService.ts')+read('services/ownershipRuntime.ts');
    expect(service).not.toMatch(/transitionOwner\([^)]*'AI_ACTIVE'/);
    expect(service).not.toMatch(/next\s*:\s*OwnerState\s*=\s*'AI_ACTIVE'/);
    expect(read('services/ownershipJournal.ts')).toMatch(/HUMAN_REAUTHORIZATION_REQUIRED/);
    expect(read('services/ownershipJournal.ts')).toMatch(/CLOSED_OWNER_IMMUTABLE/);
  });
});
