import {describe,expect,it} from 'vitest';
import {p0EntryIntegrity} from './p0EntryIntegrity.js';

describe('V3.8.0 P0 entry integrity counters',()=>{
  it('passes the fixed BTC attribution fixture with all five counters at zero',()=>{const since=100,order={id:'entry_intent_mtpwrf8g_k7hdnqwo',intentId:'intent_mtpwrf8g_k7hdnqwo',decisionChainId:'airun_mtpwqzta_a0t75rgq',clientOrderId:'ml_6eeb81c3fcbf1b889a3d53f8ce57',exchangeOrderId:'28574055715',symbol:'BTCUSDT',status:'WORKING',factSource:'BINANCE_EXACT_ORDER',createdAt:50},result=p0EntryIntegrity({since,entryOrders:[order],entryIntents:[],fills:[],primaryRuns:[{id:'airun_mtpwqzta_a0t75rgq',role:'PRIMARY_BRAIN',symbol:'BTCUSDT',startedAt:50}],events:[{type:'ENTRY_ORDER_ACTIVE_RESTORED',symbol:'BTCUSDT',payload:{symbol:'BTCUSDT',orderId:order.id,occupancyReleased:false}},{type:'CANDIDATE_LIFECYCLE_CHANGED',symbol:'BTCUSDT',payload:{status:'PRIMARY_RUNNING',runId:null,previousRunId:'airun_mtpwqzta_a0t75rgq'}}],verifiedOrderFactMismatchCount:0});expect(result).toEqual({verifiedNoActiveRiskReleaseCount:0,crossSymbolOrderMismatchCount:0,activeRemoteEntryWithNewPrimaryCount:0,unverifiedRemoteTerminalReleasedOccupancyCount:0,BrainRunMisattributionCount:0,verifiedOrderFactMismatchCount:0,passed:true});});
  it('detects each forbidden condition',()=>{const result=p0EntryIntegrity({since:0,entryOrders:[{id:'o',intentId:'i',decisionChainId:'old',symbol:'BTCUSDT',status:'WORKING',factSource:'BINANCE_OPEN_ORDERS',createdAt:1}],entryIntents:[],fills:[{decisionChainId:'old',orderId:'o',symbol:'ETHUSDT'}],primaryRuns:[{id:'new',role:'PRIMARY_BRAIN',symbol:'BTCUSDC',startedAt:2}],events:[{type:'ENTRY_ORDER_REMOTE_STATUS_UNVERIFIED',payload:{orderId:'o',occupancyReleased:true}},{type:'CANDIDATE_LIFECYCLE_CHANGED',payload:{status:'PRIMARY_RUNNING',runId:'old'}}],verifiedOrderFactMismatchCount:1});expect(result).toMatchObject({crossSymbolOrderMismatchCount:1,activeRemoteEntryWithNewPrimaryCount:1,unverifiedRemoteTerminalReleasedOccupancyCount:1,BrainRunMisattributionCount:1,verifiedOrderFactMismatchCount:1,passed:false});});
 it('distinguishes historical terminal UNKNOWN from proven no active risk at release time',()=>{const event={type:'ENTRY_ORDER_REMOTE_STATUS_UNVERIFIED',ts:200,symbol:'BTCUSDT',payload:{symbol:'BTCUSDT',clientOrderId:'client',occupancyReleased:true,activeRiskExposure:false,evidence:{status:'VERIFIED_NO_ACTIVE_RISK',checkedAt:100,validUntil:300,identityTombstone:'ENTRY:BTCUSDT:client',sources:['BINANCE_EXACT_ORDER_NOT_FOUND','BINANCE_OPEN_ORDERS_IDENTITY_ABSENT','BINANCE_USER_TRADES_IDENTITY_ABSENT','BINANCE_ALL_ORDERS_IDENTITY_ABSENT','BINANCE_LONG_SHORT_POSITION_ZERO']}}};const input={since:0,entryOrders:[],entryIntents:[],fills:[],primaryRuns:[],events:[event]};expect(p0EntryIntegrity(input)).toMatchObject({verifiedNoActiveRiskReleaseCount:1,unverifiedRemoteTerminalReleasedOccupancyCount:0});expect(p0EntryIntegrity({...input,events:[{...event,ts:301}]})).toMatchObject({verifiedNoActiveRiskReleaseCount:0,unverifiedRemoteTerminalReleasedOccupancyCount:1});});

});
