import { describe,expect,it } from 'vitest';
import { EventBus } from '../events/eventBus.js';
import { RuntimeState } from '../state/runtimeState.js';
import { PositionLifecycleTracker } from './positionLifecycleTracker.js';
import { PositionService } from './positionService.js';

const settings={takeProfit:{enabled:true,targetPriceMovePercent:.45,quantityPercent:100,minNetProfitUsd:5,minNetProfitRoiPct:0,feeSafetyBufferPct:0,exitFeeAssumption:'TAKER',slippageBufferPct:0,tpEconomicsEnabled:true,entryFeeRate:0.01,makerFeeRate:0.01,takerFeeRate:0.01}} as any;
describe('Position lifecycle integrity',()=>{
  it('tracks OPEN → INCREASE → REDUCE → CLOSE and survives serialization',()=>{const state=new RuntimeState(settings);const tracker=new PositionLifecycleTracker(state);expect(tracker.observe({symbol:'BTCUSDT',side:'LONG',quantity:1,source:'SYSTEM'}).transition).toBe('OPEN');expect(tracker.observe({symbol:'BTCUSDT',side:'LONG',quantity:2,source:'SYSTEM'}).transition).toBe('INCREASE');expect(tracker.observe({symbol:'BTCUSDT',side:'LONG',quantity:1.5,source:'RECONCILIATION'}).transition).toBe('REDUCE');const payload=state.serialize(),restored=new RuntimeState(settings);restored.restore(payload);expect(new PositionLifecycleTracker(restored).close('BTCUSDT','LONG','RECONCILIATION')?.status).toBe('CLOSED');});
  it('does not duplicate a fill and keeps negative trading net separate from unknown canonical net',()=>{const state=new RuntimeState(settings),service=new PositionService(state,new EventBus()),pos:any={id:'p',symbol:'BTCUSDT',side:'LONG',quantity:1,entryPrice:100,markPrice:100,leverage:10,unrealizedPnl:0,unrealizedPnlPercent:0,openedAt:100,firstObservedAt:100,entryTimeSource:'SYSTEM_FILL',managementStatus:'AUTO_MANAGED',humanManagedAt:null,tpStatus:'PROTECTED',tpOrderId:null,tpLastVerifiedAt:null,tpCoverageSource:'NONE'};state.positions.set(pos.id,pos);service.observeRemotePosition(pos,'RECONCILIATION');const fill={cycleId:pos.cycleId,fillId:'f1',symbol:'BTCUSDT',side:'BUY' as const,positionSide:'LONG' as const,orderId:'entry-x',clientOrderId:'entry_x',tradeId:'t1',executionTime:101,qty:1,price:100,realizedPnl:0,commission:2,commissionAsset:'USDT',commissionUsd:2,maker:true};service.recordExchangeFill(fill);service.recordExchangeFill(fill);service.recordExchangeFill({...fill,fillId:'f2',side:'SELL',orderId:'tp-x',clientOrderId:'tp_x',tradeId:'t2',executionTime:102,price:101,realizedPnl:1});service.onReconciledClose(pos,'TP');const record=[...state.tradeRecords.values()][0];expect(state.executionFills).toHaveLength(2);expect(record.grossRealizedPnl).toBe(1);expect(record.tradingNetPnlExFunding).toBe(-3);expect(record.netPnl).toBeNull();expect(state.experienceSamples.size).toBe(0);});
  it('matches fills by symbol and client id, then closes the owning decision chain once',()=>{const state=new RuntimeState(settings),bus=new EventBus(),events:any[]=[];bus.on('ORDER_FILL_RECONCILED',event=>events.push(event));bus.on('ENTRY_FILLED',event=>events.push(event));const service=new PositionService(state,bus),old:any={id:'old',clientOrderId:'ml_old',exchangeOrderId:'shared-per-symbol',symbol:'OLDUSDT',side:'SHORT',quantity:2,price:10,filledQuantity:0,leverage:10,status:'WORKING',createdAt:1,updatedAt:1,absoluteExpiresAt:999999,repriceCount:0,intentId:'old-intent',reachability:1},current:any={...old,id:'current',clientOrderId:'ml_current',symbol:'NEWUSDT',intentId:'current-intent'};state.entryOrders.set(old.id,old);state.entryOrders.set(current.id,current);state.entryIntents.set('current-intent',{id:'current-intent',brainRunId:'run-current'} as any);const fill={fillId:'fill-current',symbol:'NEWUSDT',side:'SELL' as const,positionSide:'SHORT' as const,orderId:'shared-per-symbol',clientOrderId:'ml_current',tradeId:'trade-current',executionTime:10,qty:2,price:10,realizedPnl:0,commission:0,commissionAsset:'USDT',commissionUsd:0,maker:true};service.recordExchangeFill(fill);service.recordExchangeFill(fill);expect(state.entryOrders.get('old')).toMatchObject({filledQuantity:0,status:'WORKING'});expect(state.entryOrders.get('current')).toMatchObject({filledQuantity:2,status:'FILLED'});const terminal=events.filter(event=>event.type==='ENTRY_FILLED');expect(terminal).toHaveLength(1);expect(terminal[0]?.payload).toMatchObject({decisionChainId:'run-current',intentId:'current-intent',clientOrderId:'ml_current',fillCount:1});});
});
