import { ExecutionFillSchema, ExperienceSampleSchema, TradeRecordSchema, type EntryOrder, type ExecutionFill, type Position, type TakeProfitOrder } from '@zdj/contracts';
import type { RuntimeState } from '../state/runtimeState.js';
import type { EventBus } from '../events/eventBus.js';
import { PositionLifecycleTracker } from './positionLifecycleTracker.js';
import { accountCycle, cycleFills, exactCycleRecord } from './cycleAccounting.js';
import type { TradeAuditSnapshot } from '../types.js';

type CloseReason='TP'|'MANUAL'|'RECONCILIATION'|'UNKNOWN';
const expectedEntrySide=(direction:'LONG'|'SHORT')=>direction==='LONG'?'BUY':'SELL';
const stable=(asset:string)=>['USDT','USDC','BUSD'].includes(asset.toUpperCase());

export class PositionService {
  private readonly lifecycle:PositionLifecycleTracker;
  constructor(private state:RuntimeState,private events:EventBus){this.lifecycle=new PositionLifecycleTracker(state);}
  private record(fill:ExecutionFill,stage:'ENTRY'|'EXIT'){const owner=exactCycleRecord(this.state,fill);const parsed=ExecutionFillSchema.parse({...fill,cycleId:fill.cycleId??owner?.cycleId});this.state.recordExecutionFill(parsed);this.lifecycle.attachFill(parsed,stage);}
  private currentRecord(pos:Position){
    const cycleId=pos.cycleId??this.state.lifecycles.get(this.lifecycle.key(pos.symbol,pos.side))?.cycleId;
    return [...this.state.tradeRecords.values()].find(r=>r.symbol===pos.symbol&&r.direction===pos.side&&r.cycleId===cycleId);
  }
  private ensureOpenRecord(pos:Position,source:'SYSTEM'|'IMPORTED_AT_STARTUP'|'RECONCILIATION'='SYSTEM'){
    const cycle=this.state.lifecycles.get(this.lifecycle.key(pos.symbol,pos.side)),existing=this.currentRecord(pos);if(existing){if(!existing.positionId){const linked={...existing,positionId:pos.id};this.state.tradeRecords.set(linked.tradeId,linked);return linked;}return existing;}const now=Date.now(),tradeId=`trade_${cycle?.cycleId??pos.id}`;
    const record=TradeRecordSchema.parse({tradeId,positionId:pos.id,symbol:pos.symbol,direction:pos.side,openedAt:pos.openedAt,closedAt:null,durationMs:null,entryQty:pos.quantity,entryAveragePrice:pos.entryPrice,exitAveragePrice:null,entryFee:null,exitFee:null,totalFee:null,funding:null,entryGrossNotional:pos.quantity*pos.entryPrice,exitGrossNotional:0,marginUsed:null,netRoiOnMargin:null,netReturnOnNotional:null,entryFillCount:0,exitFillCount:0,feeBreakdown:[],grossRealizedPnl:null,netPnl:null,closeReason:null,status:source==='SYSTEM'?'OPEN':'IMPORTED_OPEN_POSITION',entryRunId:null,entryIntentId:null,entryOrderIds:[],exitOrderIds:[],source,regime:this.state.eips.get(pos.symbol)?.globalRegime.regime??null,feeCompleteness:'UNKNOWN',recordCompleteness:'PARTIAL',classification:source==='IMPORTED_AT_STARTUP'?'IMPORTED':'PARTIAL',canonical:true,duplicateOf:null,cycleId:this.state.lifecycles.get(this.lifecycle.key(pos.symbol,pos.side))?.cycleId??null,repairSource:null,linkedFillIds:[],missingFacts:['EXIT_FACT','FEE_FACT'],integrityFlags:[],createdAt:pos.firstObservedAt??now,updatedAt:now,firstObservedAt:pos.firstObservedAt??pos.openedAt});
    this.state.tradeRecords.set(tradeId,record);this.events.publish('TRADE_RECORD_OPENED',record,pos.symbol);return record;
  }
  onEntryFilled(order:EntryOrder):Position{
    this.state.entryOrders.set(order.id,order);const filledQuantity=order.filledQuantity>0?order.filledQuantity:order.quantity,now=Date.now();
    const existing=[...this.state.positions.values()].find(pos=>pos.symbol===order.symbol&&pos.side===order.side);
    const intent=this.state.entryIntents.get(order.intentId),plan=intent?.profitTakePlan??null;
    const pos:Position=existing?{...existing,quantity:existing.quantity+filledQuantity,entryPrice:(existing.entryPrice*existing.quantity+order.price*filledQuantity)/(existing.quantity+filledQuantity),profitTakePlan:existing.profitTakePlan??plan,economicAdmission:existing.economicAdmission??intent?.economicAdmission??null}:{id:`pos_${order.id}`,symbol:order.symbol,side:order.side,quantity:filledQuantity,entryPrice:order.price,markPrice:order.price,leverage:order.leverage,unrealizedPnl:0,unrealizedPnlPercent:0,openedAt:now,firstObservedAt:now,entryTimeSource:'SYSTEM_FILL',managementStatus:'AUTO_MANAGED',humanManagedAt:null,tpStatus:'PENDING',tpOrderId:null,tpLastVerifiedAt:null,tpCoverageSource:'NONE',tpEconomics:null,profitTakePlan:plan,profitTakePlanSource:null,economicAdmission:intent?.economicAdmission??null,lossHandoff:{cycleId:`pos_${order.id}`,lastClosedBarAt:null,consecutiveLossBars:0,status:'ACTIVE'}};
    const transition=this.lifecycle.observe({symbol:pos.symbol,side:pos.side,quantity:pos.quantity,cycleId:order.cycleId,openedAt:pos.openedAt,firstObservedAt:pos.firstObservedAt??pos.openedAt,source:'SYSTEM'});let record=this.ensureOpenRecord(pos,'SYSTEM');pos.cycleId=transition.lifecycle.cycleId;this.state.entryOrders.set(order.id,{...order,cycleId:pos.cycleId});
    if(record.entryIntentId!==order.intentId||!record.entryOrderIds.includes(order.id)){record={...record,entryRunId:intent?.brainRunId??record.entryRunId,entryIntentId:order.intentId,entryOrderIds:[...new Set([...record.entryOrderIds,order.id,...(order.exchangeOrderId?[order.exchangeOrderId]:[])])],entryQty:pos.quantity,entryAveragePrice:pos.entryPrice,entryGrossNotional:pos.quantity*pos.entryPrice,updatedAt:now};this.state.tradeRecords.set(record.tradeId,TradeRecordSchema.parse(record));}
    this.record({cycleId:record.cycleId,fillId:`simulation-entry-${order.id}-${now}`,symbol:order.symbol,direction:order.side,side:order.side==='LONG'?'BUY':'SELL',positionSide:order.side,orderId:order.exchangeOrderId??order.id,clientOrderId:order.id,tradeId:`sim_${order.id}`,executionTime:now,qty:filledQuantity,price:order.price,realizedPnl:0,commission:0,commissionAsset:'USDT',commissionUsd:0,maker:true,source:'SIMULATION'},'ENTRY');
    this.state.positions.set(pos.id,pos);this.state.account.availableUsd=Math.max(0,(this.state.account.availableUsd??0)-(filledQuantity*order.price/order.leverage));this.events.publish('POSITION_LIFECYCLE_TRANSITION',{positionId:pos.id,transition:transition.transition,quantity:pos.quantity},pos.symbol);this.events.publish('TRADE_RECORD_OPENED',this.state.tradeRecords.get(record.tradeId),order.symbol);this.events.publish('POSITION_OPENED',pos,order.symbol);return pos;
  }
  updateMarks(){for(const [id,p] of this.state.positions){const q=this.state.snapshots.get(p.symbol)?.quote;if(!q)continue;const move=p.side==='LONG'?q.mark-p.entryPrice:p.entryPrice-q.mark,pnl=move*p.quantity;this.state.positions.set(id,{...p,markPrice:q.mark,unrealizedPnl:pnl,unrealizedPnlPercent:(move/p.entryPrice)*p.leverage*100});}}
  observeRemotePosition(remote:Position,source:'RECONCILIATION'|'IMPORTED_AT_STARTUP'='RECONCILIATION',entryOrder?:EntryOrder){
    if(entryOrder){const owner=exactCycleRecord(this.state,{symbol:entryOrder.symbol,orderId:entryOrder.exchangeOrderId??entryOrder.id,clientOrderId:entryOrder.clientOrderId??'',tradeId:''});if(owner&&(owner.status==='CLOSED'||owner.observedClosedAt))entryOrder=undefined;}
    const transition=this.lifecycle.observe({symbol:remote.symbol,side:remote.side,quantity:remote.quantity,cycleId:remote.cycleId??entryOrder?.cycleId,openedAt:remote.openedAt,firstObservedAt:remote.firstObservedAt??remote.openedAt,source});remote.cycleId=transition.lifecycle.cycleId;const record=this.ensureOpenRecord(remote,source==='RECONCILIATION'?'RECONCILIATION':'IMPORTED_AT_STARTUP');
    remote.cycleId=transition.lifecycle.cycleId;this.state.positions.set(remote.id,remote);
    if(entryOrder){entryOrder={...entryOrder,cycleId:transition.lifecycle.cycleId};this.state.entryOrders.set(entryOrder.id,entryOrder);}
    const intent=entryOrder?this.state.entryIntents.get(entryOrder.intentId):undefined;
    if(entryOrder&&record.status!=='CLOSED'&&!record.observedClosedAt){const linked=TradeRecordSchema.parse({...record,status:'OPEN',source:'SYSTEM',classification:'PARTIAL',entryIntentId:entryOrder.intentId,entryRunId:intent?.brainRunId??record.entryRunId,cycleId:transition.lifecycle.cycleId,entryOrderIds:[...new Set([...record.entryOrderIds,entryOrder.id,...(entryOrder.exchangeOrderId&&this.state.executionFills.some(f=>f.symbol===remote.symbol&&f.orderId===entryOrder.exchangeOrderId)?[entryOrder.exchangeOrderId]:[])])],linkedFillIds:[...new Set([...record.linkedFillIds,...this.state.executionFills.filter(f=>f.symbol===remote.symbol&&f.direction===remote.side&&f.orderId===entryOrder.exchangeOrderId).map(f=>f.fillId)])],entryQty:record.entryQty,entryAveragePrice:record.entryAveragePrice,entryGrossNotional:record.entryGrossNotional,updatedAt:Date.now()});this.state.tradeRecords.set(linked.tradeId,linked);}
    if(transition.transition==='REDUCE'&&record.status!=='CLOSED'){const current=this.state.tradeRecords.get(record.tradeId)??record,next=TradeRecordSchema.parse({...current,status:'PARTIALLY_CLOSED',closedAt:null,updatedAt:Date.now()});this.state.tradeRecords.set(next.tradeId,next);}
    this.events.publish('POSITION_LIFECYCLE_TRANSITION',{positionId:remote.id,transition:transition.transition,previousQty:transition.lifecycle.previousQty,currentQty:remote.quantity},remote.symbol);return transition;
  }
  recordExchangeFill(input:Omit<ExecutionFill,'direction'|'commissionUsd'|'source'> & {direction?:'LONG'|'SHORT';commissionUsd?:number|null;source?:'USER_DATA_WS'|'EXCHANGE_AUDIT'}){
    const owner=exactCycleRecord(this.state,input);
    const direction=owner?.direction??input.direction??(input.positionSide==='LONG'?'LONG':input.positionSide==='SHORT'?'SHORT':(/^(tp_|manual_|ma_|mr_|mc_|ec[0-9]*_)/i.test(input.clientOrderId)?(input.side==='SELL'?'LONG':'SHORT'):(input.side==='BUY'?'LONG':'SHORT'))),orders=[...this.state.entryOrders.values()].filter(row=>row.symbol===input.symbol),localOrder=orders.find(row=>Boolean(input.clientOrderId)&&row.clientOrderId===input.clientOrderId)??orders.find(row=>Boolean(input.orderId)&&row.exchangeOrderId===input.orderId),localIntent=localOrder?this.state.entryIntents.get(localOrder.intentId):undefined,systemProven=Boolean(localOrder||localIntent||/^(entry_|ml_|tp_|manual_|ma_|mr_|mc_|ec[0-9]*_)/i.test(input.clientOrderId)),pos=[...this.state.positions.values()].find(row=>row.symbol===input.symbol&&row.side===direction),stage=/^(tp_|manual_|ma_|mr_|mc_|ec[0-9]*_)/i.test(input.clientOrderId)||input.side!==expectedEntrySide(direction)?'EXIT':'ENTRY';
    if(!this.state.lifecycles.has(this.lifecycle.key(input.symbol,direction))&&pos)this.lifecycle.observe({symbol:input.symbol,side:direction,quantity:pos.quantity,openedAt:pos.openedAt,firstObservedAt:pos.firstObservedAt??pos.openedAt,source:'RECONCILIATION'});
    if(stage==='ENTRY'&&localOrder&&!exactCycleRecord(this.state,input)){
      const cycleId=localOrder.cycleId??`cycle_${localOrder.id}`;
      const old=[...this.state.tradeRecords.values()].find(r=>r.cycleId===cycleId);
      if(!old){const now=input.executionTime,record=TradeRecordSchema.parse({tradeId:`trade_${cycleId}`,cycleId,symbol:input.symbol,direction:localOrder.side,positionId:null,openedAt:now,closedAt:null,durationMs:null,entryQty:0,entryAveragePrice:null,exitAveragePrice:null,funding:null,grossRealizedPnl:null,netPnl:null,closeReason:null,status:'OPEN',entryRunId:localIntent?.brainRunId??null,entryIntentId:localOrder.intentId,entryOrderIds:[localOrder.id,input.orderId],exitOrderIds:[],source:'SYSTEM',regime:null,createdAt:now,updatedAt:now,firstObservedAt:now});this.state.tradeRecords.set(record.tradeId,record);}
      this.state.entryOrders.set(localOrder.id,{...localOrder,cycleId});
    }
    const exact=exactCycleRecord(this.state,input);
    if(stage==='ENTRY'&&exact&&exact.status!=='CLOSED'&&!exact.observedClosedAt){
      const active=this.state.lifecycles.get(this.lifecycle.key(input.symbol,exact.direction));
      if(!active||active.status==='CLOSED')this.lifecycle.observe({symbol:input.symbol,side:exact.direction,cycleId:exact.cycleId,quantity:input.qty,openedAt:exact.openedAt,source:'SYSTEM'});
    }
    const fill=ExecutionFillSchema.parse({...input,cycleId:exact?.cycleId??this.state.entryOrders.get(localOrder?.id)?.cycleId??input.cycleId,direction:exact?.direction??direction,commissionUsd:input.commissionUsd!==undefined?input.commissionUsd:(stable(input.commissionAsset)?input.commission:null),source:input.source??'USER_DATA_WS',attributionStatus:systemProven?'SYSTEM_ATTRIBUTED':'EXTERNAL_OR_UNLINKED',decisionChainId:localOrder?.decisionChainId??localIntent?.decisionChainId??localIntent?.brainRunId??null,allocationPlanId:(localIntent?.allocationPlan as any)?.planId??null});this.record(fill,stage);
    if(localOrder){const fills=[...(localOrder.fills??[]).filter(row=>row.tradeId!==fill.tradeId),{tradeId:fill.tradeId,qty:fill.qty,price:fill.price,commission:fill.commissionUsd,commissionAsset:fill.commissionAsset,executedAt:fill.executionTime}],filledQuantity=Math.max(localOrder.filledQuantity,fills.reduce((n,row)=>n+row.qty,0)),avg=fills.reduce((n,row)=>n+row.price*row.qty,0)/Math.max(filledQuantity,1),status=filledQuantity>=localOrder.quantity-1e-10?'FILLED':localOrder.status==='CANCELED'?'CANCELED':'PARTIALLY_FILLED',decisionChainId=fill.decisionChainId??localIntent?.brainRunId??null;this.state.entryOrders.set(localOrder.id,{...localOrder,cycleId:fill.cycleId,filledQuantity,status,fillState:filledQuantity>=localOrder.quantity-1e-10?'COMPLETE':'PARTIAL',fills,price:avg||localOrder.price,updatedAt:Date.now()});this.events.publish('ORDER_FILL_RECONCILED',{decisionChainId,brainRunId:decisionChainId,intentId:localOrder.intentId,orderId:localOrder.id,exchangeOrderId:fill.orderId,clientOrderId:fill.clientOrderId,tradeId:fill.tradeId,filledQuantity,status,fillState:status==='CANCELED'?'PARTIALLY_FILLED_THEN_CANCELED':status},fill.symbol);if(status==='FILLED'&&localOrder.status!=='FILLED')this.events.publish('ENTRY_FILLED',{decisionChainId,brainRunId:decisionChainId,intentId:localOrder.intentId,orderId:localOrder.id,exchangeOrderId:fill.orderId,clientOrderId:fill.clientOrderId,filledQuantity,fillCount:fills.length},fill.symbol);}
    const target=exact??exactCycleRecord(this.state,fill);
    if(target){const linked={...target,linkedFillIds:[...new Set([...target.linkedFillIds,fill.fillId])]},next=accountCycle(linked,cycleFills(this.state,linked));this.state.tradeRecords.set(next.tradeId,next);if(next.status==='CLOSED'&&this.state.lifecycles.get(this.lifecycle.key(next.symbol,next.direction))?.cycleId===next.cycleId)this.lifecycle.close(next.symbol,next.direction,'SYSTEM');this.events.publish('TRADE_RECORD_REPAIRED',next,fill.symbol);}
    this.events.publish(systemProven?'EXCHANGE_FILL_ATTRIBUTED':'EXCHANGE_FILL_UNATTRIBUTED',{decisionChainId:fill.decisionChainId??null,brainRunId:fill.decisionChainId??null,fill,stage,localOrderId:localOrder?.id??null},fill.symbol);return{fill,stage};
  }
  onReconciledClose(position:Position,reason:CloseReason='RECONCILIATION',source:'RECONCILIATION'|'LOCAL_LIFECYCLE_REPAIR_FROM_EXCHANGE_FACT'='RECONCILIATION'){this.lifecycle.close(position.symbol,position.side,source);this.finalizeSafe(position,reason,source);}
  onTakeProfitFilled(order:TakeProfitOrder){
    const pos=this.state.positions.get(order.positionId);if(!pos)return;const gross=(pos.side==='LONG'?order.price-pos.entryPrice:pos.entryPrice-order.price)*Math.min(pos.quantity,order.quantity),margin=pos.quantity*pos.entryPrice/pos.leverage,now=Date.now();
    this.record({cycleId:order.cycleId??pos.cycleId,fillId:`simulation-exit-${order.id}-${now}`,symbol:pos.symbol,direction:pos.side,side:pos.side==='LONG'?'SELL':'BUY',positionSide:pos.side,orderId:order.exchangeOrderId??order.id,clientOrderId:order.id,tradeId:`sim_${order.id}`,executionTime:now,qty:Math.min(pos.quantity,order.quantity),price:order.price,realizedPnl:gross,commission:0,commissionAsset:'USDT',commissionUsd:0,maker:true,source:'SIMULATION'},'EXIT');
    this.state.account.availableUsd=(this.state.account.availableUsd??0)+margin+gross;this.state.account.realizedPnlUsd24h=(this.state.account.realizedPnlUsd24h??0)+gross;this.state.positions.delete(pos.id);
    if(order.quantity<pos.quantity){const remaining={...pos,quantity:pos.quantity-order.quantity};this.state.positions.set(pos.id,remaining);this.lifecycle.observe({symbol:remaining.symbol,side:remaining.side,quantity:remaining.quantity,openedAt:remaining.openedAt,firstObservedAt:remaining.firstObservedAt??remaining.openedAt,source:'SYSTEM'});this.finalizeSafe({...pos,quantity:order.quantity},'TP','RECONCILIATION');return;}
    this.onReconciledClose(pos,'TP','RECONCILIATION');
  }
  private finalizeSafe(position:Position,reason:CloseReason,source:'RECONCILIATION'|'LOCAL_LIFECYCLE_REPAIR_FROM_EXCHANGE_FACT'='RECONCILIATION'){
    const record=this.currentRecord(position)??this.ensureOpenRecord(position,'RECONCILIATION');
    const linked={...record,observedClosedAt:record.observedClosedAt??Date.now(),closeReason:reason,repairSource:source};
    const next=accountCycle(linked,cycleFills(this.state,linked));
    this.state.tradeRecords.set(next.tradeId,next);
    this.events.publish(next.status==='CLOSED'?'TRADE_RECORD_CLOSED':'TRADE_RECORD_REPAIRED',next,next.symbol);
  }
  repairClosedCyclesFromAudit(_audit:TradeAuditSnapshot){
    throw new Error('EXPLICIT_SYNC_PREVIEW_AND_APPLY_REQUIRED');
  }
}
