import { ExecutionFillSchema, ExperienceSampleSchema, TradeRecordSchema, type EntryOrder, type ExecutionFill, type Position, type TakeProfitOrder } from '@zdj/contracts';
import type { RuntimeState } from '../state/runtimeState.js';
import type { EventBus } from '../events/eventBus.js';
import { PositionLifecycleTracker } from './positionLifecycleTracker.js';
import type { TradeAuditSnapshot } from '../types.js';

type CloseReason='TP'|'MANUAL'|'RECONCILIATION'|'UNKNOWN';
const expectedEntrySide=(direction:'LONG'|'SHORT')=>direction==='LONG'?'BUY':'SELL';
const stable=(asset:string)=>['USDT','USDC','BUSD'].includes(asset.toUpperCase());

export class PositionService {
  private readonly lifecycle:PositionLifecycleTracker;
  constructor(private state:RuntimeState,private events:EventBus){this.lifecycle=new PositionLifecycleTracker(state);}
  private record(fill:ExecutionFill,stage:'ENTRY'|'EXIT'){const parsed=ExecutionFillSchema.parse(fill);this.state.recordExecutionFill(parsed);this.lifecycle.attachFill(parsed,stage);}
  private currentRecord(pos:Position){const cycle=this.state.lifecycles.get(this.lifecycle.key(pos.symbol,pos.side));return (cycle?[...this.state.tradeRecords.values()].find(r=>r.symbol===pos.symbol&&r.direction===pos.side&&r.cycleId===cycle.cycleId):undefined)??this.state.tradeRecords.get(`trade_${pos.id}`);}
  private ensureOpenRecord(pos:Position,source:'SYSTEM'|'IMPORTED_AT_STARTUP'|'RECONCILIATION'='SYSTEM'){
    const cycle=this.state.lifecycles.get(this.lifecycle.key(pos.symbol,pos.side)),existing=this.currentRecord(pos);if(existing&&(existing.status!=='CLOSED'||existing.cycleId===cycle?.cycleId))return existing;const now=Date.now(),tradeId=existing?`trade_${pos.id}_${cycle?.cycleId??now}`:`trade_${pos.id}`;
    const record=TradeRecordSchema.parse({tradeId,symbol:pos.symbol,direction:pos.side,openedAt:pos.openedAt,closedAt:null,durationMs:null,entryQty:pos.quantity,entryAveragePrice:pos.entryPrice,exitAveragePrice:null,entryFee:null,exitFee:null,totalFee:null,funding:null,entryGrossNotional:pos.quantity*pos.entryPrice,exitGrossNotional:0,marginUsed:null,netRoiOnMargin:null,netReturnOnNotional:null,entryFillCount:0,exitFillCount:0,feeBreakdown:[],grossRealizedPnl:null,netPnl:null,closeReason:null,status:source==='SYSTEM'?'OPEN':'IMPORTED_OPEN_POSITION',entryRunId:null,entryIntentId:null,entryOrderIds:[],exitOrderIds:[],source,regime:this.state.eips.get(pos.symbol)?.globalRegime.regime??null,feeCompleteness:'UNKNOWN',recordCompleteness:'PARTIAL',classification:source==='IMPORTED_AT_STARTUP'?'IMPORTED':'PARTIAL',canonical:true,duplicateOf:null,cycleId:this.state.lifecycles.get(this.lifecycle.key(pos.symbol,pos.side))?.cycleId??null,repairSource:null,linkedFillIds:[],missingFacts:['EXIT_FACT','FEE_FACT'],integrityFlags:[],createdAt:pos.firstObservedAt??now,updatedAt:now,firstObservedAt:pos.firstObservedAt??pos.openedAt});
    this.state.tradeRecords.set(tradeId,record);this.events.publish('TRADE_RECORD_OPENED',record,pos.symbol);return record;
  }
  onEntryFilled(order:EntryOrder):Position{
    this.state.entryOrders.set(order.id,order);const filledQuantity=order.filledQuantity>0?order.filledQuantity:order.quantity,now=Date.now();
    const existing=[...this.state.positions.values()].find(pos=>pos.symbol===order.symbol&&pos.side===order.side);
    const intent=this.state.entryIntents.get(order.intentId),plan=intent?.profitTakePlan??null;
    const pos:Position=existing?{...existing,quantity:existing.quantity+filledQuantity,entryPrice:(existing.entryPrice*existing.quantity+order.price*filledQuantity)/(existing.quantity+filledQuantity),profitTakePlan:existing.profitTakePlan??plan}:{id:`pos_${order.id}`,symbol:order.symbol,side:order.side,quantity:filledQuantity,entryPrice:order.price,markPrice:order.price,leverage:order.leverage,unrealizedPnl:0,unrealizedPnlPercent:0,openedAt:now,firstObservedAt:now,entryTimeSource:'SYSTEM_FILL',managementStatus:'AUTO_MANAGED',humanManagedAt:null,tpStatus:'PENDING',tpOrderId:null,tpLastVerifiedAt:null,tpCoverageSource:'NONE',tpEconomics:null,profitTakePlan:plan,profitTakePlanSource:null,lossHandoff:{cycleId:`pos_${order.id}`,lastClosedBarAt:null,consecutiveLossBars:0,status:'ACTIVE'}};
    const transition=this.lifecycle.observe({symbol:pos.symbol,side:pos.side,quantity:pos.quantity,openedAt:pos.openedAt,firstObservedAt:pos.firstObservedAt??pos.openedAt,source:'SYSTEM'});let record=this.ensureOpenRecord(pos,'SYSTEM');
    if(record.entryIntentId!==order.intentId||!record.entryOrderIds.includes(order.id)){record={...record,entryRunId:intent?.brainRunId??record.entryRunId,entryIntentId:order.intentId,entryOrderIds:[...new Set([...record.entryOrderIds,order.id])],entryQty:pos.quantity,entryAveragePrice:pos.entryPrice,entryGrossNotional:pos.quantity*pos.entryPrice,updatedAt:now};this.state.tradeRecords.set(record.tradeId,TradeRecordSchema.parse(record));}
    this.record({fillId:`simulation-entry-${order.id}-${now}`,symbol:order.symbol,direction:order.side,side:order.side==='LONG'?'BUY':'SELL',positionSide:order.side,orderId:order.exchangeOrderId??order.id,clientOrderId:order.id,tradeId:`sim_${order.id}`,executionTime:now,qty:filledQuantity,price:order.price,realizedPnl:0,commission:0,commissionAsset:'USDT',commissionUsd:0,maker:true,source:'SIMULATION'},'ENTRY');
    this.state.positions.set(pos.id,pos);this.state.account.availableUsd=Math.max(0,(this.state.account.availableUsd??0)-(filledQuantity*order.price/order.leverage));this.events.publish('POSITION_LIFECYCLE_TRANSITION',{positionId:pos.id,transition:transition.transition,quantity:pos.quantity},pos.symbol);this.events.publish('TRADE_RECORD_OPENED',this.state.tradeRecords.get(record.tradeId),order.symbol);this.events.publish('POSITION_OPENED',pos,order.symbol);return pos;
  }
  updateMarks(){for(const [id,p] of this.state.positions){const q=this.state.snapshots.get(p.symbol)?.quote;if(!q)continue;const move=p.side==='LONG'?q.mark-p.entryPrice:p.entryPrice-q.mark,pnl=move*p.quantity;this.state.positions.set(id,{...p,markPrice:q.mark,unrealizedPnl:pnl,unrealizedPnlPercent:(move/p.entryPrice)*p.leverage*100});}}
  observeRemotePosition(remote:Position,source:'RECONCILIATION'|'IMPORTED_AT_STARTUP'='RECONCILIATION',entryOrder?:EntryOrder){
    const transition=this.lifecycle.observe({symbol:remote.symbol,side:remote.side,quantity:remote.quantity,openedAt:remote.openedAt,firstObservedAt:remote.firstObservedAt??remote.openedAt,source});const record=this.ensureOpenRecord(remote,source==='RECONCILIATION'?'RECONCILIATION':'IMPORTED_AT_STARTUP');
    const intent=entryOrder?this.state.entryIntents.get(entryOrder.intentId):undefined;
    if(entryOrder){const linked=TradeRecordSchema.parse({...record,status:'OPEN',source:'SYSTEM',classification:'PARTIAL',entryIntentId:entryOrder.intentId,entryRunId:intent?.brainRunId??record.entryRunId,cycleId:transition.lifecycle.cycleId,entryOrderIds:[...new Set([...record.entryOrderIds,entryOrder.id,...(entryOrder.exchangeOrderId&&this.state.executionFills.some(f=>f.symbol===remote.symbol&&f.orderId===entryOrder.exchangeOrderId)?[entryOrder.exchangeOrderId]:[])])],linkedFillIds:[...new Set([...record.linkedFillIds,...this.state.executionFills.filter(f=>f.symbol===remote.symbol&&f.direction===remote.side&&f.orderId===entryOrder.exchangeOrderId).map(f=>f.fillId)])],entryQty:remote.quantity,entryAveragePrice:remote.entryPrice,entryGrossNotional:remote.quantity*remote.entryPrice,updatedAt:Date.now()});this.state.tradeRecords.set(linked.tradeId,linked);}
    if(transition.transition==='REDUCE'){const current=this.state.tradeRecords.get(record.tradeId)??record,next=TradeRecordSchema.parse({...current,status:'PARTIALLY_CLOSED',entryQty:remote.quantity,updatedAt:Date.now()});this.state.tradeRecords.set(next.tradeId,next);}
    this.events.publish('POSITION_LIFECYCLE_TRANSITION',{positionId:remote.id,transition:transition.transition,previousQty:transition.lifecycle.previousQty,currentQty:remote.quantity},remote.symbol);return transition;
  }
  recordExchangeFill(input:Omit<ExecutionFill,'direction'|'commissionUsd'|'source'> & {direction?:'LONG'|'SHORT';commissionUsd?:number|null;source?:'USER_DATA_WS'|'EXCHANGE_AUDIT'}){
    const direction=input.direction??(input.positionSide==='LONG'?'LONG':input.positionSide==='SHORT'?'SHORT':input.side==='BUY'?'LONG':'SHORT'),orders=[...this.state.entryOrders.values()].filter(row=>row.symbol===input.symbol),localOrder=orders.find(row=>Boolean(input.clientOrderId)&&row.clientOrderId===input.clientOrderId)??orders.find(row=>Boolean(input.orderId)&&row.exchangeOrderId===input.orderId),localIntent=localOrder?this.state.entryIntents.get(localOrder.intentId):undefined,systemProven=Boolean(localOrder||localIntent||/^(entry_|ml_|tp_|manual_|ma_|mr_|mc_|ec[0-9]*_)/i.test(input.clientOrderId)),pos=[...this.state.positions.values()].find(row=>row.symbol===input.symbol&&row.side===direction),stage=/^(tp_|manual_|ma_|mr_|mc_|ec[0-9]*_)/i.test(input.clientOrderId)||input.side!==expectedEntrySide(direction)?'EXIT':'ENTRY';
    if(!this.state.lifecycles.has(this.lifecycle.key(input.symbol,direction))&&pos)this.lifecycle.observe({symbol:input.symbol,side:direction,quantity:pos.quantity,openedAt:pos.openedAt,firstObservedAt:pos.firstObservedAt??pos.openedAt,source:'RECONCILIATION'});
    const fill=ExecutionFillSchema.parse({...input,direction,commissionUsd:input.commissionUsd??(stable(input.commissionAsset)?input.commission: null),source:input.source??'USER_DATA_WS',attributionStatus:systemProven?'SYSTEM_ATTRIBUTED':'EXTERNAL_OR_UNLINKED',decisionChainId:localOrder?.decisionChainId??localIntent?.decisionChainId??localIntent?.brainRunId??null,allocationPlanId:(localIntent?.allocationPlan as any)?.planId??null});this.record(fill,stage);
    if(localOrder){const fills=[...(localOrder.fills??[]).filter(row=>row.tradeId!==fill.tradeId),{tradeId:fill.tradeId,qty:fill.qty,price:fill.price,commission:fill.commissionUsd,commissionAsset:fill.commissionAsset,executedAt:fill.executionTime}],filledQuantity=Math.max(localOrder.filledQuantity,fills.reduce((n,row)=>n+row.qty,0)),avg=fills.reduce((n,row)=>n+row.price*row.qty,0)/Math.max(filledQuantity,1),status=filledQuantity>=localOrder.quantity-1e-10?'FILLED':localOrder.status==='CANCELED'?'CANCELED':'PARTIALLY_FILLED',decisionChainId=fill.decisionChainId??localIntent?.brainRunId??null;this.state.entryOrders.set(localOrder.id,{...localOrder,filledQuantity,status,fillState:filledQuantity>=localOrder.quantity-1e-10?'COMPLETE':'PARTIAL',fills,price:avg||localOrder.price,updatedAt:Date.now()});this.events.publish('ORDER_FILL_RECONCILED',{decisionChainId,brainRunId:decisionChainId,intentId:localOrder.intentId,orderId:localOrder.id,exchangeOrderId:fill.orderId,clientOrderId:fill.clientOrderId,tradeId:fill.tradeId,filledQuantity,status,fillState:status==='CANCELED'?'PARTIALLY_FILLED_THEN_CANCELED':status},fill.symbol);if(status==='FILLED'&&localOrder.status!=='FILLED')this.events.publish('ENTRY_FILLED',{decisionChainId,brainRunId:decisionChainId,intentId:localOrder.intentId,orderId:localOrder.id,exchangeOrderId:fill.orderId,clientOrderId:fill.clientOrderId,filledQuantity,fillCount:fills.length},fill.symbol);}
    if(stage==='ENTRY'&&pos){let record=this.ensureOpenRecord(pos,'SYSTEM');const exactOrderIds=new Set([...(record.entryOrderIds??[]),...(localOrder?.exchangeOrderId?[localOrder.exchangeOrderId]:[])]);const entry=[...this.state.executionFills].filter(row=>row.symbol===pos.symbol&&row.direction===pos.side&&row.side===expectedEntrySide(pos.side)&&(exactOrderIds.has(row.orderId)||record.linkedFillIds.includes(row.fillId)));const qty=entry.reduce((n,row)=>n+row.qty,0),notional=entry.reduce((n,row)=>n+row.qty*row.price,0),feesKnown=entry.every(row=>row.commissionUsd!==null);record=TradeRecordSchema.parse({...record,status:'OPEN',source:'SYSTEM',entryQty:qty||record.entryQty,entryAveragePrice:qty?notional/qty:record.entryAveragePrice,entryGrossNotional:notional||record.entryGrossNotional,entryFillCount:entry.length,entryOrderIds:[...new Set([...record.entryOrderIds,fill.orderId])],linkedFillIds:[...new Set([...record.linkedFillIds,fill.fillId])],feeCompleteness:feesKnown?'COMPLETE':'PARTIAL',recordCompleteness:feesKnown?'COMPLETE':'PARTIAL',entryIntentId:localOrder?.intentId??record.entryIntentId,entryRunId:localIntent?.brainRunId??record.entryRunId,updatedAt:Date.now()});this.state.tradeRecords.set(record.tradeId,record);this.events.publish('TRADE_RECORD_OPENED_FROM_FILL',{tradeId:record.tradeId,fillId:fill.fillId,feeCompleteness:record.feeCompleteness},fill.symbol);}
    this.events.publish(systemProven?'EXCHANGE_FILL_ATTRIBUTED':'EXCHANGE_FILL_UNATTRIBUTED',{decisionChainId:fill.decisionChainId??null,brainRunId:fill.decisionChainId??null,fill,stage,localOrderId:localOrder?.id??null},fill.symbol);return{fill,stage};
  }
  onReconciledClose(position:Position,reason:CloseReason='RECONCILIATION',source:'RECONCILIATION'|'LOCAL_LIFECYCLE_REPAIR_FROM_EXCHANGE_FACT'='RECONCILIATION'){this.lifecycle.close(position.symbol,position.side,source);this.finalizeSafe(position,reason,source);}
  onTakeProfitFilled(order:TakeProfitOrder){
    const pos=this.state.positions.get(order.positionId);if(!pos)return;const gross=(pos.side==='LONG'?order.price-pos.entryPrice:pos.entryPrice-order.price)*Math.min(pos.quantity,order.quantity),margin=pos.quantity*pos.entryPrice/pos.leverage,now=Date.now();
    this.record({fillId:`simulation-exit-${order.id}-${now}`,symbol:pos.symbol,direction:pos.side,side:pos.side==='LONG'?'SELL':'BUY',positionSide:pos.side,orderId:order.exchangeOrderId??order.id,clientOrderId:order.id,tradeId:`sim_${order.id}`,executionTime:now,qty:Math.min(pos.quantity,order.quantity),price:order.price,realizedPnl:gross,commission:0,commissionAsset:'USDT',commissionUsd:0,maker:true,source:'SIMULATION'},'EXIT');
    this.state.account.availableUsd=(this.state.account.availableUsd??0)+margin+gross;this.state.account.realizedPnlUsd24h=(this.state.account.realizedPnlUsd24h??0)+gross;this.state.positions.delete(pos.id);
    if(order.quantity<pos.quantity){const remaining={...pos,quantity:pos.quantity-order.quantity};this.state.positions.set(pos.id,remaining);this.lifecycle.observe({symbol:remaining.symbol,side:remaining.side,quantity:remaining.quantity,openedAt:remaining.openedAt,firstObservedAt:remaining.firstObservedAt??remaining.openedAt,source:'SYSTEM'});this.finalizeSafe({...pos,quantity:order.quantity},'TP','RECONCILIATION');return;}
    this.onReconciledClose(pos,'TP','RECONCILIATION');
  }
  private finalizeSafe(position:Position,reason:CloseReason,source:'RECONCILIATION'|'LOCAL_LIFECYCLE_REPAIR_FROM_EXCHANGE_FACT'='RECONCILIATION'){
    const existing=this.currentRecord(position),record=existing??this.ensureOpenRecord(position,'RECONCILIATION'),tradeId=record.tradeId,closedAt=Date.now(),lifecycle=this.state.lifecycles.get(this.lifecycle.key(position.symbol,position.side));
    if(record.classification==='COMPLETE'&&record.recordCompleteness==='COMPLETE'&&record.feeCompleteness==='COMPLETE')return;
    const exactOrders=new Set([...record.entryOrderIds,...record.exitOrderIds,...(lifecycle?.entryOrderIds??[]),...(lifecycle?.exitOrderIds??[])]),fills=this.state.executionFills.filter(fill=>fill.symbol===position.symbol&&fill.direction===position.side&&(exactOrders.has(fill.orderId)||record.linkedFillIds.includes(fill.fillId))),entryFills=fills.filter(fill=>fill.side===expectedEntrySide(position.side)||lifecycle?.entryOrderIds.includes(fill.orderId)),exitFills=fills.filter(fill=>!entryFills.includes(fill)),entryQty=entryFills.reduce((sum,fill)=>sum+fill.qty,0)||record.entryQty,exitQty=exitFills.reduce((sum,fill)=>sum+fill.qty,0),entryNotional=entryFills.reduce((sum,fill)=>sum+fill.qty*fill.price,0)||record.entryGrossNotional||record.entryQty*(record.entryAveragePrice??position.entryPrice),exitNotional=exitFills.reduce((sum,fill)=>sum+fill.qty*fill.price,0),hasExitFacts=exitFills.length>0&&exitQty>=entryQty-1e-8,feesComplete=hasExitFacts&&[...entryFills,...exitFills].every(fill=>fill.commissionUsd!==null),gross=hasExitFacts?exitFills.reduce((sum,fill)=>sum+fill.realizedPnl,0):null,entryFee=feesComplete?entryFills.reduce((sum,fill)=>sum+(fill.commissionUsd??0),0):null,exitFee=feesComplete?exitFills.reduce((sum,fill)=>sum+(fill.commissionUsd??0),0):null,net=gross!=null&&feesComplete?gross-(entryFee??0)-(exitFee??0):null,margin=source==='RECONCILIATION'&&position.entryPrice>0&&position.leverage>0?entryNotional/position.leverage:null,missingFacts:string[]=[];
    if(!hasExitFacts)missingFacts.push('EXIT_FACT');if(!feesComplete)missingFacts.push('FEE_FACT');if(margin==null)missingFacts.push('MARGIN_FACT');
    const next=TradeRecordSchema.parse({...record,closedAt,durationMs:record.openedAt?Math.max(0,closedAt-record.openedAt):null,entryQty,entryAveragePrice:entryQty?entryNotional/entryQty:record.entryAveragePrice,exitAveragePrice:hasExitFacts?exitNotional/exitQty:null,entryFee,exitFee,totalFee:feesComplete?(entryFee??0)+(exitFee??0):null,entryGrossNotional:entryNotional,exitGrossNotional:hasExitFacts?exitNotional:0,marginUsed:margin,netRoiOnMargin:net!=null&&margin?net/margin*100:null,netReturnOnNotional:net!=null&&exitNotional?net/exitNotional*100:null,entryFillCount:entryFills.length,exitFillCount:exitFills.length,feeBreakdown:fills.map(fill=>({stage:entryFills.includes(fill)?'ENTRY' as const:'EXIT' as const,asset:fill.commissionAsset,amount:fill.commission,usd:fill.commissionUsd,conversionSource:fill.commissionUsd===null?null:stable(fill.commissionAsset)?'STABLE_ASSET':'MARKET_QUOTE'})),grossRealizedPnl:gross,netPnl:net,closeReason:reason,status:'CLOSED',source:record.source,feeCompleteness:feesComplete?'COMPLETE':'PARTIAL',recordCompleteness:feesComplete&&hasExitFacts?'COMPLETE':'PARTIAL',classification:record.source==='IMPORTED_AT_STARTUP'?'IMPORTED':feesComplete&&hasExitFacts?'COMPLETE':'PARTIAL',canonical:record.canonical??true,duplicateOf:record.duplicateOf??null,cycleId:record.cycleId??null,repairSource:source,linkedFillIds:[...new Set(fills.map(fill=>fill.fillId))],missingFacts,integrityFlags:hasExitFacts?[]:['CLOSED_NO_EXIT_FACT'],updatedAt:closedAt});
    this.state.tradeRecords.set(tradeId,next);if(next.classification==='COMPLETE'){const sample=ExperienceSampleSchema.parse({sampleId:`sample_${tradeId}`,tradeId,symbol:next.symbol,direction:next.direction,regime:next.regime,netPnl:next.netPnl??0,winLoss:(next.netPnl??0)>0?'WIN':(next.netPnl??0)<0?'LOSS':'FLAT',fillDelayMs:null,holdingDurationMs:next.durationMs,lesson:'按真实 Exit 与手续费事实完成闭环',mistakeTags:(next.netPnl??0)<0?['NEGATIVE_NET_PNL']:[],successTags:(next.netPnl??0)>0?['NET_PROFIT_COMPLETED']:[],createdAt:closedAt});this.state.experienceSamples.set(sample.sampleId,sample);this.events.publish('EXPERIENCE_SAMPLE_CREATED',sample,next.symbol);}this.events.publish('TRADE_RECORD_CLOSED',next,next.symbol);this.events.publish('POSITION_CLOSED',{position,netPnl:next.netPnl,grossRealizedPnl:next.grossRealizedPnl,tpOrderId:next.exitOrderIds.at(-1)??null},next.symbol);
  }
  private finalize(position:Position,reason:CloseReason,source:'RECONCILIATION'|'LOCAL_LIFECYCLE_REPAIR_FROM_EXCHANGE_FACT'='RECONCILIATION'){
    const tradeId=`trade_${position.id}`,existing=this.state.tradeRecords.get(tradeId),record=existing??this.ensureOpenRecord(position,'RECONCILIATION'),closedAt=Date.now(),lifecycle=this.state.lifecycles.get(this.lifecycle.key(position.symbol,position.side));if(record.status==='CLOSED')return;
    const fills=this.state.executionFills.filter(fill=>fill.symbol===position.symbol&&fill.direction===position.side&&fill.executionTime>=(record.openedAt??record.createdAt)-1000&&fill.executionTime<=closedAt+1000),entryFills=fills.filter(fill=>fill.side===expectedEntrySide(position.side)||lifecycle?.entryOrderIds.includes(fill.orderId)),exitFills=fills.filter(fill=>!entryFills.includes(fill));
    const entryQty=entryFills.reduce((sum,fill)=>sum+fill.qty,0)||record.entryQty,exitQty=exitFills.reduce((sum,fill)=>sum+fill.qty,0),entryNotional=entryFills.reduce((sum,fill)=>sum+fill.qty*fill.price,0)||record.entryGrossNotional||record.entryQty*(record.entryAveragePrice??position.entryPrice),exitNotional=exitFills.reduce((sum,fill)=>sum+fill.qty*fill.price,0),entryFee=entryFills.reduce((sum,fill)=>sum+(fill.commissionUsd??0),0),exitFee=exitFills.reduce((sum,fill)=>sum+(fill.commissionUsd??0),0),realized=exitFills.reduce((sum,fill)=>sum+fill.realizedPnl,0),fallbackGross=(position.side==='LONG'?((exitNotional/Math.max(1,exitQty))-(entryNotional/Math.max(1,entryQty))):((entryNotional/Math.max(1,entryQty))-(exitNotional/Math.max(1,exitQty))))*Math.min(entryQty,exitQty||position.quantity),gross=realized||fallbackGross,feesComplete=fills.length>0&&fills.every(fill=>fill.commissionUsd!==null),net=gross-entryFee-exitFee,margin=entryNotional/Math.max(1,position.leverage),next=TradeRecordSchema.parse({...record,closedAt,durationMs:record.openedAt?Math.max(0,closedAt-record.openedAt):null,entryQty,entryAveragePrice:entryQty?entryNotional/entryQty:record.entryAveragePrice,exitAveragePrice:exitQty?exitNotional/exitQty:null,entryFee,exitFee,totalFee:entryFee+exitFee,entryGrossNotional:entryNotional,exitGrossNotional:exitNotional,netRoiOnMargin:margin?net/margin*100:null,netReturnOnNotional:exitNotional?net/exitNotional*100:null,entryFillCount:entryFills.length,exitFillCount:exitFills.length,feeBreakdown:fills.map(fill=>({stage:entryFills.includes(fill)?'ENTRY':'EXIT',asset:fill.commissionAsset,amount:fill.commission,usd:fill.commissionUsd,conversionSource:fill.commissionUsd===null?null:stable(fill.commissionAsset)?'STABLE_ASSET':'MARKET_QUOTE'})),grossRealizedPnl:gross,netPnl:net,closeReason:reason,status:'CLOSED',source:source==='LOCAL_LIFECYCLE_REPAIR_FROM_EXCHANGE_FACT'?source:record.source,feeCompleteness:feesComplete?'COMPLETE':'PARTIAL',recordCompleteness:feesComplete||fills.some(fill=>fill.source==='SIMULATION')?'COMPLETE':'PARTIAL',updatedAt:closedAt});
    this.state.tradeRecords.set(tradeId,next);const sample=next.recordCompleteness==='COMPLETE'?ExperienceSampleSchema.parse({sampleId:`sample_${tradeId}`,tradeId,symbol:next.symbol,direction:next.direction,regime:next.regime,netPnl:next.netPnl??0,winLoss:(next.netPnl??0)>0?'WIN':(next.netPnl??0)<0?'LOSS':'FLAT',fillDelayMs:null,holdingDurationMs:next.durationMs,lesson:(next.netPnl??0)>0?'按净收益完成止盈':'按净收益复核手续费、入场时机与可达区间',mistakeTags:(next.netPnl??0)<0?['NEGATIVE_NET_PNL']:[],successTags:(next.netPnl??0)>0?['NET_PROFIT_COMPLETED']:[],createdAt:closedAt}):null;if(sample)this.state.experienceSamples.set(sample.sampleId,sample);if(next.recordCompleteness==='COMPLETE'){this.state.tradeOutcomes.unshift({symbol:next.symbol,side:next.direction,entryPrice:next.entryAveragePrice??position.entryPrice,exitPrice:next.exitAveragePrice??position.markPrice,pnlUsd:next.netPnl??0,openedAt:next.openedAt??closedAt,closedAt,regime:next.regime??'MIXED',fillMinutes:next.durationMs?next.durationMs/60_000:0});if(this.state.tradeOutcomes.length>1000)this.state.tradeOutcomes.length=1000;}this.events.publish('TRADE_RECORD_CLOSED',next,next.symbol);if(sample)this.events.publish('EXPERIENCE_SAMPLE_CREATED',sample,next.symbol);this.events.publish('POSITION_CLOSED',{position,netPnl:next.netPnl,grossRealizedPnl:next.grossRealizedPnl,tpOrderId:next.exitOrderIds.at(-1)??null},next.symbol);
  }
  repairClosedCyclesFromAudit(audit:TradeAuditSnapshot){
    const orderById=new Map(audit.orders.map(order=>[order.orderId,order])),commissionByTrade=new Map(audit.income.filter(row=>row.incomeType==='COMMISSION'&&row.tradeId).map(row=>[row.tradeId!,row]));
    const fills=audit.fills.map(raw=>{const order=orderById.get(raw.orderId),commission=commissionByTrade.get(raw.tradeId),knownCommission=commission??(raw.commission>0?{income:raw.commission,asset:raw.commissionAsset}:null);return{...raw,fillId:`exchange_${raw.symbol}_${raw.tradeId}`,clientOrderId:raw.clientOrderId||order?.clientOrderId||'',commission:knownCommission?Math.abs(knownCommission.income):0,commissionAsset:knownCommission?.asset||raw.commissionAsset,commissionUsd:knownCommission?(stable(knownCommission.asset)?Math.abs(knownCommission.income):null):null,source:'EXCHANGE_AUDIT' as const};}).filter(fill=>fill.clientOrderId.startsWith('entry_')||fill.clientOrderId.startsWith('tp_')||fill.clientOrderId.startsWith('manual_')).sort((a,b)=>a.executionTime-b.executionTime);
    const cycles:Array<{symbol:string;side:'LONG'|'SHORT';entries:typeof fills;exits:typeof fills;qty:number}> = [];
    for(const fill of fills){const direction=fill.positionSide==='SHORT'?'SHORT':fill.positionSide==='LONG'?'LONG':fill.side=== 'BUY'?'LONG':'SHORT',entry=fill.clientOrderId.startsWith('entry_'),exit=!entry,existing=cycles.find(c=>c.symbol===fill.symbol&&c.side===direction&&c.qty>1e-9);if(entry){if(existing)existing.entries.push(fill),existing.qty+=fill.qty;else cycles.push({symbol:fill.symbol,side:direction,entries:[fill],exits:[],qty:fill.qty});}else if(existing){existing.exits.push(fill);existing.qty-=fill.qty;if(existing.qty<=1e-8)existing.qty=0;}}
    const removedSamples:string[]=[];for(const sample of [...this.state.experienceSamples.values()])if(sample.tradeId.startsWith('trade_repair_')&&this.state.tradeRecords.get(sample.tradeId)?.recordCompleteness!=='COMPLETE'){this.state.experienceSamples.delete(sample.sampleId);removedSamples.push(sample.sampleId);}const repaired=[];for(const cycle of cycles){if(!cycle.entries.length||!cycle.exits.length||cycle.qty>1e-8)continue;const first=cycle.entries[0],last=cycle.exits.at(-1)!;for(const fill of [...cycle.entries,...cycle.exits])this.record({...fill,direction:cycle.side,positionSide:fill.positionSide==='BOTH'?cycle.side:fill.positionSide},cycle.entries.includes(fill)?'ENTRY':'EXIT');const tradeId=`trade_repair_${cycle.symbol}_${cycle.side}_${first.tradeId}_${last.tradeId}`;const entryQty=cycle.entries.reduce((sum,fill)=>sum+fill.qty,0),exitQty=cycle.exits.reduce((sum,fill)=>sum+fill.qty,0),entryNotional=cycle.entries.reduce((sum,fill)=>sum+fill.qty*fill.price,0),exitNotional=cycle.exits.reduce((sum,fill)=>sum+fill.qty*fill.price,0),entryFee=cycle.entries.reduce((sum,fill)=>sum+(fill.commissionUsd??0),0),exitFee=cycle.exits.reduce((sum,fill)=>sum+(fill.commissionUsd??0),0),gross=cycle.exits.reduce((sum,fill)=>sum+fill.realizedPnl,0),net=gross-entryFee-exitFee,hasCompleteFees=[...cycle.entries,...cycle.exits].every(fill=>fill.commissionUsd!==null),closedAt=last.executionTime,openedAt=first.executionTime,record=TradeRecordSchema.parse({tradeId,symbol:cycle.symbol,direction:cycle.side,openedAt,closedAt,durationMs:Math.max(0,closedAt-openedAt),entryQty,entryAveragePrice:entryNotional/entryQty,exitAveragePrice:exitNotional/Math.max(exitQty,1),entryFee,exitFee,totalFee:entryFee+exitFee,funding:null,entryGrossNotional:entryNotional,exitGrossNotional:exitNotional,netRoiOnMargin:null,netReturnOnNotional:exitNotional?net/exitNotional*100:null,entryFillCount:cycle.entries.length,exitFillCount:cycle.exits.length,feeBreakdown:[...cycle.entries.map(fill=>({stage:'ENTRY' as const,asset:fill.commissionAsset,amount:fill.commission,usd:fill.commissionUsd,conversionSource:fill.commissionUsd===null?null:stable(fill.commissionAsset)?'STABLE_ASSET':'MARKET_QUOTE'})),...cycle.exits.map(fill=>({stage:'EXIT' as const,asset:fill.commissionAsset,amount:fill.commission,usd:fill.commissionUsd,conversionSource:fill.commissionUsd===null?null:stable(fill.commissionAsset)?'STABLE_ASSET':'MARKET_QUOTE'}))],grossRealizedPnl:gross,netPnl:net,closeReason:cycle.exits.some(fill=>fill.clientOrderId.startsWith('tp_'))?'TP':'MANUAL',status:'CLOSED',entryRunId:null,entryIntentId:cycle.entries[0].clientOrderId,entryOrderIds:cycle.entries.map(fill=>fill.orderId),exitOrderIds:cycle.exits.map(fill=>fill.orderId),source:'LOCAL_LIFECYCLE_REPAIR_FROM_EXCHANGE_FACT',regime:null,feeCompleteness:hasCompleteFees?'COMPLETE':'PARTIAL',recordCompleteness:hasCompleteFees?'COMPLETE':'PARTIAL',createdAt:openedAt,updatedAt:closedAt,firstObservedAt:openedAt});
      this.state.tradeRecords.set(tradeId,record);const sample=hasCompleteFees?ExperienceSampleSchema.parse({sampleId:`sample_${tradeId}`,tradeId,symbol:record.symbol,direction:record.direction,regime:null,netPnl:net,winLoss:net>0?'WIN':net<0?'LOSS':'FLAT',fillDelayMs:null,holdingDurationMs:record.durationMs,lesson:net>0?'交易所事实修复后净收益为正':'交易所事实修复后净收益非正，手续费已计入',mistakeTags:net<0?['NEGATIVE_NET_PNL']:[],successTags:net>0?['NET_PROFIT_COMPLETED']:[],createdAt:closedAt}):null;if(sample)this.state.experienceSamples.set(sample.sampleId,sample);this.events.publish('TRADE_RECORD_CLOSED',record,record.symbol);if(sample)this.events.publish('EXPERIENCE_SAMPLE_CREATED',sample,record.symbol);repaired.push({tradeId,symbol:record.symbol,direction:record.direction,gross,entryFee,exitFee,net,source:record.source,complete:hasCompleteFees});}
    return{cyclesDetected:cycles.length,cyclesRepaired:repaired.length,completeCycles:repaired.filter(row=>row.complete).length,partialCycles:repaired.filter(row=>!row.complete).length,removedSamples,repaired};
  }
}
