import type { RuntimeState } from '../state/runtimeState.js';
import { privateAccountFresh } from './privateAccountReadiness.js';
import { buildRiskEnvelope } from './riskReadiness.js';
import { capitalFactVersion } from './runtimeControlService.js';

const ACTIVE_ORDER = new Set(['NEW','SUBMITTING','UNKNOWN','WORKING','PARTIALLY_FILLED']);
const ACTIVE_RESERVATION = new Set(['RESERVED','WORKING']);
type Direction = 'LONG'|'SHORT';

/** Read-only feasibility snapshot immediately before Primary. It never reserves capital or authorizes an order. */
export function evaluatePreflightFeasibility(state:RuntimeState,symbol:string,marketReasons:string[]=[],now=Date.now()){
  const capital:any=state.runtimeControl.capital,route:any=capital.routedCandidates.find((row:any)=>row.symbol===symbol),market:any=state.snapshots.get(symbol),candidate:any=state.universe.find((row:any)=>row.symbol===symbol),capacity=state.entryCapacity();
  const activeReservations=[...state.entryReservations.values()].filter((row:any)=>ACTIVE_RESERVATION.has(row.status)&&Number(row.expiresAt)>now),workingOrders=[...state.entryOrders.values()].filter((row:any)=>ACTIVE_ORDER.has(row.status));
  const storedCapitalVersion=String(capital.capitalVersion??''),currentCapitalVersion=capitalFactVersion(state),legacyInjectedRoute=storedCapitalVersion==='0'&&Number(capital.evaluatedAt??0)===0;
  const capitalVersionCurrent=legacyInjectedRoute||Boolean(storedCapitalVersion&&storedCapitalVersion!=='0'&&storedCapitalVersion===currentCapitalVersion),maxCapitalAge=Math.max(15_000,Number(state.settings.runtimeControl?.capitalCheckIntervalSeconds??30)*1000+5_000),capitalFresh=legacyInjectedRoute||(Number.isFinite(capital.evaluatedAt)&&now-Number(capital.evaluatedAt)>=0&&now-Number(capital.evaluatedAt)<=maxCapitalAge),routeGenerationCurrent=!candidate||legacyInjectedRoute||Number(capital.generation??0)===Number(candidate.selectionGeneration??capital.generation??0),privateReady=privateAccountFresh(state.account,now),governance=Boolean(candidate?.eligible&&candidate?.pipelineEligible!==false&&state.runtimeControl.mode==='RUNNING'&&state.executionGovernance?.mode==='AUTO_RUNNING'&&state.settings.riskGovernance.entrySafetyMode==='AUTO');
  const quoteAsset=String(route?.quoteAsset??'UNKNOWN'),quoteAvailable=Number(state.account.assets.find((asset:any)=>asset.asset===quoteAsset)?.availableBalance??0),reservedMargin=activeReservations.filter((row:any)=>row.quoteAsset===quoteAsset).reduce((sum:number,row:any)=>sum+Math.max(0,Number(row.marginUsd??0)),0),availableMarginUsd=quoteAsset==='UNKNOWN'?0:Math.max(0,quoteAvailable-reservedMargin),leverage=Math.max(1,Number(route?.leverage??1)),minimumNotionalUsd=Math.max(Number(route?.minExecutableNotionalUsd??0),Number(market?.quote?.minNotional??0)),balanceNotionalCap=availableMarginUsd*leverage;
  const equity=Math.max(0,Number(state.account.equityUsd??0),...(state.account.assets??[]).map((row:any)=>Number(row.usdValue??0))),expectedAdverseMovePct=Math.max(.001,Number(market?.technical?.['15m']?.atrPercent??0)/100),dailyDrawdownPct=Number(state.account.riskBaseline?.riskDrawdownPct??0),maxReservations=Number(state.settings.riskGovernance.maxConcurrentReservations??Number.POSITIVE_INFINITY);
  const requested:Direction[]=[];if(route?.longExecutable)requested.push('LONG');if(route?.shortExecutable)requested.push('SHORT');
  const riskHeadroom:Record<Direction,any>={LONG:null,SHORT:null},feasibleNotionalUsd:Record<Direction,number>={LONG:0,SHORT:0},allowedDirections:Direction[]=[];
  for(const side of requested){const routeCap=Number(side==='LONG'?(route.longFeasibleNotionalUsd??route.longRecommendedNotionalUsd??0):(route.shortFeasibleNotionalUsd??route.shortRecommendedNotionalUsd??0)),recommended=Number(side==='LONG'?(route.longRecommendedNotionalUsd??routeCap):(route.shortRecommendedNotionalUsd??routeCap)),candidateNotional=Math.max(0,Math.min(routeCap,balanceNotionalCap,recommended>0?recommended:routeCap));if(candidateNotional+1e-8<minimumNotionalUsd)continue;const risk=buildRiskEnvelope({settings:state.settings,equity:Math.max(1,equity),positions:[...state.positions.values()],symbol,side,plannedNotional:candidateNotional,reservedIntents:activeReservations.length,workingOrders:workingOrders.length,dailyDrawdownPct,expectedAdverseMovePct,quoteMarginUsage:reservedMargin,now});riskHeadroom[side]={status:risk.status,finalNotional:risk.finalNotional,reasons:risk.reasons};const finalNotional=Math.max(0,Math.min(candidateNotional,Number(risk.finalNotional??0)));if(risk.status==='PASS'&&finalNotional+1e-8>=minimumNotionalUsd){allowedDirections.push(side);feasibleNotionalUsd[side]=finalNotional;}}
  let reason='PASS';if(!market)reason='MARKET_DATA_MISSING';else if(marketReasons.length)reason=`MARKET_${marketReasons[0]}`;else if(!governance)reason='GOVERNANCE_OR_PIPELINE_BLOCKED';else if(!privateReady)reason='PRIVATE_NOT_READY';else if(capacity.used>=capacity.max)reason='POSITION_CAPACITY_FULL';else if(activeReservations.length>=maxReservations)reason='RESERVATION_CAPACITY_FULL';else if(!storedCapitalVersion)reason='CAPITAL_VERSION_MISSING';else if(!capitalVersionCurrent)reason='CAPITAL_FACTS_CHANGED';else if(!capitalFresh)reason='CAPITAL_FACTS_STALE';else if(!routeGenerationCurrent)reason='CAPITAL_ROUTE_GENERATION_STALE';else if(!route)reason='NO_CAPITAL_ROUTE';else if(equity<=0)reason='NO_EQUITY';else if(quoteAsset==='UNKNOWN'||availableMarginUsd*leverage+1e-8<minimumNotionalUsd)reason='INSUFFICIENT_AVAILABLE_MARGIN';else if(!allowedDirections.length)reason=requested.length?'RISK_HEADROOM_EXHAUSTED':'NO_FEASIBLE_DIRECTION';
  return {symbol,allowedDirections,feasibleNotionalUsd,minimumExecutableNotionalUsd:minimumNotionalUsd,quoteAsset,availableMarginUsd,reservedMarginUsd:reservedMargin,capitalVersion:storedCapitalVersion,currentCapitalVersion,capitalVersionCurrent,capitalFresh,routeGenerationCurrent,capacity,activeReservations:activeReservations.length,workingOrders:workingOrders.length,privateReady,governance,riskHeadroom,marketGeneration:state.marketGeneration,createdAt:now,expiresAt:now+Math.min(15_000,maxCapitalAge),pass:reason==='PASS',reason};
}
