import { describe,expect,it } from 'vitest';
import defaults from '../../../../config/settings.default.json' with {type:'json'};
import { SystemSettingsSchema } from '@zdj/contracts';
import { RuntimeState } from '../state/runtimeState.js';
import { capitalFactVersion } from './runtimeControlService.js';
import { evaluatePreflightFeasibility } from './preflightFeasibility.js';
function fixture(){const now=Date.now(),settings=SystemSettingsSchema.parse({...defaults,appearance:{...defaults.appearance,theme:'BINANCE_NOIR'}});settings.riskGovernance.entrySafetyMode='AUTO';const state=new RuntimeState(settings),symbol='4USDT';state.executionGovernance={...state.executionGovernance,mode:'AUTO_RUNNING'};state.account={...state.account,status:'READY',asOf:now,equityUsd:10_000,assets:[{asset:'USDT',availableBalance:1_000,walletBalance:1_000,usdValue:1_000}]};state.universe=[{symbol,eligible:true,pipelineEligible:true,selectionGeneration:1} as any];state.snapshots.set(symbol,{symbol,quote:{minNotional:5},technical:{'15m':{atrPercent:.5}}} as any);state.runtimeControl.capital={...state.runtimeControl.capital,generation:1,evaluatedAt:now,routedCandidates:[{symbol,underlying:'4',quoteAsset:'USDT',marginUsd:20,leverage:10,admission:'ALLOW',reason:'TEST',longExecutable:true,shortExecutable:true,longRecommendedNotionalUsd:200,shortRecommendedNotionalUsd:200,longFeasibleNotionalUsd:200,shortFeasibleNotionalUsd:200,minExecutableNotionalUsd:5}],directionBudget:{longAvailableNotionalUsd:10_000,shortAvailableNotionalUsd:10_000,grossAvailableNotionalUsd:10_000,evaluatedAt:now}} as any;state.runtimeControl.capital.capitalVersion=capitalFactVersion(state);return{state,symbol,now};}
describe('PreflightFeasibility',()=>{
 it('passes without creating reservations or orders when current facts can execute',()=>{const {state,symbol,now}=fixture(),r=evaluatePreflightFeasibility(state,symbol,[],now);expect(r.pass).toBe(true);expect(r.allowedDirections).toEqual(['LONG','SHORT']);expect(r.capitalVersionCurrent).toBe(true);expect(state.entryReservations.size).toBe(0);expect(state.entryOrders.size).toBe(0);});
 it('fails closed when balance changes after routing',()=>{const {state,symbol,now}=fixture();state.account.assets[0].availableBalance=0;expect(evaluatePreflightFeasibility(state,symbol,[],now).reason).toBe('CAPITAL_FACTS_CHANGED');});
 it('subtracts active reservation margin before Primary',()=>{const {state,symbol,now}=fixture();state.entryReservations.set('r1',{id:'r1',underlying:'BTC',quoteAsset:'USDT',marginUsd:999.6,notionalUsd:9996,status:'RESERVED',expiresAt:now+60_000});state.runtimeControl.capital.capitalVersion=capitalFactVersion(state);const r=evaluatePreflightFeasibility(state,symbol,[],now);expect(r.pass).toBe(false);expect(r.reason).toBe('INSUFFICIENT_AVAILABLE_MARGIN');});
 it('checks deterministic risk headroom before Primary',()=>{const {state,symbol,now}=fixture();state.settings.riskGovernance.maxGrossExposurePct=.001;state.runtimeControl.capital.capitalVersion=capitalFactVersion(state);const r=evaluatePreflightFeasibility(state,symbol,[],now);expect(r.pass).toBe(false);expect(r.reason).toBe('RISK_HEADROOM_EXHAUSTED');});
 it('fails on stale private, stale route generation and market facts',()=>{const {state,symbol,now}=fixture();state.account.asOf=now-61_000;expect(evaluatePreflightFeasibility(state,symbol,[],now).reason).toBe('PRIVATE_NOT_READY');state.account.asOf=now;state.runtimeControl.capital.capitalVersion=capitalFactVersion(state);state.runtimeControl.capital.generation=2;expect(evaluatePreflightFeasibility(state,symbol,[],now).reason).toBe('CAPITAL_ROUTE_GENERATION_STALE');state.runtimeControl.capital.generation=1;expect(evaluatePreflightFeasibility(state,symbol,['QUOTE_STALE'],now).reason).toBe('MARKET_QUOTE_STALE');});
});
