import {describe,expect,it} from 'vitest';
import {ProductionAssetResearchService} from './productionAssetResearch.js';

const days=(now:number)=>Array.from({length:30},(_,i)=>{const open=Math.floor(now/86_400_000)*86_400_000-(30-i)*86_400_000;return[open,0,0,0,0,0,open+86_400_000-1,80_000_000];});

describe('production public research domain',()=>{
  it('is read-only, explicitly sourced, and independent from execution snapshots',async()=>{const calls:string[]=[];const service=ProductionAssetResearchService.forTest({environment:()=> 'PRODUCTION',executionMode:()=> 'READ_ONLY',json:async(path:string)=>{calls.push(path);return path.includes('ticker')?[{symbol:'BTCUSDT',quoteVolume:'10',count:2}]:{symbols:[{symbol:'BTCUSDT',status:'TRADING'}]};}} as never);const facts=await service.refresh();expect(calls).toEqual(['/fapi/v1/ticker/24hr','/fapi/v1/exchangeInfo']);expect(facts[0]).toMatchObject({symbol:'BTCUSDT',sourceDomain:'PRODUCTION_PUBLIC_RESEARCH',listed:true});expect(facts[0]).not.toHaveProperty('quote');});
  it('fails closed if the transport is not production read-only',async()=>{const service=ProductionAssetResearchService.forTest({environment:()=> 'TESTNET',executionMode:()=> 'TESTNET_ENABLED',json:async()=>[]} as never);await expect(service.refresh()).rejects.toThrow('PRODUCTION_RESEARCH_DOMAIN_REQUIRED');});
  it('builds a versioned approval directory only from closed continuous 30d production facts',async()=>{const now=Date.now(),service=ProductionAssetResearchService.forTest({environment:()=> 'PRODUCTION',executionMode:()=> 'READ_ONLY',json:async(path:string)=>path.includes('ticker')?[{symbol:'SOLUSDT',quoteVolume:'100000000',count:100000,lastPrice:'100'}]:path.includes('exchangeInfo')?{symbols:[{symbol:'SOLUSDT',status:'TRADING',contractType:'PERPETUAL',quoteAsset:'USDT',onboardDate:now-400*86400000}]}:path.includes('klines')?days(now):path.includes('openInterest')?{openInterest:'50000'}:[]} as never);const review=await service.review();expect(review.approvedLiquid).toEqual(['SOL']);expect(review.methodVersion).toBe('V3.9.1-LIQUIDITY-30D-V4');expect(review.evidence[0].qualification).toMatchObject({passed:true,rejectionReasons:[]});expect(review.evidenceHash).toHaveLength(64);});
  it('isolates one symbol failure and reviews a broad universe without padding',async()=>{const now=Date.now(),symbols=Array.from({length:60},(_,i)=>({symbol:`Q${i}USDT`,status:'TRADING',contractType:'PERPETUAL',quoteAsset:'USDT',onboardDate:now-400*86400000})),tickers=symbols.map((row,i)=>({symbol:row.symbol,quoteVolume:String(100_000_000-i*1000),count:100_000-i,lastPrice:'10'})),service=ProductionAssetResearchService.forTest({environment:()=> 'PRODUCTION',executionMode:()=> 'READ_ONLY',json:async(path:string)=>path.includes('ticker')?tickers:path.includes('exchangeInfo')?{symbols}:path.includes('Q0USDT')&&path.includes('klines')?Promise.reject(new Error('single symbol failure')):path.includes('klines')?days(now):path.includes('openInterest')?{openInterest:'20000000'}:[]} as never);const review=await service.review();expect(review.evidence).toHaveLength(60);expect(review.evidence.find(x=>x.symbol==='Q0USDT')).toMatchObject({evidenceStatus:'SOURCE_FAILED'});expect(review.approvedLiquid.length).toBeGreaterThanOrEqual(40);expect(new Set(review.approvedLiquid).size).toBe(review.approvedLiquid.length);});
});
