import type { ConnectionSettings } from '@zdj/contracts';
import { BinanceTransport } from '../adapters/binance/BinanceTransport.js';
import { createHash } from 'node:crypto';

export type ProductionAssetResearchFact={symbol:string;quoteVolumeUsd24h:number;tradeCount24h:number;listed:boolean;sourceDomain:'PRODUCTION_PUBLIC_RESEARCH';fetchedAt:number};
export type AssetDirectoryReview={version:string;reviewedAt:number;nextReviewAt:number;sourceDomain:'PRODUCTION_PUBLIC_RESEARCH';methodVersion:string;evidenceHash:string;approvedLiquid:string[];approvals:Record<string,{symbol:string;reason:string;reviewedAt:number;quoteVolumeUsd24h:number;medianDailyQuoteVolumeUsd30d:number;tradeCount24h:number;openInterestUsd:number;listingAgeDays:number;liquidityComposite:number}>;thresholds:Record<string,number>;evidence:any[]};
export function mergeAssetDirectoryReview(current:any,review:AssetDirectoryReview,now=review.reviewedAt){const excluded=new Set((current.excluded??[]).map((value:any)=>underlying(String(value)))),approvals:any=Object.fromEntries(Object.entries(review.approvals).filter(([asset])=>!excluded.has(asset))),failed=new Set(review.evidence.filter((row:any)=>row.evidenceStatus==='SOURCE_FAILED').map((row:any)=>underlying(String(row.symbol))));for(const asset of failed){if(excluded.has(asset))continue;const prior=current.approvals?.[asset];if(!prior)continue;const validUntil=Number(prior.validUntil??current.nextReviewAt??0),graceUntil=Number(prior.graceUntil??validUntil+86_400_000);if(now<=graceUntil)approvals[asset]={...prior,validUntil,graceUntil,lkgSourceFailed:true};}const lkgAssets=Object.entries(approvals).filter(([,approval]:any)=>approval.lkgSourceFailed).map(([asset])=>asset);return{version:review.version,approvedLiquid:Object.keys(approvals),excluded:current.excluded??[],reviewedAt:review.reviewedAt,nextReviewAt:review.nextReviewAt,sourceDomain:review.sourceDomain,methodVersion:review.methodVersion,evidenceHash:review.evidenceHash,approvals,lkgAssets};}
const pct=(rows:number[],p:number)=>{const a=rows.filter(Number.isFinite).sort((x,y)=>x-y);return a.length?a[Math.min(a.length-1,Math.floor((a.length-1)*p))]!:0;};
const median=(rows:number[])=>pct(rows,.5),rank=(value:number,rows:number[])=>rows.length?rows.filter(x=>x<=value).length/rows.length:0,underlying=(symbol:string)=>symbol.replace(/(USDT|USDC|BUSD)$/,'');
const absoluteFloors={quoteVolumeUsd24h:20_000_000,tradeCount24h:20_000,medianDailyQuoteVolumeUsd30d:20_000_000,openInterestUsd:5_000_000,liquidityComposite:.2,listingAgeDays:180,historyDays:25};

/** Credential-free production-public governance; its facts never enter Testnet execution snapshots. */
export class ProductionAssetResearchService{
  readonly sourceDomain='PRODUCTION_PUBLIC_RESEARCH' as const;
  private constructor(private transport:Pick<BinanceTransport,'json'|'environment'|'executionMode'>,private retainedApproved:string[]=[]){ }
  static fromSettings(settings:ConnectionSettings,retainedApproved:string[]=[]){const isolated=structuredClone(settings);isolated.exchange.environment='PRODUCTION';isolated.executionMode='READ_ONLY';return new ProductionAssetResearchService(new BinanceTransport(isolated),retainedApproved);}
  static forTest(transport:Pick<BinanceTransport,'json'|'environment'|'executionMode'>,retainedApproved:string[]=[]){return new ProductionAssetResearchService(transport,retainedApproved);}
  async refresh():Promise<ProductionAssetResearchFact[]>{
    this.assertDomain();const [tickers,exchangeInfo]=await Promise.all([this.transport.json<any[]>('/fapi/v1/ticker/24hr',{timeoutMs:15_000}),this.transport.json<any>('/fapi/v1/exchangeInfo',{timeoutMs:15_000})]);
    const listed=new Set((exchangeInfo.symbols??[]).filter((row:any)=>row.status==='TRADING').map((row:any)=>String(row.symbol))),fetchedAt=Date.now();
    return tickers.map(row=>({symbol:String(row.symbol),quoteVolumeUsd24h:Math.max(0,Number(row.quoteVolume)||0),tradeCount24h:Math.max(0,Math.trunc(Number(row.count)||0)),listed:listed.has(String(row.symbol)),sourceDomain:this.sourceDomain,fetchedAt}));
  }
  async review():Promise<AssetDirectoryReview>{
    this.assertDomain();const [tickers,info]=await Promise.all([this.transport.json<any[]>('/fapi/v1/ticker/24hr',{timeoutMs:15_000}),this.transport.json<any>('/fapi/v1/exchangeInfo',{timeoutMs:15_000})]),tickerBy=new Map(tickers.map((x:any)=>[String(x.symbol),x])),now=Date.now();
    const eligible=(info.symbols??[]).filter((x:any)=>x.status==='TRADING'&&x.contractType==='PERPETUAL'&&x.quoteAsset==='USDT'&&Number(x.onboardDate)>0),contractByUnderlying=new Map(eligible.map((x:any)=>[underlying(String(x.symbol)),x])),top=eligible.map((x:any)=>({row:x,volume:Number(tickerBy.get(String(x.symbol))?.quoteVolume??0)})).sort((a:any,b:any)=>b.volume-a.volume).slice(0,120).map((x:any)=>x.row),retained=this.retainedApproved.map(value=>contractByUnderlying.get(underlying(String(value).toUpperCase()))).filter(Boolean),contracts=[...new Map([...top,...retained].map((x:any)=>[String(x.symbol),x])).values()];
    const evidence:any[]=[];
    for(let i=0;i<contracts.length;i+=8){const settled=await Promise.allSettled(contracts.slice(i,i+8).map(async(c:any)=>{const symbol=String(c.symbol),[klines,oi]=await Promise.all([this.transport.json<any[]>(`/fapi/v1/klines?symbol=${encodeURIComponent(symbol)}&interval=1d&limit=30`,{timeoutMs:15_000}),this.transport.json<any>(`/fapi/v1/openInterest?symbol=${encodeURIComponent(symbol)}`,{timeoutMs:15_000})]),closed=[...new Map(klines.filter(k=>Number(k[6])<=now).map(k=>[Number(k[0]),k])).values()].sort((a:any,b:any)=>Number(a[0])-Number(b[0])),daily=closed.map((k:any)=>Number(k[7]??0)).filter(x=>x>0),continuous=closed.every((k:any,index:number)=>index===0||Number(k[0])-Number(closed[index-1]![0])===86_400_000),ticker:any=tickerBy.get(symbol),mark=Number(ticker?.lastPrice??0);return{symbol,onboardDate:Number(c.onboardDate),contractStatus:c.status,quoteVolumeUsd24h:Number(ticker?.quoteVolume??0),tradeCount24h:Number(ticker?.count??0),medianDailyQuoteVolumeUsd30d:median(daily),historyDays:daily.length,historyContinuous:continuous,openInterestUsd:Math.max(0,Number(oi.openInterest??0)*mark),listingAgeDays:Math.max(0,(now-Number(c.onboardDate))/86_400_000),evidenceStatus:'COMPLETE'};}));settled.forEach((result,index)=>{if(result.status==='fulfilled')evidence.push(result.value);else evidence.push({symbol:String(contracts[i+index]?.symbol??'UNKNOWN'),evidenceStatus:'SOURCE_FAILED',error:result.reason instanceof Error?result.reason.message:String(result.reason),qualification:{sourceDomain:this.sourceDomain,checks:{},passed:false,rejectionReasons:['SOURCE_FAILED']}});});}
    const complete=evidence.filter(x=>x.evidenceStatus==='COMPLETE'),volumes=complete.map(x=>x.quoteVolumeUsd24h),trades=complete.map(x=>x.tradeCount24h),medians=complete.map(x=>x.medianDailyQuoteVolumeUsd30d),ois=complete.map(x=>x.openInterestUsd),thresholds={quoteVolumeUsd24h:Math.max(absoluteFloors.quoteVolumeUsd24h,pct(volumes,.1)),tradeCount24h:Math.max(absoluteFloors.tradeCount24h,pct(trades,.1)),medianDailyQuoteVolumeUsd30d:Math.max(absoluteFloors.medianDailyQuoteVolumeUsd30d,pct(medians,.1)),openInterestUsd:Math.max(absoluteFloors.openInterestUsd,pct(ois,.05)),liquidityComposite:absoluteFloors.liquidityComposite,listingAgeDays:absoluteFloors.listingAgeDays,historyDays:absoluteFloors.historyDays};
    for(const x of complete)x.liquidityComposite=(rank(x.quoteVolumeUsd24h,volumes)+rank(x.tradeCount24h,trades)+rank(x.medianDailyQuoteVolumeUsd30d,medians)+rank(x.openInterestUsd,ois))/4;
    for(const x of complete){const checks={quoteVolumeUsd24h:x.quoteVolumeUsd24h>=thresholds.quoteVolumeUsd24h,tradeCount24h:x.tradeCount24h>=thresholds.tradeCount24h,medianDailyQuoteVolumeUsd30d:x.medianDailyQuoteVolumeUsd30d>=thresholds.medianDailyQuoteVolumeUsd30d,openInterestUsd:x.openInterestUsd>=thresholds.openInterestUsd,liquidityComposite:x.liquidityComposite>=thresholds.liquidityComposite,listingAgeDays:x.listingAgeDays>=thresholds.listingAgeDays,historyDays:x.historyDays>=thresholds.historyDays,historyContinuous:x.historyContinuous};x.qualification={sourceDomain:this.sourceDomain,checks,passed:Object.values(checks).every(Boolean),rejectionReasons:Object.entries(checks).filter(([,ok])=>!ok).map(([key])=>`BELOW_${key.toUpperCase()}`)};}
    const approved=complete.filter(x=>x.qualification.passed).sort((a,b)=>b.liquidityComposite-a.liquidityComposite),approvals=Object.fromEntries(approved.map(x=>[underlying(x.symbol),{symbol:x.symbol,reason:'PRODUCTION_PUBLIC_V4_ABSOLUTE_FLOORS_PLUS_RELATIVE_CALIBRATION',reviewedAt:now,validUntil:now+7*86_400_000,quoteVolumeUsd24h:x.quoteVolumeUsd24h,medianDailyQuoteVolumeUsd30d:x.medianDailyQuoteVolumeUsd30d,tradeCount24h:Math.trunc(x.tradeCount24h),openInterestUsd:x.openInterestUsd,listingAgeDays:x.listingAgeDays,liquidityComposite:x.liquidityComposite}])),evidenceHash=createHash('sha256').update(JSON.stringify({thresholds,evidence})).digest('hex'),version=`V3.9.1-${new Date(now).toISOString().slice(0,10)}-${evidenceHash.slice(0,8)}`;
    return{version,reviewedAt:now,nextReviewAt:now+7*86_400_000,sourceDomain:this.sourceDomain,methodVersion:'V3.9.1-LIQUIDITY-30D-V4',evidenceHash,approvedLiquid:Object.keys(approvals),approvals,thresholds,evidence};
  }
  private assertDomain(){if(this.transport.environment()!=='PRODUCTION'||this.transport.executionMode()!=='READ_ONLY')throw new Error('PRODUCTION_RESEARCH_DOMAIN_REQUIRED');}
}
