import {RuntimeWriteBuffer} from './runtimeWriteBuffer.js';
import {expect,it,vi} from 'vitest';
import {readFileSync} from 'node:fs';import {SystemSettingsSchema} from '@zdj/contracts';
import {RuntimeState} from '../state/runtimeState.js';import {EventBus} from '../events/eventBus.js';
import {ReconciliationService} from './reconciliationService.js';import {ReconciliationChanges} from './reconciliationChanges.js';import {persistReconciliationJournals,latestEntryRecord} from './reconciliationJournalPersistence.js';
const settings=SystemSettingsSchema.parse(JSON.parse(readFileSync(new URL('../../../../config/settings.default.json',import.meta.url),'utf8')));
function harness(){const state=new RuntimeState(settings),bus=new EventBus(),entry=vi.fn(),manual=vi.fn();bus.on('RECONCILIATION_COMPLETED',event=>persistReconciliationJournals(event,state,entry,manual));return{state,bus,entry,manual};}
function addEntry(state:RuntimeState,id:string,status='NEW'){const row:any={id,intentId:'i'+id,symbol:'BTCUSDT',side:'LONG',status,clientOrderId:'c'+id,quantity:1,price:100,filledQuantity:0,createdAt:Date.now(),updatedAt:1,absoluteExpiresAt:Date.now()+60_000,repriceCount:0};state.entryOrders.set(id,row);state.entryIntents.set(row.intentId,{id:row.intentId} as any);return row;}
function addManual(state:RuntimeState,id:string){const row:any={id,intentId:'i'+id,symbol:'BTCUSDT',side:'SELL',positionSide:'LONG',reduceOnly:true,status:'FILLED',exchangeOrderId:'x'+id,quantity:1,filledQuantity:1,clientOrderId:'c'+id,createdAt:Date.now(),updatedAt:1};state.manualOrders.set(id,row);state.manualIntents.set(row.intentId,{id:row.intentId,action:'REDUCE',status:'COMPLETED',exchangeOrderId:row.exchangeOrderId,updatedAt:1} as any);return row;}
function service(h:ReturnType<typeof harness>,adapter:any={}){return new ReconciliationService({fetchPositions:vi.fn(async()=>[]),fetchOpenOrders:vi.fn(async()=>[]),...adapter},h.state,h.bus,{ensure:vi.fn()} as any);}
it('unchanged reconciliation with 1000 historical identities produces zero execution journal calls',async()=>{const h=harness();for(let i=0;i<1000;i++){addEntry(h.state,'e'+i);addManual(h.state,'m'+i);}await service(h).run();expect(h.entry).not.toHaveBeenCalled();expect(h.manual).not.toHaveBeenCalled();expect(h.state.manualIntents.get('im0')?.updatedAt).toBe(1);});
it('one exact changed entry persists only that identity, including UNKNOWN occupancy',async()=>{const h=harness();addEntry(h.state,'unchanged');const row=addEntry(h.state,'changed','WORKING');await service(h,{findEntryByClientOrderId:vi.fn(async()=>null)}).run();expect(h.entry).toHaveBeenCalledOnce();expect(h.entry.mock.calls[0][0].order).toMatchObject({id:row.id,status:'UNKNOWN',activeRiskExposure:true});expect(h.manual).not.toHaveBeenCalled();});
it('one changed manual persists only that identity and derived terminal intent',async()=>{const h=harness();addManual(h.state,'unchanged');const row=addManual(h.state,'changed');h.state.manualOrders.set(row.id,{...row,status:'WORKING',filledQuantity:0});await service(h,{findManualByClientOrderId:vi.fn(async()=>({...row,status:'CANCELED'}))}).run();expect(h.manual).toHaveBeenCalledOnce();expect(h.manual.mock.calls[0][0]).toMatchObject({order:{id:row.id,status:'CANCELED'},intent:{status:'CANCELED'}});expect(h.entry).not.toHaveBeenCalled();});
it('reservation-only changes, terminal and nested proof changes remain exact and synchronous',()=>{const h=harness(),e=addEntry(h.state,'e','CANCELED');h.state.entryOrders.set(e.id,{...e,reservationId:'r'});h.state.entryReservations.set('r',{id:'r',underlying:'BTC',status:'WORKING'} as any);const c=new ReconciliationChanges(h.state);c.reservation('r',()=>h.state.entryReservations.set('r',{id:'r',underlying:'BTC',status:'RELEASED'} as any));c.setEntry(e.id,{...h.state.entryOrders.get(e.id),activeRiskEvidence:{status:'VERIFIED_NO_ACTIVE_RISK',validUntil:100}});h.bus.publish('RECONCILIATION_COMPLETED',{executionChanges:c.payload()});expect(h.entry).toHaveBeenCalledOnce();expect(h.entry.mock.calls[0][0].reservation.status).toBe('RELEASED');expect(h.entry.mock.calls[0][0].order.activeRiskEvidence.validUntil).toBe(100);});
it('net no-op mutations are not written; missing change-set does not silently sweep history',()=>{const h=harness(),row=addEntry(h.state,'e'),c=new ReconciliationChanges(h.state);c.setEntry('e',{...row,price:200});c.setEntry('e',row);expect(c.payload().entryOrderIds).toEqual([]);expect(()=>h.bus.publish('RECONCILIATION_COMPLETED',{})).toThrow('CHANGE_SET_MISSING');});
it('timed listeners retain registration order, synchronous exceptions and removable identity',()=>{const bus=new EventBus(),seen:string[]=[];const measured=bus.onMeasured('test',()=>seen.push('generic'));bus.once('X',()=>seen.push('typed'));bus.publish('X');expect(seen).toEqual(['generic','typed']);bus.off('event',measured);bus.publish('X');expect(seen).toHaveLength(2);bus.onMeasured('throws',()=>{throw Error('durability');});expect(()=>bus.publish('X')).toThrow('durability');});

it('failed reconciliation journal retries persist newest identity instead of an older captured state',()=>{const h=harness(),original=addEntry(h.state,'e','UNKNOWN'),writes=new RuntimeWriteBuffer(),save=vi.fn().mockImplementationOnce(()=>{throw Error('busy');});const c=new ReconciliationChanges(h.state);c.setEntry('e',{...original,price:101});persistReconciliationJournals({id:'x',type:'RECONCILIATION_COMPLETED',ts:Date.now(),payload:{executionChanges:c.payload()}},h.state,value=>writes.apply('entry:'+value.order.id,()=>save(latestEntryRecord(h.state,value.order.id))),()=>{});expect(writes.health().pendingWrites).toBe(1);h.state.entryOrders.set('e',{...original,price:102,status:'FILLED'});writes.flush();expect(save.mock.calls.at(-1)?.[0].order).toMatchObject({price:102,status:'FILLED'});expect(writes.health().pendingWrites).toBe(0);});
