import {describe,it,expect,vi} from 'vitest';
import {SystemSettingsSchema} from '@zdj/contracts';
import defaults from '../../../../config/settings.default.json' with {type:'json'};
import {RuntimeState} from '../state/runtimeState.js';
import {EventBus} from '../events/eventBus.js';
import {ReconciliationService} from './reconciliationService.js';

const settings=()=>SystemSettingsSchema.parse({...defaults,appearance:{...defaults.appearance,theme:'BINANCE_NOIR'}});
const localOrder=(now:number)=>({id:'entry_fet',clientOrderId:'ml_fet',exchangeOrderId:'123',symbol:'FETUSDT',side:'LONG',quantity:10,price:1,filledQuantity:0,leverage:10,status:'UNKNOWN',createdAt:now-1000,updatedAt:now-500,absoluteExpiresAt:now+60_000,repriceCount:0,intentId:'intent_fet',reservationId:'r_fet',reachability:1} as any);
const position=(now:number,cycleId='cycle_fet')=>({id:'exchange_FETUSDT_LONG',cycleId,symbol:'FETUSDT',side:'LONG',quantity:10,entryPrice:1,markPrice:1,leverage:10,unrealizedPnl:0,unrealizedPnlPercent:0,openedAt:now,firstObservedAt:now,entryTimeSource:'SYSTEM_FILL',managementStatus:'AUTO_MANAGED',humanManagedAt:null,tpStatus:'PENDING',tpOrderId:null,tpLastVerifiedAt:null,tpCoverageSource:'NONE'} as any);

function fixture(now:number){const state=new RuntimeState(settings()),events:any[]=[];state.entryOrders.set('entry_fet',localOrder(now));state.entryReservations.set('r_fet',{id:'r_fet',underlying:'FET',quoteAsset:'USDT',marginUsd:1,notionalUsd:10,planId:'p',intentId:'intent_fet',createdAt:now-1000,expiresAt:now+60_000,status:'WORKING'} as any);const bus=new EventBus();bus.on('event',event=>events.push(event));const adapter:any={fetchOpenOrders:vi.fn(async()=>[]),fetchPositions:vi.fn(async()=>[]),findEntryByClientOrderId:vi.fn(async()=>null),fetchSymbolTradeFacts:vi.fn(async()=>({fills:[],income:[],orders:[]}))};const service=new ReconciliationService(adapter,state,bus,{ensure:vi.fn()} as any);return{state,events,adapter,service};}

describe('UNKNOWN active-risk audit semantics',()=>{
  it('preserves exchange terminal UNKNOWN but releases active-risk capacity only with multi-source proof',async()=>{const now=Date.now(),x=fixture(now);await x.service.run();const order:any=x.state.entryOrders.get('entry_fet'),health=x.service.health();expect(order).toMatchObject({status:'UNKNOWN',exchangeTerminalStatus:'UNKNOWN',activeRiskExposure:false,activeRiskEvidence:{status:'VERIFIED_NO_ACTIVE_RISK',identityTombstone:'ENTRY:FETUSDT:ml_fet'}});expect(order.activeRiskEvidence.sources).toEqual(expect.arrayContaining(['BINANCE_EXACT_ORDER_NOT_FOUND','BINANCE_OPEN_ORDERS_IDENTITY_ABSENT','BINANCE_USER_TRADES_IDENTITY_ABSENT','BINANCE_ALL_ORDERS_IDENTITY_ABSENT','BINANCE_LONG_SHORT_POSITION_ZERO']));expect(x.state.entryReservations.get('r_fet')?.status).toBe('RELEASED');expect(x.state.entryCapacity().inFlight).toBe(0);expect(health).toMatchObject({historicalUnknownCount:1,activeRiskUnresolvedCount:0,verifiedNoActiveRiskUnknownCount:1,unresolvedDriftCount:0});expect(x.adapter.fetchSymbolTradeFacts).toHaveBeenCalledOnce();});
  it('keeps fail-closed when a current position is durably attributed to the UNKNOWN Entry',async()=>{const now=Date.now(),x=fixture(now),linked=position(now+1000,'cycle_unknown');x.state.entryOrders.set('entry_fet',{...localOrder(now),cycleId:'cycle_unknown'} as any);x.state.positions.set(linked.id,linked);x.adapter.fetchPositions.mockResolvedValue([linked]);await x.service.run();const order:any=x.state.entryOrders.get('entry_fet'),health=x.service.health();expect(order.status).toBe('UNKNOWN');expect(order.exchangeTerminalStatus).toBe('UNKNOWN');expect(order.activeRiskExposure).toBe(true);expect(order.activeRiskEvidence).toMatchObject({status:'CONFLICT',reason:'LATE_EXCHANGE_RISK_FACT_APPEARED'});expect(order.activeRiskEvidence.sources).toContain('POSITION_ATTRIBUTED_TO_ENTRY');expect(health.activeRiskUnresolvedCount).toBe(1);expect(x.events.some(event=>event.type==='ENTRY_ORDER_NO_ACTIVE_RISK_CONFLICT')).toBe(true);});
  it('does not let an unrelated proven same-symbol position create a false POSITION_PRESENT conflict',async()=>{const now=Date.now(),x=fixture(now),other=position(now+1000,'cycle_other'),owner={...localOrder(now),id:'entry_other',clientOrderId:'ml_other',exchangeOrderId:'999',cycleId:'cycle_other',intentId:'intent_other',reservationId:null,status:'FILLED',filledQuantity:10} as any;x.state.positions.set(other.id,other);x.state.entryOrders.set(owner.id,owner);x.adapter.fetchPositions.mockResolvedValue([other]);await x.service.run();const order:any=x.state.entryOrders.get('entry_fet'),health=x.service.health();expect(order).toMatchObject({status:'UNKNOWN',exchangeTerminalStatus:'UNKNOWN',activeRiskExposure:false,activeRiskEvidence:{status:'VERIFIED_NO_ACTIVE_RISK'}});expect(order.activeRiskEvidence.sources).toContain('POSITION_PRESENT_PROVEN_OTHER_CYCLE');expect(x.state.entryReservations.get('r_fet')?.status).toBe('RELEASED');expect(health.activeRiskUnresolvedCount).toBe(0);});
  it('retains reservation when a same-symbol position exists but durable ownership is ambiguous',async()=>{const now=Date.now(),x=fixture(now),ambiguous=position(now+1000,'cycle_unproven');x.state.positions.set(ambiguous.id,ambiguous);x.adapter.fetchPositions.mockResolvedValue([ambiguous]);await x.service.run();const order:any=x.state.entryOrders.get('entry_fet');expect(order).toMatchObject({status:'UNKNOWN',exchangeTerminalStatus:'UNKNOWN',activeRiskExposure:true});expect(x.state.entryReservations.get('r_fet')?.status).toBe('WORKING');expect(x.service.health().activeRiskUnresolvedCount).toBe(1);expect(x.events.some(event=>event.type==='ENTRY_ORDER_POSITION_ATTRIBUTION_UNRESOLVED')).toBe(true);});
  it('re-enters fail-closed when a late order or fill fact conflicts with the tombstone on the next bounded risk scan',async()=>{const now=Date.now(),x=fixture(now);await x.service.run();x.adapter.fetchSymbolTradeFacts.mockResolvedValue({fills:[{clientOrderId:'ml_fet',orderId:'123'}],income:[],orders:[]});(x.service as any).lastUnknownRiskScanAt-=60_001;await x.service.run();const order:any=x.state.entryOrders.get('entry_fet');expect(order.status).toBe('UNKNOWN');expect(order.activeRiskExposure).toBe(true);expect(order.activeRiskEvidence).toMatchObject({status:'CONFLICT',reason:'LATE_EXCHANGE_RISK_FACT_APPEARED'});expect(order.activeRiskEvidence.sources).toContain('USER_TRADES_IDENTITY_PRESENT');expect(x.events.some(event=>event.type==='ENTRY_ORDER_NO_ACTIVE_RISK_CONFLICT')).toBe(true);});
  it('does not release capacity when evidence acquisition fails',async()=>{const now=Date.now(),x=fixture(now);x.adapter.fetchSymbolTradeFacts.mockRejectedValue(new Error('timeout'));await x.service.run();const order:any=x.state.entryOrders.get('entry_fet');expect(order).toMatchObject({status:'UNKNOWN',exchangeTerminalStatus:'UNKNOWN',activeRiskExposure:true});expect(x.state.entryCapacity().used).toBeGreaterThan(0);expect(x.service.health()).toMatchObject({historicalUnknownCount:1,activeRiskUnresolvedCount:1,verifiedNoActiveRiskUnknownCount:0});});
  it('recovers a legacy CANCELED+UNKNOWN record fail-closed when exact/proof queries fail',async()=>{const now=Date.now(),x=fixture(now),legacy:any={...localOrder(now),status:'CANCELED',exchangeTerminalStatus:'UNKNOWN',activeRiskExposure:true};x.state.entryOrders.set(legacy.id,legacy);x.state.entryReservations.set('r_fet',{...x.state.entryReservations.get('r_fet'),status:'RELEASED'} as any);x.adapter.fetchSymbolTradeFacts.mockRejectedValue(new Error('timeout'));await x.service.run();const order:any=x.state.entryOrders.get('entry_fet'),health=x.service.health();expect(x.adapter.findEntryByClientOrderId).toHaveBeenCalled();expect(order).toMatchObject({status:'UNKNOWN',exchangeTerminalStatus:'UNKNOWN',activeRiskExposure:true});expect(x.state.entryReservations.get('r_fet')?.status).toBe('WORKING');expect(x.state.entryCapacity()).toMatchObject({inFlight:1,used:1});expect(health).toMatchObject({historicalUnknownCount:1,activeRiskUnresolvedCount:1,verifiedNoActiveRiskUnknownCount:0});});
  it('clears risk on a legacy CANCELED+UNKNOWN record only after strict no-risk proof',async()=>{const now=Date.now(),x=fixture(now),legacy:any={...localOrder(now),status:'CANCELED',exchangeTerminalStatus:'UNKNOWN',activeRiskExposure:true};x.state.entryOrders.set(legacy.id,legacy);x.state.entryReservations.set('r_fet',{...x.state.entryReservations.get('r_fet'),status:'RELEASED'} as any);await x.service.run();const order:any=x.state.entryOrders.get('entry_fet'),health=x.service.health();expect(order).toMatchObject({status:'UNKNOWN',exchangeTerminalStatus:'UNKNOWN',activeRiskExposure:false,activeRiskEvidence:{status:'VERIFIED_NO_ACTIVE_RISK',identityTombstone:'ENTRY:FETUSDT:ml_fet'}});expect(x.state.entryReservations.get('r_fet')?.status).toBe('RELEASED');expect(x.state.entryCapacity()).toMatchObject({inFlight:0,used:0});expect(health).toMatchObject({historicalUnknownCount:1,activeRiskUnresolvedCount:0,verifiedNoActiveRiskUnknownCount:1});});
  it('records a confirmed exact CANCELED terminal and excludes it from UNKNOWN counts',async()=>{const now=Date.now(),x=fixture(now),legacy:any={...localOrder(now),status:'CANCELED',exchangeTerminalStatus:'UNKNOWN',activeRiskExposure:true};x.state.entryOrders.set(legacy.id,legacy);x.state.entryReservations.set('r_fet',{...x.state.entryReservations.get('r_fet'),status:'RELEASED'} as any);x.adapter.findEntryByClientOrderId.mockResolvedValue({...localOrder(now),status:'CANCELED'} as any);await x.service.run();const order:any=x.state.entryOrders.get('entry_fet'),health=x.service.health();expect(order).toMatchObject({status:'CANCELED',exchangeTerminalStatus:'CANCELED',activeRiskExposure:false,activeRiskEvidence:null});expect(x.state.entryReservations.get('r_fet')?.status).toBe('RELEASED');expect(x.state.entryCapacity()).toMatchObject({inFlight:0,used:0});expect(health).toMatchObject({historicalUnknownCount:0,activeRiskUnresolvedCount:0,verifiedNoActiveRiskUnknownCount:0});});
  it('keeps normal PARTIALLY_FILLED activity risk-bearing without counting it as historical UNKNOWN',async()=>{const now=Date.now(),x=fixture(now),partial:any={...localOrder(now),status:'PARTIALLY_FILLED',exchangeTerminalStatus:'UNKNOWN',activeRiskExposure:true,filledQuantity:4};x.state.entryOrders.set(partial.id,partial);x.adapter.fetchOpenOrders.mockResolvedValue([partial]);await x.service.run();const order:any=x.state.entryOrders.get('entry_fet');expect(order).toMatchObject({status:'PARTIALLY_FILLED',exchangeTerminalStatus:'UNKNOWN',activeRiskExposure:true});expect(x.state.entryCapacity()).toMatchObject({inFlight:1});expect(x.service.health()).toMatchObject({historicalUnknownCount:0,activeRiskUnresolvedCount:0,verifiedNoActiveRiskUnknownCount:0});});
});