import { describe,expect,it } from 'vitest';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { SystemSettingsSchema } from '@zdj/contracts';
import { RuntimeState } from '../state/runtimeState.js';
import { EventBus } from '../events/eventBus.js';
import { capitalFactVersion, RuntimeControlService } from './runtimeControlService.js';
import { evaluatePreflightFeasibility } from './preflightFeasibility.js';

const card=(last:number)=>({timeframe:'15m',asOf:Date.now(),sampleSize:80,lastPrice:last,trend:'RANGE',trendStrength:.4,ema8:last,ema21:last,ema55:last,emaSlope21:0,macdLine:0,macdSignal:0,macdHistogram:0,macdHistogramSlope:0,macdCrossDirection:'NONE',macdCrossAgeBars:0,bbUpper:last*1.02,bbMiddle:last,bbLower:last*.98,bbPosition:.5,bbBandwidth:.04,atr14:last*.005,atrPercent:.5,volumeZScore:0,recentSwingHigh:last*1.01,recentSwingLow:last*.99,higherHighs:2,higherLows:2,lowerHighs:1,lowerLows:1,freshnessMs:0});
const snap=(symbol:string)=>{const last=100;return{symbol,quote:{symbol,last,mark:last,bid:last-.01,ask:last+.01,tickSize:.01,stepSize:.01,minQty:.01,minNotional:5,quoteVolumeUsd24h:100_000_000,priceChangePercent24h:0,tradeCount24h:10000,ts:Date.now()},orderBook:{symbol,bids:[[99.99,100000]],asks:[[100.01,100000]],ts:Date.now()},derivatives:{symbol,openInterest:1_000_000,openInterestChange5m:0,openInterestChange15m:0,fundingRate:0,takerBuySellRatio5m:1,globalLongShortRatio:1,topTraderPositionRatio:1,ts:Date.now()},technical:{'1m':card(last),'5m':card(last),'15m':card(last),'4h':card(last),'1d':card(last),'1w':card(last)},dataCompleteness:1} as any;};
const candidate=(symbol='ETHUSDT')=>({symbol,rank:1,score:90,lifecycle:'SHORTLIST',eligible:true,exclusionReasons:[],components:{liquidity:90,tradingActivity:90,capitalActivity:80,technicalOpportunity:80,executionReachability:90,dataQuality:100},quoteVolumeUsd24h:100_000_000,spreadBps:2,lastPrice:100,change24hPercent:0,dataCompleteness:1,selectionGeneration:1,updatedAt:Date.now(),underlyingAsset:'ETH',quoteAsset:'USDT',riskTier:'LIQUID_ALT',directionPolicy:'BOTH',locationScore:80} as any);

async function fixture(){const raw=JSON.parse(await readFile(path.resolve(process.cwd(),'../..','config/settings.default.json'),'utf8'));raw.appearance={...raw.appearance,theme:'BINANCE_NOIR'};const settings=SystemSettingsSchema.parse(raw);const state=new RuntimeState(settings);state.account={...state.account,status:'READY',asOf:Date.now(),reason:null};state.universe=[candidate()];state.snapshots.set('ETHUSDT',snap('ETHUSDT'));state.snapshots.set('ETHUSDC',snap('ETHUSDC'));return{state,events:new EventBus()};}

describe('Runtime Control',()=>{
  it('allows no-write analysis but keeps Entry dispatch disabled by startup policy',async()=>{const {state,events}=await fixture();state.settings.connections.executionMode='TESTNET_ENABLED';state.settings.riskGovernance.entrySafetyMode='AUTO';state.executionGovernance={...state.executionGovernance,mode:'AUTO_RUNNING'};const control=new RuntimeControlService(state,events),previous=process.env.ZDJ_ENTRY_ADMISSION_DISABLED;process.env.ZDJ_ENTRY_ADMISSION_DISABLED='1';try{expect(control.canAnalyze()).toBe(true);expect(control.canDispatch()).toBe(false);expect(state.runtimeControl.mode).toBe('RUNNING');}finally{if(previous===undefined)delete process.env.ZDJ_ENTRY_ADMISSION_DISABLED;else process.env.ZDJ_ENTRY_ADMISSION_DISABLED=previous;}});
  it('uses a stable capitalVersion independent of selection generation',async()=>{const {state,events}=await fixture(),control=new RuntimeControlService(state,events);control.evaluate(true);const first=state.runtimeControl.capital.capitalVersion,selection=state.runtimeControl.capital.generation;control.evaluate(true);expect(state.runtimeControl.capital.capitalVersion).toBe(first);expect(state.runtimeControl.capital.generation).toBe(selection);state.account.equityUsd=123;control.evaluate(true);const equityVersion=state.runtimeControl.capital.capitalVersion;expect(equityVersion).not.toBe(first);state.settings.portfolioIntelligence={...state.settings.portfolioIntelligence,minMarginUsd:state.settings.portfolioIntelligence.minMarginUsd+1};control.evaluate(true);expect(state.runtimeControl.capital.capitalVersion).not.toBe(equityVersion);const beforeReservation=state.runtimeControl.capital.capitalVersion;state.entryReservations.set('reserve-test',{id:'reserve-test',underlying:'ETH',quoteAsset:'USDT',marginUsd:1,notionalUsd:1,status:'RESERVED',expiresAt:Date.now()+60_000});control.evaluate(true);expect(state.runtimeControl.capital.capitalVersion).not.toBe(beforeReservation);expect(capitalFactVersion(state)).toBe(state.runtimeControl.capital.capitalVersion);});
  it('V3.9 limits new risk without pausing independent runtime and recovers with facts',async()=>{
    const {state,events}=await fixture();state.settings.releasePolicy={lifecycleVersion:390};state.executionGovernance={...state.executionGovernance,mode:'AUTO_RUNNING'};
    state.account={...state.account,equityUsd:10000,riskBaseline:{capitalEpochRealizedPnlUsd:-600,riskDrawdownPct:.06}};
    const service=new RuntimeControlService(state,events);service.evaluate(true);
    expect(state.runtimeControl.mode).toBe('RUNNING');expect(service.canDispatch()).toBe(false);expect(service.capacityDiagnostics().newRiskBlocked).toBe(true);
    state.account.riskBaseline={capitalEpochRealizedPnlUsd:0,riskDrawdownPct:0};service.evaluate(true);expect(service.capacityDiagnostics().newRiskBlocked).toBe(false);
  });
  it('supports manual pause and resume without touching position services when weekly AUTO is explicitly enabled',async()=>{const {state,events}=await fixture();state.settings.releasePolicy={lifecycleVersion:382};state.settings.riskGovernance.entrySafetyMode='AUTO';state.executionGovernance={...state.executionGovernance,mode:'AUTO_RUNNING'};const control=new RuntimeControlService(state,events);const seen:string[]=[];events.on('event',e=>seen.push(e.type));control.pauseManual('验收暂停');expect(control.canDispatch()).toBe(false);expect(state.runtimeControl.mode).toBe('PAUSED_MANUAL');control.resumeManual();expect(control.canDispatch()).toBe(true);expect(seen).toContain('TRADING_PIPELINE_PAUSED_MANUAL');expect(seen).toContain('TRADING_PIPELINE_RESUMED_MANUAL');});
  it('keeps dispatch blocked in the review safety mode even after manual resume',async()=>{const {state}=await fixture();const control=new RuntimeControlService(state,new EventBus());control.pauseManual();control.resumeManual();expect(state.runtimeControl.mode).toBe('RUNNING');expect(control.canDispatch()).toBe(false);});
  it('auto-pauses with no quote margin and resumes after Universe selects an eligible USDC route',async()=>{const {state,events}=await fixture();state.account.assets=[{asset:'USDT',walletBalance:0,availableBalance:0,crossWalletBalance:0,unrealizedPnl:0,usdValue:0,marginEligible:true},{asset:'USDC',walletBalance:0,availableBalance:0,crossWalletBalance:0,unrealizedPnl:0,usdValue:0,marginEligible:true}];const control=new RuntimeControlService(state,events);control.evaluate(true);expect(state.runtimeControl.mode).toBe('PAUSED_NO_CAPITAL');state.account.assets[1]!.availableBalance=20000;state.account.assets[1]!.usdValue=20000;state.account.equityUsd=20000;state.universe=[{...candidate('ETHUSDC'),quoteAsset:'USDC'}];control.evaluate(true);expect(state.runtimeControl.mode).toBe('RUNNING');expect(state.runtimeControl.capital.usdcExecutableUnderlyings).toBe(1);});
  it('manual pause is never auto-resumed by capital recovery',async()=>{const {state}=await fixture();state.account.assets=[{asset:'USDT',walletBalance:0,availableBalance:0,crossWalletBalance:0,unrealizedPnl:0,usdValue:0,marginEligible:true},{asset:'USDC',walletBalance:500,availableBalance:500,crossWalletBalance:0,unrealizedPnl:0,usdValue:500,marginEligible:true}];const control=new RuntimeControlService(state,new EventBus());control.pauseManual();control.evaluate(true);expect(state.runtimeControl.mode).toBe('PAUSED_MANUAL');});
  it('keeps the daily risk gate closed until a Testnet manual override is activated',async()=>{const {state,events}=await fixture();state.settings.releasePolicy={lifecycleVersion:382};state.settings.riskGovernance.entrySafetyMode='AUTO';state.executionGovernance={...state.executionGovernance,mode:'AUTO_RUNNING'};state.account={...state.account,equityUsd:10_000,assets:[{asset:'USDT',walletBalance:10_000,availableBalance:10_000,crossWalletBalance:10_000,unrealizedPnl:0,usdValue:10_000,marginEligible:true}],riskBaseline:{capitalEpochRealizedPnlUsd:-600,riskDrawdownPct:.06,equityUsd:9_400}};const control=new RuntimeControlService(state,events);control.evaluate(true);expect(state.runtimeControl.mode).toBe('PAUSED_DAILY_RISK_LIMIT');expect(control.canDispatch()).toBe(false);const override=control.activateManualRiskOverride({environment:'TESTNET',executionMode:'TESTNET_ENABLED',executionGovernanceMode:'AUTO_PAUSED_RISK',reason:'验收复核'});state.executionGovernance={...state.executionGovernance,mode:'AUTO_RUNNING'};control.evaluate(true);expect(override.status).toBe('MANUAL_RISK_OVERRIDE_ACTIVE');expect(control.manualRiskOverrideActive()).toBe(true);expect(state.runtimeControl.mode).toBe('RUNNING');expect(control.canDispatch()).toBe(true);expect(state.account.riskBaseline.riskDrawdownPct).toBe(.06);});
  it('expires the override in the next risk cycle and re-applies the unchanged risk gate',async()=>{const {state,events}=await fixture();state.settings.releasePolicy={lifecycleVersion:382};state.settings.riskGovernance.entrySafetyMode='AUTO';state.executionGovernance={...state.executionGovernance,mode:'AUTO_RUNNING'};state.account={...state.account,equityUsd:10_000,riskBaseline:{capitalEpochRealizedPnlUsd:-600,riskDrawdownPct:.06,equityUsd:9_400}};const control=new RuntimeControlService(state,events);control.evaluate(true);control.activateManualRiskOverride({environment:'TESTNET',executionMode:'TESTNET_ENABLED',executionGovernanceMode:'AUTO_PAUSED_RISK',reason:'验收复核'});state.executionGovernance={...state.executionGovernance,mode:'AUTO_RUNNING'};state.runtimeControl.manualRiskOverride={...state.runtimeControl.manualRiskOverride!,expiresAt:Date.now()-1};control.evaluate(true);expect(state.runtimeControl.manualRiskOverride).toBeNull();expect(state.runtimeControl.mode).toBe('PAUSED_DAILY_RISK_LIMIT');});
  it('rejects the override outside Testnet',async()=>{const {state,events}=await fixture();state.executionGovernance={...state.executionGovernance,mode:'AUTO_PAUSED_RISK'};state.runtimeControl={...state.runtimeControl,mode:'PAUSED_DAILY_RISK_LIMIT',reasonCode:'DAILY_RISK_LIMIT'};const control=new RuntimeControlService(state,events);expect(()=>control.activateManualRiskOverride({environment:'PRODUCTION',executionMode:'LIVE_ENABLED',executionGovernanceMode:'AUTO_PAUSED_RISK',reason:'不应允许'})).toThrow('TESTNET_MANUAL_RISK_OVERRIDE_ONLY');});
  it('keeps a funded no-candidate runtime RUNNING and migrates the obsolete global pause',async()=>{const {state,events}=await fixture();state.account.assets=[{asset:'USDT',walletBalance:500,availableBalance:500,crossWalletBalance:500,unrealizedPnl:0,usdValue:500,marginEligible:true}];state.universe=[];state.runtimeControl={...state.runtimeControl,mode:'PAUSED_NO_EXECUTABLE_CONTRACT',reasonCode:'NO_EXECUTABLE_CONTRACT'};const control=new RuntimeControlService(state,events);control.evaluate(true);expect(state.runtimeControl.mode).toBe('RUNNING');expect(state.runtimeControl.reasonCode).toBe('NO_EXECUTABLE_CONTRACT');});
});


it('uses current calendar-day loss instead of an old capital-epoch loss when available',async()=>{
 const {state,events}=await fixture();state.settings.riskGovernance.circuitBreakerEnabled=true;state.settings.riskGovernance.maxDailyLossUsd=500;state.settings.releasePolicy={lifecycleVersion:390};state.executionGovernance={...state.executionGovernance,mode:'AUTO_RUNNING'};
 state.account={...state.account,equityUsd:10000,assets:[{asset:'USDT',walletBalance:10000,availableBalance:10000,crossWalletBalance:10000,unrealizedPnl:0,usdValue:10000,marginEligible:true}],riskBaseline:{capitalEpochRealizedPnlUsd:-600,calendarDayRealizedPnlUsd:0,riskDrawdownPct:0}};
 const service=new RuntimeControlService(state,events);service.evaluate(true);expect(service.capacityDiagnostics().newRiskBlocked).toBe(false);
 state.account.riskBaseline.calendarDayRealizedPnlUsd=-600;service.evaluate(true);expect(service.capacityDiagnostics().newRiskBlocked).toBe(true);expect(state.runtimeControl.mode).toBe('RUNNING');
});

it('routes and JIT validate the same direction remainder despite larger wallet asset valuation',async()=>{
 const {state,events}=await fixture();state.settings.riskGovernance.entrySafetyMode='AUTO';state.executionGovernance={...state.executionGovernance,mode:'AUTO_RUNNING'};
 state.account={...state.account,equityUsd:10000,assets:[{asset:'USDT',availableBalance:20000,walletBalance:20000,usdValue:20000}]};
 state.positions.set('short',{symbol:'BTCUSDT',side:'SHORT',quantity:1,markPrice:4990,leverage:10} as any);
 new RuntimeControlService(state,events).evaluate(true);const route:any=state.runtimeControl.capital.routedCandidates.find(r=>r.symbol==='ETHUSDT');expect(route).toBeDefined();expect(route.shortFeasibleNotionalUsd).toBe(10);expect(route.riskHeadroom.SHORT.equity).toBe(10000);
 const result=evaluatePreflightFeasibility(state,'ETHUSDT');expect(result.pass).toBe(true);expect(result.feasibleNotionalUsd.SHORT).toBe(route.shortFeasibleNotionalUsd);
 state.account.equityUsd=9900;expect(evaluatePreflightFeasibility(state,'ETHUSDT').reason).toBe('CAPITAL_FACTS_CHANGED');
});
