import {describe,expect,it} from 'vitest';
import {collectorWindowSummary,primaryObservation,riskFactCoverage} from './s01TruthAccountingObservability.js';
describe('S01 truth/accounting/observability',()=>{
 it('requires continuous history and fresh current facts',()=>{const x=riskFactCoverage({now:1000,checkedAt:900,validUntil:1100,historyCovered:false,activeOrderIdentity:false,fillIdentity:false,positionRelation:'ABSENT'});expect(x.currentRisk).toBe('UNKNOWN');const y=riskFactCoverage({now:1000,checkedAt:900,validUntil:1100,historyCovered:true,activeOrderIdentity:false,fillIdentity:false,positionRelation:'ABSENT'});expect(y.currentRisk).toBe('CURRENT_NO_ACTIVE_RISK');});
 it('does not release attributed or ambiguous positions',()=>{for(const positionRelation of ['ATTRIBUTED','AMBIGUOUS'] as const)expect(riskFactCoverage({now:1000,checkedAt:900,validUntil:1100,historyCovered:true,activeOrderIdentity:false,fillIdentity:false,positionRelation}).status).toBe('CONFLICT');});
 it('requires positive terminal proof for durable classification',()=>{const x=riskFactCoverage({now:1000,checkedAt:900,historyCovered:true,activeOrderIdentity:false,fillIdentity:false,positionRelation:'ABSENT'});expect(x.currentRisk).toBe('CURRENT_NO_ACTIVE_RISK');const y=riskFactCoverage({now:1000,checkedAt:900,historyCovered:true,terminalStatus:'CANCELED',activeOrderIdentity:false,fillIdentity:false,positionRelation:'ABSENT'});expect(y.currentRisk).toBe('DURABLE_TERMINAL_PROVEN');});
 it('automatically segments identity changes and counter rollback',()=>{const x=collectorWindowSummary([{identity:'a',at:0,count:10},{identity:'a',at:600000,count:70},{identity:'a',at:1200000,count:2},{identity:'b',at:1800000,count:8}]);expect(x).toMatchObject({identity:'b',sampleCount:1,countDelta:null,ratePerHour:null,reset:true,reason:'IDENTITY_CHANGED',peak:8});const y=collectorWindowSummary([{identity:'a',at:0,count:10},{identity:'a',at:600000,count:70}]);expect(y).toMatchObject({sampleCount:2,countDelta:60,ratePerHour:360,peak:70});});
 it('distinguishes runtime pause, market pause, resource fault and healthy idle',()=>{expect(primaryObservation({runtimePaused:true,marketOpen:true,resourceFault:false,lastRunAt:null,now:1,maxIdleMs:10})).toBe('RUNTIME_PAUSED');expect(primaryObservation({runtimePaused:false,marketOpen:false,resourceFault:false,lastRunAt:null,now:1,maxIdleMs:10})).toBe('MARKET_PAUSE');expect(primaryObservation({runtimePaused:false,marketOpen:true,resourceFault:true,lastRunAt:1,now:2,maxIdleMs:10})).toBe('RESOURCE_FAULT');});
});
