/** Same retention caps; scans run off-thread before short autocommit deletes.
 * Referenced recovery entities remain protected by their checkpoint transaction. */
export const STORAGE_MAINTENANCE_WORKER_SOURCE=[
  "const {workerData,parentPort}=require('node:worker_threads');",
  "const {existsSync}=require('node:fs');const path=require('node:path');const {DatabaseSync}=require('node:sqlite');",
  "const {caps:STORAGE_ROW_CAPS,protectedEvent,analysisChain}=workerData;",
  "const dataDir=()=>workerData.dataDir;let lastMaintenanceAt=0,cache=null;",
  "function maintainStorageBounds(now=Date.now()){",
  " if(now-lastMaintenanceAt<5000)return;lastMaintenanceAt=now;const file=path.join(dataDir(),'zdj-settings.sqlite');if(!existsSync(file))return;",
  " let db;",
  " try{",
  "  db=new DatabaseSync(file);db.exec('PRAGMA busy_timeout=25; PRAGMA foreign_keys=ON;');const tables=new Set(db.prepare(\"SELECT name FROM sqlite_master WHERE type='table'\").all().map((r)=>String(r.name))),batch=250;",
  "  const trim=(table,cap,order,where='1')=>{if(!tables.has(table))return 0;const n=Number((db.prepare(`SELECT COUNT(*) n FROM (SELECT 1 FROM \"${table}\" WHERE ${where} LIMIT ${cap+batch})`).get()).n),excess=Math.min(batch,Math.max(0,n-cap));if(!excess)return 0;const ids=db.prepare(`SELECT rowid FROM \"${table}\" WHERE ${where} ORDER BY ${order} LIMIT ?`).all(excess).map(row=>row.rowid);if(!ids.length)return 0;return Number(db.prepare(`DELETE FROM \"${table}\" WHERE rowid IN (${ids.map(()=>\"?\").join(\",\")}) AND (${where})`).run(...ids).changes);};",
  "  try{",
  "   trim('decision_snapshots',STORAGE_ROW_CAPS.decisionSnapshots,'created_at ASC,rowid ASC');",
  "   trim('decision_chains',STORAGE_ROW_CAPS.analysisChains,'updated_at ASC,rowid ASC',analysisChain);",
  "   trim('decision_chains',STORAGE_ROW_CAPS.executionChains,'updated_at ASC,rowid ASC',`json_valid(payload) AND NOT (${analysisChain})`);",
  "   if(tables.has('ai_runs_archive')){",
  "    db.prepare(`UPDATE ai_runs_archive SET payload='{}' WHERE rowid IN (SELECT rowid FROM ai_runs_archive WHERE status IN ('COMPLETED','FAILED','CANCELED') AND payload<>'{}' AND rowid NOT IN (SELECT rowid FROM ai_runs_archive WHERE status IN ('COMPLETED','FAILED','CANCELED') ORDER BY started_at DESC LIMIT ${STORAGE_ROW_CAPS.aiRawRuns}) ORDER BY started_at ASC LIMIT ${batch})`).run();",
  "    trim('ai_runs_archive',STORAGE_ROW_CAPS.aiArchiveRows,'started_at ASC,rowid ASC',\"status IN ('COMPLETED','FAILED','CANCELED') AND payload='{}'\");",
  "   }",
  "   trim('runtime_events',STORAGE_ROW_CAPS.nonCriticalRuntimeEvents,'ts ASC,rowid ASC',`NOT ${protectedEvent}`);",
  "   trim('runtime_events',STORAGE_ROW_CAPS.criticalRuntimeEvents,'ts ASC,rowid ASC',protectedEvent);",
  "   trim('shadow_mark_series',STORAGE_ROW_CAPS.shadowMarks,'ts ASC,rowid ASC');",
  "   trim('external_research_tasks',STORAGE_ROW_CAPS.externalResearchTasks,'updated_at ASC,rowid ASC',\"status IN ('COMPLETED','FAILED','EXPIRED')\");",
  "   trim('decision_episodes',STORAGE_ROW_CAPS.decisionEpisodes,'decided_at ASC,rowid ASC');",
  "   trim('state_change_observations',STORAGE_ROW_CAPS.stateChangeObservations,'observed_at ASC,rowid ASC');",
  "   trim('regime_samples',STORAGE_ROW_CAPS.regimeSamples,'sample_at ASC,rowid ASC');",
  "   trim('trade_records',STORAGE_ROW_CAPS.closedTrades,'updated_at ASC,rowid ASC',\"status NOT IN ('OPEN','WORKING','PARTIALLY_FILLED')\");",
  "   trim('entry_execution_tasks',STORAGE_ROW_CAPS.inactiveEntryExecutions,'updated_at ASC,rowid ASC','active=0');",
  "   trim('execution_tasks',STORAGE_ROW_CAPS.inactiveManualExecutions,'updated_at ASC,rowid ASC','active=0');",
  "   trim('experience_samples',STORAGE_ROW_CAPS.experienceSamples,'created_at ASC,rowid ASC');",
  "   if(tables.has('runtime_state')&&tables.has('runtime_entities')){",
  "    db.exec('BEGIN IMMEDIATE');",
  "    try{",
  "    const state=db.prepare('SELECT payload FROM runtime_state WHERE id=1').get(),lists=state?.payload?JSON.parse(String(state.payload))?._entityLists:null;",
  "    if(lists&&typeof lists==='object')for(const [kind,info] of Object.entries(lists)){const live=new Set(Array.isArray(info?.ids)?info.ids.map(String):[]),rows=db.prepare('SELECT entity_id FROM runtime_entities WHERE kind=?').all(kind);let removed=0;for(const row of rows){if(removed>=batch)break;if(!live.has(String(row.entity_id))){db.prepare('DELETE FROM runtime_entities WHERE kind=? AND entity_id=?').run(kind,row.entity_id);removed++;}}}",
  "    db.exec('COMMIT');",
  "    }catch(error){db.exec('ROLLBACK');throw error;}",
  "   }",
  "  }catch(error){throw error;}",
  "  const free=Number((db.prepare('PRAGMA freelist_count').get()).freelist_count??0);if(free>256)db.exec('PRAGMA incremental_vacuum(256)');",
  " }catch(error){return {status:'RETRY',error:String(error)};}",
  " finally{db?.close();cache=null;}",
  " return {status:\"COMPLETED\"};",
  "}",
  "",
  "parentPort.postMessage(maintainStorageBounds(workerData.now));"
].join('\n');
