import {afterEach,it,expect} from 'vitest';
import {mkdtempSync,rmSync,truncateSync,writeFileSync} from 'node:fs';
import os from 'node:os';import path from 'node:path';import {DatabaseSync} from 'node:sqlite';
import {maintainStorageBounds,resetStorageCapacityGuardForTest,storageCapacityHealth,storageEntryBlockReason,storageShouldShedNonCritical} from './storageCapacityGuard.js';
const prior=process.env.ZDJ_DATA_DIR;let dir='';
afterEach(()=>{if(dir)rmSync(dir,{recursive:true,force:true});dir='';if(prior===undefined)delete process.env.ZDJ_DATA_DIR;else process.env.ZDJ_DATA_DIR=prior;resetStorageCapacityGuardForTest();});
function size(mib:number){dir=mkdtempSync(path.join(os.tmpdir(),'zdj-storage-guard-'));process.env.ZDJ_DATA_DIR=dir;const file=path.join(dir,'zdj-settings.sqlite');writeFileSync(file,'');truncateSync(file,mib*1024*1024);resetStorageCapacityGuardForTest();}
it('allows new entry below capacity warning',()=>{size(64);expect(storageCapacityHealth(true).status).toBe('AVAILABLE');expect(storageEntryBlockReason()).toBeNull();expect(storageShouldShedNonCritical()).toBe(false);});
it('sheds noncritical persistence before blocking new entry',()=>{size(1050);expect(storageCapacityHealth(true).status).toBe('SHEDDING');expect(storageShouldShedNonCritical()).toBe(true);expect(storageEntryBlockReason()).toBeNull();});
it('blocks new entry well before emergency reserve',()=>{size(1300);expect(storageCapacityHealth(true).status).toBe('ENTRY_BLOCKED');expect(storageEntryBlockReason()).toContain('SQLITE_CAPACITY_ENTRY_BLOCKED');});
it('keeps only bounded recent snapshots and full AI payloads',()=>{dir=mkdtempSync(path.join(os.tmpdir(),'zdj-storage-bounds-'));process.env.ZDJ_DATA_DIR=dir;const db=new DatabaseSync(path.join(dir,'zdj-settings.sqlite'));try{db.exec('PRAGMA journal_mode=MEMORY; PRAGMA synchronous=OFF; CREATE TABLE decision_snapshots(snapshot_id TEXT PRIMARY KEY,created_at INTEGER NOT NULL,payload TEXT NOT NULL); CREATE TABLE ai_runs_archive(run_id TEXT PRIMARY KEY,started_at INTEGER NOT NULL,status TEXT NOT NULL,payload TEXT NOT NULL); BEGIN');const snap=db.prepare('INSERT INTO decision_snapshots VALUES(?,?,?)'),run=db.prepare('INSERT INTO ai_runs_archive VALUES(?,?,?,?)');for(let i=0;i<5002;i++)snap.run('s'+i,i,'{}');for(let i=0;i<1002;i++)run.run('r'+i,i,'COMPLETED','{"raw":true}');db.exec('COMMIT');}finally{db.close();}resetStorageCapacityGuardForTest();maintainStorageBounds();const check=new DatabaseSync(path.join(dir,'zdj-settings.sqlite'),{readOnly:true});try{expect(Number((check.prepare('SELECT count(*) n FROM decision_snapshots').get() as any).n)).toBe(5000);expect(Number((check.prepare("SELECT count(*) n FROM ai_runs_archive WHERE payload<>'{}'").get() as any).n)).toBe(1000);expect((check.prepare('SELECT min(created_at) n FROM decision_snapshots').get() as any).n).toBe(2);}finally{check.close();}});
