import type { Position, ManualOrder } from '@zdj/contracts';
import type { RuntimeState } from '../state/runtimeState.js';
import type { MarketDataHub } from './marketDataHub.js';
import type { ExchangeTradeAdapter } from '../types.js';
import type { EventBus } from '../events/eventBus.js';
import type { TpGuardian } from './tpGuardian.js';
import type { SettingsStore } from '../config/settingsStore.js';
import { binanceClientOrderIdFactory } from './binanceClientOrderIdFactory.js';

export const CLEANUP_SOURCE='HUMAN_AUTHORIZED_TESTNET_CLEANUP' as const;
export type CleanupPreview={symbol:string;side:'LONG'|'SHORT';qty:number;entry:number;mark:number;unrealizedPnl:number;bid:number;ask:number;tp:number|null;activeOrders:number};
export type CleanupResult=CleanupPreview&{status:'FULLY_CLOSED'|'PARTIAL'|'NOT_FILLED'|'FAILED';attempts:Array<{phase:string;qty:number;price:number;orderId:string|null;clientOrderId:string|null;status:string;filledQuantity:number}>;realizedPnl:number|null;fees:number|null;netPnl:number|null;marketOrderCount:number;orphanTp:number;duplicateTp:number;error?:string};
const wait=(ms:number)=>new Promise<void>(resolve=>setTimeout(resolve,ms));
export const isEligibleCleanupPnl=(pnl:number)=>Number.isFinite(pnl)&&pnl<0&&pnl>-10;
export const cleanupLimitPrice=(side:'LONG'|'SHORT',postOnly:boolean,quote:{bid:number;ask:number})=>side==='LONG'?(postOnly?quote.ask:quote.bid):(postOnly?quote.bid:quote.ask);

/** One-shot, human-invoked, Testnet-only cleanup. It is deliberately not registered with any scheduler. */
export class TestnetLowLossCleanupService {
  private running=false;
  constructor(private readonly state:RuntimeState,private readonly market:MarketDataHub,private readonly exchange:ExchangeTradeAdapter,private readonly tp:TpGuardian,private readonly events:EventBus,private readonly reconcile:()=>Promise<void>,private readonly store?:SettingsStore) {}
  private assertTestnet(){if(this.state.settings.connections.executionMode!=='TESTNET_ENABLED'||this.state.settings.connections.exchange.environment!=='TESTNET')throw new Error('TESTNET_ONLY_CLEANUP_REQUIRED');}
  private async remotePositions(){return this.exchange.fetchPositions();}
  async preview():Promise<{source:string;eligible:CleanupPreview[];excluded:{symbol:string;reason:string}[];generatedAt:number}> {
    this.assertTestnet();const positions=await this.remotePositions();const needsRefresh=positions.filter(p=>{const q=this.market.snapshot(p.symbol)?.quote;return !q||!q.ts||Date.now()-q.ts>15_000;}).map(p=>p.symbol);if(needsRefresh.length)await this.market.refreshSymbols(needsRefresh);const excluded:{symbol:string;reason:string}[]=[];const eligible:CleanupPreview[]=[];
    for(const p of positions){const q=this.market.snapshot(p.symbol)?.quote;if(!q||!Number.isFinite(p.unrealizedPnl)){excluded.push({symbol:p.symbol,reason:'DATA_INCOMPLETE'});continue;}if(p.quantity===0){excluded.push({symbol:p.symbol,reason:'ZERO_POSITION'});continue;}if(!isEligibleCleanupPnl(p.unrealizedPnl)){excluded.push({symbol:p.symbol,reason:p.unrealizedPnl>=0?'NON_NEGATIVE_PNL':'PNL_AT_OR_BELOW_MINUS_10'});continue;}const local=[...this.state.positions.values()].find(row=>row.symbol===p.symbol&&row.side===p.side),active=[...this.state.manualOrders.values()].filter(row=>row.symbol===p.symbol&&['NEW','WORKING','PARTIALLY_FILLED'].includes(row.status)).length;if(active){excluded.push({symbol:p.symbol,reason:'FULL_CLOSE_IN_PROGRESS'});continue;}eligible.push({symbol:p.symbol,side:p.side,qty:p.quantity,entry:p.entryPrice,mark:p.markPrice,unrealizedPnl:p.unrealizedPnl,bid:q.bid!,ask:q.ask!,tp:local?.tpOrderId?this.state.tpOrders.get(local.tpOrderId)?.price??null:null,activeOrders:[...this.state.entryOrders.values(),...this.state.tpOrders.values()].filter(row=>row.symbol===p.symbol&&row.status==='WORKING').length});}
    eligible.sort((a,b)=>Math.abs(a.unrealizedPnl)-Math.abs(b.unrealizedPnl));this.events.publish('TESTNET_LOW_LOSS_CLEANUP_PREVIEW',{source:CLEANUP_SOURCE,eligible,excluded});return{source:CLEANUP_SOURCE,eligible,excluded,generatedAt:Date.now()};
  }
  private async latest(position:Position){const remote=(await this.remotePositions()).find(row=>row.symbol===position.symbol&&row.side===position.side);return remote??null;}
  private async cancel(order:ManualOrder){const canceled=this.exchange.cancelManualOrder?await this.exchange.cancelManualOrder(order):{...order,status:'CANCELED' as const,updatedAt:Date.now()};this.state.manualOrders.set(order.id,canceled);this.events.publish('TESTNET_LOW_LOSS_CLEANUP_CLOSE_TIMEOUT',{source:CLEANUP_SOURCE,orderId:order.exchangeOrderId,clientOrderId:order.clientOrderId,phase:'CANCELLED'},order.symbol);}
  private async settle(position:Position,order:ManualOrder,initialQty:number,waitMs:number){const deadline=Date.now()+Math.max(0,waitMs);let current=await this.latest(position);while(current&&Date.now()<deadline){if(current.quantity<initialQty-1e-10)return current;await wait(Math.min(2_000,Math.max(0,deadline-Date.now())));current=await this.latest(position);}if(current&&current.quantity<initialQty-1e-10)return current;if(order.status==='WORKING')await this.cancel(order);await this.reconcile();return await this.latest(position);}
  private async process(item:CleanupPreview,waitMs:number):Promise<CleanupResult>{
    const local=[...this.state.positions.values()].find(row=>row.symbol===item.symbol&&row.side===item.side);if(!local)return{...item,status:'NOT_FILLED',attempts:[],realizedPnl:null,fees:null,netPnl:null,marketOrderCount:0,orphanTp:0,duplicateTp:0,error:'LOCAL_POSITION_NOT_AVAILABLE'};
    const lockId=local.id;this.tp.suspend(lockId);const attempts:CleanupResult['attempts']=[];let status:CleanupResult['status']='NOT_FILLED';let current:Position|null=null;let facts:any=null;
    try{
      for(const tp of [...this.state.tpOrders.values()].filter(row=>row.positionId===lockId&&row.status==='WORKING')){const canceled=await this.tp.cancel(tp);this.state.tpOrders.set(tp.id,canceled);}this.state.positions.set(lockId,{...local,tpStatus:'MISSING',tpOrderId:null,tpCoverageSource:'NONE',tpLastVerifiedAt:Date.now()});current=await this.latest(local);
      const phases=[{name:'PHASE1_MAKER',postOnly:true,action:'EC1' as const},{name:'PHASE2_COUNTERPARTY',postOnly:false,action:'EC2' as const},{name:'REPRICE_1_COUNTERPARTY',postOnly:false,action:'EC3' as const},{name:'REPRICE_2_COUNTERPARTY',postOnly:false,action:'EC3' as const}];
      for(const phase of phases){if(!current||current.quantity<=0){status='FULLY_CLOSED';break;}const quote=this.market.snapshot(item.symbol)?.quote;if(!quote){attempts.push({phase:phase.name,qty:current.quantity,price:0,orderId:null,clientOrderId:null,status:'NO_QUOTE',filledQuantity:0});break;}const side=current.side==='LONG'?'SELL':'BUY',price=cleanupLimitPrice(current.side,phase.postOnly,{bid:quote.bid!,ask:quote.ask!}),id=`cleanup_${current.symbol}_${Date.now()}_${attempts.length}`,client=binanceClientOrderIdFactory.create(phase.action,id);let order:ManualOrder;try{order=await this.exchange.placeManualOrder({clientOrderId:client,internalOrderId:id,symbol:current.symbol,side,positionSide:current.side,type:'LIMIT',quantity:current.quantity,price,reduceOnly:true,postOnly:phase.postOnly});}catch(error){const message=error instanceof Error?error.message:String(error);attempts.push({phase:phase.name,qty:current.quantity,price,orderId:null,clientOrderId:client,status:`SUBMIT_FAILED:${message}`,filledQuantity:0});this.events.publish('TESTNET_LOW_LOSS_CLEANUP_CLOSE_FAILED',{source:CLEANUP_SOURCE,phase:phase.name,reason:message},current.symbol);continue;}const stored={...order,positionId:lockId};this.state.manualOrders.set(stored.id,stored);this.events.publish('TESTNET_LOW_LOSS_CLEANUP_CLOSE_SUBMITTED',{source:CLEANUP_SOURCE,phase:phase.name,orderId:stored.exchangeOrderId,clientOrderId:stored.clientOrderId,qty:stored.quantity,price:stored.price,postOnly:phase.postOnly},current.symbol);const before=current.quantity;current=await this.settle(current,stored,before,waitMs);const filled=Math.max(0,before-(current?.quantity??0));attempts.push({phase:phase.name,qty:before,price,orderId:stored.exchangeOrderId,clientOrderId:stored.clientOrderId,status:current?'TIMEOUT_OR_PARTIAL':'FILLED',filledQuantity:filled});if(filled>0)this.events.publish('TESTNET_LOW_LOSS_CLEANUP_CLOSE_FILLED',{source:CLEANUP_SOURCE,phase:phase.name,orderId:stored.exchangeOrderId,filledQuantity:filled},item.symbol);}
      await this.reconcile();current=await this.latest(local);if(!current||current.quantity<=0)status='FULLY_CLOSED';else status=attempts.some(row=>row.filledQuantity>0)?'PARTIAL':'NOT_FILLED';
    }catch(error){status='FAILED';this.events.publish('TESTNET_LOW_LOSS_CLEANUP_CLOSE_FAILED',{source:CLEANUP_SOURCE,reason:error instanceof Error?error.message:String(error)},item.symbol);
    }finally{this.tp.resume(lockId);const remaining=current??await this.latest(local);if(remaining&&remaining.quantity>0){const next={...this.state.positions.get(lockId)!,quantity:remaining.quantity,markPrice:remaining.markPrice,unrealizedPnl:remaining.unrealizedPnl,tpStatus:'MISSING' as const,tpOrderId:null};this.state.positions.set(lockId,next);await this.tp.ensure(next,true);}else{await this.reconcile();}}
    if(status==='FULLY_CLOSED'&&this.exchange.fetchSymbolTradeFacts){try{facts=await this.exchange.fetchSymbolTradeFacts(item.symbol,local.openedAt,Date.now());const fills=facts.fills??[],orders=new Map((facts.orders??[]).map((row:any)=>[row.orderId,row])),exit=fills.filter((row:any)=>row.side==='SELL'&&item.side==='LONG'||row.side==='BUY'&&item.side==='SHORT'),realized=exit.reduce((sum:number,row:any)=>sum+Number(row.realizedPnl??0),0),fees=(facts.income??[]).filter((row:any)=>row.incomeType==='COMMISSION').reduce((sum:number,row:any)=>sum+Math.abs(Number(row.income??0)),0),record=[...this.state.tradeRecords.values()].find(row=>row.tradeId===`trade_${local.id}`);if(record&&exit.length){const exitNotional=exit.reduce((sum:number,row:any)=>sum+Number(row.qty??0)*Number(row.price??0),0),updated={...record,closedAt:exit.at(-1)?.executionTime??record.closedAt,exitAveragePrice:exitNotional/Math.max(1,exit.reduce((sum:number,row:any)=>sum+Number(row.qty??0),0)),exitGrossNotional:exitNotional,exitFillCount:exit.length,exitOrderIds:[...new Set(exit.map((row:any)=>String(row.orderId)))],grossRealizedPnl:realized,feeBreakdown:[...record.feeBreakdown,...exit.map((row:any)=>({stage:'EXIT',asset:row.commissionAsset,amount:row.commission,usd:null,conversionSource:null}))],missingFacts:['ENTRY_FACT','ENTRY_FEE_FACT'],integrityFlags:['ENTRY_FACT_UNAVAILABLE'],repairSource:'MANUAL_TRADE_SYNC',updatedAt:Date.now()};this.state.tradeRecords.set(record.tradeId,updated as any);this.store?.upsertTradeRecord(updated);this.events.publish('TRADE_RECORD_REPAIRED',{tradeId:record.tradeId,record:updated,source:CLEANUP_SOURCE},item.symbol);} }catch(error){this.events.publish('TESTNET_LOW_LOSS_CLEANUP_CLOSE_FAILED',{source:CLEANUP_SOURCE,phase:'TRADE_RECORD_FACTS',reason:error instanceof Error?error.message:String(error)},item.symbol);}}
    const exitFills=facts?.fills??[],realizedPnl=exitFills.reduce((sum:number,row:any)=>sum+Number(row.realizedPnl??0),0),fees=(facts?.income??[]).filter((row:any)=>row.incomeType==='COMMISSION').reduce((sum:number,row:any)=>sum+Math.abs(Number(row.income??0)),0),metrics=this.tp.metrics();return{...item,status,attempts,realizedPnl:exitFills.length?realizedPnl:null,fees:exitFills.length?fees:null,netPnl:exitFills.length?realizedPnl-fees:null,marketOrderCount:0,orphanTp:metrics.orphanTp,duplicateTp:metrics.duplicateTp};
  }
  async repairTradeRecord(symbol:string,startTime:number){this.assertTestnet();if(!this.exchange.fetchSymbolTradeFacts)throw new Error('SYMBOL_TRADE_AUDIT_UNAVAILABLE');const normalized=symbol.toUpperCase(),facts=await this.exchange.fetchSymbolTradeFacts(normalized,startTime,Date.now()),fills=facts.fills??[],record=[...this.state.tradeRecords.values()].find(row=>row.symbol===normalized&&row.status==='CLOSED');if(!record||!fills.length)return{record:null,facts};const exitNotional=fills.reduce((sum,row)=>sum+row.qty*row.price,0),exitQty=fills.reduce((sum,row)=>sum+row.qty,0),realized=fills.reduce((sum,row)=>sum+row.realizedPnl,0),exitFee=(facts.income??[]).filter(row=>row.incomeType==='COMMISSION').reduce((sum,row)=>sum+Math.abs(row.income),0),updated={...record,closedAt:fills.at(-1)!.executionTime,exitAveragePrice:exitNotional/Math.max(1,exitQty),exitGrossNotional:exitNotional,exitFillCount:fills.length,exitOrderIds:[...new Set(fills.map(row=>String(row.orderId)))],grossRealizedPnl:realized,exitFee,feeBreakdown:fills.map(row=>({stage:'EXIT' as const,asset:row.commissionAsset,amount:row.commission,usd:null,conversionSource:null})),missingFacts:['ENTRY_FACT','ENTRY_FEE_FACT'],integrityFlags:['ENTRY_FACT_UNAVAILABLE'],repairSource:'MANUAL_TRADE_SYNC',updatedAt:Date.now()};this.state.tradeRecords.set(record.tradeId,updated);this.store?.upsertTradeRecord(updated);this.events.publish('TRADE_RECORD_REPAIRED',{tradeId:record.tradeId,record:updated,source:CLEANUP_SOURCE},normalized);return{record:updated,facts};}
  async execute(confirm:boolean,options:{waitMs?:number}={}):Promise<{source:string;status:'COMPLETED'|'NO_ELIGIBLE'|'REJECTED';preview:Awaited<ReturnType<TestnetLowLossCleanupService['preview']>>;results:CleanupResult[];marketOrderCount:number}>{
    this.assertTestnet();if(!confirm)throw new Error('HUMAN_CONFIRMATION_REQUIRED');if(this.running)throw new Error('CLEANUP_ALREADY_RUNNING');this.running=true;try{const preview=await this.preview();this.events.publish('TESTNET_LOW_LOSS_CLEANUP_REQUESTED',{source:CLEANUP_SOURCE,eligible:preview.eligible.map(row=>row.symbol),confirm:true});const results:CleanupResult[]=[];for(const item of preview.eligible)results.push(await this.process(item,options.waitMs??60_000));return{source:CLEANUP_SOURCE,status:results.length?'COMPLETED':'NO_ELIGIBLE',preview,results,marketOrderCount:0};}finally{this.running=false;}
  }
}
