import type { Position, TakeProfitOrder } from '@zdj/contracts';
import { estimateTradingCost, takeProfitTarget, uid, roundToTick } from '@zdj/core';
import type { RuntimeState } from '../state/runtimeState.js';
import type { EventBus } from '../events/eventBus.js';
import type { ExchangeTradeAdapter } from '../types.js';
import { binanceClientOrderIdFactory } from './binanceClientOrderIdFactory.js';
import { confirmedTpSubmissionRejection } from './tpSubmissionOutcome.js';

export class TpGuardian {
  private retry=new Map<string,{attempt:number;nextAt:number;lastError:string}>();private repairing=new Set<string>();private suspendedPositions=new Set<string>();
  suspend(positionId:string){this.suspendedPositions.add(positionId);}
  resume(positionId:string){this.suspendedPositions.delete(positionId);}
  async cancel(order:TakeProfitOrder){return this.exchange.cancelTakeProfit(order);}
  async place(order:TakeProfitOrder){return this.exchange.placeTakeProfit(order);}
  economicsFor(position:Position,exitPrice:number){const settings=this.state.settings.takeProfit,exitRate=settings.exitFeeAssumption==='MAKER'?settings.makerFeeRate:settings.takerFeeRate;return estimateTradingCost({entryPrice:position.entryPrice,qty:position.quantity,direction:position.side,leverage:position.leverage,entryFeeRate:settings.entryFeeRate,expectedExitFeeRate:exitRate,expectedSlippagePct:settings.slippageBufferPct,feeSafetyBufferPct:settings.feeSafetyBufferPct,minNetProfitUsd:settings.minNetProfitUsd,minNetProfitRoiPct:settings.minNetProfitRoiPct},exitPrice);}
  constructor(private state:RuntimeState,private exchange:ExchangeTradeAdapter,private events:EventBus){}
  metrics(){const positions=[...this.state.positions.values()],active=[...this.state.tpOrders.values()].filter(order=>order.status==='WORKING'),byPosition=new Map<string,number>();for(const order of active)byPosition.set(order.positionId,(byPosition.get(order.positionId)??0)+1);const orphanTp=active.filter(order=>!this.state.positions.has(order.positionId)).length,duplicateTp=[...byPosition.values()].filter(count=>count>1).reduce((sum,count)=>sum+count-1,0),qtyMismatch=active.filter(order=>{const pos=this.state.positions.get(order.positionId);return Boolean(pos&&Math.abs(order.quantity-pos.quantity)>Math.max(1e-10,pos.quantity*.000001));}).length,wrongSide=active.filter(order=>{const pos=this.state.positions.get(order.positionId);return Boolean(pos&&order.side!==(pos.side==='LONG'?'SELL':'BUY'));}).length;const covered=(p:Position)=>active.some(o=>o.positionId===p.id&&o.symbol===p.symbol&&o.side===(p.side==='LONG'?'SELL':'BUY')&&Math.abs(o.quantity-p.quantity)<=Math.max(1e-10,p.quantity*1e-6));return{unverifiedTp:[...this.state.tpOrders.values()].filter(o=>o.status==='UNKNOWN').length,required:positions.length,protected:positions.filter(p=>covered(p)).length,missing:positions.filter(p=>!covered(p)).length,repairing:positions.filter(p=>p.tpStatus==='REPAIRING').length,repairFailed:positions.filter(p=>p.tpStatus==='REPAIR_FAILED').length,manualReviewRequired:positions.filter(p=>p.tpStatus==='MANUAL_REVIEW_REQUIRED').length,orphanTp,duplicateTp,qtyMismatch,wrongSide,tpMissing:positions.filter(p=>!covered(p)).length,retryQueue:[...this.retry.values()].filter(x=>x.nextAt>Date.now()).length};}
  async ensure(position:Position,force=false){
    if(this.suspendedPositions.has(position.id))return;
    if(!this.state.settings.takeProfit.enabled)return;const current=this.state.positions.get(position.id);if(!current||this.repairing.has(current.id))return;
    let existing=current.tpOrderId?this.state.tpOrders.get(current.tpOrderId):undefined;
    existing=[...this.state.tpOrders.values()].find(o=>o.positionId===current.id&&o.symbol===current.symbol&&o.status==='WORKING'&&o.side===(current.side==='LONG'?'SELL':'BUY')&&Math.abs(o.quantity-current.quantity)<=Math.max(1e-10,current.quantity*1e-6))??existing;
    existing??=[...this.state.tpOrders.values()].find(o=>o.positionId===current.id&&o.status==='UNKNOWN');
    if(existing?.status==='UNKNOWN'){try{const verified=await this.exchange.findTakeProfitByClientOrderId?.(existing);if(!verified||verified.status==='UNKNOWN')return;this.state.tpOrders.set(existing.id,verified);existing=verified;if(verified.status==='FILLED')return;}catch{return;}}
    if(existing?.status==='WORKING'&&Math.abs(existing.quantity-current.quantity)<=Math.max(1e-10,current.quantity*1e-6)&&existing.side===(current.side==='LONG'?'SELL':'BUY')){this.state.positions.set(current.id,{...current,tpStatus:'PROTECTED',tpOrderId:existing.id,tpLastVerifiedAt:Date.now()});return;}
    const retry=this.retry.get(current.id);if(!force&&retry&&retry.nextAt>Date.now())return;
    const market=this.state.snapshots.get(current.symbol);if(!market){this.state.positions.set(current.id,{...current,tpStatus:'MISSING',tpCoverageSource:'NONE'});return;}
    this.repairing.add(current.id);this.state.positions.set(current.id,{...current,tpStatus:'REPAIRING'});const attempt=(retry?.attempt??0)+1;this.events.publish('TP_REPAIR_STARTED',{positionId:current.id,attempt,source:'DETERMINISTIC_POSITION_FACTS'},current.symbol);
    const decimals=Math.max(0,(String(market.quote.stepSize).split('.')[1]??'').length);
    // Pending exits (especially UNKNOWN) are not fills. Protect actual remaining quantity.
    const rawQty=current.quantity*this.state.settings.takeProfit.quantityPercent/100;
    const qty=Number((Math.floor((rawQty+1e-12)/market.quote.stepSize)*market.quote.stepSize).toFixed(decimals));
    if(qty<market.quote.minQty){this.state.positions.set(current.id,{...current,tpStatus:'MANUAL_REVIEW_REQUIRED',tpOrderId:null,tpCoverageSource:'NONE'});this.repairing.delete(current.id);this.events.publish('TP_UNPROTECTED_DUST',{positionId:current.id,quantity:current.quantity,minQty:market.quote.minQty},current.symbol);return;}
    const ai=current.profitTakePlan,card:any=market.technical?.['15m'],roundedAi=ai?roundToTick(ai.targetPrice,market.quote.tickSize,current.side==='LONG'?'ceil':'floor'):null,aiHorizonValid=Boolean(ai&&current.openedAt>0&&Date.now()<=current.openedAt+ai.targetHorizonMinutes*60_000),aiStructureValid=Boolean(card?.isClosed===true&&Number.isFinite(card?.barCloseTime)&&Date.now()-card.barCloseTime<=1_805_000&&Number.isFinite(card?.atrPercent)&&Math.abs((roundedAi??0)-current.entryPrice)/Math.max(current.entryPrice,1)*100<=Math.max(this.state.settings.takeProfit.structureMaxMovePercent,card.atrPercent*6)),aiShapeValid=Boolean(ai&&roundedAi&&Number.isFinite(roundedAi)&&roundedAi>0&&roundedAi>=ai.acceptableTargetRange.min&&roundedAi<=ai.acceptableTargetRange.max&&aiHorizonValid&&aiStructureValid&&(current.side==='LONG'?roundedAi>current.entryPrice&&roundedAi>market.quote.ask:roundedAi<current.entryPrice&&roundedAi<market.quote.bid)),aiEconomics=aiShapeValid?this.economicsFor(current,roundedAi!):null,aiValid=Boolean(aiShapeValid&&aiEconomics&&aiEconomics.expectedNetProfit>=aiEconomics.requiredNetProfit);
    // Invalid AI targets are never nudged into profitability: fall through to structure then fixed protection.
    const deterministic=takeProfitTarget(current,market.quote.tickSize,{...this.state.settings,takeProfit:{...this.state.settings.takeProfit,mode:'STRUCTURE_15M'}} as any,market),target=aiValid?{price:roundedAi!,source:'AI' as const,reason:ai!.targetReason}:{...deterministic,source:deterministic.source==='STRUCTURE_15M'?'STRUCTURE_15M' as const:'FIXED_PROFITABLE' as const};
    this.events.publish('TP_TARGET_SELECTED',{positionId:current.id,...target,aiPlanPresent:Boolean(ai),aiPlanValid:aiValid},current.symbol);const basePrice=target.price,baseEconomics=this.economicsFor(current,basePrice);let price=basePrice,economics=baseEconomics,status:'TP_OK'|'TP_TARGET_BELOW_NET_FLOOR'|'TP_TARGET_UNREALISTIC'='TP_OK';
    if(baseEconomics.expectedNetProfit<baseEconomics.requiredNetProfit){status='TP_TARGET_BELOW_NET_FLOOR';const floor=roundToTick(baseEconomics.minProfitableExitPrice,market.quote.tickSize,current.side==='LONG'?'ceil':'floor');price=floor;economics=this.economicsFor(current,price);this.events.publish('TP_TARGET_BELOW_NET_FLOOR',{positionId:current.id,basePrice,minimumPrice:floor,requiredNetProfit:economics.requiredNetProfit,expectedNetProfit:baseEconomics.expectedNetProfit},current.symbol);}
    const liveMark=market.quote.mark;if(current.side==='LONG'&&price<=liveMark){price=roundToTick(Math.max(price,market.quote.ask+market.quote.tickSize),market.quote.tickSize,'ceil');economics=this.economicsFor(current,price);}else if(current.side==='SHORT'&&price>=liveMark){price=roundToTick(Math.min(price,market.quote.bid-market.quote.tickSize),market.quote.tickSize,'floor');economics=this.economicsFor(current,price);}
    const unreachable=current.side==='LONG'?price<=liveMark:price>=liveMark;if(unreachable||!Number.isFinite(price)||price<=0||economics.expectedNetProfit<economics.requiredNetProfit){status='TP_TARGET_UNREALISTIC';const exhausted=attempt>=5,delay=Math.min(15*60_000,60_000*2**Math.min(attempt-1,4)),nextAt=Date.now()+delay,blocked={...current,tpStatus:exhausted?'MANUAL_REVIEW_REQUIRED' as const:'REPAIR_FAILED' as const,tpOrderId:null,tpLastVerifiedAt:Date.now(),tpCoverageSource:'NONE' as const,tpEconomics:{currentTpPrice:price,expectedGrossProfit:economics.expectedGrossProfit,expectedFees:economics.estimatedTotalFee+economics.slippageBuffer+economics.feeSafetyBuffer,expectedNetProfit:economics.expectedNetProfit,requiredNetProfit:economics.requiredNetProfit,breakEvenPrice:economics.breakEvenPrice,minProfitableExitPrice:economics.minProfitableExitPrice,status}};this.state.positions.set(current.id,blocked);if(exhausted){this.retry.set(current.id,{attempt,nextAt:Date.now()+15*60_000,lastError:'TP_TARGET_UNREALISTIC'});this.events.publish('TP_MANUAL_REVIEW_REQUIRED',{positionId:current.id,attempt,price,markPrice:liveMark,reason:'TP_TARGET_UNREALISTIC'},current.symbol);}else this.retry.set(current.id,{attempt,nextAt,lastError:'TP_TARGET_UNREALISTIC'});this.events.publish('TP_TARGET_UNREALISTIC',{positionId:current.id,price,markPrice:liveMark,requiredNetProfit:economics.requiredNetProfit,expectedNetProfit:economics.expectedNetProfit,attempt,nextRetryAt:exhausted?Date.now()+15*60_000:nextAt},current.symbol);this.repairing.delete(current.id);return;}
    const now=Date.now(),tpEconomics={currentTpPrice:price,expectedGrossProfit:economics.expectedGrossProfit,expectedFees:economics.estimatedTotalFee+economics.slippageBuffer+economics.feeSafetyBuffer,expectedNetProfit:economics.expectedNetProfit,requiredNetProfit:economics.requiredNetProfit,breakEvenPrice:economics.breakEvenPrice,minProfitableExitPrice:economics.minProfitableExitPrice,status:'TP_OK' as const};this.state.positions.set(current.id,{...current,tpEconomics,profitTakePlanSource:target.source});const order:TakeProfitOrder={id:uid('tp'),clientOrderId:binanceClientOrderIdFactory.create('TP',current.id),exchangeOrderId:null,positionId:current.id,symbol:current.symbol,side:current.side==='LONG'?'SELL':'BUY',quantity:Math.max(market.quote.minQty,qty),price,status:'WORKING',createdAt:now,updatedAt:now};
    try{if(existing?.status==='WORKING'){const canceled=await this.exchange.cancelTakeProfit(existing);if(!['CANCELED','EXPIRED','REJECTED'].includes(canceled.status))throw new Error('TP_REPLACEMENT_CANCEL_UNVERIFIED');this.state.tpOrders.set(existing.id,canceled);}this.state.tpOrders.set(order.id,{...order,status:'UNKNOWN'});this.events.publish('TP_SUBMISSION_PREPARED',{positionId:current.id,order:{...order,status:'UNKNOWN'}},current.symbol);const placed=await this.exchange.placeTakeProfit(order);this.state.tpOrders.set(placed.id,placed);this.state.positions.set(current.id,{...this.state.positions.get(current.id)!,tpStatus:placed.status==='WORKING'?'PROTECTED':'PENDING',tpOrderId:placed.id,tpLastVerifiedAt:Date.now(),tpCoverageSource:'SYSTEM_CREATED'});this.retry.delete(current.id);this.events.publish('TP_PROTECTED',{positionId:current.id,order:placed,repairAttempt:attempt,tpEconomics},current.symbol);}
    catch(error){const message=error instanceof Error?error.message:String(error),submitted=this.state.tpOrders.get(order.id),rejected=submitted?.status==='UNKNOWN'&&confirmedTpSubmissionRejection(error);if(rejected){this.state.tpOrders.set(order.id,{...submitted,status:'REJECTED',updatedAt:Date.now()});this.events.publish('TP_ORDER_REJECTED',{positionId:current.id,orderId:order.id,clientOrderId:order.clientOrderId,exchangeCode:-2022,message},current.symbol);}const exhausted=attempt>=5,delay=Math.min(15*60_000,60_000*2**Math.min(attempt-1,4)),nextAt=Date.now()+delay;this.retry.set(current.id,{attempt,nextAt:exhausted?Date.now()+15*60_000:nextAt,lastError:message});const latest=this.state.positions.get(current.id);if(latest)this.state.positions.set(current.id,{...latest,tpStatus:exhausted?'MANUAL_REVIEW_REQUIRED':'REPAIR_FAILED',tpOrderId:null,tpLastVerifiedAt:Date.now(),tpCoverageSource:'NONE'});this.events.publish(exhausted?'TP_MANUAL_REVIEW_REQUIRED':'TP_REPAIR_FAILED',{positionId:current.id,orderId:order.id,clientOrderId:order.clientOrderId,submissionOutcome:rejected?'REJECTED':submitted?'UNKNOWN':'NOT_ATTEMPTED',message,attempt,nextRetryAt:exhausted?Date.now()+15*60_000:nextAt},current.symbol);}
    finally{this.repairing.delete(current.id);}
  }
  async sweep(){for(const position of this.state.positions.values())await this.ensure(position);}
}
