import {describe,it,expect} from 'vitest';
import {candidateFunnel,stage1BaselineGate,summarizeEntryQuality} from './tradingQualityBaseline.js';

describe('trading quality baseline',()=>{
  it('reports path coverage separately from quality statistics',()=>{const result=summarizeEntryQuality([{economicCompleteness:'COMPLETE_WITH_FUNDING',linkStatus:'LINKED',tradeSource:'SYSTEM',firstFillAt:1,repriceCount:1,fillToIdealBps:2,timeToPositive:{priceMs:1000,netMs:null,netStatus:'COST_INCOMPLETE'},path:[{horizonMs:30_000,sampleCount:2,maeBps:10,mfeBps:20,lastSignedBps:5}]},{economicCompleteness:'OPEN',linkStatus:'LINKED',tradeSource:'SYSTEM',firstFillAt:2,repriceCount:0,fillToIdealBps:null,timeToPositive:{priceMs:null,netMs:null,netStatus:'COST_INCOMPLETE'},path:[{horizonMs:30_000,sampleCount:0,maeBps:null,mfeBps:null,lastSignedBps:null}]}] as any);expect(result.episodeCount).toBe(2);expect(result.byHorizon['30000']).toMatchObject({coverage:{eligibleEpisodes:2,withWindow:2,withPath:1},maeBps:{count:1,median:10}});expect(result.costIncompleteCount).toBe(2);});
  it('does not hide a collapsing funnel behind a composite score',()=>{const f=candidateFunnel({candidates:100,primaryRuns:80,place:20,intents:18,orders:15,fills:3,uniqueSymbols:30});expect(f).toMatchObject({candidates:100,primaryRuns:80,place:20,intents:18,orders:15,fills:3});expect(f.orderToFill).toBeCloseTo(.2);expect(f.placeToIntent).toBeCloseTo(.9);});
  it('preserves missing funnel evidence as null instead of fabricating zero',()=>{const f=candidateFunnel({primaryRuns:10});expect(f.candidates).toBeNull();expect(f.fills).toBeNull();expect(f.candidateToPrimary).toBeNull();expect(f.orderToFill).toBeNull();});
  it('keeps the Stage 1 gate inconclusive when a mandatory baseline dimension is unavailable',()=>{expect(stage1BaselineGate({episodeCount:10,hasShortPathMarks:true,candidateSupplyAvailable:false})).toEqual({status:'INCONCLUSIVE',blockers:['ALL_CANDIDATE_SUPPLY_UNAVAILABLE']});expect(stage1BaselineGate({episodeCount:10,hasShortPathMarks:true,candidateSupplyAvailable:true})).toEqual({status:'BASELINE_READY',blockers:[]});});
});
