import {describe,expect,it} from 'vitest';
import {authorizationEconomicFacts,boundedCandidateObservationPlan,candidateShadowComparator,executableMarkout,exitQualityView,positionQualityView,selectionRegret,V393_ENTRY_ENFORCE_ENABLED,V393_PROFIT_REALIZATION_ENABLED,workingOrderSurvivalAdvisory} from './tradingQualityV393.js';
const c=(overrides:any={})=>({candidateId:'a',candidateSetId:'set1',symbol:'AAAUSDT',legal:true,selected:true,rank:1,directionAligned:true,timingVerified:true,eventAgeMs:1000,locationDistanceAtr:.2,conservativePayoffBps:30,spreadBps:2,depthUsd:10000,riskCapacity:true,observedAt:1,...overrides});

describe('V3.9.3 shadow quality views',()=>{
  it('bounds candidate observations before outcomes exist',()=>{const p=boundedCandidateObservationPlan({candidateSetId:'set1',candidates:[c(),c({candidateId:'b',symbol:'BBBUSDT',selected:false,rank:2}),c({candidateId:'c',symbol:'CCCUSDT',selected:false,rank:3})],maxCandidates:2,windowMs:60_000,observedAt:10});expect(p.planned.map(x=>x.candidateId)).toEqual(['a','b']);expect(p.excluded).toEqual([{candidateId:'c',reason:'OBSERVATION_BUDGET_EXCEEDED'}]);});
  it('keeps selection comparator shadow-only and deterministic',()=>{const rows=candidateShadowComparator([c({candidateId:'bad',symbol:'BAD',timingVerified:false,selected:true}),c({candidateId:'good',symbol:'GOOD',rank:2,selected:false})]);expect(rows[0]).toMatchObject({candidateId:'good',authorization:'NONE'});});
  it('calls selection regret opportunity quality, never imaginary PnL',()=>expect(selectionRegret({chosenCandidateId:'a',preselectedAlternativeId:'b',observedOpportunityQuality:{a:1,b:3}})).toMatchObject({opportunityRegret:2,basis:'OPPORTUNITY_QUALITY_NOT_PNL'}));
  it('separates executable ex-funding from with-funding completeness',()=>{expect(executableMarkout({side:'LONG',fillPrice:100,quantity:1,bid:100.2,ask:100.3,entryFeeUsd:.04,exitFeeBoundUsd:.05,basis:'EXECUTABLE_EX_FUNDING'}).eligible).toBe(true);expect(executableMarkout({side:'LONG',fillPrice:100,quantity:1,bid:100.2,ask:100.3,entryFeeUsd:.04,exitFeeBoundUsd:.05,fundingUsd:null,basis:'EXECUTABLE_WITH_FUNDING'}).eligible).toBe(false);});
  it('position findings never authorize a loss exit',()=>{const view=positionQualityView({cycleId:'cy',unrealizedPnl:-2,underwaterMs:20*60_000,holdingMs:30*60_000,maeBps:20,mfeBps:10,tpReachable:false,opportunityFresh:false,profitAvailable:false});expect(view.findings).toContain('LOSING_INVENTORY');expect(view.findings).toContain('STALE_OPPORTUNITY');expect(view.lossExitAuthorized).toBe(false);});
  it('does not define capture when MFE is non-positive',()=>expect(exitQualityView({cycleId:'cy',realizedNetExFunding:1,mfeSameBasis:0,exitPostMarkoutBps:{'1m':null},partialFillCount:0,feeUsd:.1}).mfeToRealizedCapture).toBeNull());
  it('never releases/resubmits UNKNOWN working-order risk',()=>expect(workingOrderSurvivalAdvisory({status:'UNKNOWN',opportunityValid:false,ttlExpired:true,cancelRequested:false,cancelAcknowledged:false,filledQuantity:0,quantity:1})).toMatchObject({advisory:'RECONCILE_ONLY',releaseReservation:false,mayResubmit:false,acceptLateFill:true}));
  it('holds reservation through cancel/fill race',()=>expect(workingOrderSurvivalAdvisory({status:'PARTIALLY_FILLED',opportunityValid:false,ttlExpired:true,cancelRequested:true,cancelAcknowledged:false,filledQuantity:.5,quantity:1})).toMatchObject({advisory:'AWAIT_CANCEL_ACK',releaseReservation:false,acceptLateFill:true}));
  it('keeps E/H hard-disabled even if profit evidence is positive',()=>{expect(V393_ENTRY_ENFORCE_ENABLED).toBe(false);expect(V393_PROFIT_REALIZATION_ENABLED).toBe(false);const x=authorizationEconomicFacts({entryFeeUsd:.1,fundingAttributedUsd:0,remainingQty:1,executablePrice:101,exitFeeUpperBoundUsd:.1,uncertaintyBufferUsd:.1,conservativeGrossPnlUsd:2,quoteFresh:true});expect(x.evidenceReady).toBe(true);expect(x.authorization).toBe('DISABLED');expect(x.reasons).toContain('POLICY_NOT_AUTHORIZED');});
});
