import {describe,it,expect} from 'vitest';
import {adverseFirst,buildEpisodeEvidence,dedupeExecutionFills,economicCompleteness,fillAnchoredPath,immediateNegativeAttribution,timeToPositive} from './tradingEpisodeEvidence.js';
const fill=(o:any={})=>({fillId:'f1',symbol:'BTCUSDT',direction:'LONG',side:'BUY',positionSide:'LONG',orderId:'ex1',clientOrderId:'c1',tradeId:'t1',executionTime:1_000,qty:1,price:100,realizedPnl:0,commission:.04,commissionAsset:'USDT',commissionUsd:.04,maker:true,source:'EXCHANGE_AUDIT',attributionStatus:'SYSTEM_ATTRIBUTED',...o});
const trade=(o:any={})=>({tradeId:'tr1',symbol:'BTCUSDT',direction:'LONG',openedAt:1_000,closedAt:10_000,durationMs:9_000,entryQty:1,exitQty:1,remainingQty:0,entryAveragePrice:100,exitAveragePrice:102,entryFee:.04,exitFee:.04,totalFee:.08,funding:null,entryGrossNotional:100,exitGrossNotional:102,marginUsed:10,netRoiOnMargin:null,netReturnOnNotional:null,entryFillCount:1,exitFillCount:1,feeBreakdown:[],grossRealizedPnl:2,tradingNetPnlExFunding:1.92,netPnl:null,pnlBasis:'CANONICAL_NET_WITH_FUNDING_UNKNOWN',fundingAttributionStatus:'UNKNOWN',closeReason:'TP',status:'CLOSED',entryRunId:'r1',entryIntentId:'i1',entryOrderIds:['o1'],exitOrderIds:['tp1'],source:'SYSTEM',regime:null,feeCompleteness:'COMPLETE',recordCompleteness:'COMPLETE',classification:'COMPLETE',canonical:true,duplicateOf:null,cycleId:'cy1',repairSource:null,linkedFillIds:['f1'],missingFacts:[],integrityFlags:[],createdAt:1_000,updatedAt:10_000,firstObservedAt:1_000,...o});
const intent={id:'i1',brainRunId:'r1',symbol:'BTCUSDT',idealPrice:99.5},exactFunding={attributionStatus:'EXACT' as const,factIds:['income1'],coverageStartAt:1_000,coverageEndAt:10_000,accountScope:'acct',cycleId:'cy1',verifiedAt:11_000};
describe('trading episode evidence',()=>{
 it('separates first and complete fill',()=>{const rows=dedupeExecutionFills([fill(),fill(),fill({fillId:'f2',tradeId:'t2',executionTime:2_000,qty:.5,price:101})] as any),ep=buildEpisodeEvidence({run:{id:'r1',symbol:'BTCUSDT'},intent,orders:[{id:'o1',intentId:'i1',symbol:'BTCUSDT',exchangeOrderId:'ex1',status:'FILLED',quantity:1.5,filledQuantity:1.5,repriceCount:2}],fills:rows as any,tradeRecords:[trade({entryQty:1.5,exitQty:1.5}) as any],marks:[]});expect(rows).toHaveLength(2);expect(ep).toMatchObject({firstFillAt:1_000,completeFillAt:2_000,economicCompleteness:'COMPLETE_EX_FUNDING',linkStatus:'LINKED'});});
 it('does not call a partial entry complete',()=>{const ep=buildEpisodeEvidence({run:{id:'r1',symbol:'BTCUSDT'},intent,orders:[{id:'o1',intentId:'i1',symbol:'BTCUSDT',exchangeOrderId:'ex1',status:'PARTIALLY_FILLED',quantity:2,filledQuantity:1.5}],fills:[fill(),fill({fillId:'f2',tradeId:'t2',executionTime:2_000,qty:.5,price:110})] as any,tradeRecords:[trade({status:'OPEN',closedAt:null,entryQty:1.5,exitQty:0,remainingQty:1.5}) as any],marks:[{ts:1_500,mark:101}]});expect(ep.completeFillAt).toBeNull();expect(ep.firstFillVwap).toBe(100);expect(ep.fillVwap).toBeCloseTo(103.333333);expect(ep.completeFillPath).toEqual([]);});
 it('opens an independent full-VWAP path',()=>{const marks=[2_000,7_000,12_000,17_000,22_000,27_000,32_000].map((ts,i)=>({ts,mark:101+i*.5})),ep=buildEpisodeEvidence({run:{id:'r1',symbol:'BTCUSDT'},intent,orders:[{id:'o1',intentId:'i1',symbol:'BTCUSDT',exchangeOrderId:'ex1',status:'FILLED',quantity:1.5,filledQuantity:1.5}],fills:[fill(),fill({fillId:'f2',tradeId:'t2',executionTime:2_000,qty:.5,price:110})] as any,tradeRecords:[],marks,now:32_000});expect(ep.schemaVersion).toBe('TQ-EPISODE-4');expect(ep.firstFillPath[0]?.horizonMs).toBe(30_000);expect(ep.firstFillPath[0]?.coverage).toBe('COMPLETE');expect(ep.completeFillPath[0]?.coverage).toBe('COMPLETE');expect(ep.firstFillPath[0]?.lastSignedBps).not.toBe(ep.completeFillPath[0]?.lastSignedBps);expect(ep.firstFillPath.map(p=>p.horizonMs)).toContain(14_400_000);});
 it('normalizes direction without leverage',()=>{const l=fillAnchoredPath({side:'LONG',fillPrice:100,fillAt:0,marks:[{ts:10_000,mark:99},{ts:20_000,mark:102}],horizonsMs:[30_000],maxGapMs:10_000,now:30_000})[0]!,s=fillAnchoredPath({side:'SHORT',fillPrice:100,fillAt:0,marks:[{ts:10_000,mark:101},{ts:20_000,mark:98}],horizonsMs:[30_000],maxGapMs:10_000,now:30_000})[0]!;expect(l.maeBps).toBeCloseTo(100);expect(s.mfeBps).toBeCloseTo(200);});
 it('does not fabricate funding/path/cost',()=>{expect(fillAnchoredPath({side:'LONG',fillPrice:100,fillAt:0,marks:[],horizonsMs:[30_000]})[0]).toMatchObject({sampleCount:0,maeBps:null});expect(economicCompleteness(trade() as any)).toBe('COMPLETE_EX_FUNDING');expect(economicCompleteness(trade({funding:.1,fundingAttributionStatus:'EXACT',pnlBasis:'CANONICAL_NET_WITH_FUNDING',netPnl:2.02}) as any,exactFunding,'acct')).toBe('COMPLETE_EX_FUNDING');expect(timeToPositive({side:'LONG',fillPrice:100,fillAt:0,marks:[{ts:1000,mark:100.2}],costBps:null}).netStatus).toBe('COST_INCOMPLETE');});
 it('uses authoritative canonical net',()=>{const ep=buildEpisodeEvidence({run:{id:'r1',symbol:'BTCUSDT'},intent,orders:[{id:'o1',intentId:'i1',symbol:'BTCUSDT',exchangeOrderId:'ex1',status:'FILLED',quantity:1,filledQuantity:1}],fills:[fill()] as any,tradeRecords:[trade({funding:.1,fundingAttributionStatus:'EXACT',pnlBasis:'CANONICAL_NET_WITH_FUNDING',netPnl:2.02}) as any],accountScope:'acct',fundingEvidenceByCycle:{cy1:exactFunding}});expect(ep.netPnl).toBeNull();expect(ep.economicEligibility.canonical.eligible).toBe(false);});
 it('rejects legacy numeric net without exact provenance',()=>{const ep=buildEpisodeEvidence({run:{id:'r1',symbol:'BTCUSDT'},intent,orders:[{id:'o1',intentId:'i1',symbol:'BTCUSDT',exchangeOrderId:'ex1',status:'FILLED',quantity:1,filledQuantity:1}],fills:[fill()] as any,tradeRecords:[trade({funding:0,netPnl:1.92,fundingAttributionStatus:undefined,pnlBasis:undefined}) as any]});expect(ep.netPnl).toBeNull();expect(ep.derivedNetPnlDiagnostic).toBe(1.92);});
 it('keeps adverse ordering ambiguous and attributes immediate loss components',()=>{expect(adverseFirst({side:'LONG',fillPrice:100,fillAt:0,marks:[{ts:1,mark:100}],adverseBoundaryBps:0,favorableBoundaryBps:0})).toBe('AMBIGUOUS');const x=immediateNegativeAttribution({side:'LONG',fillPrice:100,quantity:1,mark:99.98,bid:99.96,ask:100.02,entryFeeUsd:.04});expect(x.attributionComplete).toBe(true);expect(x.entryFeeBps).toBeCloseTo(4);});
 it('refuses approximate identity',()=>{const x=buildEpisodeEvidence({run:{id:'r1',symbol:'BTCUSDT'},intent:{id:'wrong',brainRunId:'other',symbol:'BTCUSDT'},orders:[],fills:[],tradeRecords:[]});expect(x.linkStatus).toBe('INTENT_UNKNOWN');});
});

it('does not observe positive prices beyond the first-fill window',()=>{expect(timeToPositive({side:'LONG',fillPrice:100,fillAt:0,windowEndAt:1000,marks:[{ts:1000,mark:99},{ts:1500,mark:101}],costBps:0})).toMatchObject({priceMs:null,netMs:null,netStatus:'RIGHT_CENSORED'});});
