import type {TradingQualityMetricBasis} from '@zdj/contracts';
import type {PathWindow} from './tradingEpisodeEvidence.js';
import {entryMetricEligible} from './tradingQualityEligibility.js';
const finite=(v:unknown):v is number=>typeof v==='number'&&Number.isFinite(v),pct=(from:number,to:number,side:'LONG'|'SHORT')=>(side==='LONG'?1:-1)*(to/from-1)*10_000;
export type EvidenceFlag='TRUE'|'FALSE'|'UNKNOWN';
export type CandidateShadowInput={candidateId:string;candidateSetId:string;symbol:string;legal:boolean;selected:boolean;rank:number;directionAligned:boolean|null;timingVerified:boolean|null;eventAgeMs:number|null;locationDistanceAtr:number|null;conservativePayoffBps:number|null;spreadBps:number|null;depthUsd:number|null;riskCapacity:boolean|null;observedAt:number};
export function boundedCandidateObservationPlan(input:{candidateSetId:string;candidates:CandidateShadowInput[];maxCandidates:number;windowMs:number;observedAt:number}){const legal=input.candidates.filter(c=>c.candidateSetId===input.candidateSetId&&c.legal).sort((a,b)=>a.rank-b.rank||a.symbol.localeCompare(b.symbol)),selected=legal.filter(c=>c.selected),others=legal.filter(c=>!c.selected),budget=Math.max(1,Math.floor(input.maxCandidates)),planned=[...selected,...others].slice(0,budget);return{candidateSetId:input.candidateSetId,observedAt:input.observedAt,observationUntil:input.observedAt+Math.max(1,input.windowMs),budget,planned:planned.map((row,index)=>({...row,inclusionOrder:index+1,inclusionProbability:legal.length<=budget?1:budget/legal.length})),excluded:legal.slice(budget).map(row=>({candidateId:row.candidateId,reason:'OBSERVATION_BUDGET_EXCEEDED'}))};}
/** Shadow ranking only; never an order authorization. */
export function candidateShadowComparator(rows:CandidateShadowInput[]){const unknown=(v:unknown)=>v==null||!Number.isFinite(v as number),key=(r:CandidateShadowInput)=>[r.legal?0:1,r.riskCapacity===true?0:r.riskCapacity===false?2:1,r.directionAligned===true?0:r.directionAligned===false?2:1,r.timingVerified===true?0:r.timingVerified===false?2:1,unknown(r.eventAgeMs)?Infinity:r.eventAgeMs!,unknown(r.locationDistanceAtr)?Infinity:Math.abs(r.locationDistanceAtr!),unknown(r.conservativePayoffBps)?Infinity:-r.conservativePayoffBps!,unknown(r.spreadBps)?Infinity:r.spreadBps!,unknown(r.depthUsd)?Infinity:-r.depthUsd!,r.rank,r.symbol],compare=(a:CandidateShadowInput,b:CandidateShadowInput)=>{const x=key(a),y=key(b);for(let i=0;i<x.length;i++){if(x[i]!<y[i]!)return-1;if(x[i]!>y[i]!)return 1;}return 0;};return[...rows].sort(compare).map((r,i)=>({candidateId:r.candidateId,symbol:r.symbol,shadowRank:i+1,selected:r.selected,authorization:'NONE' as const,methodVersion:'V393-SELECTION-LEX-1'}));}
export function selectionRegret(input:{chosenCandidateId:string;preselectedAlternativeId:string|null;observedOpportunityQuality:Record<string,number|null|undefined>}){const chosen=input.observedOpportunityQuality[input.chosenCandidateId],alt=input.preselectedAlternativeId?input.observedOpportunityQuality[input.preselectedAlternativeId]:null;return finite(chosen)&&finite(alt)?{status:'OBSERVED' as const,opportunityRegret:alt-chosen,chosenQuality:chosen,alternativeQuality:alt,basis:'OPPORTUNITY_QUALITY_NOT_PNL' as const}:{status:'UNKNOWN' as const,opportunityRegret:null,chosenQuality:finite(chosen)?chosen:null,alternativeQuality:finite(alt)?alt:null,basis:'OPPORTUNITY_QUALITY_NOT_PNL' as const};}
export function executableMarkout(input:{side:'LONG'|'SHORT';fillPrice:number;quantity:number;bid:number|null;ask:number|null;entryFeeUsd:number|null;exitFeeBoundUsd:number|null;fundingUsd?:number|null;basis:'EXECUTABLE_EX_FUNDING'|'EXECUTABLE_WITH_FUNDING'}){const exit=input.side==='LONG'?input.bid:input.ask,notional=input.fillPrice*input.quantity,eligibility=entryMetricEligible(input.basis as TradingQualityMetricBasis,{exactEntryAttribution:true,anchorKnown:finite(input.fillPrice)&&input.fillPrice>0,horizonMature:true,pathComplete:true,executableQuoteComplete:finite(exit)&&exit>0,entryCostComplete:finite(input.entryFeeUsd),exitCostBoundComplete:finite(input.exitFeeBoundUsd),fundingHorizonComplete:input.basis==='EXECUTABLE_EX_FUNDING'||finite(input.fundingUsd)});if(!eligibility.eligible||!finite(exit)||notional<=0)return{eligible:false,valueBps:null,reasons:eligibility.reasons};const priceMove=pct(input.fillPrice,exit,input.side),cost=((input.entryFeeUsd??0)+(input.exitFeeBoundUsd??0)-(input.basis==='EXECUTABLE_WITH_FUNDING'?(input.fundingUsd??0):0))/notional*10_000;return{eligible:true,valueBps:priceMove-cost,reasons:[]};}
export function entryQualityView(input:{episodeId:string;path:PathWindow[];eventAgeMs?:number|null;fillToIdealBps?:number|null;repriceCount?:number|null;adverseFirst?:string;timeToPositive?:{priceMs:number|null;netMs:number|null;netStatus:string};q1?:EvidenceFlag;q2?:EvidenceFlag;q3?:EvidenceFlag;q4?:EvidenceFlag;q5?:EvidenceFlag;q6?:EvidenceFlag}){const mature=input.path.filter(p=>p.coverage==='COMPLETE');return{episodeId:input.episodeId,methodVersion:'V393-ENTRY-1',horizons:mature.map(p=>({horizonMs:p.horizonMs,priceMarkoutBps:p.lastSignedBps,sampledMaeBps:p.maeBps,sampledMfeBps:p.mfeBps,sampleCount:p.sampleCount,maxGapMs:p.maxGapMs})),eventAgeMs:input.eventAgeMs??null,fillToIdealBps:input.fillToIdealBps??null,repriceCount:input.repriceCount??0,adverseFirst:input.adverseFirst??'DATA_UNAVAILABLE',timeToPositive:input.timeToPositive??null,rootCauseVector:{Q1:input.q1??'UNKNOWN',Q2:input.q2??'UNKNOWN',Q3:input.q3??'UNKNOWN',Q4:input.q4??'UNKNOWN',Q5:input.q5??'UNKNOWN',Q6:input.q6??'UNKNOWN'},authorization:'NONE' as const};}
export function positionQualityView(input:{cycleId:string;unrealizedPnl:number;underwaterMs:number;holdingMs:number;maeBps:number|null;mfeBps:number|null;tpReachable:boolean|null;opportunityFresh:boolean|null;profitAvailable:boolean|null;humanManaged?:boolean;rightCensored?:boolean;portfolioRiskOccupied?:boolean}){const f:string[]=[];if(input.unrealizedPnl<0)f.push(input.underwaterMs>15*60_000?'LOSING_INVENTORY':'UNDERWATER_NORMAL');else f.push('HEALTHY_HOLD');if(input.opportunityFresh===false)f.push('STALE_OPPORTUNITY');if(input.tpReachable===true)f.push('TP_REACHABLE');if(input.profitAvailable===true)f.push('PROFIT_AVAILABLE');if(input.humanManaged)f.push('HUMAN_HANDOFF_REQUIRED');if(input.tpReachable==null||input.opportunityFresh==null)f.push('ECONOMIC_UNKNOWN');return{cycleId:input.cycleId,findings:[...new Set(f)],holdingMs:input.holdingMs,underwaterMs:input.underwaterMs,maeBps:input.maeBps,mfeBps:input.mfeBps,rightCensored:input.rightCensored??true,humanIntervention:input.humanManaged===true,portfolioRiskOccupied:input.portfolioRiskOccupied??true,authorization:'NONE' as const,lossExitAuthorized:false};}
/** Dimensionless capture requires realized and MFE both in bps, same qty/basis/window. */
export function exitQualityView(input:{cycleId:string;realizedCaptureBps:number|null;mfeBps:number|null;realizedNetExFundingUsd:number|null;canonicalNetUsd:number|null;exitPostMarkoutBps:Record<string,number|null>;postExitReference:'FIXED_HORIZON'|'UNKNOWN';partialFillCount:number;feeUsd:number|null}){const capture=finite(input.realizedCaptureBps)&&finite(input.mfeBps)&&input.mfeBps>0?input.realizedCaptureBps/input.mfeBps:null,f:string[]=[];if(capture!=null&&capture>=.8)f.push('GOOD_CAPTURE');if(capture!=null&&capture<.5)f.push('MISSED_REALIZATION');if(finite(input.feeUsd)&&finite(input.realizedNetExFundingUsd)&&Math.abs(input.realizedNetExFundingUsd)>0&&input.feeUsd>Math.abs(input.realizedNetExFundingUsd)*.25)f.push('EXIT_COST_DRAG');if(!f.length)f.push('UNKNOWN');return{cycleId:input.cycleId,mfeToRealizedCapture:capture,captureBasis:'BPS_SAME_QTY_SAME_WINDOW' as const,realizedNetExFundingUsd:input.realizedNetExFundingUsd,canonicalNetUsd:input.canonicalNetUsd,postExitMarkoutBps:input.exitPostMarkoutBps,postExitReference:input.postExitReference,partialFillCount:input.partialFillCount,findings:f,authorization:'NONE' as const};}
export type WorkingOrderSurvivalInput={status:'NEW'|'SUBMITTING'|'UNKNOWN'|'WORKING'|'PARTIALLY_FILLED'|'FILLED'|'CANCELED'|'EXPIRED'|'REJECTED';opportunityValid:boolean|null;ttlExpired:boolean;cancelRequested:boolean;cancelAcknowledged:boolean;filledQuantity:number;quantity:number};
export function workingOrderSurvivalAdvisory(input:WorkingOrderSurvivalInput){const terminal=['FILLED','CANCELED','EXPIRED','REJECTED'].includes(input.status);if(terminal)return{advisory:'NOOP',releaseReservation:true,acceptLateFill:true,mayResubmit:false};if(input.status==='UNKNOWN')return{advisory:'RECONCILE_ONLY',releaseReservation:false,acceptLateFill:true,mayResubmit:false};if(input.cancelRequested&&!input.cancelAcknowledged)return{advisory:'AWAIT_CANCEL_ACK',releaseReservation:false,acceptLateFill:true,mayResubmit:false};if(input.ttlExpired||input.opportunityValid===false)return{advisory:'REQUEST_CANCEL',releaseReservation:false,acceptLateFill:true,mayResubmit:false};return{advisory:'KEEP_WORKING',releaseReservation:false,acceptLateFill:true,mayResubmit:false};}
export type WorkingOrderTimelineEvent={type:'SUBMIT'|'ACK'|'WORKING'|'REPRICE'|'CANCEL_REQUEST'|'CANCEL_ACK'|'PARTIAL_FILL'|'FILL'|'UNKNOWN';exchangeTime:number|null;receivedAt:number;filledQuantity:number|null;remainingQuantity:number|null;oldPrice?:number|null;newPrice?:number|null;opportunityVersion?:number|null;sourceId:string};
export function workingOrderTimelineEvidence(events:WorkingOrderTimelineEvent[]){const ordered=[...events].sort((a,b)=>(a.exchangeTime??a.receivedAt)-(b.exchangeTime??b.receivedAt)||a.receivedAt-b.receivedAt||a.sourceId.localeCompare(b.sourceId));return{events:ordered,queuePosition:'UNKNOWN' as const,exchangeTimeCoverage:{known:ordered.filter(e=>e.exchangeTime!=null).length,total:ordered.length},authorization:'NONE' as const,causalClaim:'NOT_ESTABLISHED' as const};}
export const V393_ENTRY_ENFORCE_ENABLED=false as const,V393_PROFIT_REALIZATION_ENABLED=false as const;
export function authorizationEconomicFacts(input:{entryFeeUsd:number|null;fundingAttributedUsd:number|null;remainingQty:number;executablePrice:number|null;exitFeeUpperBoundUsd:number|null;uncertaintyBufferUsd:number|null;conservativeGrossPnlUsd:number|null;quoteFresh:boolean}){const known=[input.entryFeeUsd,input.fundingAttributedUsd,input.executablePrice,input.exitFeeUpperBoundUsd,input.uncertaintyBufferUsd,input.conservativeGrossPnlUsd].every(finite),conservativeNet=known?input.conservativeGrossPnlUsd!-input.entryFeeUsd!-input.exitFeeUpperBoundUsd!+input.fundingAttributedUsd!-input.uncertaintyBufferUsd!:null,evidenceReady=known&&input.remainingQty>0&&input.quoteFresh&&conservativeNet!>0;return{evidenceReady,conservativeNet,authorization:'DISABLED' as const,featureEnabled:V393_PROFIT_REALIZATION_ENABLED,reasons:[...(!known?['ECONOMIC_FACTS_INCOMPLETE']:[]),...(input.remainingQty<=0?['NO_REMAINING_QTY']:[]),...(!input.quoteFresh?['QUOTE_STALE']:[]),...(known&&conservativeNet!<=0?['CONSERVATIVE_NET_NOT_POSITIVE']:[]),'POLICY_NOT_AUTHORIZED']};}
