import {projectTradeRecordRow} from './tradeRecordReadModel.js';
import { ExperienceSampleSchema, TradeRecordSchema, type ExperienceSample, type TradeRecord } from '@zdj/contracts';
import type { RuntimeState } from '../state/runtimeState.js';
import type { TradeAuditSnapshot, ExchangeTradeFill } from '../types.js';
import { accountCycle, cycleFills, exactCycleRecord, quantityTolerance } from './cycleAccounting.js';
import type { PositionService } from './positionService.js';

type SyncOptions={includeExternal?:boolean;repairPartial?:boolean;fillFees?:boolean;recalcNet?:boolean};
type SyncFill=ExchangeTradeFill&{clientOrderId:string;commissionUsd:number|null;source:'EXCHANGE_AUDIT'};
type Cycle={cycleId:string;symbol:string;direction:'LONG'|'SHORT';entries:SyncFill[];exits:SyncFill[];remainingQty:number};
const systemClient=(id:string)=>/^(entry_|ml_|tp_|manual_|ma_|mr_|mc_|ec[0-9]*_)/i.test(id);
const stable=(asset:string)=>['USDT','USDC','BUSD'].includes(asset.toUpperCase());
const expectedEntry=(direction:'LONG'|'SHORT')=>direction==='LONG'?'BUY':'SELL';

export interface TradeSyncPreview {window:TradeAuditSnapshot['window'];maxFills:number;fills:number;systemFills:number;externalFills:number;cyclesDetected:number;existingComplete:number;repairablePartial:number;newComplete:number;newPartial:number;duplicates:number;conflicts:number;unclosable:number;experienceChanges:number;cyclePlans:Array<{cycleId:string;symbol:string;direction:'LONG'|'SHORT';entryFills:number;exitFills:number;closed:boolean;feesComplete:boolean;action:'SKIP_COMPLETE'|'SKIP_PARTIAL'|'REPAIR_PARTIAL'|'CREATE_COMPLETE'|'CREATE_PARTIAL'|'UNCLOSABLE'}>}

export class TradeRecordSyncService {
  constructor(private state:RuntimeState,private positions:PositionService){}
  private normalize(audit:TradeAuditSnapshot):{fills:SyncFill[];external:SyncFill[]} {
    const orders=new Map(audit.orders.map(order=>[order.orderId,order])),income=new Map(audit.income.filter(row=>row.incomeType==='COMMISSION'&&row.tradeId).map(row=>[row.tradeId!,row]));
    const all=audit.fills.map(raw=>{const order=orders.get(raw.orderId),commission=income.get(raw.tradeId),asset=commission?.asset??raw.commissionAsset,amount=commission?Math.abs(commission.income):Math.abs(raw.commission);return{...raw,fillId:`exchange_${raw.symbol}_${raw.tradeId}`,clientOrderId:raw.clientOrderId||order?.clientOrderId||'',commission:amount,commissionAsset:asset,commissionUsd:stable(asset)?amount:null,source:'EXCHANGE_AUDIT' as const};});
    return{fills:all.filter(fill=>systemClient(fill.clientOrderId)),external:all.filter(fill=>!systemClient(fill.clientOrderId))};
  }
  private cycles(fills:SyncFill[]){
    const byId=new Map<string,Cycle>();let unclosable=0;
    for(const fill of fills){
      const record=exactCycleRecord(this.state,fill);
      // An exchange audit with no durable exit-order owner is evidence to retain,
      // never permission to reconstruct a cycle from symbol/time ordering.
      if(!record?.cycleId){unclosable++;continue;}
      let cycle=byId.get(record.cycleId);
      if(!cycle){
        const retained=cycleFills(this.state,record).map(f=>({...f,source:'EXCHANGE_AUDIT' as const})) as SyncFill[];
        cycle={cycleId:record.cycleId,symbol:record.symbol,direction:record.direction,entries:retained.filter(f=>f.side===expectedEntry(record.direction)),exits:retained.filter(f=>f.side!==expectedEntry(record.direction)),remainingQty:0};byId.set(record.cycleId,cycle);
      }
      const rows=fill.side===expectedEntry(cycle.direction)?cycle.entries:cycle.exits,index=rows.findIndex(f=>f.tradeId===fill.tradeId);
      if(index>=0)rows[index]=fill;else rows.push(fill);
    }
    for(const cycle of byId.values()){
      cycle.entries.sort((a,b)=>a.executionTime-b.executionTime);cycle.exits.sort((a,b)=>a.executionTime-b.executionTime);
      cycle.remainingQty=cycle.entries.reduce((n,f)=>n+f.qty,0)-cycle.exits.reduce((n,f)=>n+f.qty,0);
    }
    return{cycles:[...byId.values()].filter(c=>c.entries.length>0),unclosable:unclosable+[...byId.values()].filter(c=>!c.entries.length).length};
  }
  private matches(cycle:Cycle){const fillIds=new Set([...cycle.entries,...cycle.exits].map(fill=>`exchange_${fill.symbol}_${fill.tradeId}`)),orders=new Set([...cycle.entries,...cycle.exits].map(fill=>fill.orderId));return[...this.state.tradeRecords.values()].filter(record=>record.symbol===cycle.symbol&&(record.cycleId===cycle.cycleId||record.tradeId===this.tradeId(cycle)||record.linkedFillIds.some(id=>fillIds.has(id))||[...record.entryOrderIds,...record.exitOrderIds].some(id=>orders.has(id))));}
  private existing(cycle:Cycle){return this.matches(cycle).filter(record=>record.duplicateOf==null).sort((a,b)=>(a.tradeId.startsWith('trade_exchange_')?-1:0)-(b.tradeId.startsWith('trade_exchange_')?-1:0)||Number(b.canonical)-Number(a.canonical))[0];}
  private tradeId(cycle:Cycle){return`trade_${cycle.cycleId}`;}
  private plan(cycle:Cycle,options:SyncOptions={}):'SKIP_COMPLETE'|'SKIP_PARTIAL'|'REPAIR_PARTIAL'|'CREATE_COMPLETE'|'CREATE_PARTIAL'|'UNCLOSABLE'{const existing=this.existing(cycle),closed=Math.abs(cycle.remainingQty)<=quantityTolerance(cycle.entries.reduce((n,f)=>n+f.qty,0)),fees=[...cycle.entries,...cycle.exits].every(fill=>fill.commissionUsd!==null);if(!closed)return'UNCLOSABLE';if(existing?.classification==='COMPLETE')return'SKIP_COMPLETE';if(existing&&!options.repairPartial)return'SKIP_PARTIAL';if(existing)return'REPAIR_PARTIAL';return fees?'CREATE_COMPLETE':'CREATE_PARTIAL';}
  preview(audit:TradeAuditSnapshot,maxFills:number,options:SyncOptions={}):TradeSyncPreview{
    const normalized=this.normalize(audit),fills=options.includeExternal?[...normalized.fills,...normalized.external]:normalized.fills,{cycles,unclosable}=this.cycles(fills),plans=cycles.map(cycle=>{const action=this.plan(cycle,options);return{cycleId:cycle.cycleId,symbol:cycle.symbol,direction:cycle.direction,entryFills:cycle.entries.length,exitFills:cycle.exits.length,closed:Math.abs(cycle.remainingQty)<=quantityTolerance(cycle.entries.reduce((n,f)=>n+f.qty,0)),feesComplete:[...cycle.entries,...cycle.exits].every(fill=>fill.commissionUsd!==null),action};});
    return{window:audit.window,maxFills,fills:fills.length,systemFills:normalized.fills.length,externalFills:normalized.external.length,cyclesDetected:cycles.length,existingComplete:plans.filter(x=>x.action==='SKIP_COMPLETE').length,repairablePartial:plans.filter(x=>x.action==='REPAIR_PARTIAL').length,newComplete:plans.filter(x=>x.action==='CREATE_COMPLETE').length,newPartial:plans.filter(x=>x.action==='CREATE_PARTIAL').length,duplicates:0,conflicts:0,unclosable:unclosable+plans.filter(x=>x.action==='UNCLOSABLE').length,experienceChanges:plans.filter(x=>['CREATE_COMPLETE','REPAIR_PARTIAL'].includes(x.action)&&x.feesComplete).length,cyclePlans:plans};
  }
  private buildRecord(cycle:Cycle,existing:TradeRecord|undefined):TradeRecord{
    const all=[...cycle.entries,...cycle.exits],entryQty=cycle.entries.reduce((sum,fill)=>sum+fill.qty,0),exitQty=cycle.exits.reduce((sum,fill)=>sum+fill.qty,0),entryNotional=cycle.entries.reduce((sum,fill)=>sum+fill.qty*fill.price,0),exitNotional=cycle.exits.reduce((sum,fill)=>sum+fill.qty*fill.price,0),feesComplete=all.every(fill=>fill.commissionUsd!==null),gross=cycle.exits.reduce((sum,fill)=>sum+fill.realizedPnl,0),entryFee=feesComplete?cycle.entries.reduce((sum,fill)=>sum+(fill.commissionUsd??0),0):null,exitFee=feesComplete?cycle.exits.reduce((sum,fill)=>sum+(fill.commissionUsd??0),0):null,net=feesComplete?gross-(entryFee??0)-(exitFee??0):null,openedAt=cycle.entries[0]!.executionTime,closedAt=cycle.exits.at(-1)!.executionTime,missing=feesComplete?[]:['FEE_FACT'],id=existing?.tradeId??this.tradeId(cycle);
    const external=all.every(fill=>!systemClient(fill.clientOrderId)),classification=external?'EXTERNAL':feesComplete?'COMPLETE':'PARTIAL';
    const marginUsed=existing?.marginUsed??null,netRoiOnMargin=net!=null&&marginUsed?net/marginUsed*100:null;
    const raw=TradeRecordSchema.parse({...existing,tradeId:id,symbol:cycle.symbol,direction:cycle.direction,openedAt,closedAt,durationMs:Math.max(0,closedAt-openedAt),entryQty,entryAveragePrice:entryNotional/entryQty,exitAveragePrice:exitNotional/Math.max(exitQty,1),entryFee,exitFee,totalFee:feesComplete?(entryFee??0)+(exitFee??0):null,funding:existing?.funding??null,entryGrossNotional:entryNotional,exitGrossNotional:exitNotional,marginUsed,netRoiOnMargin,netReturnOnNotional:net!=null&&exitNotional?net/exitNotional*100:null,entryFillCount:cycle.entries.length,exitFillCount:cycle.exits.length,feeBreakdown:all.map(fill=>({stage:cycle.entries.includes(fill)?'ENTRY' as const:'EXIT' as const,asset:fill.commissionAsset,amount:fill.commission,usd:fill.commissionUsd,conversionSource:fill.commissionUsd===null?null:stable(fill.commissionAsset)?'STABLE_ASSET':'MARKET_QUOTE'})),grossRealizedPnl:gross,netPnl:net,closeReason:cycle.exits.some(fill=>/^tp_/i.test(fill.clientOrderId))?'TP':'MANUAL',status:'CLOSED',entryRunId:existing?.entryRunId??null,entryIntentId:existing?.entryIntentId??cycle.entries[0]!.clientOrderId,entryOrderIds:[...new Set(cycle.entries.map(fill=>fill.orderId))],exitOrderIds:[...new Set(cycle.exits.map(fill=>fill.orderId))],source:external?'EXTERNAL':'LOCAL_LIFECYCLE_REPAIR_FROM_EXCHANGE_FACT',regime:existing?.regime??null,feeCompleteness:feesComplete?'COMPLETE':'PARTIAL',recordCompleteness:feesComplete?'COMPLETE':'PARTIAL',classification,canonical:!external,duplicateOf:null,cycleId:cycle.cycleId,repairSource:external?'EXTERNAL_AUDIT':'MANUAL_TRADE_SYNC',linkedFillIds:all.map(fill=>`exchange_${fill.symbol}_${fill.tradeId}`),missingFacts:missing,integrityFlags:[...(existing?.integrityFlags??[]).filter(flag=>!['FILL_CONSERVATION_FAILED','CLOSED_NO_EXIT_FACT'].includes(flag)),'REPAIRED_FROM_EXCHANGE_FILL_FACTS'],createdAt:existing?.createdAt??openedAt,updatedAt:Date.now(),firstObservedAt:existing?.firstObservedAt??openedAt});
    return accountCycle(raw,all.map(f=>({...f,direction:cycle.direction,attributionStatus:'SYSTEM_ATTRIBUTED' as const})));
  }
  private repairOpenEntry(cycle:Cycle,existing:TradeRecord):TradeRecord{
    return accountCycle(existing,[...cycle.entries,...cycle.exits].map(fill=>({...fill,direction:cycle.direction,cycleId:cycle.cycleId,attributionStatus:'SYSTEM_ATTRIBUTED' as const})));
  }
  apply(audit:TradeAuditSnapshot,maxFills:number,options:SyncOptions={}):{preview:TradeSyncPreview;created:number;repaired:number;skipped:number;newComplete:number;newPartial:number;experienceCreated:number;records:TradeRecord[];samples:ExperienceSample[]}{
    const preview=this.preview(audit,maxFills,options),normalized=this.normalize(audit),{cycles}=this.cycles(options.includeExternal?[...normalized.fills,...normalized.external]:normalized.fills),records:TradeRecord[]=[],samples:ExperienceSample[]=[];let created=0,repaired=0,skipped=0,newComplete=0,newPartial=0,experienceCreated=0;
    for(const cycle of cycles){const action=this.plan(cycle,options),existing=this.existing(cycle);if(action==='UNCLOSABLE'){if(options.repairPartial&&existing&&existing.status!=='CLOSED'&&!existing.observedClosedAt&&cycle.entries.length){const record=this.repairOpenEntry(cycle,existing);for(const fill of [...cycle.entries,...cycle.exits])this.state.recordExecutionFill({...fill,cycleId:cycle.cycleId,attributionStatus:'SYSTEM_ATTRIBUTED',direction:cycle.direction,positionSide:fill.positionSide==='BOTH'?cycle.direction:fill.positionSide,source:'EXCHANGE_AUDIT'});this.state.tradeRecords.set(record.tradeId,record);records.push(record);repaired++;}continue;}if(action==='SKIP_COMPLETE'||action==='SKIP_PARTIAL'){skipped++;continue;}const record=this.buildRecord(cycle,existing);for(const fill of [...cycle.entries,...cycle.exits])this.state.recordExecutionFill({...fill,cycleId:cycle.cycleId,attributionStatus:'SYSTEM_ATTRIBUTED',direction:cycle.direction,positionSide:fill.positionSide==='BOTH'?cycle.direction:fill.positionSide,source:'EXCHANGE_AUDIT'});this.state.tradeRecords.set(record.tradeId,record);for(const duplicate of this.matches(cycle).filter(row=>row.tradeId!==record.tradeId)){const superseded=TradeRecordSchema.parse({...duplicate,canonical:false,duplicateOf:record.tradeId,classification:'DUPLICATE',repairSource:'MANUAL_TRADE_SYNC',missingFacts:[...new Set([...duplicate.missingFacts,'SUPERSEDED_BY_EXCHANGE_FACT_REPAIR'])],integrityFlags:[...new Set([...duplicate.integrityFlags,'SUPERSEDED_BY_EXCHANGE_FACT_REPAIR'])],updatedAt:Date.now()});this.state.tradeRecords.set(superseded.tradeId,superseded);this.state.experienceSamples.delete(`sample_${superseded.tradeId}`);}records.push(record);if(existing)repaired++;else{created++;if(record.classification==='COMPLETE')newComplete++;else newPartial++;}if(projectTradeRecordRow(record,{learningContext:this.state}).economicEligibility.canonicalPnlEligible&&record.netPnl!=null&&!this.state.experienceSamples.has(`sample_${record.tradeId}`)){const sample=ExperienceSampleSchema.parse({sampleId:`sample_${record.tradeId}`,tradeId:record.tradeId,symbol:record.symbol,direction:record.direction,regime:record.regime,netPnl:record.netPnl??0,winLoss:(record.netPnl??0)>0?'WIN':(record.netPnl??0)<0?'LOSS':'FLAT',fillDelayMs:null,holdingDurationMs:record.durationMs,lesson:'手动同步以交易所成交事实重算净收益',mistakeTags:(record.netPnl??0)<0?['NEGATIVE_NET_PNL']:[],successTags:(record.netPnl??0)>0?['NET_PROFIT_COMPLETED']:[],createdAt:record.closedAt??Date.now()});this.state.experienceSamples.set(sample.sampleId,sample);samples.push(sample);experienceCreated++;}}
    return{preview,created,repaired,skipped,newComplete,newPartial,experienceCreated,records,samples};
  }
}
