import {describe,expect,it} from 'vitest';
import type {TradeRecord} from '@zdj/contracts';
import {filterFormalOutcome,projectTradeRecordRow,projectTradeRecordSummary} from './tradeRecordReadModel.js';

const row=(overrides:Partial<TradeRecord>={}):TradeRecord=>({tradeId:'t',symbol:'BTCUSDT',direction:'LONG',openedAt:1,closedAt:2,durationMs:1,entryQty:1,exitQty:1,remainingQty:0,entryAveragePrice:100,exitAveragePrice:101,entryFee:.04,exitFee:.04,totalFee:.08,funding:null,entryGrossNotional:100,exitGrossNotional:101,marginUsed:10,netRoiOnMargin:null,netReturnOnNotional:null,entryFillCount:1,exitFillCount:1,feeBreakdown:[],grossRealizedPnl:1,tradingNetPnlExFunding:.92,netPnl:null,closeReason:'TP',status:'CLOSED',entryRunId:'r',entryIntentId:'i',entryOrderIds:['o'],exitOrderIds:['x'],source:'SYSTEM',regime:null,feeCompleteness:'COMPLETE',recordCompleteness:'COMPLETE',classification:'COMPLETE',canonical:true,duplicateOf:null,cycleId:'cy',repairSource:null,linkedFillIds:['f1','f2'],missingFacts:[],integrityFlags:[],createdAt:1,updatedAt:2,firstObservedAt:1,fundingAttributionStatus:'UNKNOWN',pnlBasis:'CANONICAL_NET_WITH_FUNDING_UNKNOWN',...overrides});

describe('A2 trade record read model',()=>{
  it('does not call funding-only incompleteness ledger reconciliation',()=>{const summary=projectTradeRecordSummary({records:[row()],asOf:3});expect(summary.closedCompleteCount).toBe(1);expect(summary.awaitingReconciliation).toBe(0);expect(summary.fundingUnknownCount).toBe(1);expect(summary.completed).toBe(0);expect(summary.canonicalNetPnl).toBeNull();expect(summary.canonicalNetPnlStatus).toBe('NO_ELIGIBLE_SAMPLES');expect(summary.tradingNetExFunding).toBe(.92);expect(summary.localTradingNetExFunding).toBe(.92);expect(summary.localConfirmedNetPnl).toBe(.92);expect(summary.localConfirmedFunding).toBe(0);expect(summary.localProfitCoverageStatus).toBe('PARTIAL');expect(summary.netPnl).toBeNull();});
  it('adds only exact local funding to the local confirmed subtotal',()=>{const exact=row({funding:.03,fundingAttributionStatus:'EXACT',netPnl:.95,pnlBasis:'CANONICAL_NET_WITH_FUNDING'});const summary=projectTradeRecordSummary({records:[exact]});expect(summary.localConfirmedFunding).toBeCloseTo(.03,10);expect(summary.localConfirmedNetPnl).toBeCloseTo(.95,10);expect(summary.localProfitCoverageStatus).toBe('EXACT');});
  it('excludes exchange/external trade records from the local confirmed subtotal',()=>{const local=row({tradeId:'local',source:'SYSTEM',tradingNetPnlExFunding:.92}),external=row({tradeId:'external',cycleId:'ext',source:'EXTERNAL',tradingNetPnlExFunding:50,entryOrderIds:['ext-entry'],exitOrderIds:['ext-exit'],linkedFillIds:['ext-f1','ext-f2']});const summary=projectTradeRecordSummary({records:[local,external]});expect(summary.tradingNetExFunding).toBe(50.92);expect(summary.localTradingNetExFunding).toBe(.92);expect(summary.localConfirmedNetPnl).toBe(.92);});
  it('keeps missing manifest unknown instead of reporting a complete zero cohort',()=>expect(projectTradeRecordSummary({records:[row()]}).prospective).toMatchObject({status:'MANIFEST_UNAVAILABLE',entryCycleCount:null,closedCycleCount:null}));
  it('quarantines legacy raw net from formal row display and WIN/LOSS filtering',()=>{const legacy=row({netPnl:4.2,fundingAttributionStatus:undefined,pnlBasis:undefined});const projected=projectTradeRecordRow(legacy);expect(projected.rawNetPnl).toBe(4.2);expect(projected.netPnl).toBeNull();expect(projected.formalNetPnl).toBeNull();expect(projected.formalNetPnlStatus).toBe('LEGACY_ECONOMIC_SEMANTICS_INCONSISTENT');expect(filterFormalOutcome([projected],'WIN')).toHaveLength(0);});
  it('separates ledger failures from funding unknown',()=>{const incomplete=row({classification:'PARTIAL',recordCompleteness:'PARTIAL',exitFillCount:0,exitQty:0,remainingQty:1,exitAveragePrice:null,totalFee:null});const summary=projectTradeRecordSummary({records:[incomplete]});expect(summary.closedCompleteCount).toBe(0);expect(summary.awaitingReconciliation).toBe(1);expect(summary.fundingUnknownCount).toBe(0);});
});
