import { describe, expect, it } from 'vitest';
import { TradeRecordSchema } from '@zdj/contracts';
import { RuntimeState } from '../state/runtimeState.js';
import { TradeRecordIntegrityService } from './tradeRecordIntegrityService.js';

const settings={portfolio:{maxPositions:4,maxPendingEntries:4},takeProfit:{enabled:true,quantityPercent:100}} as any;
const base=(overrides:any={})=>TradeRecordSchema.parse({tradeId:'trade_bad',symbol:'INJUSDT',direction:'LONG',openedAt:1,closedAt:2,durationMs:1,entryQty:1,entryAveragePrice:2,exitAveragePrice:3,entryFee:1,exitFee:1,totalFee:2,funding:null,entryGrossNotional:2,exitGrossNotional:3,marginUsed:1,netRoiOnMargin:100,netReturnOnNotional:10,entryFillCount:1,exitFillCount:1,feeBreakdown:[],grossRealizedPnl:1,netPnl:1,closeReason:'TP',status:'CLOSED',entryRunId:null,entryIntentId:null,entryOrderIds:['entry_1'],exitOrderIds:['tp_1'],source:'RECONCILIATION',regime:null,feeCompleteness:'COMPLETE',recordCompleteness:'COMPLETE',createdAt:1,updatedAt:2,firstObservedAt:1,...overrides});

describe('TradeRecord integrity classification',()=>{
  it('requires exact exchange fill conservation and excludes a bad COMPLETE from Experience',()=>{const state=new RuntimeState(settings),record=base({symbol:'币安人生USDT',direction:'SHORT',entryQty:46,entryFillCount:4,exitFillCount:1,entryOrderIds:['879248947'],exitOrderIds:['manual-close'],linkedFillIds:['f1','f2','f3','f4','f5','f6']});state.tradeRecords.set(record.tradeId,record);state.experienceSamples.set('sample_trade_bad',{sampleId:'sample_trade_bad',tradeId:'trade_bad'} as any);const entry=[11,10,15,16,5].map((qty,i)=>({fillId:`f${i+1}`,symbol:'币安人生USDT',direction:'SHORT',side:'SELL',positionSide:'SHORT',orderId:'879248947',clientOrderId:'entry_x',tradeId:`e${i}`,executionTime:i+1,qty,price:1,realizedPnl:0,commission:0,commissionAsset:'USDT',commissionUsd:0,maker:true,source:'EXCHANGE_AUDIT',attributionStatus:'SYSTEM_ATTRIBUTED'}));state.executionFills=[...entry,{fillId:'f6',symbol:'币安人生USDT',direction:'SHORT',side:'BUY',positionSide:'SHORT',orderId:'manual-close',clientOrderId:'manual_x',tradeId:'x',executionTime:7,qty:57,price:1,realizedPnl:0,commission:0,commissionAsset:'USDT',commissionUsd:0,maker:true,source:'EXCHANGE_AUDIT',attributionStatus:'SYSTEM_ATTRIBUTED'}] as any;new TradeRecordIntegrityService(state).classifyAll();const row=state.tradeRecords.get('trade_bad')!;expect(row.classification).toBe('PARTIAL');expect(row.missingFacts).toContain('EXCHANGE_FILL_CONSERVATION');expect(state.experienceSamples.has('sample_trade_bad')).toBe(false);});
  it('does not accept a CLOSED record without exit facts or a sentinel ROI',()=>{const state=new RuntimeState(settings);state.tradeRecords.set('trade_bad',base({exitAveragePrice:null,exitGrossNotional:0,exitFillCount:0,netRoiOnMargin:2000}));const summary=new TradeRecordIntegrityService(state).classifyAll();const row=state.tradeRecords.get('trade_bad')!;expect(row.classification).toBe('INVALID');expect(row.netPnl).toBeNull();expect(row.netRoiOnMargin).toBeNull();expect(row.missingFacts).toContain('EXIT_FACT');expect(summary.invalidClosed).toBe(1);expect(summary.invalidRoi).toBe(1);});
  it('keeps unknown fees and net PnL unknown',()=>{const state=new RuntimeState(settings);state.tradeRecords.set('trade_bad',base({feeCompleteness:'UNKNOWN',recordCompleteness:'PARTIAL'}));new TradeRecordIntegrityService(state).classifyAll();const row=state.tradeRecords.get('trade_bad')!;expect(row.entryFee).toBeNull();expect(row.exitFee).toBeNull();expect(row.totalFee).toBeNull();expect(row.netPnl).toBeNull();expect(row.classification).toBe('PARTIAL');});
  it('deduplicates legacy/canonical fill ids and clears repaired stale integrity flags',()=>{const state=new RuntimeState(settings),record=base({entryOrderIds:['164160367'],exitOrderIds:['164160867'],linkedFillIds:['ARBUSDC:59876433','exchange_ARBUSDC_59876433','exchange_ARBUSDC_59877326'],missingFacts:['EXCHANGE_FILL_CONSERVATION','MARGIN_FACT'],integrityFlags:['FILL_CONSERVATION_FAILED','CLOSED_NO_EXIT_FACT']});state.tradeRecords.set(record.tradeId,record);const entry={fillId:'ARBUSDC:59876433',symbol:'ARBUSDC',direction:'LONG',side:'BUY',positionSide:'LONG',orderId:'164160367',tradeId:'59876433',qty:1,price:2},duplicate={...entry,fillId:'exchange_ARBUSDC_59876433'},exit={...entry,fillId:'exchange_ARBUSDC_59877326',side:'SELL',orderId:'164160867',tradeId:'59877326',price:3};state.executionFills=[entry,duplicate,exit] as any;const summary=new TradeRecordIntegrityService(state).classifyAll(),row=state.tradeRecords.get('trade_bad')!;expect(summary.complete).toBe(1);expect(row.classification).toBe('COMPLETE');expect(row.missingFacts).toEqual([]);expect(row.integrityFlags).not.toContain('FILL_CONSERVATION_FAILED');expect(row.integrityFlags).not.toContain('CLOSED_NO_EXIT_FACT');});
  it('keeps a fill/PnL-conserved trade COMPLETE when only margin-based ROI is unavailable',()=>{const state=new RuntimeState(settings),record=base({marginUsed:null,netRoiOnMargin:null,linkedFillIds:['entry','exit']});state.tradeRecords.set(record.tradeId,record);state.executionFills=[{fillId:'entry',symbol:'INJUSDT',direction:'LONG',side:'BUY',positionSide:'LONG',orderId:'entry_1',clientOrderId:'entry_x',tradeId:'1',executionTime:1,qty:1,price:2,realizedPnl:0,commission:1,commissionAsset:'USDT',commissionUsd:1,maker:true,source:'EXCHANGE_AUDIT',attributionStatus:'SYSTEM_ATTRIBUTED'},{fillId:'exit',symbol:'INJUSDT',direction:'LONG',side:'SELL',positionSide:'LONG',orderId:'tp_1',clientOrderId:'tp_x',tradeId:'2',executionTime:2,qty:1,price:3,realizedPnl:1,commission:1,commissionAsset:'USDT',commissionUsd:1,maker:true,source:'EXCHANGE_AUDIT',attributionStatus:'SYSTEM_ATTRIBUTED'}] as any;const summary=new TradeRecordIntegrityService(state).classifyAll();const row=state.tradeRecords.get('trade_bad')!;expect(row.classification).toBe('COMPLETE');expect(row.missingFacts).not.toContain('MARGIN_FACT');expect(row.netRoiOnMargin).toBeNull();expect(summary.missingMargin).toBe(1);});
});
