import {describe,it,expect} from 'vitest';
import {adverseFirst,buildEpisodeEvidence,dedupeExecutionFills,economicCompleteness,fillAnchoredPath,immediateNegativeAttribution,timeToPositive} from './tradingEpisodeEvidence.js';

const fill=(overrides:any={})=>({fillId:'f1',symbol:'BTCUSDT',direction:'LONG',side:'BUY',positionSide:'LONG',orderId:'ex1',clientOrderId:'c1',tradeId:'t1',executionTime:1_000,qty:1,price:100,realizedPnl:0,commission:.04,commissionAsset:'USDT',commissionUsd:.04,maker:true,source:'EXCHANGE_AUDIT',attributionStatus:'SYSTEM_ATTRIBUTED',...overrides});
const trade=(overrides:any={})=>({tradeId:'tr1',symbol:'BTCUSDT',direction:'LONG',openedAt:1_000,closedAt:10_000,durationMs:9_000,entryQty:1,entryAveragePrice:100,exitAveragePrice:102,entryFee:.04,exitFee:.04,totalFee:.08,funding:null,entryGrossNotional:100,exitGrossNotional:102,marginUsed:10,netRoiOnMargin:19.2,netReturnOnNotional:.0192,entryFillCount:1,exitFillCount:1,feeBreakdown:[],grossRealizedPnl:2,netPnl:1.92,closeReason:'TP',status:'CLOSED',entryRunId:'r1',entryIntentId:'i1',entryOrderIds:['o1'],exitOrderIds:['tp1'],source:'SYSTEM',regime:null,feeCompleteness:'COMPLETE',recordCompleteness:'COMPLETE',classification:'COMPLETE',canonical:true,duplicateOf:null,cycleId:'cy1',repairSource:null,linkedFillIds:['f1'],missingFacts:[],integrityFlags:[],createdAt:1_000,updatedAt:10_000,firstObservedAt:1_000,...overrides});
const intent={id:'i1',brainRunId:'r1',symbol:'BTCUSDT',idealPrice:99.5};

describe('trading episode evidence',()=>{
  it('deduplicates by exchange identity and separates first from complete fill',()=>{const rows=dedupeExecutionFills([fill(),fill(),fill({fillId:'f2',tradeId:'t2',executionTime:2_000,qty:.5,price:101})] as any);expect(rows).toHaveLength(2);const episode=buildEpisodeEvidence({run:{id:'r1',symbol:'BTCUSDT'},intent,orders:[{id:'o1',intentId:'i1',symbol:'BTCUSDT',exchangeOrderId:'ex1',status:'FILLED',quantity:1.5,filledQuantity:1.5,repriceCount:2}],fills:rows as any,tradeRecords:[trade({entryQty:1.5}) as any],marks:[]});expect(episode).toMatchObject({firstFillAt:1_000,completeFillAt:2_000,repriceCount:2,tradeId:'tr1',cycleId:'cy1',economicCompleteness:'COMPLETE_EX_FUNDING',linkStatus:'LINKED'});});
  it('does not call a partial entry complete or rewrite first-fill path with later VWAP',()=>{const episode=buildEpisodeEvidence({run:{id:'r1',symbol:'BTCUSDT'},intent,orders:[{id:'o1',intentId:'i1',symbol:'BTCUSDT',exchangeOrderId:'ex1',status:'PARTIALLY_FILLED',quantity:2,filledQuantity:1.5}],fills:[fill(),fill({fillId:'f2',tradeId:'t2',executionTime:2_000,qty:.5,price:110})] as any,tradeRecords:[trade({status:'OPEN',closedAt:null,entryQty:1.5}) as any],marks:[{ts:1_500,mark:101}]});expect(episode.completeFillAt).toBeNull();expect(episode.firstFillVwap).toBe(100);expect(episode.fillVwap).toBeCloseTo(103.333333);expect(episode.path[0]).toMatchObject({coverage:'SPARSE',mfeBps:null});});
  it('computes direction-normalized fill path without leverage',()=>{const long=fillAnchoredPath({side:'LONG',fillPrice:100,fillAt:0,marks:[{ts:10_000,mark:99},{ts:20_000,mark:102}],horizonsMs:[30_000],maxGapMs:10_000,now:30_000})[0]!,short=fillAnchoredPath({side:'SHORT',fillPrice:100,fillAt:0,marks:[{ts:10_000,mark:101},{ts:20_000,mark:98}],horizonsMs:[30_000],maxGapMs:10_000,now:30_000})[0]!;expect(long.maeBps).toBeCloseTo(100);expect(long.mfeBps).toBeCloseTo(200);expect(short.maeBps).toBeCloseTo(100);expect(short.mfeBps).toBeCloseTo(200);});
  it('does not fabricate missing path, funding, or cost completeness',()=>{expect(fillAnchoredPath({side:'LONG',fillPrice:100,fillAt:0,marks:[],horizonsMs:[30_000]})[0]).toMatchObject({sampleCount:0,maeBps:null,mfeBps:null});expect(economicCompleteness(trade() as any)).toBe('COMPLETE_EX_FUNDING');expect(economicCompleteness(trade({funding:.1}) as any)).toBe('COMPLETE_WITH_FUNDING');expect(timeToPositive({side:'LONG',fillPrice:100,fillAt:0,marks:[{ts:1_000,mark:100.2}],costBps:null}).netStatus).toBe('COST_INCOMPLETE');});
  it('keeps adverse ordering ambiguous when both boundaries first appear at the same observation',()=>{expect(adverseFirst({side:'LONG',fillPrice:100,fillAt:0,marks:[{ts:1,mark:100}],adverseBoundaryBps:0,favorableBoundaryBps:0})).toBe('AMBIGUOUS');expect(adverseFirst({side:'LONG',fillPrice:100,fillAt:0,marks:[],adverseBoundaryBps:10,favorableBoundaryBps:10})).toBe('DATA_UNAVAILABLE');});
  it('attributes immediate executable loss without calling all of it timing failure',()=>{const x=immediateNegativeAttribution({side:'LONG',fillPrice:100,quantity:1,mark:99.98,bid:99.96,ask:100.02,entryFeeUsd:.04});expect(x.attributionComplete).toBe(true);expect(x.fillToMarkBps).toBeLessThan(0);expect(x.markToExecutableBps).toBeLessThan(0);expect(x.entryFeeBps).toBeCloseTo(4);});
  it('refuses approximate attribution when exact run-intent identity is absent',()=>{const x=buildEpisodeEvidence({run:{id:'r1',symbol:'BTCUSDT'},intent:{id:'wrong',brainRunId:'other',symbol:'BTCUSDT'},orders:[],fills:[],tradeRecords:[]});expect(x.linkStatus).toBe('INTENT_UNKNOWN');expect(x.tradeId).toBeNull();});
});
