import {describe,expect,it} from 'vitest';
import type {TradingQualityExperimentManifest} from '@zdj/contracts';
import {TradingQualityV393EvidenceStore} from './tradingQualityV393EvidenceStore.js';
import type {CandidateShadowInput} from './tradingQualityV393.js';
const manifest=(o:Partial<TradingQualityExperimentManifest>={}):TradingQualityExperimentManifest=>({experimentId:'exp-v393-1',environment:'TESTNET',accountScope:'acct-hash',codeHead:'9db99885043e',configHash:'config123',policyVersion:'V393-SHADOW-1',metricVersion:'V393-METRIC-1',ruleHash:'rule1234',analysisPlanHash:'analysis1',decisionStartAt:1000,entryEnrollmentEndAt:10_000,followupEndAt:20_000,authoritativeClock:'EXCHANGE_EVENT_TIME',enrollmentRuleVersion:'V393-ENROLL-1',transitionalRule:'BASELINE_PREEXISTING_ORDER_IS_TRANSITIONAL',exclusionReasons:[],runtimeSessions:[],createdAt:900,...o});
const c=(id:string,rank:number,set='set-1'):CandidateShadowInput=>({candidateId:id,candidateSetId:set,symbol:`${id}USDT`,legal:true,selected:rank===1,rank,directionAligned:true,timingVerified:true,eventAgeMs:100,locationDistanceAtr:.1,conservativePayoffBps:20-rank,spreadBps:1,depthUsd:10000,riskCapacity:true,observedAt:2000});
describe('V3.9.3 bounded evidence store',()=>{
 it('freezes manifest and enrollment instead of using restart timestamps',()=>{const s=new TradingQualityV393EvidenceStore(':memory:'),m=manifest();s.freezeManifest(m);expect(()=>s.freezeManifest({...m,metricVersion:'CHANGED'})).toThrow('EXPERIMENT_MANIFEST_IMMUTABLE');const e={decisionAt:2000,intentCreatedAt:2001,cycleCreatedAt:2002,source:'NEW_DECISION' as const,environment:m.environment,accountScope:m.accountScope,codeHead:m.codeHead,configHash:m.configHash,policyVersion:m.policyVersion,metricVersion:m.metricVersion,ruleHash:m.ruleHash};expect(s.enroll(m.experimentId,'cy1',e)).toEqual({enrolled:true,reasons:[]});expect(s.enroll(m.experimentId,'old',{...e,source:'TRANSITIONAL_EXISTING_ORDER'}).enrolled).toBe(false);expect(()=>s.enroll(m.experimentId,'cy1',{...e,decisionAt:2001,intentCreatedAt:2002,cycleCreatedAt:2003})).toThrow('COHORT_ENROLLMENT_IMMUTABLE');s.close();});
 it('bounds candidate alternatives and samples cached included symbols only',()=>{const s=new TradingQualityV393EvidenceStore(':memory:',{maxCandidateSets:2,maxCandidatesPerSet:2,maxActiveEntries:4,maxActivePositions:4,maxRecentExits:4,maxWritesPerMinute:100,maxQueuedWrites:10,retentionMs:60_000}),m=manifest();s.freezeManifest(m);const r=s.observeCandidateSet({experimentId:m.experimentId,candidateSetId:'set-1',candidates:[c('A',1),c('B',2),c('C',3)],maxCandidates:10,windowMs:15_000,observedAt:2000,preselectedAlternativeId:'B',sourceIds:['decision:set-1'],sourceRevisions:{generation:1}});expect(r.plan.planned.map(x=>x.candidateId)).toEqual(['A','B']);expect(r.plan.excluded).toEqual([{candidateId:'C',reason:'OBSERVATION_BUDGET_EXCEEDED'}]);expect(s.recordCachedQuotes(m.experimentId,[{symbol:'AUSDT',ts:2500,mark:100,bid:99,ask:101,receivedAt:2500},{symbol:'BUSDT',ts:2500,mark:200,bid:199,ask:201,receivedAt:2500},{symbol:'CUSDT',ts:2500,mark:300,bid:299,ask:301,receivedAt:2500}],2500).stored).toBe(2);expect(s.snapshot(m.experimentId,3000).markCount).toBe(2);s.close();});
 it('stores position/exit provenance but never grants authorization',()=>{const s=new TradingQualityV393EvidenceStore(':memory:'),m=manifest();s.freezeManifest(m);expect(s.append(m.experimentId,{lifecycle:'POSITION',subjectId:'cy1',sourceIds:['p1','f1'],sourceRevisions:{v:2},metricVersion:m.metricVersion,asOf:3000,maturity:'OPEN',payload:{underwaterMs:10}})).toMatchObject({stored:true,authorization:'NONE'});expect(s.append(m.experimentId,{lifecycle:'EXIT',subjectId:'cy1',sourceIds:['x1'],sourceRevisions:{v:1},metricVersion:m.metricVersion,asOf:4000,maturity:'MATURE',payload:{postExit:'5m'}})).toMatchObject({stored:true,authorization:'NONE'});expect(s.snapshot(m.experimentId,5000)).toMatchObject({authorization:'NONE',markCount:0});s.close();});
 it('degrades evidence when candidate-set budget is exhausted',()=>{const s=new TradingQualityV393EvidenceStore(':memory:',{maxCandidateSets:1,maxCandidatesPerSet:2,maxActiveEntries:4,maxActivePositions:4,maxRecentExits:4,maxWritesPerMinute:100,maxQueuedWrites:10,retentionMs:60_000}),m=manifest();s.freezeManifest(m);s.observeCandidateSet({experimentId:m.experimentId,candidateSetId:'set-1',candidates:[c('A',1)],maxCandidates:1,windowMs:15_000,observedAt:2000,sourceIds:['s1'],sourceRevisions:{v:1}});expect(s.observeCandidateSet({experimentId:m.experimentId,candidateSetId:'set-2',candidates:[c('B',1,'set-2')],maxCandidates:1,windowMs:15_000,observedAt:2500,sourceIds:['s2'],sourceRevisions:{v:1}})).toEqual({stored:false,degradation:'EVIDENCE_DEGRADED',reasons:['CANDIDATE_SET_BUDGET_EXCEEDED'],authorization:'NONE'});s.close();});
});
