import {DatabaseSync} from 'node:sqlite';
import {createHash} from 'node:crypto';
import {TradingQualityEnrollmentEvidenceSchema,TradingQualityExperimentManifestSchema,type TradingQualityEnrollmentEvidence,type TradingQualityExperimentManifest} from '@zdj/contracts';
import {prospectiveCohortMember} from './tradingQualityEligibility.js';
import {V393_DEFAULT_OBSERVATION_BUDGET,evidenceEnvelope,observationAdmission,type EvidenceLifecycle,type EvidenceMaturity,type ObservationBudget} from './tradingQualityObservationPlan.js';
import {boundedCandidateObservationPlan,type CandidateShadowInput} from './tradingQualityV393.js';
const digest=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex'),parse=<T>(v:unknown)=>JSON.parse(String(v)) as T;
export type CachedQualityQuote={symbol:string;ts:number;mark:number;bid:number|null;ask:number|null;receivedAt:number};
export type DerivedEvidenceInput<T>={lifecycle:EvidenceLifecycle;subjectId:string;sourceIds:string[];sourceRevisions:unknown;metricVersion:string;asOf:number;maturity:EvidenceMaturity;payload:T};
/** Evidence-only SQLite: no RuntimeState/exchange dependency and therefore no order authority. */
export class TradingQualityV393EvidenceStore{
 private db:DatabaseSync;
 constructor(file:string,private budget:ObservationBudget=V393_DEFAULT_OBSERVATION_BUDGET){this.db=new DatabaseSync(file);this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA busy_timeout=1000;
 CREATE TABLE IF NOT EXISTS v393_manifest(experiment_id TEXT PRIMARY KEY,hash TEXT NOT NULL,payload TEXT NOT NULL,created_at INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS v393_enrollment(experiment_id TEXT NOT NULL,subject_id TEXT NOT NULL,hash TEXT NOT NULL,payload TEXT NOT NULL,enrolled_at INTEGER NOT NULL,PRIMARY KEY(experiment_id,subject_id));
 CREATE TABLE IF NOT EXISTS v393_evidence(experiment_id TEXT NOT NULL,lifecycle TEXT NOT NULL,subject_id TEXT NOT NULL,version_id TEXT NOT NULL,as_of INTEGER NOT NULL,expires_at INTEGER NOT NULL,payload TEXT NOT NULL,PRIMARY KEY(experiment_id,lifecycle,subject_id,version_id));
 CREATE INDEX IF NOT EXISTS v393_evidence_asof ON v393_evidence(experiment_id,lifecycle,as_of);
 CREATE TABLE IF NOT EXISTS v393_candidate_member(experiment_id TEXT NOT NULL,set_id TEXT NOT NULL,candidate_id TEXT NOT NULL,symbol TEXT NOT NULL,anchor_at INTEGER NOT NULL,until_at INTEGER NOT NULL,inclusion_probability REAL NOT NULL,preselected INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(experiment_id,set_id,candidate_id));
 CREATE INDEX IF NOT EXISTS v393_candidate_active ON v393_candidate_member(experiment_id,until_at,symbol);
 CREATE TABLE IF NOT EXISTS v393_marks(experiment_id TEXT NOT NULL,lifecycle TEXT NOT NULL,subject_id TEXT NOT NULL,ts INTEGER NOT NULL,mark REAL NOT NULL,bid REAL,ask REAL,received_at INTEGER NOT NULL,PRIMARY KEY(experiment_id,lifecycle,subject_id,ts));
 CREATE TABLE IF NOT EXISTS v393_write_log(ts INTEGER NOT NULL); CREATE INDEX IF NOT EXISTS v393_write_log_ts ON v393_write_log(ts);`);}
 private manifest(id:string){const r=this.db.prepare('SELECT payload FROM v393_manifest WHERE experiment_id=?').get(id) as any;return r?TradingQualityExperimentManifestSchema.parse(parse(r.payload)):undefined;}
 private log(now:number){this.db.prepare('INSERT INTO v393_write_log VALUES(?)').run(now);this.db.prepare('DELETE FROM v393_write_log WHERE ts<?').run(now-60_000);}
 private demand(now:number){const n=(sql:string,...args:any[])=>Number((this.db.prepare(sql).get(...args) as any)?.n??0),count=(k:string)=>n('SELECT COUNT(DISTINCT subject_id) n FROM v393_evidence WHERE lifecycle=? AND expires_at>?',k,now);return{candidateSets:n('SELECT COUNT(DISTINCT set_id) n FROM v393_candidate_member WHERE until_at>?',now),candidatesPerSet:n('SELECT COALESCE(MAX(n),0) n FROM (SELECT COUNT(*) n FROM v393_candidate_member WHERE until_at>? GROUP BY set_id)',now),activeEntries:count('ENTRY'),activePositions:count('POSITION'),recentExits:count('EXIT'),writesLastMinute:n('SELECT COUNT(*) n FROM v393_write_log WHERE ts>=?',now-60_000),queuedWrites:0};}
 health(now=Date.now()){return{...observationAdmission(this.demand(now),this.budget),store:'V393_DERIVED_EVIDENCE_SQLITE' as const,tradeAuthorization:'NONE' as const};}
 freezeManifest(input:TradingQualityExperimentManifest){const m=TradingQualityExperimentManifestSchema.parse(input),h=digest(m),old=this.db.prepare('SELECT hash FROM v393_manifest WHERE experiment_id=?').get(m.experimentId) as any;if(old){if(String(old.hash)!==h)throw new Error('EXPERIMENT_MANIFEST_IMMUTABLE');return m;}this.db.prepare('INSERT INTO v393_manifest VALUES(?,?,?,?)').run(m.experimentId,h,JSON.stringify(m),m.createdAt);this.log(m.createdAt);return m;}
 enroll(experimentId:string,subjectId:string,input:TradingQualityEnrollmentEvidence){const m=this.manifest(experimentId);if(!m)throw new Error('EXPERIMENT_MANIFEST_NOT_FROZEN');const e=TradingQualityEnrollmentEvidenceSchema.parse(input),elig=prospectiveCohortMember(m,e);if(!elig.eligible)return{enrolled:false,reasons:elig.reasons};const h=digest(e),old=this.db.prepare('SELECT hash FROM v393_enrollment WHERE experiment_id=? AND subject_id=?').get(experimentId,subjectId) as any;if(old){if(String(old.hash)!==h)throw new Error('COHORT_ENROLLMENT_IMMUTABLE');return{enrolled:true,reasons:[]};}this.db.prepare('INSERT INTO v393_enrollment VALUES(?,?,?,?,?)').run(experimentId,subjectId,h,JSON.stringify(e),e.decisionAt);this.log(e.decisionAt);return{enrolled:true,reasons:[]};}
 append<T>(experimentId:string,input:DerivedEvidenceInput<T>,retentionMs=this.budget.retentionMs){if(!this.manifest(experimentId))throw new Error('EXPERIMENT_MANIFEST_NOT_FROZEN');const a=observationAdmission(this.demand(input.asOf),this.budget);if(!a.admitted)return{stored:false,degradation:a.degradation,reasons:a.reasons};const env=evidenceEnvelope({...input,computedAt:input.asOf}),versionId=digest(env),r=this.db.prepare('INSERT OR IGNORE INTO v393_evidence VALUES(?,?,?,?,?,?,?)').run(experimentId,input.lifecycle,input.subjectId,versionId,input.asOf,input.asOf+retentionMs,JSON.stringify(env));if(Number(r.changes)>0)this.log(input.asOf);return{stored:Number(r.changes)>0,degradation:'READY' as const,reasons:[],versionId,authorization:'NONE' as const};}
 observeCandidateSet(input:{experimentId:string;candidateSetId:string;candidates:CandidateShadowInput[];maxCandidates:number;windowMs:number;observedAt:number;preselectedAlternativeId?:string|null;sourceIds:string[];sourceRevisions:unknown}){if(!this.manifest(input.experimentId))throw new Error('EXPERIMENT_MANIFEST_NOT_FROZEN');const active=Number((this.db.prepare('SELECT COUNT(DISTINCT set_id) n FROM v393_candidate_member WHERE experiment_id=? AND until_at>?').get(input.experimentId,input.observedAt) as any)?.n??0),exists=this.db.prepare('SELECT 1 ok FROM v393_candidate_member WHERE experiment_id=? AND set_id=? LIMIT 1').get(input.experimentId,input.candidateSetId) as any;if(!exists&&active>=this.budget.maxCandidateSets)return{stored:false,degradation:'EVIDENCE_DEGRADED' as const,reasons:['CANDIDATE_SET_BUDGET_EXCEEDED'],authorization:'NONE' as const};const plan=boundedCandidateObservationPlan({candidateSetId:input.candidateSetId,candidates:input.candidates,maxCandidates:Math.min(input.maxCandidates,this.budget.maxCandidatesPerSet),windowMs:input.windowMs,observedAt:input.observedAt});this.db.exec('BEGIN IMMEDIATE');try{for(const x of plan.planned)this.db.prepare('INSERT OR IGNORE INTO v393_candidate_member VALUES(?,?,?,?,?,?,?,?)').run(input.experimentId,input.candidateSetId,x.candidateId,x.symbol,input.observedAt,plan.observationUntil,x.inclusionProbability,x.candidateId===input.preselectedAlternativeId?1:0);this.db.exec('COMMIT');}catch(e){try{this.db.exec('ROLLBACK');}catch{}throw e;}if(plan.planned.length)this.log(input.observedAt);this.append(input.experimentId,{lifecycle:'CANDIDATE',subjectId:input.candidateSetId,sourceIds:input.sourceIds,sourceRevisions:input.sourceRevisions,metricVersion:'V393-SELECTION-LEX-1',asOf:input.observedAt,maturity:'OPEN',payload:{plan,preselectedAlternativeId:input.preselectedAlternativeId??null,authorization:'NONE'}});return{stored:true,plan,authorization:'NONE' as const};}
 /** Consumes already-cached quotes only; it never opens REST/WS connections. */
 recordCachedQuotes(experimentId:string,quotes:CachedQualityQuote[],now:number){const active=this.db.prepare('SELECT set_id,candidate_id,symbol,anchor_at,until_at FROM v393_candidate_member WHERE experiment_id=? AND anchor_at<=? AND until_at>=?').all(experimentId,now,now) as any[],bySymbol=new Map(quotes.map(q=>[q.symbol,q]));let stored=0;for(const row of active){const q=bySymbol.get(String(row.symbol));if(!q||q.ts<Number(row.anchor_at)||q.ts>Number(row.until_at)||q.ts>now||now-q.receivedAt>5000||!Number.isFinite(q.mark)||q.mark<=0)continue;if(!observationAdmission(this.demand(now),this.budget).admitted)break;const r=this.db.prepare('INSERT OR IGNORE INTO v393_marks VALUES(?,?,?,?,?,?,?,?)').run(experimentId,'CANDIDATE',`${row.set_id}:${row.candidate_id}`,q.ts,q.mark,q.bid,q.ask,q.receivedAt);if(Number(r.changes)>0){stored++;this.log(now);}}return{stored,degradation:this.health(now).degradation,authorization:'NONE' as const};}
 prune(now:number){this.db.prepare('DELETE FROM v393_marks WHERE ts<?').run(now-this.budget.retentionMs);this.db.prepare('DELETE FROM v393_evidence WHERE expires_at<?').run(now);this.db.prepare('DELETE FROM v393_write_log WHERE ts<?').run(now-60_000);}
 snapshot(experimentId:string,asOf=Date.now()){const evidence=this.db.prepare('SELECT payload FROM v393_evidence WHERE experiment_id=? AND as_of<=? ORDER BY as_of,subject_id').all(experimentId,asOf).map((r:any)=>parse(r.payload)),enrollment=this.db.prepare('SELECT subject_id,payload FROM v393_enrollment WHERE experiment_id=? ORDER BY subject_id').all(experimentId).map((r:any)=>({subjectId:r.subject_id,evidence:parse(r.payload)})),markCount=Number((this.db.prepare('SELECT COUNT(*) n FROM v393_marks WHERE experiment_id=? AND ts<=?').get(experimentId,asOf) as any)?.n??0);return{experimentId,asOf,manifest:this.manifest(experimentId)??null,enrollment,evidence,markCount,health:this.health(asOf),authorization:'NONE' as const};}
 close(){this.db.close();}
}
