import {describe,expect,it} from 'vitest';
import {authorizationEconomicFacts,boundedCandidateObservationPlan,candidateShadowComparator,executableMarkout,exitQualityView,positionQualityView,selectionRegret,V393_ENTRY_ENFORCE_ENABLED,V393_PROFIT_REALIZATION_ENABLED,workingOrderSurvivalAdvisory,workingOrderTimelineEvidence} from './tradingQualityV393.js';
const c=(o:any={})=>({candidateId:'a',candidateSetId:'set1',symbol:'AAAUSDT',legal:true,selected:true,rank:1,directionAligned:true,timingVerified:true,eventAgeMs:1000,locationDistanceAtr:.2,conservativePayoffBps:30,spreadBps:2,depthUsd:10000,riskCapacity:true,observedAt:1,...o});
describe('V3.9.3 shadow quality views',()=>{
 it('bounds candidates before outcomes',()=>{const p=boundedCandidateObservationPlan({candidateSetId:'set1',candidates:[c(),c({candidateId:'b',symbol:'BBB',selected:false,rank:2}),c({candidateId:'c',symbol:'CCC',selected:false,rank:3})],maxCandidates:2,windowMs:60_000,observedAt:10});expect(p.planned.map(x=>x.candidateId)).toEqual(['a','b']);});
 it('keeps comparator shadow-only',()=>expect(candidateShadowComparator([c({candidateId:'bad',timingVerified:false}),c({candidateId:'good',rank:2,selected:false})])[0]).toMatchObject({candidateId:'good',authorization:'NONE'}));
 it('uses opportunity quality, not fake PnL',()=>expect(selectionRegret({chosenCandidateId:'a',preselectedAlternativeId:'b',observedOpportunityQuality:{a:1,b:3}})).toMatchObject({opportunityRegret:2,basis:'OPPORTUNITY_QUALITY_NOT_PNL'}));
 it('separates ex-funding and with-funding completeness',()=>{expect(executableMarkout({side:'LONG',fillPrice:100,quantity:1,bid:100.2,ask:100.3,entryFeeUsd:.04,exitFeeBoundUsd:.05,basis:'EXECUTABLE_EX_FUNDING'}).eligible).toBe(true);expect(executableMarkout({side:'LONG',fillPrice:100,quantity:1,bid:100.2,ask:100.3,entryFeeUsd:.04,exitFeeBoundUsd:.05,fundingUsd:null,basis:'EXECUTABLE_WITH_FUNDING'}).eligible).toBe(false);});
 it('retains losing human-managed positions as right-censored risk occupancy',()=>{const v=positionQualityView({cycleId:'cy',unrealizedPnl:-2,underwaterMs:20*60_000,holdingMs:30*60_000,maeBps:20,mfeBps:10,tpReachable:false,opportunityFresh:false,profitAvailable:false,humanManaged:true,rightCensored:true});expect(v.findings).toContain('LOSING_INVENTORY');expect(v.findings).toContain('HUMAN_HANDOFF_REQUIRED');expect(v).toMatchObject({rightCensored:true,humanIntervention:true,portfolioRiskOccupied:true,lossExitAuthorized:false});});
 it('computes capture only from same-unit bps',()=>{expect(exitQualityView({cycleId:'cy',realizedCaptureBps:20,mfeBps:40,realizedNetExFundingUsd:2,canonicalNetUsd:null,exitPostMarkoutBps:{'1m':null},postExitReference:'FIXED_HORIZON',partialFillCount:0,feeUsd:.1})).toMatchObject({mfeToRealizedCapture:.5,captureBasis:'BPS_SAME_QTY_SAME_WINDOW'});expect(exitQualityView({cycleId:'cy',realizedCaptureBps:20,mfeBps:0,realizedNetExFundingUsd:2,canonicalNetUsd:null,exitPostMarkoutBps:{},postExitReference:'UNKNOWN',partialFillCount:0,feeUsd:.1}).mfeToRealizedCapture).toBeNull();});
 it('keeps maker timeline clocks and queue position unknown',()=>{const v=workingOrderTimelineEvidence([{type:'FILL',exchangeTime:30,receivedAt:40,filledQuantity:1,remainingQuantity:0,sourceId:'f'},{type:'SUBMIT',exchangeTime:null,receivedAt:10,filledQuantity:0,remainingQuantity:1,sourceId:'s'}]);expect(v.events.map(x=>x.type)).toEqual(['SUBMIT','FILL']);expect(v).toMatchObject({queuePosition:'UNKNOWN',authorization:'NONE',causalClaim:'NOT_ESTABLISHED'});});
 it('never releases UNKNOWN order risk',()=>expect(workingOrderSurvivalAdvisory({status:'UNKNOWN',opportunityValid:false,ttlExpired:true,cancelRequested:false,cancelAcknowledged:false,filledQuantity:0,quantity:1})).toMatchObject({advisory:'RECONCILE_ONLY',releaseReservation:false,mayResubmit:false,acceptLateFill:true}));
 it('holds reservation through cancel/fill race',()=>expect(workingOrderSurvivalAdvisory({status:'PARTIALLY_FILLED',opportunityValid:false,ttlExpired:true,cancelRequested:true,cancelAcknowledged:false,filledQuantity:.5,quantity:1})).toMatchObject({advisory:'AWAIT_CANCEL_ACK',releaseReservation:false}));
 it('keeps E/H hard-disabled',()=>{expect(V393_ENTRY_ENFORCE_ENABLED).toBe(false);expect(V393_PROFIT_REALIZATION_ENABLED).toBe(false);const x=authorizationEconomicFacts({entryFeeUsd:.1,fundingAttributedUsd:0,remainingQty:1,executablePrice:101,exitFeeUpperBoundUsd:.1,uncertaintyBufferUsd:.1,conservativeGrossPnlUsd:2,quoteFresh:true});expect(x.evidenceReady).toBe(true);expect(x.authorization).toBe('DISABLED');});
});
