import { describe, expect, it } from 'vitest';
import { RuntimeState } from '../state/runtimeState.js';
import { EventBus } from '../events/eventBus.js';
import { PositionService } from './positionService.js';
import { TradeRecordSyncService } from './tradeRecordSyncService.js';
import type { TradeAuditSnapshot } from '../types.js';

const settings={portfolio:{maxPositions:4,maxPendingEntries:4},takeProfit:{enabled:true,quantityPercent:100}} as any;
const audit:TradeAuditSnapshot={source:'BINANCE_TESTNET_PRIVATE',fetchedAt:30,window:{startTime:0,endTime:30},positions:[],openOrders:[],orders:[{symbol:'BTCUSDT',orderId:'entry-order',clientOrderId:'entry_test',side:'BUY',positionSide:'LONG',status:'FILLED',type:'LIMIT',origQty:1,executedQty:1,avgPrice:100,updateTime:10},{symbol:'BTCUSDT',orderId:'tp-order',clientOrderId:'tp_test',side:'SELL',positionSide:'LONG',status:'FILLED',type:'LIMIT',origQty:1,executedQty:1,avgPrice:102,updateTime:20}],fills:[{symbol:'BTCUSDT',side:'BUY',positionSide:'LONG',orderId:'entry-order',clientOrderId:'entry_test',tradeId:'entry-fill',executionTime:10,qty:1,price:100,realizedPnl:0,commission:.1,commissionAsset:'USDT',maker:true},{symbol:'BTCUSDT',side:'SELL',positionSide:'LONG',orderId:'tp-order',clientOrderId:'tp_test',tradeId:'exit-fill',executionTime:20,qty:1,price:102,realizedPnl:2,commission:.1,commissionAsset:'USDT',maker:true}],income:[{symbol:'BTCUSDT',incomeType:'COMMISSION',income:-.1,asset:'USDT',time:10,info:null,tradeId:'entry-fill',transactionId:null},{symbol:'BTCUSDT',incomeType:'COMMISSION',income:-.1,asset:'USDT',time:20,info:null,tradeId:'exit-fill',transactionId:null}]};

describe('TradeRecord manual sync',()=>{
  it('previews without mutating and is idempotent across repeated apply',()=>{const state=new RuntimeState(settings),service=new TradeRecordSyncService(state,new PositionService(state,new EventBus()));const preview=service.preview(audit,500,{repairPartial:true,fillFees:true,recalcNet:true});expect(state.tradeRecords.size).toBe(0);expect(preview.newComplete).toBe(1);const first=service.apply(audit,500,{repairPartial:true,fillFees:true,recalcNet:true});expect(first.created).toBe(1);expect(first.newComplete).toBe(1);expect(first.experienceCreated).toBe(1);expect(state.tradeRecords.size).toBe(1);expect(state.experienceSamples.size).toBe(1);const second=service.apply(audit,500,{repairPartial:true,fillFees:true,recalcNet:true});expect(second.created).toBe(0);expect(second.repaired).toBe(0);expect(second.skipped).toBe(1);expect(second.experienceCreated).toBe(0);expect(state.tradeRecords.size).toBe(1);expect(state.experienceSamples.size).toBe(1);});
  it('does not include external fills by default',()=>{const state=new RuntimeState(settings),service=new TradeRecordSyncService(state,new PositionService(state,new EventBus())),external={...audit,fills:[...audit.fills.map(fill=>({...fill,clientOrderId:fill.clientOrderId.replace(/^(entry|tp)/,'external')}))],orders:audit.orders.map(order=>({...order,clientOrderId:order.clientOrderId.replace(/^(entry|tp)/,'external')}))};const preview=service.preview(external,500,{});expect(preview.systemFills).toBe(0);expect(preview.externalFills).toBe(2);expect(preview.fills).toBe(0);});
  it('attributes EC1 manual reduce-only fills and conserves the 57/5 entry and exit facts',()=>{const state=new RuntimeState(settings),service=new TradeRecordSyncService(state,new PositionService(state,new EventBus()));const entry=[11,10,15,16,5].map((qty,i)=>({symbol:'币安人生USDT',side:'SELL' as const,positionSide:'SHORT' as const,orderId:'879248947',clientOrderId:'entry_mtp3',tradeId:`e${i}`,executionTime:100+i,qty,price:.57,realizedPnl:0,commission:0,commissionAsset:'USDT',maker:true})),exit=[9,12,15,16,5].map((qty,i)=>({symbol:'币安人生USDT',side:'BUY' as const,positionSide:'SHORT' as const,orderId:'879261091',clientOrderId:'ec1_mtp3',tradeId:`x${i}`,executionTime:200+i,qty,price:.56,realizedPnl:1,commission:0,commissionAsset:'USDT',maker:true})),snapshot:TradeAuditSnapshot={...audit,orders:[],fills:[...entry,...exit],income:[]};const preview=service.preview(snapshot,200,{repairPartial:true});expect(preview.cyclePlans).toMatchObject([{symbol:'币安人生USDT',direction:'SHORT',entryFills:5,exitFills:5,closed:true,action:'CREATE_COMPLETE'}]);const first=service.apply(snapshot,200,{repairPartial:true}),synced=first.records[0]!;const legacy={...synced,tradeId:'trade_exchange_币安人生USDT_SHORT',entryQty:46,entryFillCount:4,entryOrderIds:['entry_local'],exitOrderIds:[],linkedFillIds:synced.linkedFillIds.filter(id=>!id.endsWith('_e0')),classification:'PARTIAL' as const,recordCompleteness:'COMPLETE' as const,feeCompleteness:'COMPLETE' as const,canonical:true,duplicateOf:null,missingFacts:['EXCHANGE_FILL_CONSERVATION'],integrityFlags:['FILL_CONSERVATION_FAILED']};state.tradeRecords.set(legacy.tradeId,legacy);const result=service.apply(snapshot,200,{repairPartial:true}),row=state.tradeRecords.get(legacy.tradeId)!;expect(row.entryQty).toBe(57);expect(row.entryFillCount).toBe(5);expect(row.exitFillCount).toBe(5);expect(row.entryOrderIds).toEqual(['879248947']);expect(row.exitOrderIds).toEqual(['879261091']);expect(row.classification).toBe('COMPLETE');expect(result.repaired).toBe(1);const superseded=state.tradeRecords.get(synced.tradeId)!;expect(superseded.duplicateOf).toBe(legacy.tradeId);expect(superseded.canonical).toBe(false);expect(result.samples).toHaveLength(1);});
});
