import { classifyAsset, decorateUniverse, isOnlineAsset, resolveUnderlying, selectUniverse } from '@zdj/core';
import type { RuntimeState } from '../state/runtimeState.js';
import type { EventBus } from '../events/eventBus.js';
import { reconcileCandidateLifecycles } from './candidateLifecycleDeriver.js';
import { decisionContextKey, decisionSettingsContext } from './decisionContext.js';
import { candidateSupplyHealth } from './candidateSupplyHealth.js';

/** Canonical form shared by API-originated compact Symbols and UI slash notation. */
export function canonicalBlacklistValue(value:string){
  return String(value??'').trim().normalize('NFKC').replace(/[\s/_-]+/g,'').toUpperCase();
}

export class UniverseCoordinator {
  constructor(private state:RuntimeState,private events:EventBus){}
  refresh(){
    reconcileCandidateLifecycles(this.state,this.events,'UNIVERSE_REFRESH');
    const positions=[...this.state.positions.values()].map(p=>({symbol:String(p.symbol),side:p.side as 'LONG'|'SHORT',quantity:Number(p.quantity),markPrice:Number(p.markPrice),leverage:Number(p.leverage)}));
    const makerTotals:Record<string,{filled:number;quantity:number}>={},seenMakerFacts=new Set<string>(),makerMatureAt=Date.now()-60_000;for(const order of this.state.entryOrders.values()){const identity=`${order.symbol}:${order.clientOrderId??order.exchangeOrderId??order.id}`;if(seenMakerFacts.has(identity)||order.maker!==true||!String(order.factSource??'').startsWith('BINANCE')||!order.verifiedAt||order.createdAt>makerMatureAt||['NEW','SUBMITTING','UNKNOWN','WORKING','PARTIALLY_FILLED'].includes(order.status))continue;seenMakerFacts.add(identity);const key=order.symbol.toUpperCase(),current=makerTotals[key]??{filled:0,quantity:0};current.filled+=Math.max(0,order.filledQuantity);current.quantity+=Math.max(0,order.quantity);makerTotals[key]=current;}const makerFillQuality:Record<string,number|undefined>={};for(const [symbol,total] of Object.entries(makerTotals))makerFillQuality[symbol]=total.quantity>0?Math.max(0,Math.min(1,total.filled/total.quantity)):undefined;
    const blacklist=new Set(this.state.settings.selection.marketQuality.symbolBlacklist.map(canonicalBlacklistValue)),underlyingBlacklist=new Set(this.state.settings.selection.marketQuality.underlyingBlacklist.map(canonicalBlacklistValue));
    this.state.universe=decorateUniverse(selectUniverse({snapshots:[...this.state.snapshots.values()],positions:this.state.positionSymbols(),pendingEntries:this.state.activeEntrySymbols(),settings:this.state.settings,generation:this.state.marketGeneration,makerFillQuality}),[...this.state.snapshots.values()],this.state.settings,this.state.account.assets,positions).filter(candidate=>!blacklist.has(canonicalBlacklistValue(candidate.symbol))&&!underlyingBlacklist.has(canonicalBlacklistValue(candidate.underlyingAsset??resolveUnderlying(candidate.symbol))));
    const quality=this.state.settings.selection.marketQuality,now=Date.now();for(const candidate of this.state.universe){candidate.assetAdmission=classifyAsset(candidate.symbol,this.state.settings,now);const lastPrimary=Math.max(0,...this.state.aiRuns.filter((run:any)=>run.symbol===candidate.symbol&&run.role==='PRIMARY_BRAIN'&&run.completedAt).map((run:any)=>Number(run.completedAt)));candidate.schedulerPriority=candidate.assetAdmission.classification==='CORE'&&now-lastPrimary>=5*60_000?1_000_000+(now-lastPrimary):candidate.score;if(!isOnlineAsset(candidate.assetAdmission)){candidate.eligible=false;candidate.pipelineEligible=false;candidate.exclusionReasons=[...candidate.exclusionReasons,`ASSET_${candidate.assetAdmission.classification}`];}const tier=candidate.riskTier,grade=candidate.marketQuality?.grade,isNewListing=candidate.marketQuality?.reasons.includes('QUALITY_NEW_LISTING')===true;if(quality.enabled&&((isNewListing&&!quality.allowNewListings)||(tier==='SPECULATIVE'&&(!quality.allowSpeculative||grade!=='A')))){candidate.eligible=false;candidate.pipelineEligible=false;candidate.exclusionReasons=[...candidate.exclusionReasons,'MARKET_QUALITY_TIER_POLICY'];}}
    if(quality.liquidityTopN>0){const allowed=this.state.universe.filter(x=>x.eligible).sort((a,b)=>b.quoteVolumeUsd24h-a.quoteVolumeUsd24h).slice(0,quality.liquidityTopN).map(x=>x.symbol),top=new Set(allowed);for(const candidate of this.state.universe)if(candidate.eligible&&!top.has(candidate.symbol)){candidate.eligible=false;candidate.pipelineEligible=false;candidate.exclusionReasons=[...candidate.exclusionReasons,'MARKET_QUALITY_LIQUIDITY_TOP_N'];}}
    for(const candidate of this.state.universe){
      let row=this.state.candidateLifecycle.get(candidate.symbol);const cooldown=this.state.rejectionCooldown.get(candidate.symbol);
      const snapshot=this.state.snapshots.get(candidate.symbol),route=this.state.runtimeControl.capital.routedCandidates.find((x:any)=>x.symbol===candidate.symbol),contextKey=snapshot?decisionContextKey({market:snapshot,settingsContext:decisionSettingsContext(this.state.settings),longExecutable:route?.longExecutable,shortExecutable:route?.shortExecutable,confirmation:row?.confirmation}):null,fingerprint=JSON.stringify({trend:snapshot?.technical?.['15m']?.trend,atr:Math.round((snapshot?.quote?.last??0)/Math.max(.0000001,snapshot?.technical?.['15m']?.atr14??1)),spread:Math.round(candidate.spreadBps)});
      if(row?.status==='WAITING_CAPITAL_ROUTE'){row={...row,status:'READY',reason:'LEGACY_CAPITAL_ROUTE_GATE_REMOVED',nextEligibleAt:null,updatedAt:now};this.state.candidateLifecycle.set(candidate.symbol,row);}
      if(row?.nextEligibleAt&&row.nextEligibleAt<=now&&(!row.decisionContextKey||row.decisionContextKey!==contextKey)){this.state.candidateLifecycle.set(candidate.symbol,{...row,status:'READY',reason:'DECISION_CONTEXT_CHANGED',nextEligibleAt:null,updatedAt:now});this.state.rejectionCooldown.delete(candidate.symbol);}
      else if(row?.decisionContextKey&&contextKey&&row.decisionContextKey!==contextKey&&['REJECT_COOLDOWN','TECHNICAL_COOLDOWN'].includes(row.status)){this.state.candidateLifecycle.set(candidate.symbol,{...row,status:'READY',reason:'MATERIAL_STATE_CHANGE',nextEligibleAt:null,updatedAt:now,fingerprint});this.state.rejectionCooldown.delete(candidate.symbol);}
      const current=this.state.candidateLifecycle.get(candidate.symbol);
      const blocked=current?.status==='POSITION_HELD'?'POSITION_HELD':current?.status==='EXCLUDED_UNDERLYING'?'EXCLUDED_UNDERLYING':this.state.activeEntrySymbols().has(candidate.symbol)?'ENTRY_WORKING':current?.status==='WAITING_CAPITAL_ROUTE'?undefined:current?.status;
      candidate.lifecycle=(blocked??'READY') as any;candidate.lifecycleReason=current?.reason;candidate.nextEligibleAt=current?.nextEligibleAt??null;
      candidate.pipelineEligible=!blocked||['READY','SCOUT_QUEUED','SCOUT_RUNNING','SCOUT_DONE','PRIMARY_QUEUED','PRIMARY_RUNNING','PLACE_READY'].includes(blocked);
      if(cooldown&&cooldown.until>now)candidate.pipelineEligible=false;
    }
    const transient=new Set(['ACTIVE_POSITION','ACTIVE_ENTRY_ORDER','QUOTE_STALE','ORDER_BOOK_STALE','TECHNICAL_1m_STALE','TECHNICAL_5m_STALE','TECHNICAL_15m_STALE']);for(const candidate of this.state.universe)candidate.residentEligible=isOnlineAsset(candidate.assetAdmission!)&&Boolean(candidate.marketQuality?.admitted)&&candidate.selectedContract===candidate.symbol&&candidate.exclusionReasons.every(reason=>transient.has(reason));
    const ranked=this.state.universe.filter(x=>x.residentEligible).sort((a,b)=>b.score-a.score).slice(0,this.state.settings.selection.universeTopN);ranked.forEach((candidate,index)=>{candidate.rank=index+1;if(candidate.pipelineEligible&&(!this.state.candidateLifecycle.get(candidate.symbol)||this.state.candidateLifecycle.get(candidate.symbol)?.status==='READY'))candidate.lifecycle='SHORTLIST';});const rankedSymbols=new Set(ranked.map(x=>x.symbol));for(const candidate of this.state.universe)if(!rankedSymbols.has(candidate.symbol))candidate.rank=0;this.state.universe.sort((a,b)=>(b.residentEligible?1:0)-(a.residentEligible?1:0)||b.score-a.score);
    const pool=this.state.pool.replenish(this.state.universe);
    const rankingShadow=ranked.slice(0,25).flatMap(candidate=>{const m=this.state.snapshots.get(candidate.symbol);if(!m)return[];const t=m.technical['15m'],t5=m.technical['5m'];return[{symbol:candidate.symbol,baselineRank:candidate.rank,baselineScore:candidate.score,features:{trend15m:t.trend,trend5m:t5.trend,price:m.quote.last,emaDistanceAtr:t.atr14>0?(m.quote.last-t.ema21)/t.atr14:null,spreadBps:candidate.spreadBps,locationScore:candidate.locationScore,underlyingBlocked:candidate.exclusionReasons.includes('DUPLICATE_UNDERLYING'),waiting:this.state.candidateLifecycle.get(candidate.symbol)?.status==='WAIT_FOR_PRICE',fillProbability:null}}]});
    this.events.publish('CANDIDATE_RANKING_SHADOW',{observedAt:now,model:'FEATURES_ONLY_NO_NEW_RANKING',onlineRankChanged:false,candidates:rankingShadow});
    const admissionCounts=Object.fromEntries(['CORE','APPROVED_LIQUID','RESEARCH_ONLY','EXCLUDED'].map(classification=>[classification,this.state.universe.filter(candidate=>candidate.assetAdmission?.classification===classification).length]));
    this.events.publish('ASSET_ADMISSION_EVALUATED',{directoryVersion:this.state.settings.selection.assetDirectory.version,sourceDomain:'STATIC_GOVERNANCE',counts:admissionCounts,onlineEligible:admissionCounts.CORE+admissionCounts.APPROVED_LIQUID});
    const supply=candidateSupplyHealth(this.state),qualifiedSupply=supply.residentCount,readySupply=supply.executionReadyCount,target=Math.min(this.state.settings.selection.poolMax,this.state.settings.selection.poolTarget),targetGap=Math.max(0,target-supply.poolReadyCount),freshCount=pool.filter(item=>this.state.snapshots.has(item.symbol)&&this.state.universe.find(x=>x.symbol===item.symbol)?.exclusionReasons.every(reason=>!reason.endsWith('_STALE'))).length,occupiedUnderlyings=new Set([...this.state.positionSymbols(),...this.state.activeEntrySymbols()].map(symbol=>resolveUnderlying(symbol))),freeUnderlyingCount=new Set(this.state.universe.filter(x=>x.residentEligible&&x.rank>0&&!occupiedUnderlyings.has(x.underlyingAsset??resolveUnderlying(x.symbol))).map(x=>x.underlyingAsset??resolveUnderlying(x.symbol))).size;
    this.events.publish('CANDIDATE_SUPPLY_HEALTH',supply);
    this.events.publish('POOL_SUPPLY_HEALTH',{lowWatermark:4,target,qualifiedSupply,readySupply,residentCount:supply.poolResidentCount,freshCount,freeUnderlyingCount,opportunityCount:supply.pipelineReadyCount,executableCount:supply.executionReadyCount,poolCount:supply.poolResidentCount,readyCount:supply.poolReadyCount,waitingCount:supply.poolWaitingCount,targetGap,supplyShortage:qualifiedSupply<target,refillFailure:readySupply>=target&&targetGap>0,belowLowWatermark:supply.poolReadyCount<4,qualityRelaxed:false,topBlockers:supply.topBlockers,zombieSnapshotCount:supply.zombieSnapshotCount});
    this.events.publish('UNIVERSE_UPDATED' ,{generation:this.state.marketGeneration,total:this.state.universe.length,eligible:this.state.universe.filter(x=>x.eligible&&x.rank>0).length});
    this.events.publish('POOL_UPDATED',{count:pool.length,readyCount:supply.poolReadyCount,waitingCount:supply.poolWaitingCount,items:pool.map(x=>({symbol:x.symbol,score:x.score,state:x.state}))});
    return {universe:this.state.universe,pool};
  }
}
