import {describe,it,expect,vi} from 'vitest';
import {readFileSync} from 'node:fs';
import {EntryIntelligencePacketSchema,MarketSymbolSnapshotSchema,EntryDecisionV370Schema,EntryDecisionJsonSchema} from '@zdj/contracts';
import {buildCompactBrainPrompt,compactEntryFacts,directionPermissions} from '@zdj/core';
import {entryDecisionParse} from './aiFabric.js';
import {waitingContext,waitTrigger} from './entryWaiting.js';
import {OpenAiCompatibleClient,AiRequestError} from '../adapters/ai/OpenAiCompatibleClient.js';
const fixture=JSON.parse(readFileSync(new URL('./fixtures/v363-entry.json',import.meta.url),'utf8'))[0];
const packet=EntryIntelligencePacketSchema.parse(fixture.packet);
const frozenPrimary=JSON.parse(readFileSync(new URL('../../../../docs/reports/final-closure-audit-20260910/primary-detail.json',import.meta.url),'utf8'))[0];
const decision={action:'FINAL',direction:'LONG',decision:'WAIT_FOR_PRICE',confidence:.7,idealPrice:null,acceptablePriceRange:null,horizonMinutes:null,waitCondition:{operator:'LTE',price:packet.market.quote.bid*.99,validForMinutes:3},directionReason:'15m UP',timingReason:'Wait pullback',reason:'Price timing',entryInvalidation:'15m reverses'};
describe('V3.8.0 compact one-shot and WAIT safety',()=>{
  it('retains required facts without Scout, repeated evidence, optional research modules, and includes explicit economics',()=>{const facts=compactEntryFacts(packet);expect(Object.keys(facts.technical)).toEqual(['1m','5m','15m']);const prompt=buildCompactBrainPrompt(packet);expect(prompt.length).toBeLessThan(10000);expect(prompt).not.toContain('SCOUT:');expect(prompt).not.toContain('globalRegime');expect(facts.economics).toMatchObject({unit:'BPS',minimumEconomicEdgeBps:expect.any(Number),provenance:expect.any(String)});expect((facts as any).evidence).toBeUndefined();});
  it('maps WAIT explicitly and never fabricates an executable range',()=>{const d=entryDecisionParse(decision,packet);expect(d.decision).toBe('WAIT_FOR_PRICE');expect(d.idealPrice).toBeNull();expect(d.acceptablePriceRange).toBeNull();});
  it('rejects ambiguous probability and guessed execution fields instead of repairing them',()=>{expect(()=>EntryDecisionV370Schema.parse({...decision,decision:'PLACE_LONG',waitCondition:null,confidence:'HIGH'})).toThrow();expect(()=>EntryDecisionV370Schema.parse({...decision,idealPrice:1})).toThrow();expect(()=>EntryDecisionV370Schema.parse({...decision,waitCondition:null})).toThrow();});
  it('sends complete mutually exclusive schema variants to llama.cpp',()=>{expect(EntryDecisionJsonSchema.oneOf).toHaveLength(4);for(const branch of EntryDecisionJsonSchema.oneOf){expect(branch.required).toContain('action');expect(branch.required).toContain('supportingEvidenceRefs');expect(branch.additionalProperties).toBe(false);}});
  it('accepts only a 15m-aligned PLACE and rejects a counter-direction timing rewrite',()=>{const q=packet.market.quote,place={...decision,decision:'PLACE_LONG',waitCondition:null,idealPrice:q.bid,acceptablePriceRange:{min:q.bid,max:q.ask},horizonMinutes:3};expect(entryDecisionParse(place,packet).decision).toBe('PLACE_LONG');expect(()=>entryDecisionParse({...place,decision:'PLACE_SHORT',direction:'SHORT'},packet)).toThrow(/15m direction/);expect(()=>entryDecisionParse({...place,acceptablePriceRange:{min:q.ask,max:q.bid}},packet)).toThrow();});
  it('freezes symmetric LONG/SHORT replay: 1m/5m timing cannot reverse decisive 15m structure',()=>{const q=packet.market.quote,base={...decision,waitCondition:null,idealPrice:q.bid,acceptablePriceRange:{min:q.bid,max:q.ask},horizonMinutes:3};const down=EntryIntelligencePacketSchema.parse({...packet,market:{...packet.market,technical:{...packet.market.technical,'15m':{...packet.market.technical['15m'],trend:'DOWN'}}}});expect(entryDecisionParse({...base,direction:'SHORT',decision:'PLACE_SHORT'},down).decision).toBe('PLACE_SHORT');expect(()=>entryDecisionParse({...base,direction:'LONG',decision:'PLACE_LONG'},down)).toThrow(/15m direction/);expect(compactEntryFacts(down).technical['1m']).toHaveProperty('missingClosedBarAnchor',true);});
  it('replays a frozen current Primary input without converting a 15m DOWN timing conflict into LONG',()=>{const p=EntryIntelligencePacketSchema.parse(JSON.parse(frozenPrimary.inputPreview).packet),q=p.market.quote,base={...decision,confidence:.5,waitCondition:null,idealPrice:q.bid,acceptablePriceRange:{min:q.bid,max:q.ask},horizonMinutes:3,supportingEvidenceRefs:['technical.15m.confirmed','technical.1m.confirmed']};expect(p.market.technical['15m'].trend).toBe('DOWN');expect(compactEntryFacts(p).technical['1m']).toHaveProperty('missingClosedBarAnchor',true);expect(entryDecisionParse({...base,direction:'SHORT',decision:'PLACE_SHORT'},p).decision).toBe('PLACE_SHORT');expect(()=>entryDecisionParse({...base,direction:'LONG',decision:'PLACE_LONG'},p)).toThrow(/15m direction/);});
  it('unchanged or expired WAIT consumes no AI call; material triggers require confirmation and survive serialization',()=>{const m=MarketSymbolSnapshotSchema.parse({...packet.market,symbol:packet.symbol,dataCompleteness:1});m.quote.ts=Date.now();const d=entryDecisionParse(decision,packet),w=waitingContext(d,'run',m),restored=JSON.parse(JSON.stringify(w));expect(waitTrigger(restored,m)).toBeNull();m.quote.bid=w.condition.price;expect(waitTrigger(restored,m)).toBe('PRICE_TRIGGERED');expect(restored.orderAuthorization).toBe(false);expect(waitTrigger(restored,m,w.expiresAt)).toBeNull();m.quote.bid=packet.market.quote.bid;m.technical['15m'].trend='DOWN';expect(waitTrigger(restored,m)).toBe('MATERIAL_STATE_CHANGE');});
  it('captures token usage on schema failure',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({choices:[{message:{content:'{"decision":"PLACE_LONG"}'}}],usage:{prompt_tokens:123,completion_tokens:20}}),{status:200})));try{const client=new OpenAiCompatibleClient();await expect(client.runJson({baseUrl:'http://isolated.invalid/v1',model:'test',prompt:'fixture',schemaName:'V370',timeoutMs:1000,parse:()=>{throw new Error('missing price');}})).rejects.toMatchObject({stage:'PARSE',usage:{inputTokens:123,outputTokens:20},rawOutput:'{"decision":"PLACE_LONG"}'});}finally{vi.unstubAllGlobals();}});
});


describe('V392 final canary protocol regression',()=>{
  it('accepts the supplied economics fact through the real parser while rejecting invented references',()=>{
    const q=packet.market.quote,place={...decision,decision:'PLACE_LONG',waitCondition:null,idealPrice:q.bid,acceptablePriceRange:{min:q.bid,max:q.ask},horizonMinutes:3,supportingEvidenceRefs:['economics.entry']};
    expect(compactEntryFacts(packet).validFactIds).toContain('economics.entry');
    expect(entryDecisionParse(place,packet).decision).toBe('PLACE_LONG');
    expect(()=>entryDecisionParse({...place,supportingEvidenceRefs:['economics.invented']},packet)).toThrow(/unknown supportingEvidenceRefs/);
    const tp={targetPrice:0.2032,acceptableTargetRange:{min:0.2035,max:0.2032},targetHorizonMinutes:15,targetReason:'frozen canary reversed bounds',evidenceRefs:['technical.15m.confirmed']};
    expect(()=>entryDecisionParse({...place,profitTakePlan:tp},packet)).toThrow();
  });
});
