import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {EntryIntelligencePacketSchema,EntryDecisionV370Schema,EntryDecisionJsonSchema} from '@zdj/contracts';
import {buildCompactBrainPrompt,compactEntryFacts} from '@zdj/core';
import {entryDecisionParse} from './aiFabric.js';

const fixture=JSON.parse(readFileSync(new URL('./fixtures/v363-entry.json',import.meta.url),'utf8'))[0];
const rawPacket=fixture.packet;
const technicalWith1h={...rawPacket.market.technical,'1h':rawPacket.market.technical['1h']??rawPacket.market.technical['4h']};
const basePacket=EntryIntelligencePacketSchema.parse({...rawPacket,market:{...rawPacket.market,technical:technicalWith1h}});
const envelope=(maxLong=1000,maxShort=1000)=>({version:'V3.9.3_PRE_AI_EXECUTION_ENVELOPE',symbol:basePacket.symbol,underlying:basePacket.symbol.replace(/(USDT|USDC)$/,''),quoteAsset:'USDT',createdAt:Date.now(),expiresAt:Date.now()+60_000,notice:'EXECUTION FACTS ARE NOT MARKET SIGNALS.',account:{status:'READY',equityUsd:5000,availableMarginUsd:4000,reservedMarginUsd:0,executionLeaseMarginUsd:0,freeMarginUsd:4000},positionCapacity:{used:0,max:8,slotAvailable:true,sameUnderlyingOccupied:false},leverage:10,exchange:{tickSize:basePacket.market.quote.tickSize,stepSize:basePacket.market.quote.stepSize,minQty:basePacket.market.quote.minQty,minNotional:basePacket.market.quote.minNotional},makerReachableBand:{min:basePacket.market.quote.bid*.99,max:basePacket.market.quote.ask*1.01},recentTradedPrices:basePacket.market.recentTradedPrices??[],fees:{makerFeeBps:2,takerFeeBps:5,roundTripCostBps:7,safetyMarginBps:2},LONG:{executable:maxLong>0,maxMarginUsd:maxLong/10,maxNotionalUsd:maxLong,maxQuantityUnits:1000,riskHeadroom:{factVersion:'l',remaining:{gross:maxLong},blockers:[],reason:'PASS'}},SHORT:{executable:maxShort>0,maxMarginUsd:maxShort/10,maxNotionalUsd:maxShort,maxQuantityUnits:2000,riskHeadroom:{factVersion:'s',remaining:{gross:maxShort},blockers:[],reason:'PASS'}},leaseRequiredMarginUsd:Math.max(maxLong,maxShort)/10});
const referenceMarket=(symbol:string)=>({symbol,quote:basePacket.market.quote,technical:technicalWith1h,derivatives:basePacket.market.derivatives,orderBook:basePacket.market.orderBook,recentTradedPrices:basePacket.market.recentTradedPrices});
const packet=(trend:'UP'|'DOWN'='UP',long=1000,short=1000)=>EntryIntelligencePacketSchema.parse({...basePacket,market:{...basePacket.market,technical:{...technicalWith1h,'15m':{...technicalWith1h['15m'],trend}}},executionEnvelope:envelope(long,short),referenceMarkets:{btc:referenceMarket('BTCUSDT'),eth:referenceMarket('ETHUSDT')}});
const place=(side:'LONG'|'SHORT',p=packet())=>({action:'FINAL',schemaVersion:'V3.9.3',decision:`PLACE_${side}`,tradeSide:side,structureDirection:side,direction:side,quantityUnits:100,opportunityType:'TREND_RESUMPTION',marketRegime:'TREND',confidence:.6,idealPrice:p.market.quote.bid,acceptablePriceRange:{min:p.market.quote.bid,max:p.market.quote.ask},horizonMinutes:3,waitCondition:null,directionReason:'model chose side from market facts',timingReason:'timing acceptable',entryLocationReason:'maker range reachable',reason:'entry selected',entryInvalidation:'entry authorization expires',supportingEvidenceRefs:['technical.15m.confirmed'],profitTakePlan:{targetPrice:p.market.quote.ask*1.002,acceptableTargetRange:{min:p.market.quote.ask*1.001,max:p.market.quote.ask*1.003},targetHorizonMinutes:15,targetReason:'net positive target',evidenceRefs:['technical.15m.confirmed']},rejectLayer:'NONE',blockingCondition:'',releaseCondition:'',timingEvent:null});
const candidatePlace=(side:'LONG'|'SHORT',p=packet())=>({...place(side,p),schemaVersion:'V3.9.7',selectedCandidateId:`cand_${side.toLowerCase()}`,quantityUnits:null});

describe('V3.9.7 candidate-selection Primary contract with legacy archive compatibility',()=>{
  it('15m UP + AI SHORT keeps SHORT unchanged',()=>{const p=packet('UP');const d=entryDecisionParse(place('SHORT',p),p);expect(d.decision).toBe('PLACE_SHORT');expect(d.tradeSide).toBe('SHORT');expect(d.quantityUnits).toBe(100);});
  it('15m DOWN + AI LONG keeps LONG unchanged',()=>{const p=packet('DOWN');const d=entryDecisionParse(place('LONG',p),p);expect(d.decision).toBe('PLACE_LONG');expect(d.tradeSide).toBe('LONG');expect(d.quantityUnits).toBe(100);});
  it('capacity asymmetry is execution fact, never a direction answer',()=>{const p=packet('UP',100,5000);const prompt=buildCompactBrainPrompt(p);expect(prompt).toContain('EXECUTION FACTS ARE NOT MARKET SIGNALS.');expect(entryDecisionParse(place('LONG',p),p).tradeSide).toBe('LONG');});
  it('keeps legacy integer quantity parsing but live PLACE requires candidate id and null quantity',()=>{const p=packet();expect(EntryDecisionV370Schema.parse(place('LONG',p)).quantityUnits).toBe(100);expect(EntryDecisionV370Schema.parse(candidatePlace('LONG',p))).toMatchObject({selectedCandidateId:'cand_long',quantityUnits:null});expect(()=>EntryDecisionV370Schema.parse({...candidatePlace('LONG',p),quantityUnits:100})).toThrow();expect(()=>EntryDecisionV370Schema.parse({...candidatePlace('LONG',p),selectedCandidateId:null})).toThrow();});
  it('live schema exposes candidate selection but no raw sizing or legacy directional bias grammar',()=>{const raw=JSON.stringify(EntryDecisionJsonSchema);expect(raw).toContain('selectedCandidateId');expect(raw).toContain('"quantityUnits":{"type":"null"}');expect(raw).not.toContain('preferredDirection');expect(raw).not.toContain('SHORT_ONLY');expect(raw).not.toContain('LONG_ONLY');expect(raw).not.toContain('altLongQuality');expect(raw).not.toContain('longException');});
  it('Primary prompt is split and contains Symbol + BTC + ETH multi-timeframe facts without direction recommendation keys',()=>{const p=packet();const facts:any=compactEntryFacts(p),prompt=buildCompactBrainPrompt(p);for(const tf of ['1m','5m','15m','1h','4h','1d','1w'])expect(facts).toHaveProperty(`MARKET_FACTS.symbol.technical.${tf}`);for(const asset of ['BTC','ETH'])for(const tf of ['15m','1h','4h','1d','1w'])expect(facts).toHaveProperty(`MARKET_FACTS.${asset}.technical.${tf}`);expect(facts).toHaveProperty('EXECUTION_ENVELOPE.LONG.maxQuantityUnits');expect(prompt).not.toContain('preferredDirection');expect(prompt).not.toContain('SHORT_ONLY');expect(prompt).not.toContain('LONG_ONLY');expect(prompt).not.toContain('15mDirectionAuthority');});
  it('TESTNET funds-only Primary never receives portfolio, human-capacity, historical-risk or stress observations',()=>{const p:any=packet();p.executionEnvelope.resourcePolicy='TESTNET_FUNDS_ONLY';p.executionEnvelope.economics={humanManagedExposure:{positions:99,notionalUsd:999999,maxPositions:1,maxNotionalUsd:0,withinLimits:false}};p.executionEnvelope.LONG.riskHeadroom={blockers:['OBS_GROSS_LIMIT','OBS_HUMAN_CAPACITY']};p.portfolio={grossExposure:999999,directionExposure:999999,clusterExposure:999999,stress:'OBS_STRESS_REJECT'};p.experience={historicalClaims:['OBS_HISTORICAL_UNKNOWN']};const facts:any=compactEntryFacts(p);expect(facts.MARKET_FACTS.portfolio).toBeUndefined();expect(facts.MARKET_FACTS.experience).toBeUndefined();expect(facts.EXECUTION_ENVELOPE.economics.humanManagedExposure).toBeUndefined();expect(facts.EXECUTION_ENVELOPE.LONG.riskHeadroom).toBeUndefined();expect(JSON.stringify(facts)).not.toMatch(/OBS_GROSS_LIMIT|OBS_HUMAN_CAPACITY|OBS_STRESS_REJECT|OBS_HISTORICAL_UNKNOWN/);});
});
