/* Offline implementation primitives consumed by the runtime projections and coordinator tests.
 * They are deliberately fail-closed: an absent fact is UNKNOWN, never zero or success. */
export type Scope={environment:string;accountId:string;symbol:string;positionSide:'LONG'|'SHORT'|'BOTH'};
export type OwnerState='AI_ACTIVE'|'HANDOFF_PENDING'|'HUMAN_MANAGED'|'CLOSED';
export type Ownership={scope:string;cycleId:string;ownerState:OwnerState;ownerVersion:number;planRef:string|null;deadline:number|null;transitionedAt:number;reason:string;acknowledgedAt:number|null};
export const canonicalScope=(s:Scope)=>JSON.stringify([s.environment,s.accountId,s.symbol.toUpperCase(),s.positionSide]);
export function transitionOwner(current:Ownership|null,next:OwnerState,expectedVersion:number,now:number,reason:string):Ownership{
  if(current&&current.ownerVersion!==expectedVersion)throw new Error('OWNER_VERSION_CONFLICT');
  if(current?.ownerState==='CLOSED'&&next!=='CLOSED')throw new Error('CLOSED_OWNER_IMMUTABLE');
  if(current?.ownerState==='HUMAN_MANAGED'&&next==='AI_ACTIVE')throw new Error('HUMAN_REAUTHORIZATION_REQUIRED');
  return{scope:current?.scope??'',cycleId:current?.cycleId??'',ownerState:next,ownerVersion:(current?.ownerVersion??0)+1,planRef:current?.planRef??null,deadline:current?.deadline??null,transitionedAt:now,reason,acknowledgedAt:current?.acknowledgedAt??null};
}
export type QuantityClaim={scope:string;cycleId:string;source:'AI'|'MANUAL'|'TP';claimId:string;quantityUnits:number;version:number;status:'ACTIVE'|'RELEASED'|'UNKNOWN'};
export function allocateSharedQuantity(claims:QuantityClaim[],requested:number,available:number){const used=claims.filter(c=>c.status!=='RELEASED').reduce((n,c)=>n+c.quantityUnits,0);if(!Number.isInteger(requested)||requested<=0)return{allowed:false,reason:'INVALID_QUANTITY_UNITS',remaining:Math.max(0,available-used)};if(used+requested>available)return{allowed:false,reason:'SHARED_QUANTITY_BUDGET_EXCEEDED',remaining:Math.max(0,available-used)};return{allowed:true,reason:'OK',remaining:available-used-requested};}

export type ExitFacts={grossRealizedToDate:number|null;incurredFees:number|null;signedFunding:number|null;projectedExitGross:number|null;projectedExitFee:number|null;uncertaintyBuffer:number|null;factsStatus:'EXACT'|'CONSERVATIVE_BOUND'|'UNKNOWN'|'CONFLICT'};
export function estimateExit(f:ExitFacts){const values=[f.grossRealizedToDate,f.incurredFees,f.signedFunding,f.projectedExitGross,f.projectedExitFee,f.uncertaintyBuffer];if(f.factsStatus==='CONFLICT'||values.some(v=>v==null||!Number.isFinite(v)))return{netIfAllClosed:null,status:f.factsStatus,reason:'EXIT_FACTS_INCOMPLETE'};return{netIfAllClosed:f.grossRealizedToDate!+f.projectedExitGross!-f.incurredFees!-f.projectedExitFee!+f.signedFunding!-f.uncertaintyBuffer!,status:f.factsStatus,reason:'EXACT_COST_FORMULA'};}
export type FundingFact={id:string;accountScope:string;asset:string;amount:number;time:number;cycleId?:string|null};
export function attributeFunding(facts:FundingFact[],input:{accountScope:string;cycleId:string;start:number;end:number;coverageComplete:boolean}){const rows=facts.filter(f=>f.accountScope===input.accountScope&&f.time>=input.start&&f.time<=input.end);if(!input.coverageComplete)return{status:'UNKNOWN' as const,amount:null,sourceIds:rows.map(r=>r.id),reason:'COVERAGE_INCOMPLETE'};if(rows.some(r=>!Number.isFinite(r.amount)))return{status:'UNKNOWN' as const,amount:null,sourceIds:rows.map(r=>r.id),reason:'NONFINITE_FUNDING'};return{status:'EXACT' as const,amount:rows.reduce((n,r)=>n+r.amount,0),sourceIds:rows.map(r=>r.id),reason:'ACCOUNT_TIME_SCOPE_EXACT'};}
export function capitalBaseline(input:{snapshots:Array<{at:number;equity:number}>;flows:Array<{at:number;amount:number;type:'DEPOSIT'|'WITHDRAWAL'|'TRADING_PNL'}>;start:number;end:number}){const snapshots=input.snapshots.filter(s=>s.at>=input.start&&s.at<=input.end).sort((a,b)=>a.at-b.at),flows=input.flows.filter(f=>f.at>=input.start&&f.at<=input.end);if(!snapshots.length)return{status:'UNKNOWN' as const,startingEquity:null,endingEquity:null,flowAdjustedChange:null,gap:'NO_SNAPSHOT'};const first=snapshots[0]!,last=snapshots.at(-1)!,nonTrading=flows.filter(f=>f.type!=='TRADING_PNL').reduce((n,f)=>n+(f.type==='DEPOSIT'?f.amount:-f.amount),0),pnl=flows.filter(f=>f.type==='TRADING_PNL').reduce((n,f)=>n+f.amount,0);return{status:'EXACT' as const,startingEquity:first.equity,endingEquity:last.equity,flowAdjustedChange:last.equity-first.equity-nonTrading,gap:null,flowBreakdown:{nonTrading,pnl}};}
export function decideAiExit(input:{owner:OwnerState;now:number;deadline:number|null;estimate:ReturnType<typeof estimateExit>;thesisInvalid:boolean;lossLimit:number;minProfit:number;allowSmallLoss:boolean}){if(input.owner!=='AI_ACTIVE')return{outcome:'BLOCKED_FACTS',reason:'OWNER_NOT_AI_ACTIVE'} as const;if(input.deadline==null||input.now>=input.deadline)return{outcome:'HANDOFF',reason:'AI_MANAGEMENT_EXPIRED'} as const;if(input.estimate.netIfAllClosed==null)return{outcome:'BLOCKED_FACTS',reason:'EXIT_FACTS_UNKNOWN'} as const;const n=input.estimate.netIfAllClosed;if(n<-input.lossLimit)return{outcome:'HANDOFF',reason:'LOSS_LIMIT_EXCEEDED'} as const;if(input.thesisInvalid&&input.allowSmallLoss&&n<0)return{outcome:'ALLOW',reason:'THESIS_INVALID_SMALL_LOSS'} as const;if(n>=input.minProfit)return{outcome:'ALLOW',reason:'NET_PROFIT_THRESHOLD'} as const;return{outcome:'HOLD',reason:'NO_EXIT_CONDITION'} as const;}

export type PortfolioInput={equity:number|null;positions:Array<{scope:string;notional:number;unrealizedPnl:number;human:boolean}>;claims:QuantityClaim[];unknownClaims:number;stressLoss:number|null;coverage:'EXACT'|'UNKNOWN'};
export function portfolioRiskSnapshot(i:PortfolioInput){const human=i.positions.filter(p=>p.human),gross=i.positions.reduce((n,p)=>n+Math.abs(p.notional),0);return{asOf:Date.now(),equity:i.equity,positions:i.positions,claims:i.claims,unknownClaims:i.unknownClaims,humanBook:{count:human.length,notional:human.reduce((n,p)=>n+Math.abs(p.notional),0)},grossNotional:gross,stressLoss:i.stressLoss,coverage:i.coverage,admission:i.coverage==='EXACT'&&i.equity!=null?'ELIGIBLE_FOR_OFFLINE_CHECK':'BLOCKED_FACTS'};}

export type TradePlan={schemaVersion:'V396-PLAN-1';planId:string;planVersion:number;cycleId:string;scope:string;quantityUnits:number;targetHorizonMinutes:number;managementDurationMs:number;aiManagementDeadline:number|null;direction:'LONG'|'SHORT'|'WAIT';evidenceRefs:string[];provenanceHash:string};
export function validateTradePlan(p:TradePlan,now:number){const errors:string[]=[];if(!p.planId||p.planVersion<1)errors.push('PLAN_ID_INVALID');if(!Number.isInteger(p.quantityUnits)||p.quantityUnits<0)errors.push('QUANTITY_UNITS_INVALID');if(p.direction==='WAIT'&&p.quantityUnits!==0)errors.push('WAIT_WITH_QUANTITY');if(p.aiManagementDeadline!=null&&p.aiManagementDeadline<now)errors.push('DEADLINE_EXPIRED');if(!p.evidenceRefs.length)errors.push('EVIDENCE_MISSING');return{valid:errors.length===0,errors};}

export type TokenLedgerRow={eventId:string;role:'ENTRY'|'REVIEW'|'SCOUT'|'EXTERNAL_RESEARCH';inputTokens:number|null;outputTokens:number|null;latencyMs:number|null;usageStatus:'EXACT'|'UNKNOWN';promptHash:string;reason:string};
export function tokenLedgerTotal(rows:TokenLedgerRow[]){return{rows:rows.length,inputTokens:rows.every(r=>r.inputTokens!=null)?rows.reduce((n,r)=>n+r.inputTokens!,0):null,outputTokens:rows.every(r=>r.outputTokens!=null)?rows.reduce((n,r)=>n+r.outputTokens!,0):null,unknownUsage:rows.filter(r=>r.usageStatus==='UNKNOWN').length};}

export type ReplayEvent={at:number;availableAt:number;type:string;payload:unknown};
export function replayAvailable(events:ReplayEvent[],at:number){return events.filter(e=>e.availableAt<=at&&e.at<=at).sort((a,b)=>a.at-b.at);}
export function experimentId(manifest:unknown){return [...new TextEncoder().encode(JSON.stringify(manifest))].reduce((h,b)=>(h*31+b)>>>0,2166136261).toString(16).padStart(8,'0');}
export function releaseReadiness(input:{sourceHash:string;settingsHash:string;schemaHash:string;testsPass:boolean;externalCanaryRun:boolean}){return{status:input.testsPass?'READY_FOR_REVIEW':'BLOCKED_OFFLINE',sourceHash:input.sourceHash,settingsHash:input.settingsHash,schemaHash:input.schemaHash,externalStatus:input.externalCanaryRun?'RUN':'NOT_RUN_EXTERNAL',engineLifecycle:'NOT_USED',deployment:'NOT_USED'};}
