import {describe,expect,it} from 'vitest';
import {allocateSharedQuantity,attributeFunding,capitalBaseline,canonicalScope,decideAiExit,estimateExit,experimentId,portfolioRiskSnapshot,releaseReadiness,replayAvailable,tokenLedgerTotal,transitionOwner,validateTradePlan} from './v396OfflineStages.js';

describe('V3.9.6 offline stage integration',()=>{
 it('S02 uses one canonical scope and CAS ownership',()=>{const scope=canonicalScope({environment:'TESTNET',accountId:'a',symbol:'btcusdt',positionSide:'BOTH'});expect(scope).toBe(JSON.stringify(['TESTNET','a','BTCUSDT','BOTH']));const first=transitionOwner(null,'AI_ACTIVE',0,1,'PLAN');expect(()=>transitionOwner(first,'HUMAN_MANAGED',0,2,'HANDOFF')).toThrow('OWNER_VERSION_CONFLICT');const human=transitionOwner(first,'HUMAN_MANAGED',1,2,'HANDOFF');expect(()=>transitionOwner(human,'AI_ACTIVE',2,3,'AUTO')).toThrow('HUMAN_REAUTHORIZATION_REQUIRED');});
 it('S02/S04 share quantity budget across AI, manual and TP',()=>{const claims:any[]=[{scope:'s',cycleId:'c',source:'TP',claimId:'t',quantityUnits:6,version:1,status:'ACTIVE'}];expect(allocateSharedQuantity(claims,4,10).allowed).toBe(true);expect(allocateSharedQuantity(claims,5,10)).toMatchObject({allowed:false,reason:'SHARED_QUANTITY_BUDGET_EXCEEDED'});});
 it('S03 applies signed funding and the ten-USDT boundary without tolerance',()=>{const e=estimateExit({grossRealizedToDate:-2,incurredFees:1,signedFunding:-.5,projectedExitGross:-5,projectedExitFee:.5,uncertaintyBuffer:.2,factsStatus:'EXACT'});expect(e.netIfAllClosed).toBe(-9.2);expect(decideAiExit({owner:'AI_ACTIVE',now:1,deadline:10,estimate:e,thesisInvalid:true,lossLimit:10,minProfit:.15,allowSmallLoss:true}).outcome).toBe('ALLOW');const deep=estimateExit({...({grossRealizedToDate:-2,incurredFees:1,signedFunding:-.5,projectedExitGross:-6,projectedExitFee:.5,uncertaintyBuffer:.2,factsStatus:'EXACT'})});expect(decideAiExit({owner:'AI_ACTIVE',now:1,deadline:10,estimate:deep,thesisInvalid:true,lossLimit:10,minProfit:.15,allowSmallLoss:true}).outcome).toBe('HANDOFF');});
 it('S03 blocks unknown cost and expired/owner-invalid authorization',()=>{const e=estimateExit({grossRealizedToDate:1,incurredFees:null,signedFunding:0,projectedExitGross:1,projectedExitFee:0,uncertaintyBuffer:0,factsStatus:'UNKNOWN'});expect(decideAiExit({owner:'AI_ACTIVE',now:1,deadline:10,estimate:e,thesisInvalid:true,lossLimit:10,minProfit:.15,allowSmallLoss:true}).outcome).toBe('BLOCKED_FACTS');expect(decideAiExit({owner:'HUMAN_MANAGED',now:1,deadline:10,estimate:e,thesisInvalid:true,lossLimit:10,minProfit:.15,allowSmallLoss:true}).outcome).toBe('BLOCKED_FACTS');});
 it('S01 attributes signed funding only within account/time coverage',()=>{const x=attributeFunding([{id:'f1',accountScope:'a',asset:'USDT',amount:-.2,time:5},{id:'f2',accountScope:'a',asset:'USDT',amount:.1,time:6}],{accountScope:'a',cycleId:'c',start:1,end:10,coverageComplete:true});expect(x).toMatchObject({status:'EXACT',amount:-.1,sourceIds:['f1','f2']});expect(attributeFunding([], {accountScope:'a',cycleId:'c',start:1,end:10,coverageComplete:false}).status).toBe('UNKNOWN');});
 it('S01 separates deposits from trading PnL and reports missing baseline',()=>{expect(capitalBaseline({snapshots:[{at:1,equity:100},{at:3,equity:110}],flows:[{at:2,amount:20,type:'DEPOSIT'},{at:2,amount:-10,type:'TRADING_PNL'}],start:1,end:3})).toMatchObject({status:'EXACT',flowAdjustedChange:-10,flowBreakdown:{nonTrading:20,pnl:-10}});expect(capitalBaseline({snapshots:[],flows:[],start:1,end:3})).toMatchObject({status:'UNKNOWN',gap:'NO_SNAPSHOT'});});
 it('S05 retains human risk and blocks incomplete portfolio admission',()=>{const p=portfolioRiskSnapshot({equity:100,positions:[{scope:'s',notional:50,unrealizedPnl:-3,human:true}],claims:[],unknownClaims:1,stressLoss:null,coverage:'UNKNOWN'});expect(p.humanBook.notional).toBe(50);expect(p.admission).toBe('BLOCKED_FACTS');});
 it('S06 rejects executable plans with no evidence or invalid WAIT quantity',()=>{const p:any={schemaVersion:'V396-PLAN-1',planId:'p',planVersion:1,cycleId:'c',scope:'s',quantityUnits:1,targetHorizonMinutes:10,managementDurationMs:100,aiManagementDeadline:100,evidenceRefs:[],direction:'WAIT',provenanceHash:'x'};expect(validateTradePlan(p,1)).toMatchObject({valid:false,errors:expect.arrayContaining(['WAIT_WITH_QUANTITY','EVIDENCE_MISSING'])});});
 it('S07 keeps unknown token usage unknown and is additive by role',()=>{expect(tokenLedgerTotal([{eventId:'1',role:'ENTRY',inputTokens:1,outputTokens:2,latencyMs:3,usageStatus:'EXACT',promptHash:'h',reason:'x'},{eventId:'2',role:'REVIEW',inputTokens:null,outputTokens:null,latencyMs:4,usageStatus:'UNKNOWN',promptHash:'h',reason:'retry'}])).toMatchObject({rows:2,inputTokens:null,outputTokens:null,unknownUsage:1});});
 it('S09 replay only consumes facts available at event time and hashes manifests',()=>{const e=[{at:2,availableAt:3,type:'late',payload:1},{at:1,availableAt:1,type:'on-time',payload:2}];expect(replayAvailable(e,2).map(x=>x.type)).toEqual(['on-time']);expect(experimentId({split:'fixed',cost:.1})).toBe(experimentId({split:'fixed',cost:.1}));expect(experimentId({split:'fixed',cost:.2})).not.toBe(experimentId({split:'fixed',cost:.1}));});
 it('S10 release material records external canary as not run',()=>expect(releaseReadiness({sourceHash:'s',settingsHash:'c',schemaHash:'x',testsPass:true,externalCanaryRun:false})).toMatchObject({status:'READY_FOR_REVIEW',externalStatus:'NOT_RUN_EXTERNAL',engineLifecycle:'NOT_USED',deployment:'NOT_USED'}));
});
