import {createHash} from 'node:crypto';
/* Offline implementation primitives consumed by the runtime projections and coordinator tests.
 * They are deliberately fail-closed: an absent fact is UNKNOWN, never zero or success. */
export type Scope={environment:string;accountId:string;symbol:string;positionSide:'LONG'|'SHORT'|'BOTH'};
export type OwnerState='AI_ACTIVE'|'HANDOFF_PENDING'|'HUMAN_MANAGED'|'CLOSED';
export type Ownership={scope:string;cycleId:string;ownerState:OwnerState;ownerVersion:number;planRef:string|null;deadline:number|null;transitionedAt:number;reason:string;acknowledgedAt:number|null};
export const canonicalScope=(s:Scope)=>{if(!s.environment?.trim()||!s.accountId?.trim()||!s.symbol?.trim()||!['LONG','SHORT','BOTH'].includes(s.positionSide))throw new Error('INVALID_SCOPE');return JSON.stringify([s.environment,s.accountId,s.symbol.toUpperCase(),s.positionSide]);};
export function transitionOwner(current:Ownership|null,next:OwnerState,expectedVersion:number,now:number,reason:string):Ownership{
  if(!current||!current.scope||!current.cycleId||!Number.isSafeInteger(expectedVersion)||!Number.isFinite(now)||now<current.transitionedAt)throw new Error('INVALID_OWNER_TRANSITION');
  if(current.ownerVersion!==expectedVersion)throw new Error('OWNER_VERSION_CONFLICT');
  if(current?.ownerState==='CLOSED'&&next!=='CLOSED')throw new Error('CLOSED_OWNER_IMMUTABLE');
  if(current?.ownerState==='HUMAN_MANAGED'&&next==='AI_ACTIVE')throw new Error('HUMAN_REAUTHORIZATION_REQUIRED');
  return{scope:current?.scope??'',cycleId:current?.cycleId??'',ownerState:next,ownerVersion:(current?.ownerVersion??0)+1,planRef:current?.planRef??null,deadline:current?.deadline??null,transitionedAt:now,reason,acknowledgedAt:current?.acknowledgedAt??null};
}
export type QuantityClaim={scope:string;cycleId:string;source:'AI'|'MANUAL'|'TP';claimId:string;quantityUnits:number;version:number;status:'ACTIVE'|'RELEASED'|'UNKNOWN'};
export function allocateSharedQuantity(claims:QuantityClaim[],requested:number,available:number){if(!Number.isSafeInteger(available)||available<0||claims.some(c=>!Number.isSafeInteger(c.quantityUnits)||c.quantityUnits<0||!['ACTIVE','RELEASED','UNKNOWN'].includes(c.status))||new Set(claims.map(c=>c.claimId)).size!==claims.length||new Set(claims.map(c=>c.scope)).size>1)return{allowed:false,reason:'INVALID_BUDGET_FACTS',remaining:0};const used=claims.filter(c=>c.status!=='RELEASED').reduce((n,c)=>n+c.quantityUnits,0);if(!Number.isSafeInteger(requested)||requested<=0)return{allowed:false,reason:'INVALID_QUANTITY_UNITS',remaining:Math.max(0,available-used)};if(!Number.isSafeInteger(used)||!Number.isSafeInteger(used+requested)||used+requested>available)return{allowed:false,reason:'SHARED_QUANTITY_BUDGET_EXCEEDED',remaining:Math.max(0,available-used)};return{allowed:true,reason:'OK',remaining:available-used-requested};}

export type ExitFacts={grossRealizedToDate:number|null;incurredFees:number|null;signedFunding:number|null;projectedExitGross:number|null;projectedExitFee:number|null;uncertaintyBuffer:number|null;factsStatus:'EXACT'|'CONSERVATIVE_BOUND'|'UNKNOWN'|'CONFLICT'};
export function estimateExit(f:ExitFacts){const values=[f.grossRealizedToDate,f.incurredFees,f.signedFunding,f.projectedExitGross,f.projectedExitFee,f.uncertaintyBuffer];if(!['EXACT','CONSERVATIVE_BOUND'].includes(f.factsStatus)||values.some(v=>v==null||!Number.isFinite(v))||[f.incurredFees,f.projectedExitFee,f.uncertaintyBuffer].some(v=>v!<0))return{netIfAllClosed:null,status:f.factsStatus==='CONFLICT'?'CONFLICT' as const:'UNKNOWN' as const,reason:'EXIT_FACTS_INCOMPLETE'};return{netIfAllClosed:f.grossRealizedToDate!+f.projectedExitGross!-f.incurredFees!-f.projectedExitFee!+f.signedFunding!-f.uncertaintyBuffer!,status:f.factsStatus,reason:'EXACT_COST_FORMULA'};}
export type FundingFact={id:string;accountScope:string;asset:string;amount:number;time:number;cycleId?:string|null};
export function attributeFunding(facts:FundingFact[],input:{accountScope:string;cycleId:string;start:number;end:number;coverageComplete:boolean;asset?:string}){const rows=facts.filter(f=>f.accountScope===input.accountScope&&f.time>=input.start&&f.time<=input.end);if(!Number.isFinite(input.start)||!Number.isFinite(input.end)||input.start>=input.end||!input.accountScope||!input.cycleId||!input.coverageComplete)return{status:'UNKNOWN' as const,amount:null,sourceIds:rows.map(r=>r.id),reason:'COVERAGE_INCOMPLETE'};if(rows.some(r=>!Number.isFinite(r.amount)||r.cycleId!==input.cycleId||r.asset!==(input.asset??'USDT')||!r.id)||new Set(rows.map(r=>r.id)).size!==rows.length)return{status:'UNKNOWN' as const,amount:null,sourceIds:rows.map(r=>r.id),reason:'NONFINITE_FUNDING'};return{status:'EXACT' as const,amount:rows.reduce((n,r)=>n+r.amount,0),sourceIds:rows.map(r=>r.id),reason:'ACCOUNT_CYCLE_ASSET_COVERAGE_EXACT'};}
export function capitalBaseline(input:{snapshots:Array<{at:number;equity:number}>;flows:Array<{at:number;amount:number;type:'DEPOSIT'|'WITHDRAWAL'|'TRADING_PNL'}>;start:number;end:number}){const snapshots=input.snapshots.filter(s=>s.at>=input.start&&s.at<=input.end).sort((a,b)=>a.at-b.at),flows=input.flows.filter(f=>f.at>=input.start&&f.at<=input.end);if(!snapshots.length)return{status:'UNKNOWN' as const,startingEquity:null,endingEquity:null,flowAdjustedChange:null,gap:'NO_SNAPSHOT'};const first=snapshots[0]!,last=snapshots.at(-1)!;if(!Number.isFinite(input.start)||!Number.isFinite(input.end)||input.end<=input.start||first.at!==input.start||last.at!==input.end||snapshots.some(s=>!Number.isFinite(s.equity)||s.equity<0)||flows.some(f=>!Number.isFinite(f.amount)||(f.type!=='TRADING_PNL'&&f.amount<0)))return{status:'UNKNOWN' as const,startingEquity:null,endingEquity:null,flowAdjustedChange:null,gap:'INVALID_OR_PARTIAL_BASELINE'};const nonTrading=flows.filter(f=>f.type!=='TRADING_PNL').reduce((n,f)=>n+(f.type==='DEPOSIT'?f.amount:-f.amount),0),pnl=flows.filter(f=>f.type==='TRADING_PNL').reduce((n,f)=>n+f.amount,0);return{status:'EXACT' as const,startingEquity:first.equity,endingEquity:last.equity,flowAdjustedChange:last.equity-first.equity-nonTrading,gap:null,flowBreakdown:{nonTrading,pnl}};}
export function decideAiExit(input:{owner:OwnerState;now:number;deadline:number|null;estimate:ReturnType<typeof estimateExit>;thesisInvalid:boolean;lossLimit:number;minProfit:number;allowSmallLoss:boolean}){if(!Number.isFinite(input.now)||!Number.isFinite(input.lossLimit)||input.lossLimit<0||input.lossLimit>10||!Number.isFinite(input.minProfit)||input.minProfit<=0)return{outcome:'BLOCKED_FACTS',reason:'INVALID_EXIT_POLICY'} as const;if(input.owner!=='AI_ACTIVE')return{outcome:'BLOCKED_FACTS',reason:'OWNER_NOT_AI_ACTIVE'} as const;if(input.deadline==null||!Number.isFinite(input.deadline)||input.now>=input.deadline)return{outcome:'HANDOFF',reason:'AI_MANAGEMENT_EXPIRED'} as const;if(!['EXACT','CONSERVATIVE_BOUND'].includes(input.estimate.status)||input.estimate.netIfAllClosed==null||!Number.isFinite(input.estimate.netIfAllClosed))return{outcome:'BLOCKED_FACTS',reason:'EXIT_FACTS_UNKNOWN'} as const;const n=input.estimate.netIfAllClosed;if(n<-input.lossLimit)return{outcome:'HANDOFF',reason:'LOSS_LIMIT_EXCEEDED'} as const;if(input.thesisInvalid&&input.allowSmallLoss&&n<0)return{outcome:'ALLOW',reason:'THESIS_INVALID_SMALL_LOSS'} as const;if(n>=input.minProfit)return{outcome:'ALLOW',reason:'NET_PROFIT_THRESHOLD'} as const;return{outcome:'HOLD',reason:'NO_EXIT_CONDITION'} as const;}

export type PortfolioInput={equity:number|null;positions:Array<{scope:string;notional:number;unrealizedPnl:number;human:boolean}>;claims:QuantityClaim[];unknownClaims:number;stressLoss:number|null;coverage:'EXACT'|'UNKNOWN'};
export function portfolioRiskSnapshot(i:PortfolioInput){const human=i.positions.filter(p=>p.human),gross=i.positions.reduce((n,p)=>n+Math.abs(p.notional),0);return{asOf:Date.now(),equity:i.equity,positions:i.positions,claims:i.claims,unknownClaims:i.unknownClaims,humanBook:{count:human.length,notional:human.reduce((n,p)=>n+Math.abs(p.notional),0)},grossNotional:gross,stressLoss:i.stressLoss,coverage:i.coverage,admission:i.coverage==='EXACT'&&i.equity!=null&&Number.isFinite(i.equity)&&i.equity>0&&i.unknownClaims===0&&i.stressLoss!=null&&Number.isFinite(i.stressLoss)&&i.stressLoss>=0&&i.positions.every(p=>Number.isFinite(p.notional)&&Number.isFinite(p.unrealizedPnl))&&i.claims.every(c=>c.status!=='UNKNOWN')?'ELIGIBLE_FOR_OFFLINE_CHECK':'BLOCKED_FACTS'};}

export type TradePlan={schemaVersion:'V396-PLAN-1';planId:string;planVersion:number;cycleId:string;scope:string;quantityUnits:number;targetHorizonMinutes:number;managementDurationMs:number;aiManagementDeadline:number|null;direction:'LONG'|'SHORT'|'WAIT';evidenceRefs:string[];provenanceHash:string};
export function validateTradePlan(p:TradePlan,now:number){const errors:string[]=[];if(p.schemaVersion!=='V396-PLAN-1'||!p.planId||!p.cycleId||!p.scope||!p.provenanceHash||!Number.isSafeInteger(p.planVersion)||p.planVersion<1)errors.push('PLAN_ID_INVALID');if(!Number.isSafeInteger(p.quantityUnits)||p.quantityUnits<0||(p.direction!=='WAIT'&&p.quantityUnits===0))errors.push('QUANTITY_UNITS_INVALID');if(p.direction==='WAIT'&&p.quantityUnits!==0)errors.push('WAIT_WITH_QUANTITY');if(!Number.isFinite(now)||!['LONG','SHORT','WAIT'].includes(p.direction)||p.direction!=='WAIT'&&(p.aiManagementDeadline==null||!Number.isFinite(p.aiManagementDeadline)||p.aiManagementDeadline<=now||!Number.isFinite(p.managementDurationMs)||p.managementDurationMs<=0||!Number.isFinite(p.targetHorizonMinutes)||p.targetHorizonMinutes<=0))errors.push('DEADLINE_EXPIRED');if(!p.evidenceRefs.length)errors.push('EVIDENCE_MISSING');return{valid:errors.length===0,errors};}

export type TokenLedgerRow={eventId:string;role:'ENTRY'|'REVIEW'|'SCOUT'|'EXTERNAL_RESEARCH';inputTokens:number|null;outputTokens:number|null;latencyMs:number|null;usageStatus:'EXACT'|'UNKNOWN';promptHash:string;reason:string};
export function tokenLedgerTotal(rows:TokenLedgerRow[]){const known=rows.every(r=>r.usageStatus==='EXACT'&&Number.isSafeInteger(r.inputTokens)&&r.inputTokens!>=0&&Number.isSafeInteger(r.outputTokens)&&r.outputTokens!>=0)&&new Set(rows.map(r=>r.eventId)).size===rows.length;return{rows:rows.length,inputTokens:known?rows.reduce((n,r)=>n+r.inputTokens!,0):null,outputTokens:known?rows.reduce((n,r)=>n+r.outputTokens!,0):null,unknownUsage:rows.filter(r=>r.usageStatus==='UNKNOWN').length};}

export type ReplayEvent={at:number;availableAt:number;type:string;payload:unknown};
export function replayAvailable(events:ReplayEvent[],at:number){return events.filter(e=>e.availableAt<=at&&e.at<=at).sort((a,b)=>a.at-b.at);}
export function experimentId(manifest:unknown){
  const canonical=(v:unknown):unknown=>{if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,canonical(x)]));if(v===undefined||typeof v==='number'&&!Number.isFinite(v))throw new Error('INVALID_MANIFEST');return v;};
  return createHash('sha256').update(JSON.stringify(canonical(manifest))).digest('hex');
}
export function releaseReadiness(input:{sourceHash:string;settingsHash:string;schemaHash:string;testsPass:boolean;externalCanaryRun:boolean}){return{status:input.testsPass?'READY_FOR_REVIEW':'BLOCKED_OFFLINE',sourceHash:input.sourceHash,settingsHash:input.settingsHash,schemaHash:input.schemaHash,externalStatus:input.externalCanaryRun?'RUN':'NOT_RUN_EXTERNAL',engineLifecycle:'NOT_USED',deployment:'NOT_USED'};}
