import { createHmac } from 'node:crypto';
import type { EntryOrder, ManualOrder, Position, TakeProfitOrder } from '@zdj/contracts';
import type { ExchangeTradeAdapter, TradeAuditSnapshot, ExchangeTradeFill, ExchangeIncomeFact, ExchangeOrderFact } from '../../types.js';
import { BinanceTransport } from '../binance/BinanceTransport.js';
import { BinanceUserDataStream } from '../binance/BinanceUserDataStream.js';
import { binanceClientOrderIdFactory } from '../../services/binanceClientOrderIdFactory.js';
type Credentials={apiKey:string;apiSecret:string}|null;

export class ExternalTradeAdapter implements ExchangeTradeAdapter {
  private userStream:BinanceUserDataStream|null=null;private positionMode:{hedge:boolean;checkedAt:number}|null=null;private openTimeCache=new Map<string,{openedAt:number;source:Position['entryTimeSource'];checkedAt:number}>();private leverageCache=new Map<string,number>();private serverTime:{offset:number;fetchedAt:number}|null=null;private writeStats={testnetWrites:0,productionWrites:0,blockedProductionWriteAttempts:0,lastWriteAt:null as number|null,lastWritePath:null as string|null};
  constructor(private transport:BinanceTransport,private credentials:Credentials,private recvWindowMs=5000){}
  hasCredentials(){return Boolean(this.credentials);}
  setCredentials(credentials:Credentials){this.stopUserData();this.credentials=credentials;this.enrichmentGeneration++;this.enrichmentFlight=null;this.enrichment={income:null,incomeAsOf:null,prices:new Map(),pricesAsOf:null,lastAttempt:0,lastError:null};this.positionMode=null;this.openTimeCache.clear();this.leverageCache.clear();}
  private creds(){if(!this.credentials)throw new Error('TRADING_BLOCKED: credentials unavailable from SecretStore');if(!this.transport.effectiveBaseUrl().includes('testnet.binancefuture.com')){this.writeStats.blockedProductionWriteAttempts++;throw new Error('TESTNET_ONLY_WRITE_LOCK: production private writes disabled');}return this.credentials;}
  private serverTimeFlight:Promise<void>|null=null;
  private async refreshServerTime(){if(this.serverTime&&Date.now()-this.serverTime.fetchedAt<=5000)return;if(!this.serverTimeFlight)this.serverTimeFlight=this.transport.json<{serverTime:number}>('/fapi/v1/time').then(server=>{if(!Number.isFinite(server.serverTime))throw new Error('BINANCE_CLOCK_INVALID');this.serverTime={offset:server.serverTime-Date.now(),fetchedAt:Date.now()};}).finally(()=>{this.serverTimeFlight=null;});await this.serverTimeFlight;}
  private async signed<T>(method:string,path:string,params:Record<string,string|number|boolean>={},purpose?:string){const write=method!=='GET';if(write){try{this.transport.assertTestnetExchangeWrite();this.writeStats.testnetWrites++;this.writeStats.lastWriteAt=Date.now();this.writeStats.lastWritePath=path;}catch(error){this.writeStats.blockedProductionWriteAttempts++;throw error;}}const c=this.creds(),now=Date.now();await this.refreshServerTime();const timestamp=Date.now()+(this.serverTime?.offset??0),q=new URLSearchParams();for(const[k,v]of Object.entries({...params,recvWindow:Math.min(60_000,Math.max(this.recvWindowMs,60_000)),timestamp}))q.set(k,String(v));const payload=q.toString();q.set('signature',createHmac('sha256',c.apiSecret).update(payload).digest('hex'));return this.transport.json<T>(`${path}?${q}`,{method,purpose,headers:{'X-MBX-APIKEY':c.apiKey}});}
  writeBoundaryMetrics(){return{environment:this.transport.environment(),executionMode:this.transport.executionMode(),lockedToTestnet:true,...this.writeStats};}
  async fetchRealizedPnlSince(startTime:number,endTime=Date.now()){const rows=await this.signed<any[]>('GET','/fapi/v1/income',{incomeType:'REALIZED_PNL',startTime,endTime,limit:1000});return rows.reduce((sum,row)=>sum+Number(row.income??0),0);}
  private async hedgeMode(){if(this.positionMode&&Date.now()-this.positionMode.checkedAt<60_000)return this.positionMode.hedge;const value=await this.signed<{dualSidePosition:boolean}>('GET','/fapi/v1/positionSide/dual');this.positionMode={hedge:Boolean(value.dualSidePosition),checkedAt:Date.now()};return this.positionMode.hedge;}
  async placeEntry(order:EntryOrder){const hedge=await this.hedgeMode(),clientOrderId=binanceClientOrderIdFactory.assert(order.clientOrderId??binanceClientOrderIdFactory.create('ML',order.id)),params:Record<string,string|number|boolean>={symbol:order.symbol,side:order.side==='LONG'?'BUY':'SELL',type:'LIMIT',timeInForce:'GTX',quantity:order.quantity,price:order.price,newClientOrderId:clientOrderId};if(hedge)params.positionSide=order.side;const result=await this.signed<any>('POST','/fapi/v1/order',params,'NEW_ENTRY');return{...order,clientOrderId,exchangeOrderId:String(result.orderId),status:'WORKING' as const,updatedAt:Date.now()};}
  async findEntryByClientOrderId(order:EntryOrder){try{const clientOrderId=String(order.clientOrderId??'').trim(),exchangeOrderId=String(order.exchangeOrderId??'').trim();if(!clientOrderId&&!exchangeOrderId)return null;const query=clientOrderId?{symbol:order.symbol,origClientOrderId:binanceClientOrderIdFactory.assert(clientOrderId)}:{symbol:order.symbol,orderId:exchangeOrderId};const row=await this.signed<any>('GET','/fapi/v1/order',query);const executed=Number(row.executedQty??0),status=executed>=order.quantity-1e-10?'FILLED':executed>0&&['NEW','PARTIALLY_FILLED'].includes(String(row.status))?'PARTIALLY_FILLED':String(row.status)==='NEW'?'WORKING':String(row.status);let verifiedExchangeFills:any[]=[];if(executed>0){try{const rows=await this.signed<any[]>('GET','/fapi/v1/userTrades',{symbol:order.symbol,orderId:String(row.orderId),limit:1000});verifiedExchangeFills=rows.filter(fill=>String(fill.orderId)===String(row.orderId)).map(fill=>({symbol:String(fill.symbol??order.symbol),side:String(fill.side)==='BUY'?'BUY':'SELL',positionSide:['LONG','SHORT'].includes(String(fill.positionSide))?String(fill.positionSide):'BOTH',orderId:String(fill.orderId),clientOrderId:String(fill.clientOrderId??row.clientOrderId??clientOrderId),tradeId:String(fill.id??fill.tradeId),executionTime:Number(fill.time??row.updateTime??Date.now()),qty:Number(fill.qty??0),price:Number(fill.price??0),realizedPnl:Number(fill.realizedPnl??0),commission:Number(fill.commission??0),commissionAsset:String(fill.commissionAsset??''),maker:Boolean(fill.maker)})).filter(fill=>fill.qty>0&&fill.price>0);}catch{/* Exact order truth remains authoritative; fill detail is retried by the audit/sync path. */}}return{...order,clientOrderId:String(row.clientOrderId??order.clientOrderId??''),exchangeOrderId:String(row.orderId),quantity:Number(row.origQty??order.quantity),price:Number(row.price??order.price),filledQuantity:executed,status,statusSource:'BINANCE_EXACT_ORDER',updatedAt:Number(row.updateTime??Date.now()),orderType:String(row.type??'LIMIT'),timeInForce:String(row.timeInForce??'UNKNOWN'),maker:String(row.timeInForce??'')==='GTX',factSource:'BINANCE_EXACT_ORDER',verifiedAt:Date.now(),verifiedExchangeFills} as EntryOrder;}catch(error){if(String(error).includes('-2013')||String(error).includes('-2011'))return null;throw error;}}
  async cancelEntry(order:EntryOrder){
    try{await this.signed('DELETE','/fapi/v1/order',{symbol:order.symbol,origClientOrderId:order.clientOrderId??order.id});}
    catch(error){if(!String(error).includes('-2011'))throw error;}
    const verified=await this.findEntryByClientOrderId(order);
    return verified??{...order,status:'UNKNOWN' as const,updatedAt:Date.now()};
  }
  async replaceEntry(order:EntryOrder,price:number){
    // Native amend preserves exchange identity and cumulative fills; cancel/recreate could duplicate filled quantity.
    await this.signed('PUT','/fapi/v1/order',{symbol:order.symbol,origClientOrderId:order.clientOrderId??order.id,side:order.side==='LONG'?'BUY':'SELL',quantity:order.quantity,price},'NEW_ENTRY');
    const verified=await this.findEntryByClientOrderId(order);
    if(!verified)return{...order,status:'UNKNOWN' as const,updatedAt:Date.now()};
    return{...verified,repriceCount:order.repriceCount+1,absoluteExpiresAt:order.absoluteExpiresAt,createdAt:order.createdAt};
  }
  async placeTakeProfit(order:TakeProfitOrder){const hedge=await this.hedgeMode(),clientOrderId=binanceClientOrderIdFactory.assert(order.clientOrderId??binanceClientOrderIdFactory.create('TP',order.id)),params:Record<string,string|number|boolean>={symbol:order.symbol,side:order.side,type:'LIMIT',timeInForce:'GTC',quantity:order.quantity,price:order.price,newClientOrderId:clientOrderId};if(hedge)params.positionSide=order.side==='SELL'?'LONG':'SHORT';else params.reduceOnly=true;const result=await this.signed<any>('POST','/fapi/v1/order',params);return{...order,clientOrderId,exchangeOrderId:String(result.orderId),status:'WORKING' as const,updatedAt:Date.now()};}
  async placeManualOrder(request:{clientOrderId:string;internalOrderId?:string;symbol:string;side:'BUY'|'SELL';positionSide?:'LONG'|'SHORT';type:'LIMIT'|'MARKET';quantity:number;price?:number;reduceOnly:boolean;postOnly:boolean}){const hedge=await this.hedgeMode(),clientOrderId=binanceClientOrderIdFactory.assert(request.clientOrderId),params:Record<string,string|number|boolean>={symbol:request.symbol,side:request.side,type:request.type,quantity:request.quantity,newClientOrderId:clientOrderId};if(request.type==='LIMIT'){params.price=request.price!;params.timeInForce=request.postOnly?'GTX':'GTC';}if(request.reduceOnly&&!hedge)params.reduceOnly=true;if(hedge&&request.positionSide)params.positionSide=request.positionSide;const result=await this.signed<any>('POST','/fapi/v1/order',params);const now=Date.now(),id=request.internalOrderId??`manual_order_${now}`;return{id,intentId:request.internalOrderId??id,clientOrderId,exchangeOrderId:String(result.orderId),positionId:'',symbol:request.symbol,side:request.side,positionSide:hedge?(request.positionSide??null):'BOTH',type:request.type,quantity:request.quantity,price:request.price??null,reduceOnly:request.reduceOnly,postOnly:request.postOnly,status:(result.status==='FILLED'?'FILLED':'WORKING') as 'FILLED'|'WORKING',filledQuantity:Number(result.executedQty??0),createdAt:now,updatedAt:now} as ManualOrder;}
  async findManualByClientOrderId(request:{symbol:string;clientOrderId:string;internalOrderId:string;positionId:string;side:'BUY'|'SELL';positionSide:'LONG'|'SHORT';quantity:number;price:number;reduceOnly:boolean;postOnly:boolean}){try{const row=await this.signed<any>('GET','/fapi/v1/order',{symbol:request.symbol,origClientOrderId:binanceClientOrderIdFactory.assert(request.clientOrderId)}),executed=Number(row.executedQty??0),raw=String(row.status),status=executed>=request.quantity-1e-10?'FILLED':executed>0&&['NEW','PARTIALLY_FILLED'].includes(raw)?'PARTIALLY_FILLED':['NEW','PARTIALLY_FILLED'].includes(raw)?'WORKING':raw==='CANCELED'?'CANCELED':raw==='EXPIRED'?'EXPIRED':raw==='REJECTED'?'REJECTED':'UNKNOWN',now=Date.now();return{id:request.internalOrderId,intentId:request.internalOrderId,clientOrderId:String(row.clientOrderId??request.clientOrderId),exchangeOrderId:String(row.orderId),positionId:request.positionId,symbol:request.symbol,side:request.side,positionSide:(String(row.positionSide??request.positionSide) as any),type:'LIMIT' as const,quantity:Number(row.origQty??request.quantity),price:Number(row.price??request.price),reduceOnly:request.reduceOnly,postOnly:request.postOnly,status,filledQuantity:executed,createdAt:Number(row.time??now),updatedAt:Number(row.updateTime??now)} as ManualOrder;}catch(error){if(String(error).includes('-2013')||String(error).includes('-2011'))return null;throw error;}}
  async cancelManualOrder(order:ManualOrder){
    try{await this.signed('DELETE','/fapi/v1/order',{symbol:order.symbol,orderId:order.exchangeOrderId?Number(order.exchangeOrderId):undefined,origClientOrderId:order.clientOrderId});}
    catch(error){if(!String(error).includes('-2011'))throw error;}
    const verified=await this.findManualByClientOrderId({symbol:order.symbol,clientOrderId:order.clientOrderId!,internalOrderId:order.id,positionId:order.positionId,side:order.side,positionSide:order.positionSide==='LONG'||order.positionSide==='SHORT'?order.positionSide:order.side==='SELL'?'LONG':'SHORT',quantity:order.quantity,price:order.price??0,reduceOnly:order.reduceOnly,postOnly:order.postOnly});
    return verified?{...verified,intentId:order.intentId,createdAt:order.createdAt}:{...order,status:'UNKNOWN' as const,updatedAt:Date.now()};
  }
  async findTakeProfitByClientOrderId(order:TakeProfitOrder){
    try{const row=await this.signed<any>('GET','/fapi/v1/order',{symbol:order.symbol,origClientOrderId:order.clientOrderId??order.id});const raw=String(row.status),executed=Number(row.executedQty??0),quantity=Number(row.origQty??order.quantity);
      const status:TakeProfitOrder['status']=executed>=quantity-1e-10?'FILLED':['NEW','PARTIALLY_FILLED'].includes(raw)?'WORKING':['FILLED','CANCELED','EXPIRED','REJECTED'].includes(raw)?raw as TakeProfitOrder['status']:'UNKNOWN';
      return{...order,exchangeOrderId:String(row.orderId),quantity:Math.max(0,quantity-executed),price:Number(row.price??order.price),status,updatedAt:Number(row.updateTime??Date.now())};
    }catch(error){if(String(error).includes('-2013')||String(error).includes('-2011'))return null;throw error;}
  }
  async cancelTakeProfit(order:TakeProfitOrder){
    try{await this.signed('DELETE','/fapi/v1/order',{symbol:order.symbol,origClientOrderId:order.clientOrderId??order.id});}catch(error){if(!String(error).includes('-2011'))throw error;}
    const verified=await this.findTakeProfitByClientOrderId(order);if(!verified||verified.status==='UNKNOWN'||verified.status==='WORKING')throw new Error('TP_CANCEL_RESULT_UNVERIFIED');return verified;
  }
  async cancelSymbolOrders(symbol:string,conditional:boolean){const rows=await this.signed<any[]>('GET','/fapi/v1/openOrders',{symbol}),conditionalTypes=new Set(['STOP','STOP_MARKET','TAKE_PROFIT','TAKE_PROFIT_MARKET','TRAILING_STOP_MARKET']);let canceled=0,skipped=0;for(const row of rows){const type=String(row.type),isConditional=conditionalTypes.has(type)||String(row.clientOrderId??'').startsWith('tp_');if(isConditional!==conditional){skipped++;continue;}try{await this.signed('DELETE','/fapi/v1/order',{symbol,orderId:Number(row.orderId)});canceled++;}catch(error){if(String(error).includes('-2011')){canceled++;continue;}throw error;}}return{symbol,conditional,canceled,skipped,scope:conditional?'SYMBOL_CONDITIONAL':'SYMBOL_ORDINARY_LIMIT'};}
  async fetchOpenOrders(symbol?:string){const verifiedAt=Date.now(),rows=await this.signed<any[]>('GET','/fapi/v1/openOrders',symbol?{symbol}:undefined);return rows.map(row=>String(row.clientOrderId).startsWith('tp_')?({id:String(row.clientOrderId),clientOrderId:String(row.clientOrderId??''),exchangeOrderId:String(row.orderId),positionId:'exchange-unknown',positionSide:String(row.positionSide??'BOTH'),symbol:String(row.symbol),side:row.side,quantity:Math.max(0,Number(row.origQty)-Number(row.executedQty??0)),price:Number(row.price),status:'WORKING',createdAt:Number(row.time??Date.now()),updatedAt:Number(row.updateTime??Date.now()),factSource:'BINANCE_OPEN_ORDERS',verifiedAt} as TakeProfitOrder):({id:String(row.clientOrderId||`${row.symbol}:${row.orderId}`),clientOrderId:String(row.clientOrderId??''),exchangeOrderId:String(row.orderId),symbol:String(row.symbol),side:row.side==='BUY'?'LONG':'SHORT',quantity:Number(row.origQty),price:Number(row.price),filledQuantity:Number(row.executedQty),leverage:1,status:row.status==='NEW'?'WORKING':row.status,createdAt:Number(row.time??Date.now()),updatedAt:Number(row.updateTime??Date.now()),absoluteExpiresAt:Number.MAX_SAFE_INTEGER,repriceCount:0,intentId:'exchange-recovered',reachability:0,orderType:String(row.type??'LIMIT'),timeInForce:String(row.timeInForce??'UNKNOWN'),maker:String(row.timeInForce??'')==='GTX',factSource:'BINANCE_OPEN_ORDERS',verifiedAt} as EntryOrder));}
  async fetchRecentTradeAudit(startTime:number,endTime:number,maxFills=500):Promise<TradeAuditSnapshot>{
    const [incomeRows,positions,openOrders]=await Promise.all([
      this.signed<any[]>('GET','/fapi/v1/income',{startTime,endTime,limit:1000}),
      this.fetchPositions(),this.fetchOpenOrders(),
    ]);
    const income=incomeRows.map(row=>({symbol:String(row.symbol??''),incomeType:String(row.incomeType??'UNKNOWN'),income:Number(row.income??0),asset:String(row.asset??''),time:Number(row.time??0),info:row.info==null?null:String(row.info),tradeId:row.tradeId==null?null:String(row.tradeId),transactionId:row.tranId==null?null:String(row.tranId)})).filter(row=>row.time>=startTime&&row.time<=endTime);
    const symbols=[...new Set([...income.map(row=>row.symbol),...positions.map(row=>row.symbol),...openOrders.map(row=>row.symbol)].filter(Boolean))];
    const fills:TradeAuditSnapshot['fills']=[],orders:TradeAuditSnapshot['orders']=[];
    for(const symbol of symbols){
      const [trades,allOrders]=await Promise.all([
        this.signed<any[]>('GET','/fapi/v1/userTrades',{symbol,startTime,endTime,limit:1000}),
        this.signed<any[]>('GET','/fapi/v1/allOrders',{symbol,startTime,endTime,limit:1000}),
      ]);
      for(const row of trades)fills.push({symbol:String(row.symbol),side:String(row.side)==='BUY'?'BUY':'SELL',positionSide:['LONG','SHORT'].includes(String(row.positionSide))?String(row.positionSide) as 'LONG'|'SHORT':'BOTH',orderId:String(row.orderId),clientOrderId:String(row.clientOrderId??''),tradeId:String(row.id??row.tradeId??''),executionTime:Number(row.time??0),qty:Number(row.qty??0),price:Number(row.price??0),realizedPnl:Number(row.realizedPnl??0),commission:Number(row.commission??0),commissionAsset:String(row.commissionAsset??''),maker:Boolean(row.maker)});
      for(const row of allOrders)orders.push({symbol:String(row.symbol),orderId:String(row.orderId),clientOrderId:String(row.clientOrderId??''),side:String(row.side),positionSide:String(row.positionSide??'BOTH'),status:String(row.status),type:String(row.type),origQty:Number(row.origQty??0),executedQty:Number(row.executedQty??0),avgPrice:Number(row.avgPrice??row.price??0),updateTime:Number(row.updateTime??row.time??0)});
    }
    const orderById=new Map(orders.map(row=>[row.orderId,row]));for(const fill of fills){const order=orderById.get(fill.orderId);if(order)fill.clientOrderId=order.clientOrderId;}
    fills.sort((a,b)=>a.executionTime-b.executionTime);const selected=fills.slice(Math.max(0,fills.length-Math.max(1,Math.min(1000,maxFills))));
    const selectedOrders=new Set(selected.map(fill=>fill.orderId));return{window:{startTime,endTime},source:'BINANCE_TESTNET_PRIVATE',fetchedAt:Date.now(),fills:selected,income,orders:orders.filter(order=>selectedOrders.has(order.orderId)||order.updateTime>=startTime),positions,openOrders};
  }
  async fetchSymbolTradeFacts(symbol:string,startTime:number,endTime:number):Promise<{fills:ExchangeTradeFill[];income:ExchangeIncomeFact[];orders:ExchangeOrderFact[]}>{const [incomeRows,trades,allOrders]=await Promise.all([this.signed<any[]>('GET','/fapi/v1/income',{symbol,startTime,endTime,limit:1000}),this.signed<any[]>('GET','/fapi/v1/userTrades',{symbol,startTime,endTime,limit:1000}),this.signed<any[]>('GET','/fapi/v1/allOrders',{symbol,startTime,endTime,limit:1000})]);return{fills:trades.map(row=>({symbol:String(row.symbol),side:(String(row.side)==='BUY'?'BUY':'SELL') as 'BUY'|'SELL',positionSide:(['LONG','SHORT'].includes(String(row.positionSide))?String(row.positionSide):'BOTH') as 'LONG'|'SHORT'|'BOTH',orderId:String(row.orderId),clientOrderId:String(row.clientOrderId??''),tradeId:String(row.id??row.tradeId??''),executionTime:Number(row.time??0),qty:Number(row.qty??0),price:Number(row.price??0),realizedPnl:Number(row.realizedPnl??0),commission:Number(row.commission??0),commissionAsset:String(row.commissionAsset??''),maker:Boolean(row.maker)})),income:incomeRows.map(row=>({symbol:String(row.symbol??symbol),incomeType:String(row.incomeType??'UNKNOWN'),income:Number(row.income??0),asset:String(row.asset??''),time:Number(row.time??0),info:row.info==null?null:String(row.info),tradeId:row.tradeId==null?null:String(row.tradeId),transactionId:row.tranId==null?null:String(row.tranId)})),orders:allOrders.map(row=>({symbol:String(row.symbol),orderId:String(row.orderId),clientOrderId:String(row.clientOrderId??''),side:String(row.side),positionSide:String(row.positionSide??'BOTH'),status:String(row.status),type:String(row.type),origQty:Number(row.origQty??0),executedQty:Number(row.executedQty??0),avgPrice:Number(row.avgPrice??row.price??0),updateTime:Number(row.updateTime??row.time??0)}))};}
  private async recoverOpenedAt(symbol:string,side:'LONG'|'SHORT',_quantity:number){const key=`${symbol}:${side}`,cached=this.openTimeCache.get(key);if(cached&&Date.now()-cached.checkedAt<6*60*60_000)return cached;const result={openedAt:0,source:'UNKNOWN' as const,checkedAt:Date.now()};this.openTimeCache.set(key,result);return result;}
  async fetchPositions(){const rows=(await this.signed<any[]>('GET','/fapi/v2/positionRisk')).filter(row=>Number(row.positionAmt)!==0);return Promise.all(rows.map(async row=>{const amount=Number(row.positionAmt),direction:'LONG'|'SHORT'=amount>0?'LONG':'SHORT',time=await this.recoverOpenedAt(String(row.symbol),direction,Math.abs(amount));return{id:`exchange_${row.symbol}_${row.positionSide}`,symbol:String(row.symbol),side:direction,quantity:Math.abs(amount),entryPrice:Number(row.entryPrice),markPrice:Number(row.markPrice),leverage:Number(row.leverage),unrealizedPnl:Number(row.unRealizedProfit),unrealizedPnlPercent:0,openedAt:time.openedAt,firstObservedAt:null,entryTimeSource:time.source,managementStatus:'AUTO_MANAGED',humanManagedAt:null,tpStatus:'PENDING',tpOrderId:null,tpLastVerifiedAt:null,tpCoverageSource:'NONE'} as Position;}));}
  private enrichmentGeneration=0;
  private enrichmentFlight:Promise<void>|null=null;
  private enrichment={income:null as number|null,incomeAsOf:null as number|null,prices:new Map<string,number>(),pricesAsOf:null as number|null,lastAttempt:0,lastError:null as string|null};
  async fetchAccountSnapshot(){
    const account=await this.signed<any>('GET','/fapi/v2/account');
    const nonzero=(account.assets??[]).filter((row:any)=>Math.abs(Number(row.walletBalance??0))>0||Math.abs(Number(row.availableBalance??0))>0),prices=new Map<string,number>();
    for(const [asset,price] of (Date.now()-(this.enrichment.pricesAsOf??0)<120_000?this.enrichment.prices:new Map<string,number>()))prices.set(asset,price);
    if(!this.enrichmentFlight&&Date.now()-this.enrichment.lastAttempt>=60_000){
      this.enrichment.lastAttempt=Date.now();const generation=this.enrichmentGeneration,cache=this.enrichment;
      this.enrichmentFlight=Promise.allSettled([
        this.signed<any[]>('GET','/fapi/v1/income',{incomeType:'REALIZED_PNL',startTime:Date.now()-24*60*60_000,limit:1000}).then(rows=>{cache.income=rows.reduce((sum,row)=>sum+Number(row.income??0),0);cache.incomeAsOf=Date.now();}),
        ...nonzero.filter((row:any)=>!['USDT','USDC','BUSD'].includes(String(row.asset))).map(async(row:any)=>{const quote=await this.transport.json<any>(`/fapi/v1/premiumIndex?symbol=${row.asset}USDT`);const price=Number(quote.markPrice);if(!Number.isFinite(price)||price<=0)throw new Error('VALUATION_PRICE_INVALID');cache.prices.set(String(row.asset),price);cache.pricesAsOf=Date.now();})
      ]).then(results=>{cache.lastError=results.some(r=>r.status==='rejected')?'ENRICHMENT_PARTIAL_FAILURE':null;}).finally(()=>{if(generation===this.enrichmentGeneration)this.enrichmentFlight=null;});
    }
    const assets=nonzero.map((row:any)=>{const asset=String(row.asset),wallet=Number(row.walletBalance??0),stable=['USDT','USDC','BUSD'].includes(asset),price=stable?1:prices.get(asset);return{asset,walletBalance:wallet,availableBalance:Number(row.availableBalance??0),crossWalletBalance:row.crossWalletBalance==null?null:Number(row.crossWalletBalance),unrealizedPnl:Number(row.unrealizedProfit??0),usdValue:Number.isFinite(price)?wallet*price!:null,marginEligible:Boolean(row.marginAvailable??asset==='USDT')};});
    const usdt=assets.find(row=>row.asset==='USDT'),equity=assets.reduce((sum,row)=>sum+(row.usdValue??0),0)+Number(account.totalUnrealizedProfit??0);
    return{walletBalanceUsd:assets.reduce((sum,row)=>sum+(row.usdValue??0),0),availableUsd:Number(usdt?.availableBalance??account.availableBalance),equityUsd:assets.some(row=>row.usdValue===null)&&account.totalMarginBalance!=null&&Number.isFinite(Number(account.totalMarginBalance))?Number(account.totalMarginBalance):equity,unrealizedPnlUsd:Number(account.totalUnrealizedProfit??0),realizedPnlUsd24h:Date.now()-(this.enrichment.incomeAsOf??0)<120_000?this.enrichment.income:null,assets,enrichment:{incomeAsOf:this.enrichment.incomeAsOf,valuationAsOf:this.enrichment.pricesAsOf,error:this.enrichment.lastError,pending:Boolean(this.enrichmentFlight)},asOf:Date.now()};
  }
  async validatePrivate(){const account=await this.fetchAccountSnapshot(),orders=await this.fetchOpenOrders(),positions=await this.fetchPositions();return{status:'BINANCE TESTNET PRIVATE READY',endpoint:this.transport.effectiveBaseUrl(),accountAvailable:Number.isFinite(account.walletBalanceUsd),openOrders:orders.length,positions:positions.length};}
  async setLeverage(symbol:string,requested:number){let maximum=this.leverageCache.get(symbol);if(!maximum){const rows=await this.signed<any[]>('GET','/fapi/v1/leverageBracket',{symbol}),bracket=Array.isArray(rows)?rows[0]:rows;maximum=Math.max(1,Number(bracket?.brackets?.[0]?.initialLeverage??requested));this.leverageCache.set(symbol,maximum);}const leverage=Math.min(requested,maximum);await this.signed('POST','/fapi/v1/leverage',{symbol,leverage});}
  startUserData(onEvent:(event:any)=>void){if(!this.credentials||!this.transport.effectiveBaseUrl().includes('testnet.binancefuture.com'))return null;this.userStream=new BinanceUserDataStream(this.transport,this.credentials.apiKey,onEvent);this.userStream.start();return this.userStream;}
  stopUserData(){this.userStream?.stop();this.userStream=null;}
  userDataMetrics(){return this.userStream?.metrics()??{state:'GATED'};}
}
