import {describe,it,expect,vi} from 'vitest';
import {EventEmitter} from 'node:events';
import {createApiRouter,withExecutionOutcomes} from './router.js';
vi.mock('./projections.js',()=>({dashboardProjection:()=>({})}));
const now=Date.now();
const o={id:'entry',intentId:'intent',decisionChainId:'primary',clientOrderId:'client',exchangeOrderId:'exchange',quantity:135,price:7.442,filledQuantity:0,status:'CANCELED',createdAt:now-900000,updatedAt:now-10000};
const events=[{id:'created',type:'ENTRY_ORDER_CREATED',ts:now-890000,payload:{brainRunId:'primary',order:{...o,status:'WORKING',submittedAt:now-890000}}},{id:'review',type:'PENDING_ENTRY_REVIEW_COMPLETED',ts:now-11000,payload:{orderId:'entry',runId:'review',decision:'CANCEL'}},{id:'cancel',type:'ENTRY_ORDER_USER_DATA_CONFIRMED',ts:now-10000,payload:{orderId:'entry',clientOrderId:'client',exchangeOrderId:'exchange',status:'CANCELED',filledQuantity:0}}];
const runtime=()=>({pipelineStatus:()=>({}),market:{metrics:()=>({})},events:Object.assign(new EventEmitter(),{publish:vi.fn()}),state:{runtimeControl:{capital:{generation:1}},account:{},entryOrders:new Map([['entry',o]]),tpOrders:new Map()},settingsStore:{runtimeEvents:vi.fn(()=>events),getAiRun:vi.fn(()=>({normalizedPreview:JSON.stringify({reason:'actual archived model reason'})}))},reconciliation:{health:()=>({}),currentOpenEntryOrders:vi.fn(()=>({status:'READY',verifiedAt:now,items:[]})),currentOpenManualOrders:vi.fn(()=>({status:'READY',items:[]}))}} as any);
describe('read-only orders API and Run projection',()=>{
 it('returns complete normal terminal history separately from current open orders',()=>{const r=runtime(),router=createApiRouter(r) as any;const handler=router.stack.find((l:any)=>l.route?.path==='/orders').route.stack[0].handle;const response={json:vi.fn()};handler({query:{status:'CANCELED',limit:'50'}},response);expect(response.json.mock.calls[0][0]).toMatchObject({entry:[],entryHistory:{readOnly:true,total:1,items:[{id:'entry',decisionRunId:'primary',lifecycleStatus:'CANCELED',review:[{reason:'actual archived model reason'}]}]}});expect(r.settingsStore.runtimeEvents).toHaveBeenCalledTimes(1);expect(o.status).toBe('CANCELED');r.events.emit('event',{type:'RUNTIME_STOPPED'});});
 it('Run list consumes identity-bound terminal more than five minutes after decision',()=>{const r=runtime(),items=withExecutionOutcomes(r,[{id:'primary',role:'PRIMARY_BRAIN',decision:'PLACE_SHORT',completedAt:now-900000}]);expect(items[0].execution).toMatchObject({executionState:'CANCELED',wasSubmitted:true,terminalAt:now-10000});});
 it('a different Primary on the same symbol cannot inherit the previous order',()=>{const r=runtime();const items=withExecutionOutcomes(r,[{id:'unrelated',symbol:'UNIUSDT',role:'PRIMARY_BRAIN',decision:'PLACE_SHORT',completedAt:now}]);expect(items[0].execution?.orderId).toBeNull();});
});
