import {mkdtemp,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import { afterEach,describe,expect,it } from 'vitest';import { EngineRuntime } from '../runtime/appRuntime.js';import { dashboardProjection,redactAudit } from './projections.js';import {TradeRecordSchema} from '@zdj/contracts';
let runtime:EngineRuntime|null=null,dir='';afterEach(async()=>{runtime?.stop();if(dir)await rm(dir,{recursive:true,force:true});});describe('dashboard projections',()=>{it('schema-validates one server-side snapshot and redacts audit secrets',async()=>{dir=await mkdtemp(path.join(os.tmpdir(),'mits-projection-'));runtime=await EngineRuntime.createTestHarness({configDir:'../../config',dataDir:dir});await runtime.market.refresh(120);runtime.universe.refresh();const view=dashboardProjection(runtime);expect(view.universe.total).toBe(120);expect(redactAudit({apiKey:'abcd',apiSecret:'secret-value',ok:true})).not.toContain('secret-value');expect(redactAudit({apiKey:'abcd'})).toContain('[REDACTED]');},15_000);it('redacts undefined, null, strings, errors and cyclic values without throwing',()=>{const cyclic:any={};cyclic.self=cyclic;const values=[undefined,null,'apiSecret=hidden',new Error('authorization: hidden'),cyclic];for(const value of values)expect(()=>redactAudit(value)).not.toThrow();expect(redactAudit(undefined)).toBe('undefined');expect(redactAudit(null)).toBe('null');expect(redactAudit('apiSecret=hidden')).not.toContain('hidden');expect(redactAudit(new Error('authorization: hidden'))).not.toContain('hidden');expect(redactAudit(cyclic)).toContain('[Circular]');});});
it('projects exchange-complete trading PnL while funding keeps canonical net unavailable',async()=>{dir=await mkdtemp(path.join(os.tmpdir(),'mits-projection-funding-'));runtime=await EngineRuntime.createTestHarness({configDir:'../../config',dataDir:dir});const record=TradeRecordSchema.parse({tradeId:'ex-funding-only',symbol:'ADAUSDC',direction:'LONG',openedAt:1,closedAt:2,durationMs:1,entryQty:1,exitQty:1,remainingQty:0,entryAveragePrice:1,exitAveragePrice:2,entryFee:.1,exitFee:.1,totalFee:.2,funding:null,entryGrossNotional:1,exitGrossNotional:2,marginUsed:1,netRoiOnMargin:null,netReturnOnNotional:null,entryFillCount:1,exitFillCount:1,feeBreakdown:[],grossRealizedPnl:.4,netPnl:null,tradingNetPnlExFunding:.2,fundingAttributionStatus:'UNKNOWN',closeReason:'TP',status:'CLOSED',entryRunId:null,entryIntentId:'entry_one',entryOrderIds:['entry_one'],exitOrderIds:['tp_one'],source:'SYSTEM',regime:null,feeCompleteness:'COMPLETE',recordCompleteness:'COMPLETE',classification:'COMPLETE',canonical:true,duplicateOf:null,cycleId:'cycle_one',repairSource:null,linkedFillIds:['entry-fill','exit-fill'],missingFacts:[],integrityFlags:[],createdAt:1,updatedAt:2,firstObservedAt:1});runtime.state.tradeRecords.set(record.tradeId,record);const view=dashboardProjection(runtime);expect(view.tradeTradingNetExFunding).toBe(.2);expect(view.tradeNetPnl).toBeNull();expect(view.tradeFundingUnknownCount).toBe(1);});

it('projects the configured 5000+5000 wallet baseline separately from rolling local and exchange PnL',async()=>{
  dir=await mkdtemp(path.join(os.tmpdir(),'mits-projection-performance-'));
  runtime=await EngineRuntime.createTestHarness({configDir:'../../config',dataDir:dir});
  const now=Date.now();
  runtime.state.settings.performanceTracking={enabled:true,baselineWalletByQuote:{USDT:5000,USDC:5000},rollingDays:7};
  runtime.state.account={...runtime.state.account,status:'READY',asOf:now,reason:null,
    walletBalanceUsd:10808.93368463,availableUsd:7450,equityUsd:10000,unrealizedPnlUsd:-808.93368463,realizedPnlUsd24h:null,
    assets:[
      {asset:'USDT',walletBalance:5806.75955113,availableBalance:2553.19425728,crossWalletBalance:null,unrealizedPnl:-800,usdValue:5806.75955113,marginEligible:true},
      {asset:'USDC',walletBalance:5002.1741335,availableBalance:4897.19730283,crossWalletBalance:null,unrealizedPnl:-8.93368463,usdValue:5002.1741335,marginEligible:true},
    ]};
  const record=TradeRecordSchema.parse({tradeId:'weekly-local',symbol:'BTCUSDT',direction:'LONG',openedAt:now-60_000,closedAt:now-30_000,durationMs:30_000,entryQty:1,exitQty:1,remainingQty:0,entryAveragePrice:100,exitAveragePrice:101,entryFee:.1,exitFee:.1,totalFee:.2,funding:null,entryGrossNotional:100,exitGrossNotional:101,marginUsed:10,netRoiOnMargin:null,netReturnOnNotional:null,entryFillCount:1,exitFillCount:1,feeBreakdown:[],grossRealizedPnl:1,tradingNetPnlExFunding:.8,netPnl:null,closeReason:'TP',status:'CLOSED',entryRunId:null,entryIntentId:'entry_week',entryOrderIds:['entry_week'],exitOrderIds:['exit_week'],source:'SYSTEM',regime:null,feeCompleteness:'COMPLETE',recordCompleteness:'COMPLETE',classification:'COMPLETE',canonical:true,duplicateOf:null,cycleId:'cycle_week',repairSource:null,linkedFillIds:['f1','f2'],missingFacts:[],integrityFlags:[],createdAt:now-60_000,updatedAt:now-30_000,firstObservedAt:now-60_000,fundingAttributionStatus:'UNKNOWN',pnlBasis:'CANONICAL_NET_WITH_FUNDING_UNKNOWN'});
  runtime.state.tradeRecords.set(record.tradeId,record);
  (runtime as any).exchangePerformance={status:'READY',source:'BINANCE_INCOME',fetchedAt:now,windowStart:now-7*86_400_000,windowEnd:now,realizedPnl:10,commission:-2,funding:1,tradingNetExFunding:8,allInNet:9,cashFlow:0,otherIncome:0,rowCount:13,realizedEvents:5,commissionEvents:5,fundingEvents:3,error:null};
  const view=dashboardProjection(runtime);
  expect(view.performanceTracking?.baseline).toMatchObject({configuredCombinedWallet:10000,currentCombinedWallet:10808.93368463,status:'READY'});
  expect(view.performanceTracking?.baseline.combinedWalletGain).toBeCloseTo(808.93368463,8);
  expect(view.performanceTracking?.rolling.local).toMatchObject({completeCycles:1,exFundingNet:.8,fundingUnknownCycles:1});
  expect(view.performanceTracking?.rolling.exchange).toMatchObject({tradingNetExFunding:8,funding:1,allInNet:9,cashFlow:0});
});
