import express from 'express';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { BinanceTransport } from '../adapters/binance/BinanceTransport.js';
import { createRuntimeSettingsResourcesRouter } from './runtimeSettingsResources.js';

const servers:any[]=[];afterEach(async()=>{for(const server of servers.splice(0))await new Promise<void>(resolve=>server.close(()=>resolve()));});
function settings(){return{settingsVersion:1,connections:{proxy:{enabled:true,protocol:'SOCKS5H',url:'socks5h://127.0.0.1:20081',forceBinanceRest:true,forceBinanceWs:true,proxyDns:true,binanceRestRoute:'CONFIGURED',bypassLocalhost:true,failClosed:true},exchange:{provider:'BINANCE_USDM',environment:'TESTNET',productionBaseUrl:'https://fapi.binance.com',testnetBaseUrl:'https://testnet.binancefuture.com',credentialRef:'binance-primary',recvWindowMs:5000,autoTimeSync:true},marketDataMode:'BINANCE',executionMode:'READ_ONLY',aiMode:'OPENAI_COMPATIBLE'},aiResources:[{id:'primary',role:'PRIMARY_BRAIN',enabled:true,baseUrl:'http://127.0.0.1:8084/v1',model:'qwen',maxConcurrency:1,gpu:'gpu'}]};}
async function fixture(){const state:any={settings:settings(),aiResources:[]},load=new Map([['primary',{active:0,totalRuns:0,failures:0,lastLatencyMs:null,currentSymbol:null,currentRunId:null,currentStartedAt:null,lastCompletedAt:null,lastDirection:null,lastDecision:null,idleReason:'WAITING_CANDIDATE',nextStep:'wait',queueDepth:0}]]),runtime:any={state,ai:{load,probeResources:vi.fn().mockResolvedValue(undefined)},events:{publish:vi.fn()},settingsStore:{resourceSave:vi.fn().mockResolvedValue(undefined),resourceDelete:vi.fn().mockResolvedValue(undefined)},updateSettings:vi.fn(async(input:any)=>{state.settings={...input,settingsVersion:Number(input.settingsVersion??0)+1};return state.settings;})};state.aiResources=[];const app=express();app.use(express.json());app.use(createRuntimeSettingsResourcesRouter(runtime));const server=app.listen(0);servers.push(server);await new Promise(resolve=>server.once('listening',resolve));const address=server.address() as any;return{runtime,url:`http://127.0.0.1:${address.port}`};}

describe('runtime settings resource CRUD',()=>{
  it('persists AI CRUD into SystemSettings and immediately refreshes runtime AI resources',async()=>{const{runtime,url}=await fixture();const item={id:'scout2',role:'SCOUT',baseUrl:'http://127.0.0.1:8081/v1',model:'qwen-scout',maxConcurrency:1,gpu:'B580',enabled:true,status:'READY'};const saved=await fetch(`${url}/settings/resources/ai`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(item)});expect(saved.status).toBe(200);expect(runtime.updateSettings).toHaveBeenCalledTimes(1);expect(runtime.state.settings.aiResources.map((x:any)=>x.id)).toContain('scout2');expect(runtime.state.aiResources.map((x:any)=>x.id)).toContain('scout2');expect(runtime.ai.load.has('scout2')).toBe(true);const removed=await fetch(`${url}/settings/resources/ai/scout2`,{method:'DELETE'});expect(removed.status).toBe(204);expect(runtime.state.settings.aiResources.map((x:any)=>x.id)).not.toContain('scout2');expect(runtime.ai.load.has('scout2')).toBe(false);});
  it('makes proxy CRUD canonical, fail-closed and immediately visible to Binance transports',async()=>{const{runtime,url}=await fixture(),transport=new BinanceTransport(runtime.state.settings.connections);const saved=await fetch(`${url}/settings/resources/proxy`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:'new-proxy',url:'socks5h://127.0.0.1:29999',enabled:true,binanceRestRoute:'DIRECT',forceBinanceRest:false})});expect(saved.status).toBe(200);expect(runtime.state.settings.connections.proxy).toMatchObject({url:'socks5h://127.0.0.1:29999',enabled:true,binanceRestRoute:'CONFIGURED',forceBinanceRest:true,forceBinanceWs:true,proxyDns:true,failClosed:true});expect(transport.restRoute()).toMatchObject({mode:'CONFIGURED',throughProxy:true,proxyUrl:'socks5h://127.0.0.1:29999',failClosed:true});const removed=await fetch(`${url}/settings/resources/proxy/binance-proxy`,{method:'DELETE'});expect(removed.status).toBe(204);expect(runtime.state.settings.connections.proxy.enabled).toBe(false);expect(()=>transport.websocketOptions()).toThrow(/PROXY_REQUIRED/);});
});