import express from 'express';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { BinanceTransport } from '../adapters/binance/BinanceTransport.js';
import { createRuntimeSettingsResourcesRouter } from './runtimeSettingsResources.js';

const servers:any[]=[];afterEach(async()=>{for(const server of servers.splice(0))await new Promise<void>(resolve=>server.close(()=>resolve()));});
function settings(legacy=false){return{settingsVersion:1,connections:{proxy:{enabled:true,protocol:'SOCKS5H',url:'socks5h://127.0.0.1:20081',forceBinanceRest:!legacy,forceBinanceWs:!legacy,proxyDns:!legacy,binanceRestRoute:legacy?'DIRECT':'CONFIGURED',bypassLocalhost:true,failClosed:!legacy},exchange:{provider:'BINANCE_USDM',environment:'TESTNET',productionBaseUrl:'https://fapi.binance.com',testnetBaseUrl:'https://demo-fapi.binance.com',testnetRestBaseUrl:'https://demo-fapi.binance.com',testnetWsBaseUrl:'wss://stream.binancefuture.com/ws',productionRestBaseUrl:'https://fapi.binance.com',productionWsBaseUrl:'wss://fstream.binance.com/ws',credentialRef:'binance-primary',recvWindowMs:5000,autoTimeSync:true},marketDataMode:'BINANCE',executionMode:'READ_ONLY',aiMode:'OPENAI_COMPATIBLE'},aiResources:[{id:'primary',role:'PRIMARY_BRAIN',enabled:true,baseUrl:'http://127.0.0.1:8084/v1',model:'qwen',maxConcurrency:1,gpu:'gpu'}]};}
async function fixture(legacy=false){const state:any={settings:settings(legacy),aiResources:[]},load=new Map([['primary',{active:0,totalRuns:0,failures:0,lastLatencyMs:null,currentSymbol:null,currentRunId:null,currentStartedAt:null,lastCompletedAt:null,lastDirection:null,lastDecision:null,idleReason:'WAITING_CANDIDATE',nextStep:'wait',queueDepth:0}]]),market={retentionSymbols:vi.fn(()=>new Set(['BTCUSDT'])),stop:vi.fn(),setRetentionSymbols:vi.fn()},runtime:any={state,market,ai:{load,probeResources:vi.fn().mockResolvedValue(undefined)},events:{publish:vi.fn()},settingsStore:{resourceSave:vi.fn().mockResolvedValue(undefined),resourceDelete:vi.fn().mockResolvedValue(undefined)},updateSettings:vi.fn(async(input:any)=>{state.settings={...input,settingsVersion:Number(input.settingsVersion??0)+1};return state.settings;}),updateSettingsIfVersion:vi.fn(async(input:any,expected:number)=>{if(state.settings.settingsVersion!==expected)throw new Error('SETTINGS_VERSION_CONFLICT');state.settings={...input,settingsVersion:expected+1};return state.settings;}),updateResourceSettings:vi.fn(async(input:any,expected:number,mutation:any)=>{if(state.settings.settingsVersion!==expected)throw new Error('SETTINGS_VERSION_CONFLICT');state.settings={...input,settingsVersion:expected+1};if(mutation.operation==='SAVE')runtime.settingsStore.resourceSave(mutation.kind,mutation.value);else runtime.settingsStore.resourceDelete(mutation.kind,mutation.id);return state.settings;})};state.aiResources=[];const app=express();app.use(express.json());app.use(createRuntimeSettingsResourcesRouter(runtime));const server=app.listen(0);servers.push(server);await new Promise(resolve=>server.once('listening',resolve));const address=server.address() as any;return{runtime,url:`http://127.0.0.1:${address.port}`};}

describe('runtime settings resource CRUD',()=>{
  it('migrates legacy DIRECT proxy settings to persisted proxy-only truth',async()=>{const{runtime}=await fixture(true);await vi.waitFor(()=>expect(runtime.updateSettingsIfVersion).toHaveBeenCalled());expect(runtime.state.settings.connections.proxy).toMatchObject({binanceRestRoute:'CONFIGURED',forceBinanceRest:true,forceBinanceWs:true,proxyDns:true,failClosed:true});expect(runtime.market.stop).toHaveBeenCalled();expect(runtime.market.setRetentionSymbols).toHaveBeenCalledWith(new Set(['BTCUSDT']));});
  it('persists AI CRUD and keeps enabled Scout in runtime resources',async()=>{const{runtime,url}=await fixture();const item={id:'scout2',role:'SCOUT',baseUrl:'http://127.0.0.1:8081/v1',model:'qwen-scout',maxConcurrency:1,gpu:'B580',enabled:true,status:'READY'};const saved=await fetch(`${url}/settings/resources/ai`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...item,expectedSettingsVersion:1})});expect(saved.status).toBe(200);expect(runtime.updateResourceSettings).toHaveBeenCalledTimes(1);expect(runtime.state.settings.aiResources.map((x:any)=>x.id)).toContain('scout2');expect(runtime.state.settings.aiResources.find((x:any)=>x.id==='scout2')?.enabled).toBe(true);expect(runtime.state.aiResources.map((x:any)=>x.id)).toContain('scout2');expect(runtime.ai.load.has('scout2')).toBe(true);const removed=await fetch(`${url}/settings/resources/ai/scout2`,{method:'DELETE',headers:{'if-match':'2'}});expect(removed.status).toBe(204);expect(runtime.state.settings.aiResources.map((x:any)=>x.id)).not.toContain('scout2');expect(runtime.ai.load.has('scout2')).toBe(false);});
  it('makes proxy CRUD canonical, fail-closed and immediately visible to REST and WS consumers',async()=>{const{runtime,url}=await fixture(),transport=new BinanceTransport(runtime.state.settings.connections);const saved=await fetch(`${url}/settings/resources/proxy`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:'new-proxy',url:'socks5h://127.0.0.1:29999',enabled:true,binanceRestRoute:'DIRECT',forceBinanceRest:false,expectedSettingsVersion:1})});expect(saved.status).toBe(200);expect(runtime.state.settings.connections.proxy).toMatchObject({url:'socks5h://127.0.0.1:29999',enabled:true,binanceRestRoute:'CONFIGURED',forceBinanceRest:true,forceBinanceWs:true,proxyDns:true,failClosed:true});expect(transport.restRoute()).toMatchObject({mode:'CONFIGURED',throughProxy:true,proxyUrl:'socks5h://127.0.0.1:29999',failClosed:true});expect(runtime.market.stop).toHaveBeenCalledTimes(1);expect(runtime.market.setRetentionSymbols).toHaveBeenLastCalledWith(new Set(['BTCUSDT']));const removed=await fetch(`${url}/settings/resources/proxy/binance-proxy`,{method:'DELETE',headers:{'if-match':'2'}});expect(removed.status).toBe(204);expect(runtime.state.settings.connections.proxy.enabled).toBe(false);expect(()=>transport.websocketOptions()).toThrow(/PROXY_REQUIRED/);expect(runtime.market.stop).toHaveBeenCalledTimes(2);});
  it('rejects stale resource edits with optimistic concurrency instead of overwriting newer settings',async()=>{const{url}=await fixture();const first=await fetch(`${url}/settings/resources/proxy`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:'socks5h://127.0.0.1:29998',expectedSettingsVersion:1})});expect(first.status).toBe(200);const stale=await fetch(`${url}/settings/resources/proxy`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:'socks5h://127.0.0.1:29997',expectedSettingsVersion:1})});expect(stale.status).toBe(409);expect(await stale.json()).toMatchObject({error:{message:'SETTINGS_VERSION_CONFLICT'},currentSettingsVersion:2});});
  it('applies Binance Demo exchange REST and keeps WS independently configurable',async()=>{const{runtime,url}=await fixture();const saved=await fetch(`${url}/settings/resources/exchange`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({environment:'TESTNET',restBaseUrl:'https://demo-fapi.binance.com',wsBaseUrl:'wss://stream.binancefuture.com/ws',expectedSettingsVersion:1})});expect(saved.status).toBe(200);expect(runtime.state.settings.connections.exchange).toMatchObject({testnetRestBaseUrl:'https://demo-fapi.binance.com',testnetWsBaseUrl:'wss://stream.binancefuture.com/ws'});});

  it('guards active exchange deletion and rejects secret material in resource payloads',async()=>{const{url}=await fixture();const del=await fetch(`${url}/settings/resources/exchange/binance-usdm`,{method:'DELETE',headers:{'if-match':'1'}});expect(del.status).toBe(409);expect(await del.json()).toMatchObject({error:{message:'ACTIVE_EXCHANGE_DELETE_REQUIRES_REPLACEMENT'}});const secret=await fetch(`${url}/settings/resources/exchange/binance-usdm`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({environment:'TESTNET',apiKey:'must-not-persist',expectedSettingsVersion:1})});expect(secret.status).toBeGreaterThanOrEqual(400);});
  it('keeps Exchange Proxy and AI under Resource Manager when generic settings are saved',async()=>{const{runtime,url}=await fixture();const requested=structuredClone(runtime.state.settings);requested.portfolio={maxPositions:9};requested.connections.exchange={...requested.connections.exchange,testnetRestBaseUrl:'https://evil.example'};requested.connections.proxy={...requested.connections.proxy,url:'socks5h://127.0.0.1:29999'};requested.aiResources=[];const response=await fetch(`${url}/settings`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(requested)});expect(response.status).toBe(200);expect(runtime.state.settings.connections.exchange.testnetRestBaseUrl).toBe('https://demo-fapi.binance.com');expect(runtime.state.settings.connections.proxy.url).toBe('socks5h://127.0.0.1:20081');expect(runtime.state.settings.aiResources).toHaveLength(1);});
});
