import WebSocket from 'ws';
import { RecentTradePrices } from './recentTradePrices.js';
import type { Candle, OrderBook, Quote } from '@zdj/contracts';
import { BinanceTransport } from '../binance/BinanceTransport.js';

type StreamMetrics={state:'STOPPED'|'CONNECTING'|'LIVE'|'BACKOFF';connectedAt:number|null;lastMessageAt:number|null;lastTickerMessageAt:number|null;lastBookTickerMessageAt:number|null;lastPongAt:number|null;reconnects:number;gaps:number;gapsByType:{websocketConnection:number;quote:number;bookTicker:number;depthSequence:number;kline:number;eventTimestamp:number;subscription:number};backfills:number;subscriptions:number;cumulativeSubscriptions:number;recoverySuccess:number;recoveryFailure:number;lastError:string|null};
type QuotePatch=Partial<Pick<Quote,'last'|'mark'|'bid'|'ask'|'quoteVolumeUsd24h'|'priceChangePercent24h'|'tradeCount24h'|'ts'>>;
const fresh=(ts:number|undefined,maxAge:number)=>Boolean(ts&&Number.isFinite(ts)&&Date.now()-ts>=-1_000&&Date.now()-ts<=maxAge);
type LaneName='PUBLIC'|'MARKET'|`PUBLIC_${number}`|`MARKET_${number}`;
type Control={method:'SUBSCRIBE'|'UNSUBSCRIBE';params:string[];id:number};
const createLane=()=>({socket:null as WebSocket|null,retry:null as NodeJS.Timeout|null,heartbeat:null as NodeJS.Timeout|null,attempt:0,requestId:1,controlQueue:[] as Control[],controlTimer:null as NodeJS.Timeout|null,ackTimer:null as NodeJS.Timeout|null,pending:null as Control|null,lastControlAt:0,subscribed:new Set<string>(),confirmed:new Set<string>(),lastAckAt:null as number|null,lastMessageAt:0,state:'STOPPED' as StreamMetrics['state'],connectedAt:null as number|null,lastError:null as string|null,reconnects:0});

/** Two shared Binance USD-M sockets: Public for high-frequency book/depth and Market for ticker/mark/kline/trades. */
export class BinanceMarketStream {
  readonly tradedPrices=new RecentTradePrices();
  private stopped=true;
  private readonly lanes:Record<string,ReturnType<typeof createLane>>={PUBLIC:createLane(),MARKET:createLane()};
  private laneNames(){return Object.keys(this.lanes) as LaneName[];}
  private laneKind(name:LaneName):'PUBLIC'|'MARKET'{return name.startsWith('PUBLIC')?'PUBLIC':'MARKET';}
  /** Split complete retained coverage; never silently discard protected symbols. */
  private ensureLanes(){const needed=new Set<LaneName>();for(const kind of ['PUBLIC','MARKET'] as const){const count=Math.max(1,Math.ceil(this.symbols.size/(kind==='MARKET'?160:1023)));for(let i=0;i<count;i++){const name:LaneName=i===0?kind:`${kind}_${i}`;needed.add(name);if(!this.lanes[name]){this.lanes[name]=createLane();if(!this.stopped)this.connect(name);}}}for(const name of this.laneNames())if(!needed.has(name)){const lane=this.lanes[name]!;this.clearControls(name);if(lane.retry)clearTimeout(lane.retry);if(lane.heartbeat)clearInterval(lane.heartbeat);const socket=lane.socket;lane.socket=null;socket?.close();delete this.lanes[name];}}
  private symbols=new Set<string>(); private quotes=new Map<string,QuotePatch>(); private quoteFieldTimes=new Map<string,Partial<Record<keyof QuotePatch,number>>>(); private books=new Map<string,OrderBook>(); private candles=new Map<string,Candle[]>(); private lastDepthUpdate=new Map<string,number>(); private backfillInFlight=new Set<string>(); private recoveryCooldown=new Map<string,number>(); private lastKlineClosed=new Map<string,number>(); private lastKlineGap:Record<string,unknown>|null=null;
  private readonly streamTraffic:Record<'PUBLIC'|'MARKET',{totalMessages:number;totalDecodedBytes:number;buckets:Array<{slot:number;messages:number;decodedBytes:number;byType:Record<string,{messages:number;decodedBytes:number}>}>;totalByType:Record<string,{messages:number;decodedBytes:number}>}>={PUBLIC:{totalMessages:0,totalDecodedBytes:0,buckets:[],totalByType:{}},MARKET:{totalMessages:0,totalDecodedBytes:0,buckets:[],totalByType:{}}};
  private readonly metricsValue:StreamMetrics={state:'STOPPED',connectedAt:null,lastMessageAt:null,lastTickerMessageAt:null,lastBookTickerMessageAt:null,lastPongAt:null,reconnects:0,gaps:0,gapsByType:{websocketConnection:0,quote:0,bookTicker:0,depthSequence:0,kline:0,eventTimestamp:0,subscription:0},backfills:0,subscriptions:0,cumulativeSubscriptions:0,recoverySuccess:0,recoveryFailure:0,lastError:null};
  constructor(private readonly transport:BinanceTransport,private readonly backfill:(symbol:string)=>Promise<{book:OrderBook;candles:Candle[]}>){}
  private recoveryQueue=new Set<string>();
  private recoveryActive=0;
  private recoveryTimer:NodeJS.Timeout|null=null;
  private recoveryGeneration=0;
  private retainSymbols(symbols:string[]){
    this.symbols=new Set(symbols.map(x=>x.toUpperCase()));this.tradedPrices.retain(this.symbols);this.ensureLanes();
    for(const symbol of [...this.quotes.keys()])if(!this.symbols.has(symbol)){this.quotes.delete(symbol);this.quoteFieldTimes.delete(symbol);}
    for(const symbol of [...this.books.keys()])if(!this.symbols.has(symbol))this.books.delete(symbol);
    for(const key of [...this.candles.keys()])if(!this.symbols.has(key.split(':')[0]!))this.candles.delete(key);
    for(const symbol of [...this.lastDepthUpdate.keys()])if(!this.symbols.has(symbol))this.lastDepthUpdate.delete(symbol);
    for(const symbol of [...this.recoveryCooldown.keys()])if(!this.symbols.has(symbol))this.recoveryCooldown.delete(symbol);
    for(const key of [...this.lastKlineClosed.keys()])if(!this.symbols.has(key.split(':')[0]!))this.lastKlineClosed.delete(key);
  }
  start(symbols:string[]){this.retainSymbols(symbols);if(!this.stopped){this.subscribeSymbols();return;}this.stopped=false;for(const name of this.laneNames())this.connect(name);}
  updateSymbols(symbols:string[]){this.retainSymbols(symbols);this.subscribeSymbols();}
  stop(){this.stopped=true;this.recoveryGeneration++;this.recoveryQueue.clear();if(this.recoveryTimer)clearTimeout(this.recoveryTimer);this.recoveryTimer=null;for(const laneName of this.laneNames()){const lane=this.lanes[laneName]!;this.clearControls(laneName);if(lane.retry)clearTimeout(lane.retry);if(lane.heartbeat)clearInterval(lane.heartbeat);lane.retry=lane.heartbeat=null;lane.socket?.close();lane.socket=null;lane.state='STOPPED';}this.updateAggregateState();}
  metrics(){const observedAt=Date.now(),fields=['last','mark','bid','ask'] as const,staleByField=Object.fromEntries(fields.map(field=>[field,[...this.symbols].filter(symbol=>!fresh(this.quoteFieldTimes.get(symbol)?.[field],5_000)).length]));return{quoteFactFreshness:{evaluatedAt:observedAt,maxAgeMs:5_000,retainedSymbols:this.symbols.size,staleByField,samples:[...this.symbols].slice(0,16).map(symbol=>({symbol,fields:this.quoteFreshness(symbol)}))},...this.metricsValue,recovery:{active:this.recoveryActive,queued:this.recoveryQueue.size,maxConcurrent:2,minStartIntervalMs:500},gapsByType:{...this.metricsValue.gapsByType},lastKlineGap:this.lastKlineGap?{...this.lastKlineGap}:null,streamTraffic:Object.fromEntries((['PUBLIC','MARKET'] as const).map(name=>{const traffic=this.streamTraffic[name],slot=Math.floor(observedAt/1_000),valid=traffic.buckets.filter(row=>row.slot>=slot-59&&row.slot<=slot),byType:Record<string,{messages:number;decodedBytes:number}>={};for(const bucket of valid)for(const [kind,counts] of Object.entries(bucket.byType)){const value=byType[kind]??{messages:0,decodedBytes:0};value.messages+=counts.messages;value.decodedBytes+=counts.decodedBytes;byType[kind]=value;}return[name,{last60sDecodedBytes:valid.reduce((sum,row)=>sum+row.decodedBytes,0),last60sMessages:valid.reduce((sum,row)=>sum+row.messages,0),last60sByType:byType,totalByType:Object.fromEntries(Object.entries(traffic.totalByType).map(([kind,counts])=>[kind,{...counts}])),totalDecodedBytes:traffic.totalDecodedBytes,totalMessages:traffic.totalMessages,windowAsOf:observedAt,windowResolutionMs:1_000,requestedGlobalStreams:this.laneNames().filter(lane=>this.laneKind(lane)===name).flatMap(lane=>[...this.lanes[lane]!.subscribed].filter(item=>item.startsWith('!'))),subscriptionEvidence:this.laneNames().filter(lane=>this.laneKind(lane)===name).every(lane=>this.lanes[lane]!.lastAckAt!==null&&!this.lanes[lane]!.pending&&!this.lanes[lane]!.controlQueue.length&&this.lanes[lane]!.subscribed.size===this.lanes[lane]!.confirmed.size&&[...this.lanes[lane]!.subscribed].every(item=>this.lanes[lane]!.confirmed.has(item)))?'EXCHANGE_ACKED':'PENDING_EXCHANGE_ACK',measurement:'DECODED_WS_APPLICATION_PAYLOAD_NOT_SSH_WIRE_BYTES'}];})),lanes:Object.fromEntries(this.laneNames().map(name=>{const lane=this.lanes[name]!;return[name,{state:lane.state,connectedAt:lane.connectedAt,lastMessageAt:lane.lastMessageAt||null,reconnects:lane.reconnects,lastError:lane.lastError,subscriptions:lane.subscribed.size,confirmedSubscriptions:lane.confirmed.size,pendingControls:lane.controlQueue.length+(lane.pending?1:0),lastAckAt:lane.lastAckAt}];}))};}
  /** A partial fact never lends its timestamp to unrelated fields. */
  quoteFields(symbol:string,maxAgeMs=5_000):QuotePatch{
    const q=this.quotes.get(symbol),times=this.quoteFieldTimes.get(symbol);if(!q||!times)return{};
    const fields:QuotePatch={};for(const field of Object.keys(times) as Array<keyof QuotePatch>)if(field!=='ts'&&fresh(times[field],maxAgeMs)&&q[field]!==undefined)fields[field]=q[field];
    const required=['last','mark','bid','ask'] as const;if(required.every(field=>fields[field]!==undefined))fields.ts=Math.min(...required.map(field=>times[field]!));return fields;
  }
  quote(symbol:string,maxAgeMs=5_000){const q=this.quoteFields(symbol,maxAgeMs);return q.ts!==undefined?q:undefined;}
  quoteFreshness(symbol:string,maxAgeMs=5_000){const times=this.quoteFieldTimes.get(symbol)??{};return Object.fromEntries(Object.entries(times).map(([field,ts])=>[field,{at:ts,ageMs:Date.now()-ts!,fresh:fresh(ts,maxAgeMs)}]));}
  book(symbol:string,maxAgeMs=5_000){const b=this.books.get(symbol);return b&&fresh(b.ts,maxAgeMs)?b:undefined;}
  candleSeries(symbol:string,maxAgeMs=120_000,timeframe='1m'){const c=this.candles.get(timeframe==='1m'?symbol:`${symbol}:${timeframe}`);return c?.length&&fresh(c.at(-1)?.closeTime,maxAgeMs)?c:undefined;}
  seed(symbol:string,book:OrderBook,candles:Candle[]){if(Number.isFinite(book.ts)&&book.ts>0&&book.ts<=Date.now()+1_000&&book.ts>=(this.books.get(symbol)?.ts??0))this.books.set(symbol,book);this.seedCandles(symbol,'1m',candles);}
  seedQuote(symbol:string,patch:QuotePatch){if(this.quotes.size>=512&&!this.quotes.has(symbol)){const oldest=this.quotes.keys().next().value!;this.quotes.delete(oldest);this.quoteFieldTimes.delete(oldest);}this.mergeQuote(symbol,patch);}
  seedCandles(symbol:string,timeframe:string,rows:Candle[]){const key=timeframe==='1m'?symbol:`${symbol}:${timeframe}`,merged=new Map(rows.map(c=>[c.openTime,c]));for(const c of this.candles.get(key)??[]){const other=merged.get(c.openTime);if(!other||(c.isClosed&&!other.isClosed)||(!(other.isClosed&&!c.isClosed)&&(c.receivedAt??0)>=(other.receivedAt??0)))merged.set(c.openTime,c);}this.candles.set(key,[...merged.values()].sort((a,b)=>a.openTime-b.openTime).slice(-300));}
  private updateAggregateState(){if(this.stopped){this.metricsValue.state='STOPPED';return;}const states=this.laneNames().map(name=>this.lanes[name]!.state);this.metricsValue.state=states.every(x=>x==='LIVE')?'LIVE':states.some(x=>x==='CONNECTING')?'CONNECTING':'BACKOFF';this.metricsValue.connectedAt=Math.max(...this.laneNames().map(name=>this.lanes[name]!.connectedAt??0))||null;this.metricsValue.lastMessageAt=Math.max(...this.laneNames().map(name=>this.lanes[name]!.lastMessageAt||0))||null;this.metricsValue.lastError=this.laneNames().map(name=>this.lanes[name]!.lastError).find(Boolean)??null;}
  private connect(laneName:LaneName){if(this.stopped)return;const lane=this.lanes[laneName]!;lane.state='CONNECTING';this.updateAggregateState();let socket:WebSocket;try{socket=new WebSocket(this.transport.effectiveWsUrl(this.laneKind(laneName)),{...this.transport.websocketOptions(),handshakeTimeout:15_000});}catch(error){this.schedule(laneName,error);return;}lane.socket=socket;
    socket.on('open',()=>{if(lane.socket!==socket)return;this.clearControls(laneName);lane.subscribed.clear();lane.confirmed.clear();lane.lastAckAt=null;if(this.laneKind(laneName)==='PUBLIC')this.lastDepthUpdate.clear();const now=Date.now();lane.state='LIVE';lane.connectedAt=now;lane.lastMessageAt=now;lane.lastError=null;if(this.laneKind(laneName)==='MARKET')this.metricsValue.lastTickerMessageAt=now;else this.metricsValue.lastBookTickerMessageAt=now;this.subscribeLane(laneName);this.updateAggregateState();lane.heartbeat=setInterval(()=>{if(lane.socket!==socket||socket.readyState!==WebSocket.OPEN)return;const eventAt=this.laneKind(laneName)==='MARKET'?this.metricsValue.lastTickerMessageAt:this.metricsValue.lastBookTickerMessageAt,alive=fresh(lane.lastMessageAt||undefined,45_000)&&fresh(eventAt??undefined,45_000);if(!alive){socket.terminate();return;}socket.ping();},15_000);});
    socket.on('pong',()=>{if(lane.socket===socket)this.metricsValue.lastPongAt=Date.now();});socket.on('message',raw=>{if(lane.socket===socket)this.onMessage(String(raw),laneName);});
    socket.on('error',error=>{if(lane.socket!==socket)return;lane.lastError=error.message;this.updateAggregateState();});socket.on('close',(code,reason)=>{if(lane.socket!==socket)return;this.clearControls(laneName);if(reason.length)lane.lastError=`WS_CLOSE_${code}: ${String(reason)}`;if(lane.heartbeat)clearInterval(lane.heartbeat);lane.heartbeat=null;if(lane.socket===socket)lane.socket=null;if(!this.stopped)this.schedule(laneName,new Error(lane.lastError??'socket closed'));});
  }
  private schedule(laneName:LaneName,error:unknown){if(this.stopped)return;const lane=this.lanes[laneName]!;lane.state='BACKOFF';lane.lastError=error instanceof Error?error.message:String(error);lane.reconnects++;this.metricsValue.reconnects++;this.metricsValue.gaps++;this.metricsValue.gapsByType.websocketConnection++;this.updateAggregateState();const delay=Math.min(30_000,500*2**Math.min(lane.attempt++,6))+Math.floor(Math.random()*250);lane.retry=setTimeout(()=>this.connect(laneName),delay);}
  /**
   * Binance's two all-market ticker/mark arrays dominated actual SOCKS traffic.
   * Discovery is a separate, cached REST call in BinancePublicMarketDataProvider;
   * streaming facts only need to cover the authoritative retained symbol set.
   * The MARKET lane has a 1024-stream server limit: reserve headroom for churn.
   * Do not client-filter global arrays after receipt (that saves no SSH bytes).
   */
  private desired(laneName:LaneName){
    const kind=this.laneKind(laneName),index=laneName===kind?0:Number(laneName.split('_')[1]),size=kind==='MARKET'?160:1023;
    const symbols=[...this.symbols].slice(index*size,(index+1)*size).map(symbol=>symbol.toLowerCase());
    if(kind==='PUBLIC')return new Set([...(index===0?['!bookTicker']:[]),...symbols.map(symbol=>`${symbol}@depth20@500ms`)]);
    return new Set(symbols.flatMap(symbol=>[`${symbol}@ticker`,`${symbol}@markPrice@1s`,`${symbol}@kline_1m`,`${symbol}@kline_5m`,`${symbol}@kline_15m`,`${symbol}@aggTrade`]));
  }

  private subscribeSymbols(){for(const name of this.laneNames())this.subscribeLane(name);}
  private subscribeLane(laneName:LaneName){
    const lane=this.lanes[laneName]!;if(lane.socket?.readyState!==WebSocket.OPEN)return;
    const desired=this.desired(laneName),projected=new Set(lane.confirmed);
    // Replace unsent churn with the latest target, preserving the one wire command.
    if(lane.pending)for(const item of lane.pending.params)lane.pending.method==='SUBSCRIBE'?projected.add(item):projected.delete(item);
    lane.controlQueue=[];
    const remove=[...projected].filter(x=>!desired.has(x)),add=[...desired].filter(x=>!projected.has(x));
    for(const [method,items] of [['UNSUBSCRIBE',remove],['SUBSCRIBE',add]] as const)for(let i=0;i<items.length;i+=100)lane.controlQueue.push({method,params:items.slice(i,i+100),id:lane.requestId++});
    lane.subscribed=desired;this.metricsValue.subscriptions=this.laneNames().reduce((sum,name)=>sum+this.lanes[name]!.subscribed.size,0);this.metricsValue.cumulativeSubscriptions+=add.length;this.pumpControls(laneName);
  }
  private clearControls(laneName:LaneName){const lane=this.lanes[laneName]!;if(lane.controlTimer)clearTimeout(lane.controlTimer);lane.controlTimer=null;lane.controlQueue=[];if(lane.ackTimer)clearTimeout(lane.ackTimer);lane.ackTimer=null;lane.pending=null;}
  private pumpControls(laneName:LaneName){const lane=this.lanes[laneName]!;if(lane.pending||lane.controlTimer||!lane.controlQueue.length||lane.socket?.readyState!==WebSocket.OPEN)return;lane.controlTimer=setTimeout(()=>{lane.controlTimer=null;if(lane.socket?.readyState!==WebSocket.OPEN)return;const command=lane.controlQueue.shift();if(command){lane.pending=command;lane.lastControlAt=Date.now();lane.ackTimer=setTimeout(()=>{lane.ackTimer=null;if(lane.pending?.id===command.id){lane.lastError='WS_SUBSCRIPTION_ACK_TIMEOUT';this.metricsValue.gaps++;this.metricsValue.gapsByType.subscription++;this.updateAggregateState();lane.socket?.terminate();}},10_000);lane.socket.send(JSON.stringify(command));}this.pumpControls(laneName);},Math.max(0,350-(Date.now()-lane.lastControlAt)));}
  /** Event-only buckets: never retain a symbol, credential, payload or raw frame in diagnostics. */
  private payloadType(value:any):string{const data=value?.data??value,first=Array.isArray(data)?data[0]:data,e=String(first?.e??'');if(Array.isArray(data)&&data.some((row:any)=>String(row?.e??'')!==e))return 'MIXED_OR_OTHER';if(e==='bookTicker'||(!e&&first?.s&&first?.b!=null&&first?.a!=null))return 'BOOK_TICKER';if(e==='24hrTicker')return 'TICKER_24H';if(e==='markPriceUpdate')return 'MARK_PRICE';if(e==='depthUpdate')return 'DEPTH';if(e==='kline')return 'KLINE';if(e==='aggTrade')return 'AGG_TRADE';return 'CONTROL_OR_OTHER';}
  private recordStreamPayload(laneName:LaneName,raw:string,kind:string){const traffic=this.streamTraffic[this.laneKind(laneName)],slot=Math.floor(Date.now()/1_000),decodedBytes=Buffer.byteLength(raw,'utf8');let current=traffic.buckets.at(-1);if(!current||current.slot!==slot){current={slot,messages:0,decodedBytes:0,byType:{}};traffic.buckets.push(current);}current.messages++;current.decodedBytes+=decodedBytes;const part=current.byType[kind]??{messages:0,decodedBytes:0};part.messages++;part.decodedBytes+=decodedBytes;current.byType[kind]=part;const total=traffic.totalByType[kind]??{messages:0,decodedBytes:0};total.messages++;total.decodedBytes+=decodedBytes;traffic.totalByType[kind]=total;traffic.totalMessages++;traffic.totalDecodedBytes+=decodedBytes;while(traffic.buckets.length>60||(traffic.buckets.length>0&&traffic.buckets[0]!.slot<slot-59))traffic.buckets.shift();}
  private onMessage(raw:string,laneName:LaneName='MARKET'){const lane=this.lanes[laneName]!;lane.lastMessageAt=Date.now();this.metricsValue.lastMessageAt=lane.lastMessageAt;let value:any;try{value=JSON.parse(raw);}catch{this.recordStreamPayload(this.laneKind(laneName),raw,'INVALID_JSON');return;}this.recordStreamPayload(this.laneKind(laneName),raw,this.payloadType(value));const controlError=value?.error??(value?.code!=null&&value?.msg!=null?{code:value.code,msg:value.msg,id:value.id??null}:null);if(controlError){lane.lastError=`WS_CONTROL_ERROR:${JSON.stringify(controlError)}`;this.metricsValue.lastError=lane.lastError;this.metricsValue.gaps++;this.metricsValue.gapsByType.subscription++;if(lane.socket?.readyState===WebSocket.OPEN)lane.socket.terminate();return;}if(value?.id===lane.pending?.id&&lane.pending&&value.result===null){const command=lane.pending;for(const item of command.params){if(command.method==='SUBSCRIBE')lane.confirmed.add(item);else lane.confirmed.delete(item);}lane.lastAckAt=Date.now();if(lane.ackTimer)clearTimeout(lane.ackTimer);lane.ackTimer=null;lane.pending=null;this.pumpControls(laneName);return;}const data=value?.data??value;if(Array.isArray(data)){for(const row of data)this.onEvent(row,laneName);return;}this.onEvent(data,laneName);}
  private onEvent(d:any,laneName:LaneName='MARKET'){if(!d||typeof d!=='object')return;const lane=this.lanes[laneName]!;if(d.e&&Date.now()-(lane.connectedAt??Date.now())>15000)lane.attempt=0;if(d.e==='aggTrade'){const s=String(d.s);if(this.symbols.has(s))this.tradedPrices.record(s,Number(d.p),Number(d.T));}
    else if(d.e==='24hrTicker'||(d.s&&d.c!=null&&d.q!=null)){this.metricsValue.lastTickerMessageAt=Date.now();const s=String(d.s);if(!this.symbols.has(s))return;this.mergeQuote(s,{last:Number(d.c),quoteVolumeUsd24h:Number(d.q),priceChangePercent24h:Number(d.P),tradeCount24h:Number(d.n),ts:Number(d.E)||Date.now()});}
    else if(d.e==='markPriceUpdate'||(d.s&&d.p!=null&&d.i!=null)){const s=String(d.s);if(this.symbols.has(s))this.mergeQuote(s,{mark:Number(d.p),ts:Number(d.E)||Date.now()});}
    else if(d.e==='bookTicker'||(d.s&&d.b!=null&&d.a!=null&&!d.e)){this.metricsValue.lastBookTickerMessageAt=Date.now();const s=String(d.s);if(this.symbols.has(s))this.mergeQuote(s,{bid:Number(d.b),ask:Number(d.a),ts:Number(d.E)||Date.now()});}
    else if(d.e==='depthUpdate'||(d.bids&&d.asks)){const s=String(d.s);if(!this.symbols.has(s)||this.backfillInFlight.has(s))return;const previous=this.lastDepthUpdate.get(s),first=Number(d.U??d.firstUpdateId??0),last=Number(d.u??d.lastUpdateId??0),pu=Number(d.pu??0);if(previous&&last<=previous)return;const contiguous=!previous||pu===previous||(first>0&&first<=previous+1&&last>=previous+1);if(!contiguous){if((this.recoveryCooldown.get(s)??0)<=Date.now()){this.metricsValue.gaps++;this.metricsValue.gapsByType.depthSequence++;this.lastDepthUpdate.delete(s);void this.recover(s);}return;}const eventAt=Number(d.E)||Date.now();if(!Number.isFinite(eventAt)||eventAt>Date.now()+1_000||eventAt<(this.books.get(s)?.ts??0))return;this.lastDepthUpdate.set(s,last);this.books.set(s,{symbol:s,bids:(d.b??d.bids).map((x:any)=>[Number(x[0]),Number(x[1])] as [number,number]),asks:(d.a??d.asks).map((x:any)=>[Number(x[0]),Number(x[1])] as [number,number]),ts:Number(d.E)||Date.now()});}
    else if(d.e==='kline'){const s=String(d.s);if(!this.symbols.has(s))return;const k=d.k,tf=String(k.i??'1m');if(!['1m','5m','15m'].includes(tf))return;const key=tf==='1m'?s:`${s}:${tf}`,receivedAt=Number(d.E)||Date.now();const candle:Candle={openTime:Number(k.t),closeTime:Number(k.T),receivedAt,isClosed:Boolean(k.x),source:'BINANCE_WS',open:Number(k.o),high:Number(k.h),low:Number(k.l),close:Number(k.c),volume:Number(k.v),quoteVolume:Number(k.q),trades:Number(k.n)};const rows=this.candles.get(key)??[];const at=rows.findIndex(x=>x.openTime===candle.openTime);if(at>=0){const prior=rows[at]!;if(prior.isClosed&&!candle.isClosed||(prior.receivedAt??0)>receivedAt)return;rows[at]=candle;}else rows.push(candle);this.candles.set(key,rows.sort((a,b)=>a.openTime-b.openTime).slice(-300));if(candle.isClosed){const period=tf==='1m'?60_000:tf==='5m'?300_000:900_000,previous=this.lastKlineClosed.get(key);if(previous!==undefined&&candle.openTime>previous+period){this.metricsValue.gaps++;this.metricsValue.gapsByType.kline++;this.lastKlineGap={symbol:s,timeframe:tf,expectedOpenTime:previous+period,actualOpenTime:candle.openTime,missingBars:Math.round((candle.openTime-previous)/period)-1,at:receivedAt};}if(previous===undefined||candle.openTime>previous)this.lastKlineClosed.set(key,candle.openTime);}}
  }
  private mergeQuote(symbol:string,patch:QuotePatch){
    const at=Number(patch.ts);if(!Number.isFinite(at)||at<=0||at>Date.now()+1_000)return;
    const q=this.quotes.get(symbol)??{},times=this.quoteFieldTimes.get(symbol)??{};
    for(const field of Object.keys(patch) as Array<keyof QuotePatch>){if(field==='ts')continue;const value=patch[field];if(!Number.isFinite(value)||at<(times[field]??0))continue;if(['last','mark','bid','ask'].includes(field)&&Number(value)<=0)continue;q[field]=value;times[field]=at;}
    const required=['last','mark','bid','ask'] as const;q.ts=required.every(field=>times[field]!==undefined)?Math.min(...required.map(field=>times[field]!)):undefined;
    this.quotes.set(symbol,q);this.quoteFieldTimes.set(symbol,times);
  }
  private recover(symbol:string){const now=Date.now();if(this.backfillInFlight.has(symbol)||this.recoveryQueue.has(symbol)||(this.recoveryCooldown.get(symbol)??0)>now||!this.symbols.has(symbol))return;this.recoveryCooldown.set(symbol,now+60_000);this.recoveryQueue.add(symbol);this.pumpRecovery();}
  private pumpRecovery(){if(this.recoveryActive>=2||this.recoveryTimer)return;const symbol=this.recoveryQueue.values().next().value as string|undefined;if(!symbol)return;this.recoveryQueue.delete(symbol);if(!this.symbols.has(symbol)){this.pumpRecovery();return;}this.recoveryActive++;this.backfillInFlight.add(symbol);const generation=this.recoveryGeneration;void this.runRecovery(symbol,generation);this.recoveryTimer=setTimeout(()=>{this.recoveryTimer=null;this.pumpRecovery();},500);}
  private async runRecovery(symbol:string,generation:number){try{const value=await this.backfill(symbol);if(generation!==this.recoveryGeneration||!this.symbols.has(symbol))return;if(Number.isFinite(value.book.ts)&&value.book.ts>0&&value.book.ts<=Date.now()+1_000&&value.book.ts>=(this.books.get(symbol)?.ts??0))this.books.set(symbol,value.book);this.seedCandles(symbol,'1m',value.candles);this.lastDepthUpdate.delete(symbol);this.metricsValue.backfills++;this.metricsValue.recoverySuccess++;}catch(error){this.metricsValue.recoveryFailure++;this.metricsValue.lastError=error instanceof Error?error.message:String(error);}finally{this.backfillInFlight.delete(symbol);this.recoveryActive--;this.pumpRecovery();}}
}
