import WebSocket from 'ws';
import { RecentTradePrices } from './recentTradePrices.js';
import type { Candle, OrderBook, Quote } from '@zdj/contracts';
import { BinanceTransport } from '../binance/BinanceTransport.js';

type StreamMetrics={state:'STOPPED'|'CONNECTING'|'LIVE'|'BACKOFF';connectedAt:number|null;lastMessageAt:number|null;lastTickerMessageAt:number|null;lastBookTickerMessageAt:number|null;lastPongAt:number|null;reconnects:number;gaps:number;gapsByType:{websocketConnection:number;quote:number;bookTicker:number;depthSequence:number;kline:number;eventTimestamp:number;subscription:number};backfills:number;subscriptions:number;cumulativeSubscriptions:number;recoverySuccess:number;recoveryFailure:number;lastError:string|null};
type QuotePatch=Partial<Pick<Quote,'last'|'mark'|'bid'|'ask'|'quoteVolumeUsd24h'|'priceChangePercent24h'|'tradeCount24h'|'ts'>>;
const fresh=(ts:number|undefined,maxAge:number)=>Boolean(ts&&Date.now()-ts<=maxAge);

/** Two shared Binance USD-M sockets: Public for high-frequency book/depth and Market for ticker/mark/kline/trades. */
export class BinanceMarketStream {
  readonly tradedPrices=new RecentTradePrices();
  private stopped=true;
  private readonly lanes={
    PUBLIC:{socket:null as WebSocket|null,retry:null as NodeJS.Timeout|null,heartbeat:null as NodeJS.Timeout|null,attempt:0,requestId:1,controlQueue:[] as Array<{method:'SUBSCRIBE'|'UNSUBSCRIBE';params:string[];id:number}>,controlTimer:null as NodeJS.Timeout|null,lastControlAt:0,subscribed:new Set<string>(),lastMessageAt:0,state:'STOPPED' as StreamMetrics['state'],connectedAt:null as number|null,lastError:null as string|null,reconnects:0},
    MARKET:{socket:null as WebSocket|null,retry:null as NodeJS.Timeout|null,heartbeat:null as NodeJS.Timeout|null,attempt:0,requestId:1,controlQueue:[] as Array<{method:'SUBSCRIBE'|'UNSUBSCRIBE';params:string[];id:number}>,controlTimer:null as NodeJS.Timeout|null,lastControlAt:0,subscribed:new Set<string>(),lastMessageAt:0,state:'STOPPED' as StreamMetrics['state'],connectedAt:null as number|null,lastError:null as string|null,reconnects:0},
  };
  private symbols=new Set<string>(); private quotes=new Map<string,QuotePatch>(); private books=new Map<string,OrderBook>(); private candles=new Map<string,Candle[]>(); private lastDepthUpdate=new Map<string,number>(); private backfillInFlight=new Set<string>(); private recoveryCooldown=new Map<string,number>(); private lastKlineClosed=new Map<string,number>(); private lastKlineGap:Record<string,unknown>|null=null;
  private readonly metricsValue:StreamMetrics={state:'STOPPED',connectedAt:null,lastMessageAt:null,lastTickerMessageAt:null,lastBookTickerMessageAt:null,lastPongAt:null,reconnects:0,gaps:0,gapsByType:{websocketConnection:0,quote:0,bookTicker:0,depthSequence:0,kline:0,eventTimestamp:0,subscription:0},backfills:0,subscriptions:0,cumulativeSubscriptions:0,recoverySuccess:0,recoveryFailure:0,lastError:null};
  constructor(private readonly transport:BinanceTransport,private readonly backfill:(symbol:string)=>Promise<{book:OrderBook;candles:Candle[]}>){}
  private retainSymbols(symbols:string[]){
    this.symbols=new Set(symbols.map(x=>x.toUpperCase()));this.tradedPrices.retain(this.symbols);
    for(const symbol of [...this.quotes.keys()])if(!this.symbols.has(symbol))this.quotes.delete(symbol);
    for(const symbol of [...this.books.keys()])if(!this.symbols.has(symbol))this.books.delete(symbol);
    for(const key of [...this.candles.keys()])if(!this.symbols.has(key.split(':')[0]!))this.candles.delete(key);
    for(const symbol of [...this.lastDepthUpdate.keys()])if(!this.symbols.has(symbol))this.lastDepthUpdate.delete(symbol);
    for(const symbol of [...this.recoveryCooldown.keys()])if(!this.symbols.has(symbol))this.recoveryCooldown.delete(symbol);
    for(const key of [...this.lastKlineClosed.keys()])if(!this.symbols.has(key.split(':')[0]!))this.lastKlineClosed.delete(key);
  }
  start(symbols:string[]){this.retainSymbols(symbols);if(!this.stopped){this.subscribeSymbols();return;}this.stopped=false;this.connect('PUBLIC');this.connect('MARKET');}
  updateSymbols(symbols:string[]){this.retainSymbols(symbols);this.subscribeSymbols();}
  stop(){this.stopped=true;for(const laneName of ['PUBLIC','MARKET'] as const){const lane=this.lanes[laneName];this.clearControls(laneName);if(lane.retry)clearTimeout(lane.retry);if(lane.heartbeat)clearInterval(lane.heartbeat);lane.retry=lane.heartbeat=null;lane.socket?.close();lane.socket=null;lane.state='STOPPED';}this.updateAggregateState();}
  metrics(){return{...this.metricsValue,gapsByType:{...this.metricsValue.gapsByType},lastKlineGap:this.lastKlineGap?{...this.lastKlineGap}:null,lanes:Object.fromEntries((['PUBLIC','MARKET'] as const).map(name=>[name,{state:this.lanes[name].state,connectedAt:this.lanes[name].connectedAt,lastMessageAt:this.lanes[name].lastMessageAt||null,reconnects:this.lanes[name].reconnects,lastError:this.lanes[name].lastError,subscriptions:this.lanes[name].subscribed.size}]))};}
  quote(symbol:string,maxAgeMs=5_000){const q=this.quotes.get(symbol);return q&&fresh(q.ts,maxAgeMs)?q:undefined;}
  book(symbol:string,maxAgeMs=5_000){const b=this.books.get(symbol);return b&&fresh(b.ts,maxAgeMs)?b:undefined;}
  candleSeries(symbol:string,maxAgeMs=120_000,timeframe='1m'){const c=this.candles.get(timeframe==='1m'?symbol:`${symbol}:${timeframe}`);return c?.length&&fresh(c.at(-1)?.closeTime,maxAgeMs)?c:undefined;}
  seed(symbol:string,book:OrderBook,candles:Candle[]){this.books.set(symbol,book);this.seedCandles(symbol,'1m',candles);}
  seedCandles(symbol:string,timeframe:string,rows:Candle[]){const key=timeframe==='1m'?symbol:`${symbol}:${timeframe}`,merged=new Map(rows.map(c=>[c.openTime,c]));for(const c of this.candles.get(key)??[]){const other=merged.get(c.openTime);if(!other||(c.isClosed&&!other.isClosed)||(!(other.isClosed&&!c.isClosed)&&(c.receivedAt??0)>=(other.receivedAt??0)))merged.set(c.openTime,c);}this.candles.set(key,[...merged.values()].sort((a,b)=>a.openTime-b.openTime).slice(-300));}
  private updateAggregateState(){if(this.stopped){this.metricsValue.state='STOPPED';return;}const states=(['PUBLIC','MARKET'] as const).map(name=>this.lanes[name].state);this.metricsValue.state=states.every(x=>x==='LIVE')?'LIVE':states.some(x=>x==='CONNECTING')?'CONNECTING':'BACKOFF';this.metricsValue.connectedAt=Math.max(...(['PUBLIC','MARKET'] as const).map(name=>this.lanes[name].connectedAt??0))||null;this.metricsValue.lastMessageAt=Math.max(...(['PUBLIC','MARKET'] as const).map(name=>this.lanes[name].lastMessageAt||0))||null;this.metricsValue.lastError=(['MARKET','PUBLIC'] as const).map(name=>this.lanes[name].lastError).find(Boolean)??null;}
  private connect(laneName:'PUBLIC'|'MARKET'){if(this.stopped)return;const lane=this.lanes[laneName];lane.state='CONNECTING';this.updateAggregateState();let socket:WebSocket;try{socket=new WebSocket(this.transport.effectiveWsUrl(laneName),{...this.transport.websocketOptions(),handshakeTimeout:15_000});}catch(error){this.schedule(laneName,error);return;}lane.socket=socket;
    socket.on('open',()=>{this.clearControls(laneName);lane.subscribed.clear();if(laneName==='PUBLIC'){this.lastDepthUpdate.clear();this.backfillInFlight.clear();}const now=Date.now();lane.state='LIVE';lane.connectedAt=now;lane.lastMessageAt=now;lane.lastError=null;if(laneName==='MARKET')this.metricsValue.lastTickerMessageAt=now;else this.metricsValue.lastBookTickerMessageAt=now;this.subscribeLane(laneName);this.updateAggregateState();lane.heartbeat=setInterval(()=>{if(lane.socket!==socket||socket.readyState!==WebSocket.OPEN)return;const eventAt=laneName==='MARKET'?this.metricsValue.lastTickerMessageAt:this.metricsValue.lastBookTickerMessageAt,alive=fresh(lane.lastMessageAt||undefined,45_000)&&fresh(eventAt??undefined,45_000);if(!alive){socket.terminate();return;}socket.ping();},15_000);});
    socket.on('pong',()=>{this.metricsValue.lastPongAt=Date.now();});socket.on('message',raw=>this.onMessage(String(raw),laneName));
    socket.on('error',error=>{lane.lastError=error.message;this.updateAggregateState();});socket.on('close',(code,reason)=>{this.clearControls(laneName);if(reason.length)lane.lastError=`WS_CLOSE_${code}: ${String(reason)}`;if(lane.heartbeat)clearInterval(lane.heartbeat);lane.heartbeat=null;if(lane.socket===socket)lane.socket=null;if(!this.stopped)this.schedule(laneName,new Error(lane.lastError??'socket closed'));});
  }
  private schedule(laneName:'PUBLIC'|'MARKET',error:unknown){if(this.stopped)return;const lane=this.lanes[laneName];lane.state='BACKOFF';lane.lastError=error instanceof Error?error.message:String(error);lane.reconnects++;this.metricsValue.reconnects++;this.metricsValue.gaps++;this.metricsValue.gapsByType.websocketConnection++;this.updateAggregateState();const delay=Math.min(30_000,500*2**Math.min(lane.attempt++,6))+Math.floor(Math.random()*250);lane.retry=setTimeout(()=>this.connect(laneName),delay);}
  private desired(laneName:'PUBLIC'|'MARKET'){return laneName==='PUBLIC'?new Set(['!bookTicker',...[...this.symbols].map(s=>`${s.toLowerCase()}@depth20@500ms`)]):new Set(['!ticker@arr','!markPrice@arr@1s',...[...this.symbols].flatMap(s=>[`${s.toLowerCase()}@kline_1m`,`${s.toLowerCase()}@kline_5m`,`${s.toLowerCase()}@kline_15m`,`${s.toLowerCase()}@aggTrade`])]);}
  private subscribeSymbols(){this.subscribeLane('PUBLIC');this.subscribeLane('MARKET');}
  private subscribeLane(laneName:'PUBLIC'|'MARKET'){const lane=this.lanes[laneName];if(lane.socket?.readyState!==WebSocket.OPEN)return;const desired=this.desired(laneName),remove=[...lane.subscribed].filter(x=>!desired.has(x)),add=[...desired].filter(x=>!lane.subscribed.has(x));for(const [method,items] of [['UNSUBSCRIBE',remove],['SUBSCRIBE',add]] as const)for(let i=0;i<items.length;i+=100)lane.controlQueue.push({method,params:items.slice(i,i+100),id:lane.requestId++});lane.subscribed=desired;this.metricsValue.subscriptions=this.lanes.PUBLIC.subscribed.size+this.lanes.MARKET.subscribed.size;this.metricsValue.cumulativeSubscriptions+=add.length;this.pumpControls(laneName);}
  private clearControls(laneName:'PUBLIC'|'MARKET'){const lane=this.lanes[laneName];if(lane.controlTimer)clearTimeout(lane.controlTimer);lane.controlTimer=null;lane.controlQueue=[];}
  private pumpControls(laneName:'PUBLIC'|'MARKET'){const lane=this.lanes[laneName];if(lane.controlTimer||!lane.controlQueue.length||lane.socket?.readyState!==WebSocket.OPEN)return;lane.controlTimer=setTimeout(()=>{lane.controlTimer=null;if(lane.socket?.readyState!==WebSocket.OPEN)return;const command=lane.controlQueue.shift();if(command){lane.socket.send(JSON.stringify(command));lane.lastControlAt=Date.now();}this.pumpControls(laneName);},Math.max(0,350-(Date.now()-lane.lastControlAt)));}
  private onMessage(raw:string,laneName:'PUBLIC'|'MARKET'='MARKET'){const lane=this.lanes[laneName];lane.lastMessageAt=Date.now();this.metricsValue.lastMessageAt=lane.lastMessageAt;let value:any;try{value=JSON.parse(raw);}catch{return;}const controlError=value?.error??(value?.code!=null&&value?.msg!=null?{code:value.code,msg:value.msg,id:value.id??null}:null);if(controlError){lane.lastError=`WS_CONTROL_ERROR:${JSON.stringify(controlError)}`;this.metricsValue.lastError=lane.lastError;this.metricsValue.gaps++;this.metricsValue.gapsByType.subscription++;if(lane.socket?.readyState===WebSocket.OPEN)lane.socket.terminate();return;}const data=value.data??value;if(Array.isArray(data)){for(const row of data)this.onEvent(row,laneName);return;}this.onEvent(data,laneName);}
  private onEvent(d:any,laneName:'PUBLIC'|'MARKET'='MARKET'){if(!d||typeof d!=='object')return;const lane=this.lanes[laneName];if(d.e&&Date.now()-(lane.connectedAt??Date.now())>15000)lane.attempt=0;if(d.e==='aggTrade'){const s=String(d.s);if(this.symbols.has(s))this.tradedPrices.record(s,Number(d.p),Number(d.T));}
    else if(d.e==='24hrTicker'||(d.s&&d.c!=null&&d.q!=null)){this.metricsValue.lastTickerMessageAt=Date.now();const s=String(d.s);if(!this.symbols.has(s))return;this.mergeQuote(s,{last:Number(d.c),quoteVolumeUsd24h:Number(d.q),priceChangePercent24h:Number(d.P),tradeCount24h:Number(d.n),ts:Number(d.E)||Date.now()});}
    else if(d.e==='markPriceUpdate'||(d.s&&d.p!=null&&d.i!=null)){const s=String(d.s);if(this.symbols.has(s))this.mergeQuote(s,{mark:Number(d.p),ts:Number(d.E)||Date.now()});}
    else if(d.e==='bookTicker'||(d.s&&d.b!=null&&d.a!=null&&!d.e)){this.metricsValue.lastBookTickerMessageAt=Date.now();const s=String(d.s);if(this.symbols.has(s))this.mergeQuote(s,{bid:Number(d.b),ask:Number(d.a),ts:Number(d.E)||Date.now()});}
    else if(d.e==='depthUpdate'||(d.bids&&d.asks)){const s=String(d.s);if(!this.symbols.has(s)||this.backfillInFlight.has(s))return;const previous=this.lastDepthUpdate.get(s),first=Number(d.U??d.firstUpdateId??0),last=Number(d.u??d.lastUpdateId??0),pu=Number(d.pu??0);if(previous&&last<=previous)return;const contiguous=!previous||pu===previous||(first>0&&first<=previous+1&&last>=previous+1);if(!contiguous){if((this.recoveryCooldown.get(s)??0)<=Date.now()){this.metricsValue.gaps++;this.metricsValue.gapsByType.depthSequence++;this.lastDepthUpdate.delete(s);void this.recover(s);}return;}this.lastDepthUpdate.set(s,last);this.books.set(s,{symbol:s,bids:(d.b??d.bids).map((x:any)=>[Number(x[0]),Number(x[1])] as [number,number]),asks:(d.a??d.asks).map((x:any)=>[Number(x[0]),Number(x[1])] as [number,number]),ts:Number(d.E)||Date.now()});}
    else if(d.e==='kline'){const s=String(d.s);if(!this.symbols.has(s))return;const k=d.k,tf=String(k.i??'1m');if(!['1m','5m','15m'].includes(tf))return;const key=tf==='1m'?s:`${s}:${tf}`,receivedAt=Number(d.E)||Date.now();const candle:Candle={openTime:Number(k.t),closeTime:Number(k.T),receivedAt,isClosed:Boolean(k.x),source:'BINANCE_WS',open:Number(k.o),high:Number(k.h),low:Number(k.l),close:Number(k.c),volume:Number(k.v),quoteVolume:Number(k.q),trades:Number(k.n)};const rows=this.candles.get(key)??[];const at=rows.findIndex(x=>x.openTime===candle.openTime);if(at>=0){const prior=rows[at]!;if(prior.isClosed&&!candle.isClosed||(prior.receivedAt??0)>receivedAt)return;rows[at]=candle;}else rows.push(candle);this.candles.set(key,rows.sort((a,b)=>a.openTime-b.openTime).slice(-300));if(candle.isClosed){const period=tf==='1m'?60_000:tf==='5m'?300_000:900_000,previous=this.lastKlineClosed.get(key);if(previous!==undefined&&candle.openTime>previous+period){this.metricsValue.gaps++;this.metricsValue.gapsByType.kline++;this.lastKlineGap={symbol:s,timeframe:tf,expectedOpenTime:previous+period,actualOpenTime:candle.openTime,missingBars:Math.round((candle.openTime-previous)/period)-1,at:receivedAt};}if(previous===undefined||candle.openTime>previous)this.lastKlineClosed.set(key,candle.openTime);}}
  }
  private mergeQuote(symbol:string,patch:QuotePatch){this.quotes.set(symbol,{...this.quotes.get(symbol),...patch});}
  private async recover(symbol:string){const now=Date.now();if(this.backfillInFlight.has(symbol)||(this.recoveryCooldown.get(symbol)??0)>now)return;this.recoveryCooldown.set(symbol,now+60_000);this.backfillInFlight.add(symbol);try{const value=await this.backfill(symbol);if(!this.symbols.has(symbol))return;this.books.set(symbol,value.book);this.seedCandles(symbol,'1m',value.candles);this.lastDepthUpdate.delete(symbol);this.metricsValue.backfills++;this.metricsValue.recoverySuccess++;}catch(error){this.metricsValue.recoveryFailure++;this.metricsValue.lastError=error instanceof Error?error.message:String(error);}finally{this.backfillInFlight.delete(symbol);}}
}
